"""autoport stub — see docs/porting.md."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'narrowgauge/fr-ashbury-red-cream.blend'
_UPSTREAM_DAT = 'narrowgauge/fr-ashbury.dat'

SPECS = [
Vehicle(
    name='FR-Ashbury-unfitted',
    waytype='narrowgauge_track',
    copyright='jamespetts',
    freight='Passagiere',
    intro_year=1868,
    intro_month=10,
    retire_year=1886,
    retire_month=3,
    speed=60,
    length=2,
    weight=2,
    axles=2,
    brake_force=0,
    rolling_resistance=19,
    payload=16,
    min_loading_time=15,
    max_loading_time=55,
    cost=280000,
    runningcost=0,
    fixed_cost=333,
    bidirectional=1,
    can_lead_from_rear=0,
    constraint_prev=['any'],
    constraint_next=['any'],
    payload_by_class=[0, 16, 0, 0],
    comfort_by_class=[0, 30, 30, 49],
    liverytype=['FR-Royal-Purple', 'FR-Royal-Purple-Cream', 'FR-Col-Stephens', 'FR-Green-Cream', 'FR-Cherry-Red', 'FR-Red-Cream'],
    upgrade=['FR-Ashbury-fitted'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='FR-Ashbury-fitted',
    waytype='narrowgauge_track',
    copyright='jamespetts',
    freight='Passagiere',
    intro_year=1887,
    intro_month=4,
    retire_year=1935,
    retire_month=10,
    speed=60,
    length=2,
    weight=2,
    axles=2,
    rolling_resistance=19,
    payload=16,
    min_loading_time=15,
    max_loading_time=55,
    cost=270000,
    runningcost=0,
    fixed_cost=4913,
    upgrade_price=20000,
    bidirectional=1,
    can_lead_from_rear=0,
    constraint_prev=['any'],
    constraint_next=['any'],
    payload_by_class=[0, 16, 0, 0],
    comfort_by_class=[0, 30, 30, 49],
    liverytype=['FR-Royal-Purple', 'FR-Royal-Purple-Cream', 'FR-Col-Stephens', 'FR-Green-Cream', 'FR-Cherry-Red', 'FR-Red-Cream'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='FR-Ashbury-first-unfitted',
    waytype='narrowgauge_track',
    copyright='jamespetts',
    freight='Passagiere',
    intro_year=1868,
    intro_month=10,
    retire_year=1886,
    retire_month=3,
    speed=60,
    length=2,
    weight=2,
    axles=2,
    brake_force=0,
    rolling_resistance=19,
    payload=12,
    min_loading_time=15,
    max_loading_time=55,
    cost=287600,
    runningcost=0,
    fixed_cost=333,
    bidirectional=1,
    can_lead_from_rear=0,
    constraint_prev=['any'],
    constraint_next=['any'],
    payload_by_class=[0, 0, 0, 12],
    comfort_by_class=[0, 30, 30, 49],
    liverytype=['FR-Royal-Purple', 'FR-Royal-Purple-Cream', 'FR-Col-Stephens', 'FR-Green-Cream', 'FR-Cherry-Red', 'FR-Red-Cream'],
    upgrade=['FR-Ashbury-first-fitted'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='FR-Ashbury-first-fitted',
    waytype='narrowgauge_track',
    copyright='jamespetts',
    freight='Passagiere',
    intro_year=1887,
    intro_month=4,
    retire_year=1935,
    retire_month=10,
    speed=60,
    length=2,
    weight=2,
    axles=2,
    rolling_resistance=19,
    payload=12,
    min_loading_time=15,
    max_loading_time=55,
    cost=270000,
    runningcost=0,
    fixed_cost=4913,
    upgrade_price=20000,
    bidirectional=1,
    can_lead_from_rear=0,
    constraint_prev=['any'],
    constraint_next=['any'],
    payload_by_class=[0, 0, 0, 12],
    comfort_by_class=[0, 30, 30, 49],
    liverytype=['FR-Royal-Purple', 'FR-Royal-Purple-Cream', 'FR-Col-Stephens', 'FR-Green-Cream', 'FR-Cherry-Red', 'FR-Red-Cream'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
