"""autoport stub — see docs/porting.md."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'narrowgauge/fr-small-birmingham-red-cream.blend'
_UPSTREAM_DAT = 'narrowgauge/fr-small-birmingham.dat'

SPECS = [
Vehicle(
    name='FR-Small-Birmingham-unfitted',
    waytype='narrowgauge_track',
    copyright='jamespetts',
    freight='Passagiere',
    intro_year=1863,
    intro_month=7,
    retire_year=1868,
    retire_month=10,
    speed=60,
    length=2,
    weight=1.3,
    axles=2,
    brake_force=0,
    rolling_resistance=20,
    payload=14,
    min_loading_time=25,
    max_loading_time=50,
    cost=275000,
    runningcost=0,
    fixed_cost=327,
    bidirectional=1,
    can_lead_from_rear=0,
    constraint_prev=['any'],
    constraint_next=['any'],
    payload_by_class=[0, 14, 0, 0],
    comfort_by_class=[0, 34, 35, 53],
    liverytype=['FR-Royal-Purple', 'FR-Royal-Purple-Cream', 'FR-Col-Stephens', 'FR-Green-Cream', 'FR-Cherry-Red', 'FR-Red-Cream'],
    upgrade=['FR-Small-Birmingham-fitted'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='FR-Small-Birmingham-fitted',
    waytype='narrowgauge_track',
    copyright='jamespetts',
    freight='Passagiere',
    intro_year=1887,
    intro_month=4,
    retire_year=1935,
    retire_month=10,
    speed=60,
    length=2,
    weight=1.3,
    rolling_resistance=20,
    payload=14,
    min_loading_time=25,
    max_loading_time=50,
    cost=320000,
    runningcost=0,
    fixed_cost=381,
    upgrade_price=20000,
    bidirectional=1,
    can_lead_from_rear=0,
    constraint_prev=['any'],
    constraint_next=['any'],
    payload_by_class=[0, 14, 0, 0],
    comfort_by_class=[0, 34, 35, 53],
    liverytype=['FR-Royal-Purple', 'FR-Royal-Purple-Cream', 'FR-Col-Stephens', 'FR-Green-Cream', 'FR-Cherry-Red', 'FR-Red-Cream'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='FR-Small-Birmingham-second-unfitted',
    waytype='narrowgauge_track',
    copyright='jamespetts',
    freight='Passagiere',
    intro_year=1863,
    intro_month=7,
    retire_year=1868,
    retire_month=10,
    speed=60,
    length=2,
    weight=1.3,
    axles=2,
    brake_force=0,
    rolling_resistance=20,
    payload=14,
    min_loading_time=25,
    max_loading_time=50,
    cost=275250,
    runningcost=0,
    fixed_cost=327,
    bidirectional=1,
    can_lead_from_rear=0,
    constraint_prev=['any'],
    constraint_next=['any'],
    payload_by_class=[0, 0, 14, 0],
    comfort_by_class=[0, 34, 35, 53],
    liverytype=['FR-Royal-Purple', 'FR-Royal-Purple-Cream', 'FR-Col-Stephens', 'FR-Green-Cream', 'FR-Cherry-Red', 'FR-Red-Cream'],
    upgrade=['FR-Small-Birmingham-second-fitted'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='FR-Small-Birmingham-second-fitted',
    waytype='narrowgauge_track',
    copyright='jamespetts',
    freight='Passagiere',
    intro_year=1887,
    intro_month=4,
    retire_year=1935,
    retire_month=10,
    speed=60,
    length=2,
    weight=1.3,
    rolling_resistance=20,
    payload=14,
    min_loading_time=25,
    max_loading_time=50,
    cost=320000,
    runningcost=0,
    fixed_cost=381,
    upgrade_price=20000,
    bidirectional=1,
    can_lead_from_rear=0,
    constraint_prev=['any'],
    constraint_next=['any'],
    payload_by_class=[0, 0, 14, 0],
    comfort_by_class=[0, 34, 35, 53],
    liverytype=['FR-Royal-Purple', 'FR-Royal-Purple-Cream', 'FR-Col-Stephens', 'FR-Green-Cream', 'FR-Cherry-Red', 'FR-Red-Cream'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='FR-Small-Birmingham-first-unfitted',
    waytype='narrowgauge_track',
    copyright='jamespetts',
    freight='Passagiere',
    intro_year=1863,
    intro_month=7,
    retire_year=1868,
    retire_month=10,
    speed=60,
    length=2,
    weight=1.3,
    axles=2,
    brake_force=0,
    rolling_resistance=20,
    payload=12,
    min_loading_time=25,
    max_loading_time=50,
    cost=280000,
    runningcost=0,
    fixed_cost=327,
    bidirectional=1,
    can_lead_from_rear=0,
    constraint_prev=['any'],
    constraint_next=['any'],
    payload_by_class=[0, 0, 0, 12],
    comfort_by_class=[0, 34, 35, 53],
    liverytype=['FR-Royal-Purple', 'FR-Royal-Purple-Cream', 'FR-Col-Stephens', 'FR-Green-Cream', 'FR-Cherry-Red', 'FR-Red-Cream'],
    upgrade=['FR-Small-Birmingham-first-fitted'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='FR-Small-Birmingham-first-fitted',
    waytype='narrowgauge_track',
    copyright='jamespetts',
    freight='Passagiere',
    intro_year=1887,
    intro_month=4,
    retire_year=1935,
    retire_month=10,
    speed=60,
    length=2,
    weight=1.3,
    rolling_resistance=20,
    payload=12,
    min_loading_time=25,
    max_loading_time=50,
    cost=330000,
    runningcost=0,
    fixed_cost=381,
    upgrade_price=20000,
    bidirectional=1,
    can_lead_from_rear=0,
    constraint_prev=['any'],
    constraint_next=['any'],
    payload_by_class=[0, 0, 0, 12],
    comfort_by_class=[0, 34, 35, 53],
    liverytype=['FR-Royal-Purple', 'FR-Royal-Purple-Cream', 'FR-Col-Stephens', 'FR-Green-Cream', 'FR-Cherry-Red', 'FR-Red-Cream'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
