"""autoport stub — see docs/porting.md."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'narrowgauge/lbr-carriage.blend'
_UPSTREAM_DAT = 'narrowgauge/lbr-carriages.dat'

SPECS = [
Vehicle(
    name='lbr-third',
    waytype='narrowgauge_track',
    copyright='jamespetts',
    freight='Passagiere',
    intro_year=1898,
    intro_month=6,
    retire_year=1964,
    retire_month=5,
    speed=72,
    length=6,
    weight=8.9,
    axles=4,
    rolling_resistance=17,
    payload=56,
    min_loading_time=15,
    max_loading_time=55,
    cost=665000,
    runningcost=0,
    fixed_cost=250,
    bidirectional=1,
    can_lead_from_rear=0,
    constraint_prev=['any'],
    constraint_next=['any'],
    payload_by_class=[0, 56, 0, 0],
    comfort_by_class=[0, 41, 41, 88],
    liverytype=['L&BR-Standard', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'FR-Green-Cream', 'FR-Cherry-Red', 'FR-Red-Cream'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='lbr-composite',
    waytype='narrowgauge_track',
    copyright='jamespetts',
    freight='Passagiere',
    intro_year=1898,
    intro_month=6,
    retire_year=1964,
    retire_month=5,
    speed=72,
    length=6,
    weight=8.9,
    axles=4,
    rolling_resistance=17,
    payload=32,
    min_loading_time=15,
    max_loading_time=55,
    cost=668500,
    runningcost=0,
    fixed_cost=250,
    bidirectional=1,
    can_lead_from_rear=0,
    constraint_prev=['any'],
    constraint_next=['any'],
    payload_by_class=[0, 32, 0, 12],
    comfort_by_class=[0, 41, 41, 88],
    liverytype=['L&BR-Standard', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'FR-Green-Cream', 'FR-Cherry-Red', 'FR-Red-Cream'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='lbr-brake',
    waytype='narrowgauge_track',
    copyright='jamespetts',
    freight='Passagiere',
    intro_year=1898,
    intro_month=6,
    retire_year=1964,
    retire_month=5,
    speed=72,
    length=6,
    weight=8.5,
    axles=4,
    rolling_resistance=17,
    payload=40,
    min_loading_time=15,
    max_loading_time=55,
    cost=660000,
    runningcost=0,
    fixed_cost=5036,
    bidirectional=1,
    can_lead_from_rear=0,
    payload_by_class=[0, 40, 0, 0],
    comfort_by_class=[0, 41, 41, 88],
    liverytype=['L&BR-Standard', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'FR-Green-Cream', 'FR-Cherry-Red', 'FR-Red-Cream'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
