"""autoport stub — see docs/porting.md."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'narrowgauge/quarrymens-carriage-open.blend'
_UPSTREAM_DAT = 'narrowgauge/quarrymens-carriage.dat'

SPECS = [
Vehicle(
    name='quarrymens-carriage-open',
    waytype='narrowgauge_track',
    copyright='jamespetts',
    freight='Passagiere',
    intro_year=1867,
    intro_month=2,
    retire_year=1873,
    retire_month=12,
    speed=50,
    length=3,
    weight=1.4,
    axles=2,
    brake_force=0,
    rolling_resistance=20,
    payload=16,
    min_loading_time=12,
    max_loading_time=50,
    overcrowded_capacity=4,
    cost=190000,
    runningcost=0,
    fixed_cost=250,
    bidirectional=1,
    can_lead_from_rear=0,
    constraint_prev=['any'],
    constraint_next=['any'],
    payload_by_class=[16],
    comfort_by_class=[11],
    upgrade=['quarrymens-carriage-enclosed'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='quarrymens-carriage-enclosed',
    waytype='narrowgauge_track',
    copyright='jamespetts',
    freight='Passagiere',
    intro_year=1873,
    intro_month=11,
    retire_year=1885,
    retire_month=9,
    speed=50,
    length=3,
    weight=1.9,
    axles=2,
    brake_force=0,
    rolling_resistance=20,
    payload=16,
    min_loading_time=12,
    max_loading_time=50,
    overcrowded_capacity=0,
    cost=280000,
    runningcost=0,
    fixed_cost=265,
    upgrade_price=62222,
    bidirectional=1,
    can_lead_from_rear=0,
    constraint_prev=['any'],
    constraint_next=['any'],
    payload_by_class=[16],
    comfort_by_class=[11],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='quarrymens-carriage-glazed',
    waytype='narrowgauge_track',
    copyright='jamespetts',
    freight='Passagiere',
    intro_year=1885,
    intro_month=8,
    retire_year=1929,
    retire_month=12,
    speed=50,
    length=3,
    weight=2.2,
    axles=2,
    rolling_resistance=18,
    payload=16,
    min_loading_time=12,
    max_loading_time=50,
    overcrowded_capacity=1,
    cost=340000,
    runningcost=0,
    fixed_cost=265,
    bidirectional=1,
    can_lead_from_rear=0,
    constraint_prev=['any'],
    constraint_next=['any'],
    payload_by_class=[16],
    comfort_by_class=[29],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
