"""4-wheel-1870s-sub."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# These are the 5 compartment high density (suburban) versions
# of the carriages in 4-wheel-1870s.dat. The 1870s were the
# first decade in which railway carriages were specifically
# built either for long-distance or suburban use.
# These carriages come in fitted and unfitted varieties, as they
# span the 1870s, the period in which continuous brakes were
# introduced. Fitted vehicles must be coupled to other fitted
# vehicles of the same brake type (so LBSCR fitted vehicles,
# which used the Westinghouse brake, cannot be coupled to
# vacuum fitted vehicles).
# Third class
_BLEND = 'trains/Carriages/ger-4-wheel-1870-26ft-second-teak.blend'
_UPSTREAM_DAT = 'trains/4-wheel-1870s-sub.dat'

SPECS = [
    Vehicle(
        name='4-wheel-sub-1870s-unfitted',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1870,
        intro_month=1,
        retire_year=1878,
        retire_month=2,
        speed=145,
        length=5,
        weight=9,
        axles=2,
        brake_force=0,
        rolling_resistance=18,
        payload=50,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=25,
        cost=300000,
        runningcost=0,
        fixed_cost=357,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['any'],
        constraint_next=['any'],
        payload_by_class=[0, 50, 0, 0],
        comfort_by_class=[0, 52, 60, 66],
        liverytype=['LNWR-Early', 'MR-Early', 'MR-Standard', 'GNR-early', 'GWR-two-tone', 'LSWR-purple-brown', 'LSWR-pea-green', 'LSWR-royal-green', 'GWR-overall-brown', 'GWR-lake', 'WW1-Austerity', 'GWR-chocolate-cream-lined'],
        upgrade=['4-wheel-sub-1870s-fitted'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='4-wheel-sub-1870s-unfitted-composite',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1870,
        intro_month=1,
        retire_year=1878,
        retire_month=2,
        speed=145,
        length=5,
        weight=9,
        axles=2,
        brake_force=0,
        rolling_resistance=18,
        payload=16,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=4,
        cost=312000,
        runningcost=0,
        fixed_cost=371,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['any'],
        constraint_next=['any'],
        payload_by_class=[0, 0, 16, 16],
        comfort_by_class=[0, 52, 60, 66],
        liverytype=['LNWR-Early', 'MR-Early', 'MR-Standard', 'GNR-early', 'GWR-two-tone', 'LSWR-purple-brown', 'LSWR-pea-green', 'LSWR-royal-green', 'GWR-overall-brown', 'GWR-lake', 'WW1-Austerity', 'GWR-chocolate-cream-lined'],
        upgrade=['4-wheel-sub-1870s-fitted-composite'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='4-wheel-sub-1870s-brake-front-unfitted',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1870,
        intro_month=1,
        retire_year=1878,
        retire_month=2,
        speed=145,
        length=5,
        weight=9,
        axles=2,
        brake_force=4,
        rolling_resistance=18,
        payload=30,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=15,
        cost=300000,
        runningcost=0,
        fixed_cost=5157,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['any'],
        constraint_next=['any'],
        payload_by_class=[0, 30, 0, 0],
        comfort_by_class=[0, 52, 60, 66],
        liverytype=['LNWR-Early', 'MR-Early', 'MR-Standard', 'GNR-early', 'GWR-two-tone', 'LSWR-purple-brown', 'LSWR-pea-green', 'LSWR-royal-green', 'GWR-overall-brown', 'GWR-lake', 'WW1-Austerity', 'GWR-chocolate-cream-lined'],
        upgrade=['4-wheel-sub-1870s-brake-front-fitted'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='4-wheel-sub-1870s-brake-rear-unfitted',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1870,
        intro_month=1,
        retire_year=1878,
        retire_month=2,
        speed=145,
        length=5,
        weight=9,
        axles=2,
        brake_force=4,
        rolling_resistance=18,
        payload=30,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=15,
        cost=300000,
        runningcost=0,
        fixed_cost=5157,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        payload_by_class=[0, 30, 0, 0],
        comfort_by_class=[0, 52, 60, 66],
        liverytype=['LNWR-Early', 'MR-Early', 'MR-Standard', 'GNR-early', 'GWR-two-tone', 'LSWR-purple-brown', 'LSWR-pea-green', 'LSWR-royal-green', 'GWR-overall-brown', 'GWR-lake', 'WW1-Austerity', 'GWR-chocolate-cream-lined'],
        upgrade=['4-wheel-sub-1870s-brake-rear-fitted'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='4-wheel-sub-1870s-fitted',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1876,
        intro_month=3,
        retire_year=1911,
        retire_month=7,
        speed=145,
        length=5,
        weight=10,
        axles=2,
        brake_force=4,
        rolling_resistance=18,
        payload=50,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=25,
        cost=355000,
        runningcost=0,
        fixed_cost=423,
        upgrade_price=65000,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'MR-6Wheel-Mail', '4-wheel-1870s-fast-freight-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-front', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-brake-third', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', '4-wheel-1870s-milk-fitted', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', '4-wheel-sub-1870s-fitted-composite', '4-wheel-1870s-luggage-third-fitted', '4-wheel-1870s-tricomposite-fitted', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-6-wheel-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'MR-6Wheel-Mail', '4-wheel-1870s-fast-freight-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-rear', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-brake-third', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', '4-wheel-1870s-milk-fitted', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', '4-wheel-sub-1870s-fitted-composite', '4-wheel-1870s-luggage-third-fitted', '4-wheel-1870s-tricomposite-fitted', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-6-wheel-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear'],
        payload_by_class=[0, 50, 0, 0],
        comfort_by_class=[0, 52, 60, 66],
        liverytype=['LNWR-Early', 'MR-Early', 'MR-Standard', 'GNR-early', 'GWR-two-tone', 'LSWR-purple-brown', 'LSWR-pea-green', 'LSWR-royal-green', 'GWR-overall-brown', 'GWR-lake', 'WW1-Austerity', 'GWR-chocolate-cream-lined'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='4-wheel-sub-1870s-fitted-composite',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1876,
        intro_month=3,
        retire_year=1911,
        retire_month=7,
        speed=145,
        length=5,
        weight=9,
        axles=2,
        brake_force=4,
        rolling_resistance=18,
        payload=16,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=8,
        cost=367000,
        runningcost=0,
        fixed_cost=437,
        upgrade_price=65000,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'MR-6Wheel-Mail', '4-wheel-1870s-fast-freight-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-front', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-brake-third', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', '4-wheel-1870s-milk-fitted', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', '4-wheel-sub-1870s-fitted-composite', '4-wheel-1870s-luggage-third-fitted', '4-wheel-1870s-tricomposite-fitted', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-6-wheel-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'MR-6Wheel-Mail', '4-wheel-1870s-fast-freight-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-rear', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-brake-third', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', '4-wheel-1870s-milk-fitted', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', '4-wheel-sub-1870s-fitted-composite', '4-wheel-1870s-luggage-third-fitted', '4-wheel-1870s-tricomposite-fitted', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-6-wheel-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear'],
        payload_by_class=[0, 0, 16, 16],
        comfort_by_class=[0, 52, 60, 66],
        liverytype=['LNWR-Early', 'MR-Early', 'MR-Standard', 'GNR-early', 'GWR-two-tone', 'LSWR-purple-brown', 'LSWR-pea-green', 'LSWR-royal-green', 'GWR-overall-brown', 'GWR-lake', 'WW1-Austerity', 'GWR-chocolate-cream-lined'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='4-wheel-sub-1870s-brake-front-fitted',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1876,
        intro_month=3,
        retire_year=1911,
        retire_month=7,
        speed=145,
        length=5,
        weight=10,
        axles=2,
        brake_force=4,
        rolling_resistance=18,
        payload=30,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=15,
        cost=355000,
        runningcost=0,
        fixed_cost=5223,
        upgrade_price=65000,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'MR-6Wheel-Mail', '4-wheel-1870s-fast-freight-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-rear', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-brake-third', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', '4-wheel-1870s-milk-fitted', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', '4-wheel-sub-1870s-fitted-composite', '4-wheel-1870s-luggage-third-fitted', '4-wheel-1870s-tricomposite-fitted', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-6-wheel-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear', 'none'],
        payload_by_class=[0, 30, 0, 0],
        comfort_by_class=[0, 52, 60, 66],
        liverytype=['LNWR-Early', 'MR-Early', 'MR-Standard', 'GNR-early', 'GWR-two-tone', 'LSWR-purple-brown', 'LSWR-pea-green', 'LSWR-royal-green', 'GWR-overall-brown', 'GWR-lake', 'WW1-Austerity', 'GWR-chocolate-cream-lined'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='4-wheel-sub-1870s-brake-rear-fitted',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1876,
        intro_month=3,
        retire_year=1911,
        retire_month=7,
        speed=145,
        length=5,
        weight=10,
        axles=2,
        brake_force=4,
        rolling_resistance=18,
        payload=30,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=15,
        cost=355000,
        runningcost=0,
        fixed_cost=5223,
        upgrade_price=65000,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'MR-6Wheel-Mail', '4-wheel-1870s-fast-freight-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-front', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-brake-third', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', '4-wheel-1870s-milk-fitted', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', '4-wheel-sub-1870s-fitted-composite', '4-wheel-1870s-luggage-third-fitted', '4-wheel-1870s-tricomposite-fitted', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-6-wheel-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        payload_by_class=[0, 30, 0, 0],
        comfort_by_class=[0, 52, 60, 66],
        liverytype=['LNWR-Early', 'MR-Early', 'MR-Standard', 'GNR-early', 'GWR-two-tone', 'LSWR-purple-brown', 'LSWR-pea-green', 'LSWR-royal-green', 'GWR-overall-brown', 'GWR-lake', 'WW1-Austerity', 'GWR-chocolate-cream-lined'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
