"""b&djr-4wheel-first."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Carriages/b&djr-4wheel-second-varnished.blend'
_UPSTREAM_DAT = 'trains/b&djr-4wheel-first.dat'

SPECS = [
    Vehicle(
        name='b&djr-4wheel-first',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1839,
        intro_month=3,
        retire_year=1848,
        retire_month=12,
        speed=125,
        length=3,
        weight=2.8,
        axles=2,
        brake_force=0,
        rolling_resistance=19,
        payload=18,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=9,
        cost=150000,
        runningcost=0,
        fixed_cost=125,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['any'],
        constraint_next=['any'],
        payload_by_class=[0, 0, 0, 18],
        comfort_by_class=[0, 0, 0, 57],
        liverytype=['LMR-Standard', 'MR-Early', 'LNWR-Early', 'GNR-early', 'LSWR-early', 'B&DJR-standard', 'MCR-standard', 'Stockton-Darlington-early', 'Stockton-Darlington-lake', 'London-&-Birmingham-standard', 'ECR-standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='b&djr-4wheel-first-Guard-front',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1839,
        intro_month=3,
        retire_year=1848,
        retire_month=12,
        speed=125,
        length=3,
        weight=2.8,
        axles=2,
        brake_force=1,
        rolling_resistance=19,
        payload=18,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=9,
        cost=151000,
        runningcost=0,
        fixed_cost=4926,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['any'],
        constraint_next=['any'],
        payload_by_class=[0, 0, 0, 18],
        comfort_by_class=[0, 0, 0, 57],
        liverytype=['LMR-Standard', 'MR-Early', 'LNWR-Early', 'GNR-early', 'LSWR-early', 'B&DJR-standard', 'MCR-standard', 'Stockton-Darlington-early', 'Stockton-Darlington-lake', 'London-&-Birmingham-standard', 'ECR-standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='b&djr-4wheel-first-Guard-rear',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1839,
        intro_month=3,
        retire_year=1848,
        retire_month=12,
        speed=125,
        length=3,
        weight=2.8,
        axles=2,
        brake_force=1,
        rolling_resistance=19,
        payload=18,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=9,
        cost=151000,
        runningcost=0,
        fixed_cost=4926,
        bidirectional=1,
        can_lead_from_rear=0,
        payload_by_class=[0, 0, 0, 18],
        comfort_by_class=[0, 0, 0, 57],
        liverytype=['LMR-Standard', 'MR-Early', 'LNWR-Early', 'GNR-early', 'LSWR-early', 'B&DJR-standard', 'MCR-standard', 'Stockton-Darlington-early', 'Stockton-Darlington-lake', 'London-&-Birmingham-standard', 'ECR-standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
