"""br-127."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# https://railcar.co.uk/type/class-127/summary
# https://en.wikipedia.org/wiki/British_Rail_Class_127
# These are functionally very similar to the class 125s - allow players to create this equivalence by making the TS optional.
_BLEND = 'trains/Railcars/br-127-dmbs-bg.blend'
_UPSTREAM_DAT = 'trains/br-127.dat'

SPECS = [
    Vehicle(
        name='BR-127-DMBS-front',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1959,
        intro_month=11,
        retire_year=1977,
        retire_month=6,
        speed=113,
        length=11,
        weight=40.6,
        axles=4,
        power=355,
        gear=50,
        tractive_effort=50,
        payload=65,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=64,
        cost=1380000,
        runningcost=355,
        fixed_cost=13046,
        increase_maintenance_after_years=15,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='spompeytransportvideo-class-117.wav',
        constraint_prev=['BR-127-DMBS-rear', 'none'],
        constraint_next=['BR-127-TSL'],
        payload_by_class=[0, 65],
        comfort_by_class=[0, 75],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-127-TSL',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1959,
        intro_month=11,
        retire_year=1977,
        retire_month=6,
        speed=113,
        length=11,
        weight=30.5,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=90,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=92,
        cost=605000,
        runningcost=0,
        fixed_cost=720,
        increase_maintenance_after_years=10,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-127-DMBS-front'],
        constraint_next=['BR-127-DMBS-rear', 'BR-127-TS'],
        payload_by_class=[0, 90],
        comfort_by_class=[0, 75],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-127-TS',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1959,
        intro_month=11,
        retire_year=1977,
        retire_month=6,
        speed=113,
        length=11,
        weight=30.5,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=106,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=110,
        cost=605000,
        runningcost=0,
        fixed_cost=720,
        increase_maintenance_after_years=10,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-127-TSL'],
        constraint_next=['BR-127-DMBS-rear'],
        payload_by_class=[0, 106],
        comfort_by_class=[0, 75],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-127-DMBS-rear',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1959,
        intro_month=11,
        retire_year=1977,
        retire_month=6,
        speed=113,
        length=11,
        weight=40.6,
        axles=4,
        power=355,
        gear=50,
        tractive_effort=50,
        payload=65,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=64,
        cost=1380000,
        runningcost=355,
        fixed_cost=13046,
        increase_maintenance_after_years=15,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        constraint_prev=['BR-127-TSL', 'BR-127-TS'],
        constraint_next=['BR-127-DMBS-front', 'none'],
        payload_by_class=[0, 65],
        comfort_by_class=[0, 75],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
