"""br-142."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/br-142-a.blend'
_UPSTREAM_DAT = 'trains/br-142.dat'

SPECS = [
    Vehicle(
        name='br-142-front',
        waytype='track',
        copyright='Kieron/jonbridg',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1985,
        intro_month=5,
        retire_year=1990,
        retire_month=2,
        speed=120,
        length=9,
        weight=24,
        axles=2,
        power=153,
        gear=50,
        tractive_effort=35,
        payload=56,
        min_loading_time=20,
        max_loading_time=55,
        overcrowded_capacity=43,
        cost=1250000,
        runningcost=50,
        fixed_cost=6651,
        increase_maintenance_after_years=26,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-light',
        sound='video47-class-142.wav',
        constraint_prev=['br-150-rear', 'br-153', 'br-153-trolley', 'br-158-rear', 'br-156-rear', 'br-142-rear', 'br-141-1-rear', 'br-142-1-rear', 'br-144-0-rear', 'br-144-1-rear', 'BR-170Rear', 'br-159-rear', 'none'],
        constraint_next=['br-142-rear'],
        payload_by_class=[0, 56],
        comfort_by_class=[0, 64],
        liverytype=['GMPTE-orange-brown', 'Provincial', 'BR-Large-Logo', 't&wpte'],
        upgrade=['br-142-1-front'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='br-142-rear',
        waytype='track',
        copyright='Kieron/jonbridg',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1985,
        intro_month=5,
        retire_year=1990,
        retire_month=2,
        speed=120,
        length=9,
        weight=24,
        axles=2,
        power=153,
        gear=50,
        tractive_effort=35,
        payload=50,
        min_loading_time=20,
        max_loading_time=55,
        overcrowded_capacity=41,
        cost=1250000,
        runningcost=50,
        fixed_cost=6651,
        increase_maintenance_after_years=26,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-light',
        sound='video47-class-142.wav',
        constraint_prev=['br-142-front'],
        constraint_next=['br-150-front', 'br-153', 'br-158-front', 'br-156-front', 'br-153-trolley', 'br-156-front-trolley', 'br-142-front', 'br-141-1-front', 'br-142-1-front', 'br-144-0-front', 'br-144-1-front', 'BR-170Front', 'br-159-front', 'none'],
        payload_by_class=[0, 50],
        comfort_by_class=[0, 64],
        liverytype=['GMPTE-orange-brown', 'Provincial', 'BR-Blue', 't&wpte'],
        upgrade=['br-142-1-rear'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='br-142-1-front',
        waytype='track',
        copyright='Kieron/jonbridg',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1990,
        intro_month=2,
        retire_year=1991,
        retire_month=3,
        speed=120,
        length=9,
        weight=24,
        axles=2,
        power=172,
        gear=50,
        tractive_effort=35,
        payload=56,
        min_loading_time=20,
        max_loading_time=55,
        overcrowded_capacity=43,
        cost=1375000,
        runningcost=34,
        fixed_cost=6716,
        upgrade_price=250000,
        increase_maintenance_after_years=21,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-light',
        sound='video47-class-142.wav',
        constraint_prev=['br-150-rear', 'br-153', 'br-153-trolley', 'br-158-rear', 'br-156-rear', 'br-142-rear', 'br-141-1-rear', 'br-142-1-rear', 'br-144-0-rear', 'br-144-1-rear', 'BR-170Rear', 'br-159-rear', 'none'],
        constraint_next=['br-142-1-rear'],
        payload_by_class=[0, 56],
        comfort_by_class=[0, 64],
        liverytype=['Regional-Railways-Standard', 'GMPTE-orange-brown', 'GMPTE-black-red', 'Provincial', 'BR-Large-Logo', 't&wpte', 'Merseyrail91', 'Merseyrail00'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='br-142-1-rear',
        waytype='track',
        copyright='Kieron/jonbridg',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1990,
        intro_month=2,
        retire_year=1991,
        retire_month=3,
        speed=120,
        length=9,
        weight=24,
        axles=2,
        power=172,
        gear=50,
        tractive_effort=35,
        payload=50,
        min_loading_time=20,
        max_loading_time=55,
        overcrowded_capacity=41,
        cost=1375000,
        runningcost=34,
        fixed_cost=6716,
        upgrade_price=250000,
        increase_maintenance_after_years=21,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-light',
        sound='video47-class-142.wav',
        constraint_prev=['br-142-1-front'],
        constraint_next=['br-150-front', 'br-153', 'br-158-front', 'br-156-front', 'br-153-trolley', 'br-156-front-trolley', 'br-142-front', 'br-141-1-front', 'br-142-1-front', 'br-144-0-front', 'br-144-1-front', 'BR-170Front', 'br-159-front', 'none'],
        payload_by_class=[0, 50],
        comfort_by_class=[0, 64],
        liverytype=['Regional-Railways-Standard', 'GMPTE-orange-brown', 'GMPTE-black-red', 'Provincial', 'BR-Blue', 't&wpte', 'Merseyrail91', 'Merseyrail00'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
