"""br-120."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://railcar.co.uk/type/120/
_BLEND = 'trains/Railcars/br-120-tslrb-bg.blend'
_UPSTREAM_DAT = 'trains/br-120.dat'

SPECS = [
    Vehicle(
        name='BR-120-DMBC',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1958,
        intro_month=3,
        retire_year=1963,
        retire_month=7,
        speed=109,
        length=11,
        weight=36.9,
        axles=4,
        power=224,
        gear=50,
        tractive_effort=55,
        payload=18,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=15,
        cost=1400000,
        runningcost=224,
        fixed_cost=11458,
        increase_maintenance_after_years=16,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='spompeytransportvideo-class-117.wav',
        constraint_prev=['BR-121', 'BR-117-DMS', 'BR-104Rear', 'BR-128', 'BR-101-DMCL', 'BR-101-DTCL', 'BR-114-DTCL', 'BR-120-DMSL', 'BR-110-DMCL', 'none'],
        constraint_next=['BR-120-TSLRB'],
        payload_by_class=[0, 16, 0, 18],
        comfort_by_class=[0, 109, 0, 130],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-120-TSLRB',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1958,
        intro_month=3,
        retire_year=1963,
        retire_month=7,
        speed=109,
        length=11,
        weight=31.1,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=60,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=22,
        catering_level=2,
        cost=580000,
        runningcost=0,
        fixed_cost=690,
        increase_maintenance_after_years=16,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-120-DMBC'],
        constraint_next=['BR-120-DMSL'],
        payload_by_class=[0, 60, 0, 0],
        comfort_by_class=[0, 109, 0, 130],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-120-DMSL',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1958,
        intro_month=3,
        retire_year=1963,
        retire_month=7,
        speed=109,
        length=11,
        weight=37.1,
        axles=4,
        power=224,
        gear=50,
        tractive_effort=55,
        payload=68,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=25,
        cost=1400000,
        runningcost=0,
        fixed_cost=583,
        increase_maintenance_after_years=16,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='video47-class-121.wav',
        constraint_prev=['BR-120-TSLRB'],
        constraint_next=['BR-121', 'BR-117-DMBS', 'BR-104Front', 'BR-128', 'BR-101-DMBS', 'BR-120-DMBC', 'BR-114-DMBS', 'BR-110-DMBC', 'none'],
        payload_by_class=[0, 68, 0, 0],
        comfort_by_class=[0, 109, 0, 130],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
