"""br-165."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://web.archive.org/web/20080219234521/http://www.therailwaycentre.com/New%20DMU%20Tech%20Data%20/DMU_165.html
_BLEND = 'trains/Railcars/br-165-a-nse.blend'
_UPSTREAM_DAT = 'trains/br-165.dat'

SPECS = [
    Vehicle(
        name='BR-165Front',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1991,
        intro_month=8,
        retire_year=1998,
        retire_month=11,
        speed=120,
        length=13,
        weight=37,
        axles=4,
        power=260,
        gear=50,
        tractive_effort=55,
        brake_force=27,
        rolling_resistance=13,
        payload=60,
        min_loading_time=17,
        max_loading_time=55,
        overcrowded_capacity=66,
        cost=1752000,
        runningcost=78,
        fixed_cost=6913,
        increase_maintenance_after_years=23,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-light',
        sound='konakaboom-class-165.wav',
        constraint_prev=['BR-165Rear', 'BR-166Rear', 'none'],
        constraint_next=['BR-165Rear', 'BR-165Middle'],
        payload_by_class=[0, 60, 0, 24],
        comfort_by_class=[0, 84, 0, 110],
        liverytype=['NSE-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-165Middle',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1991,
        intro_month=8,
        retire_year=1998,
        retire_month=11,
        speed=120,
        length=13,
        weight=37,
        axles=4,
        power=260,
        gear=50,
        tractive_effort=55,
        brake_force=27,
        payload=106,
        min_loading_time=17,
        max_loading_time=55,
        overcrowded_capacity=80,
        cost=1752000,
        runningcost=78,
        fixed_cost=913,
        increase_maintenance_after_years=23,
        bidirectional=1,
        can_lead_from_rear=0,
        smoke='Diesel-light',
        constraint_prev=['BR-165Front', 'BR-165Middle'],
        constraint_next=['BR-165Rear'],
        payload_by_class=[0, 106, 0, 0],
        comfort_by_class=[0, 84, 0, 110],
        liverytype=['NSE-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-165Rear',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1991,
        intro_month=8,
        retire_year=1998,
        retire_month=11,
        speed=120,
        length=13,
        weight=39,
        axles=4,
        power=260,
        gear=50,
        tractive_effort=55,
        brake_force=27,
        rolling_resistance=13,
        payload=94,
        min_loading_time=17,
        max_loading_time=55,
        overcrowded_capacity=74,
        cost=1752000,
        runningcost=78,
        fixed_cost=6913,
        increase_maintenance_after_years=23,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-light',
        sound='konakaboom-class-165.wav',
        constraint_prev=['BR-165Middle', 'BR-165Front'],
        constraint_next=['BR-165Front', 'BR-166Front', 'none'],
        payload_by_class=[0, 94, 0, 0],
        comfort_by_class=[0, 84, 0, 110],
        liverytype=['NSE-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
