"""br-110."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# https://railcar.co.uk/type/class-110/
_BLEND = 'trains/Railcars/br-110-dmbc-bg.blend'
_UPSTREAM_DAT = 'trains/br-110.dat'

SPECS = [
    Vehicle(
        name='BR-110-DMBC',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1961,
        intro_month=7,
        retire_year=1985,
        retire_month=4,
        speed=113,
        length=10,
        weight=32.5,
        axles=4,
        power=268,
        gear=50,
        tractive_effort=40,
        payload=33,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=18,
        cost=1367500,
        runningcost=268,
        fixed_cost=8459,
        increase_maintenance_after_years=4,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='spompeytransportvideo-class-117.wav',
        constraint_prev=['BR-121', 'BR-117-DMS', 'BR-104Rear', 'BR-128', 'BR-101-DMCL', 'BR-101-DTCL', 'BR-114-DTCL', 'BR-120-DMSL', 'BR-110-DMCL', 'none'],
        constraint_next=['BR-110-DMCL', 'BR-110-TSL'],
        payload_by_class=[0, 33, 0, 12],
        comfort_by_class=[0, 80, 0, 107],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-110-TSL',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1961,
        intro_month=7,
        retire_year=1985,
        retire_month=4,
        speed=113,
        length=10,
        weight=24.4,
        axles=4,
        power=0,
        payload=72,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=30,
        cost=620000,
        runningcost=0,
        fixed_cost=714,
        increase_maintenance_after_years=4,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-110-DMBC'],
        constraint_next=['BR-110-DMCL'],
        payload_by_class=[0, 72, 0, 0],
        comfort_by_class=[0, 80, 0, 107],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-110-DMCL',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1961,
        intro_month=7,
        retire_year=1985,
        retire_month=4,
        speed=113,
        length=10,
        weight=32.0,
        axles=4,
        power=268,
        gear=50,
        tractive_effort=40,
        payload=54,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=32,
        cost=1367500,
        runningcost=268,
        fixed_cost=8459,
        increase_maintenance_after_years=4,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        constraint_prev=['BR-110-TSL', 'BR-110-DMBC'],
        constraint_next=['BR-121', 'BR-117-DMBS', 'BR-104Front', 'BR-128', 'BR-101-DMBS', 'BR-120-DMBC', 'BR-114-DMBS', 'BR-110-DMBC', 'none'],
        payload_by_class=[0, 54, 0, 12],
        comfort_by_class=[0, 80, 0, 107],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
