"""br-123."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://www.railcar.co.uk/type/class-123/numbering
_BLEND = 'trains/Railcars/br-123-dmbs-bg.blend'
_UPSTREAM_DAT = 'trains/br-123.dat'

SPECS = [
    Vehicle(
        name='BR-123-DMBS',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1963,
        intro_month=5,
        retire_year=1977,
        retire_month=8,
        speed=112,
        length=11,
        weight=42,
        axles=4,
        power=343,
        gear=50,
        tractive_effort=57,
        payload=32,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=11,
        cost=1471000,
        runningcost=172,
        fixed_cost=11022,
        increase_maintenance_after_years=5,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='video47-class-121.wav',
        constraint_prev=['BR-123-TS', 'BR-123-TBS'],
        constraint_next=['BR-123-DMS', 'none'],
        payload_by_class=[0, 32, 0, 0],
        comfort_by_class=[0, 125, 0, 145],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-123-TCK',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1963,
        intro_month=5,
        retire_year=1977,
        retire_month=8,
        speed=112,
        length=11,
        weight=37,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=24,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=16,
        cost=602100,
        runningcost=0,
        fixed_cost=717,
        increase_maintenance_after_years=5,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-123-DMS'],
        constraint_next=['BR-123-TS', 'BR-123-TBS'],
        payload_by_class=[0, 24, 0, 24],
        comfort_by_class=[0, 125, 0, 145],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-123-TS',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1963,
        intro_month=5,
        retire_year=1977,
        retire_month=8,
        speed=112,
        length=11,
        weight=33,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=64,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=21,
        cost=602100,
        runningcost=0,
        fixed_cost=717,
        increase_maintenance_after_years=5,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-123-TCK'],
        constraint_next=['BR-123-DMBS'],
        payload_by_class=[0, 64, 0, 0],
        comfort_by_class=[0, 125, 0, 145],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-123-TBS',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1963,
        intro_month=5,
        retire_year=1977,
        retire_month=8,
        speed=112,
        length=11,
        weight=34,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=32,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=15,
        catering_level=3,
        cost=758000,
        runningcost=0,
        fixed_cost=902,
        increase_maintenance_after_years=5,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-123-TCK'],
        constraint_next=['BR-123-DMBS'],
        payload_by_class=[0, 32, 0, 0],
        comfort_by_class=[0, 125, 0, 145],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-123-DMS',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1963,
        intro_month=5,
        retire_year=1977,
        retire_month=8,
        speed=112,
        length=11,
        weight=42,
        axles=4,
        power=343,
        gear=50,
        tractive_effort=57,
        payload=56,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=22,
        cost=1471000,
        runningcost=172,
        fixed_cost=11022,
        increase_maintenance_after_years=5,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='video47-class-121.wav',
        constraint_prev=['BR-123-DMBS', 'none'],
        constraint_next=['BR-123-TCK'],
        payload_by_class=[0, 56, 0, 0],
        comfort_by_class=[0, 125, 0, 145],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
