"""br-104."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://www.railcar.co.uk/print/diagrams/558.jpg
# DMCL
_BLEND = 'trains/Railcars/br-104-bg-nse.blend'
_UPSTREAM_DAT = 'trains/br-104.dat'

SPECS = [
    Vehicle(
        name='BR-104Front',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1957,
        intro_month=9,
        retire_year=1970,
        retire_month=6,
        speed=113,
        length=10,
        weight=32,
        axles=4,
        power=224,
        gear=50,
        tractive_effort=32,
        payload=54,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=40,
        cost=1250000,
        runningcost=224,
        fixed_cost=7302,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='spompeytransportvideo-class-117.wav',
        constraint_prev=['BR-121', 'BR-117-DMS', 'BR-104Rear', 'BR-128', 'BR-101-DMCL', 'BR-101-DTCL', 'BR-114-DTCL', 'BR-120-DMSL', 'BR-110-DMCL', 'none'],
        constraint_next=['BR-104Rear', 'BR-104Middle'],
        payload_by_class=[0, 54, 0, 12],
        comfort_by_class=[0, 80, 0, 107],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'Regional-Railways-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-104Middle',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1957,
        intro_month=9,
        retire_year=1970,
        retire_month=6,
        speed=113,
        length=10,
        weight=23,
        axles=4,
        power=0,
        payload=69,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=27,
        cost=600000,
        runningcost=0,
        fixed_cost=714,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-104Front', 'BR-104Middle'],
        constraint_next=['BR-104Rear'],
        payload_by_class=[0, 69, 0, 0],
        comfort_by_class=[0, 80, 0, 107],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'Regional-Railways-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-104Rear',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1957,
        intro_month=9,
        retire_year=1970,
        retire_month=6,
        speed=113,
        length=10,
        weight=32,
        axles=4,
        power=224,
        gear=50,
        tractive_effort=32,
        payload=52,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=31,
        cost=1250000,
        runningcost=224,
        fixed_cost=7302,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='video47-class-121.wav',
        constraint_prev=['BR-104Middle', 'BR-104Front'],
        constraint_next=['BR-121', 'BR-117-DMBS', 'BR-104Front', 'BR-128', 'BR-101-DMBS', 'BR-120-DMBC', 'BR-114-DMBS', 'BR-110-DMBC', 'none'],
        payload_by_class=[0, 52, 0, 0],
        comfort_by_class=[0, 80, 0, 107],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'Regional-Railways-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
