"""br-117."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://www.railcar.co.uk/print/diagrams/852.jpg
_BLEND = 'trains/Railcars/br-117-tcl-g-new-bad-align.blend'
_UPSTREAM_DAT = 'trains/br-117.dat'

SPECS = [
    Vehicle(
        name='BR-117-DMS',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1959,
        intro_month=9,
        retire_year=1980,
        retire_month=11,
        speed=113,
        length=11,
        weight=36.5,
        axles=4,
        power=224,
        gear=50,
        tractive_effort=32,
        payload=89,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=90,
        cost=1290000,
        runningcost=224,
        fixed_cost=11344,
        increase_maintenance_after_years=10,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='spompeytransportvideo-class-117.wav',
        constraint_prev=['BR-121', 'BR-117-DMBS', 'BR-117-TCL', 'BR-128'],
        constraint_next=['BR-121', 'BR-117-DMBS', 'BR-104Front', 'BR-128', 'BR-101-DMBS', 'BR-120-DMBC', 'BR-114-DMBS', 'BR-110-DMBC', 'none'],
        payload_by_class=[0, 89, 0, 0],
        comfort_by_class=[0, 75, 0, 88],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'Regional-Railways-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-117-TCL',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1959,
        intro_month=9,
        retire_year=1980,
        retire_month=11,
        speed=113,
        length=11,
        weight=30.5,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=48,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=75,
        cost=605000,
        runningcost=0,
        fixed_cost=720,
        increase_maintenance_after_years=10,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-117-DMBS'],
        constraint_next=['BR-117-DMS'],
        payload_by_class=[0, 48, 0, 22],
        comfort_by_class=[0, 75, 0, 88],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'Regional-Railways-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-117-DMBS',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1959,
        intro_month=9,
        retire_year=1980,
        retire_month=11,
        speed=113,
        length=11,
        weight=36.5,
        axles=4,
        power=224,
        gear=50,
        tractive_effort=32,
        payload=65,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=65,
        cost=1290000,
        runningcost=224,
        fixed_cost=11344,
        increase_maintenance_after_years=10,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='video47-class-121.wav',
        constraint_prev=['BR-121', 'BR-117-DMS', 'BR-104Rear', 'BR-128', 'BR-101-DMCL', 'BR-101-DTCL', 'BR-114-DTCL', 'BR-120-DMSL', 'BR-110-DMCL', 'none'],
        constraint_next=['BR-121', 'BR-117-DMS', 'BR-117-TCL', 'BR-104Front', 'BR-128'],
        payload_by_class=[0, 65, 0, 0],
        comfort_by_class=[0, 75, 0, 88],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'Regional-Railways-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
