"""br-180."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/br-180-a-fgw.blend'
_UPSTREAM_DAT = 'trains/br-180.dat'

SPECS = [
    Vehicle(
        name='BR-180Front',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=2000,
        intro_month=7,
        retire_year=2017,
        retire_month=9,
        speed=200,
        length=14,
        weight=52,
        axles=4,
        power=560,
        gear=50,
        tractive_effort=56,
        brake_force=39,
        rolling_resistance=13,
        payload=48,
        min_loading_time=30,
        max_loading_time=150,
        overcrowded_capacity=13,
        cost=2705000,
        runningcost=112,
        fixed_cost=7409,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='video47-class-175.wav',
        constraint_prev=['BR-180Rear', 'none'],
        constraint_next=['BR-180Rear', 'BR-180Middle', 'BR-180Middle-Buffet', 'BR-180Middle-first'],
        payload_by_class=[0, 48, 0, 0],
        comfort_by_class=[0, 134, 0, 153],
        liverytype=['Firstgroup-Mauve'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-180Middle',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=2000,
        intro_month=7,
        retire_year=2017,
        retire_month=9,
        speed=200,
        length=13,
        weight=50,
        axles=4,
        power=560,
        gear=50,
        tractive_effort=56,
        brake_force=38,
        rolling_resistance=13,
        payload=72,
        min_loading_time=30,
        max_loading_time=150,
        overcrowded_capacity=20,
        catering_level=1,
        cost=2705000,
        runningcost=112,
        fixed_cost=1409,
        bidirectional=1,
        can_lead_from_rear=0,
        smoke='Diesel',
        constraint_prev=['BR-180Front', 'BR-180Middle', 'BR-180Middle-Buffet', 'BR-180Middle-first'],
        constraint_next=['BR-180Rear', 'BR-180Middle', 'BR-180Middle-Buffet', 'BR-180Middle-first'],
        payload_by_class=[0, 72, 0, 0],
        comfort_by_class=[0, 134, 0, 153],
        liverytype=['Firstgroup-Mauve'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-180Middle-first',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=2000,
        intro_month=7,
        retire_year=2017,
        retire_month=9,
        speed=200,
        length=13,
        weight=50,
        axles=4,
        power=560,
        gear=50,
        tractive_effort=56,
        brake_force=38,
        rolling_resistance=13,
        payload=40,
        min_loading_time=30,
        max_loading_time=150,
        overcrowded_capacity=20,
        catering_level=1,
        cost=2705000,
        runningcost=112,
        fixed_cost=1409,
        bidirectional=1,
        can_lead_from_rear=0,
        smoke='Diesel',
        constraint_prev=['BR-180Front', 'BR-180Middle', 'BR-180Middle-Buffet', 'BR-180Middle-first'],
        constraint_next=['BR-180Rear', 'BR-180Middle', 'BR-180Middle-Buffet', 'BR-180Middle-first'],
        payload_by_class=[0, 0, 0, 40],
        comfort_by_class=[0, 134, 0, 153],
        liverytype=['Firstgroup-Mauve'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-180Middle-Buffet',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=2000,
        intro_month=7,
        retire_year=2017,
        retire_month=9,
        speed=200,
        length=13,
        weight=50,
        axles=4,
        power=560,
        gear=50,
        tractive_effort=56,
        payload=56,
        min_loading_time=30,
        max_loading_time=150,
        overcrowded_capacity=20,
        catering_level=2,
        cost=2957000,
        runningcost=112,
        fixed_cost=19540,
        bidirectional=1,
        can_lead_from_rear=0,
        smoke='Diesel',
        constraint_prev=['BR-180Front', 'BR-180Middle', 'BR-180Middle-first'],
        constraint_next=['BR-180Rear', 'BR-180Middle', 'BR-180Middle-first'],
        payload_by_class=[0, 56, 0, 0],
        comfort_by_class=[0, 134, 0, 153],
        liverytype=['Firstgroup-Mauve'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-180Rear',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=2000,
        intro_month=7,
        retire_year=2017,
        retire_month=9,
        speed=200,
        length=14,
        weight=51,
        axles=4,
        power=560,
        gear=50,
        tractive_effort=56,
        brake_force=39,
        rolling_resistance=13,
        payload=58,
        min_loading_time=30,
        max_loading_time=150,
        overcrowded_capacity=16,
        cost=2705000,
        runningcost=112,
        fixed_cost=7409,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='video47-class-175.wav',
        constraint_prev=['BR-180Front', 'BR-180Middle', 'BR-180Middle-Buffet', 'BR-180Middle-first'],
        constraint_next=['BR-180Front', 'none'],
        payload_by_class=[0, 58, 0, 0],
        comfort_by_class=[0, 134, 0, 153],
        liverytype=['Firstgroup-Mauve'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
