"""br-150."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/br-150-a-provincial.blend'
_UPSTREAM_DAT = 'trains/br-150.dat'

SPECS = [
    Vehicle(
        name='br-150-front',
        waytype='track',
        copyright='Kieron/Jamespetts/Rollmaterial',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1984,
        intro_month=3,
        retire_year=1993,
        retire_month=9,
        speed=121,
        length=10,
        weight=36,
        axles=4,
        power=212,
        gear=50,
        tractive_effort=36,
        brake_force=27,
        rolling_resistance=13,
        payload=84,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=63,
        cost=1840000,
        runningcost=64,
        fixed_cost=6958,
        increase_maintenance_after_years=24,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-light',
        sound='spompeytransportvideo-class-150.wav',
        constraint_prev=['br-150-rear', 'br-153', 'br-153-trolley', 'br-158-rear', 'br-156-rear', 'br-142-rear', 'br-141-1-rear', 'br-142-1-rear', 'br-144-0-rear', 'br-144-1-rear', 'BR-170Rear', 'br-159-rear', 'none'],
        constraint_next=['br-150-rear', 'br-150-centre'],
        payload_by_class=[0, 84],
        comfort_by_class=[0, 82],
        liverytype=['Provincial', 'Sprinter', 'Regional-Railways-Standard', 'Anglia-original'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='br-150-centre',
        waytype='track',
        copyright='Kieron/Jamespetts/Rollmaterial',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1984,
        intro_month=3,
        retire_year=1993,
        retire_month=9,
        speed=121,
        length=10,
        weight=36,
        axles=4,
        power=212,
        gear=50,
        tractive_effort=36,
        brake_force=27,
        rolling_resistance=13,
        payload=79,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=59,
        cost=1840000,
        runningcost=64,
        fixed_cost=958,
        increase_maintenance_after_years=24,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-light',
        constraint_prev=['br-150-front'],
        constraint_next=['br-150-rear'],
        payload_by_class=[0, 79],
        comfort_by_class=[0, 82],
        liverytype=['Provincial', 'Sprinter', 'Regional-Railways-Standard', 'Anglia-original'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='br-150-rear',
        waytype='track',
        copyright='Kieron/Jamespetts/Rollmaterial',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1984,
        intro_month=3,
        retire_year=1993,
        retire_month=9,
        speed=121,
        length=10,
        weight=36,
        power=212,
        gear=50,
        tractive_effort=36,
        brake_force=27,
        rolling_resistance=13,
        payload=79,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=59,
        cost=1840000,
        runningcost=64,
        fixed_cost=6958,
        increase_maintenance_after_years=24,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        constraint_prev=['br-150-front', 'br-150-centre'],
        constraint_next=['br-150-front', 'br-153', 'br-158-front', 'br-156-front', 'br-153-trolley', 'br-156-front-trolley', 'br-142-front', 'br-141-1-front', 'br-142-1-front', 'br-144-0-front', 'br-144-1-front', 'BR-170Front', 'br-159-front', 'none'],
        payload_by_class=[0, 79],
        comfort_by_class=[0, 82],
        liverytype=['Provincial', 'Sprinter', 'Regional-Railways-Standard', 'Anglia-original'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
