"""br-156."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/br-156-a-sprinter.blend'
_UPSTREAM_DAT = 'trains/br-156.dat'

SPECS = [
    Vehicle(
        name='br-156-front',
        waytype='track',
        copyright='Kieron/Rollmaterial/jamespetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1987,
        intro_month=7,
        retire_year=1998,
        retire_month=11,
        speed=120,
        length=13,
        weight=36,
        axles=4,
        power=212,
        gear=50,
        tractive_effort=47,
        brake_force=27,
        payload=84,
        min_loading_time=20,
        max_loading_time=65,
        overcrowded_capacity=34,
        cost=1960000,
        runningcost=64,
        fixed_cost=7021,
        upgrade_price=0,
        increase_maintenance_after_years=23,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-light',
        sound='spompeytransportvideo-class-150.wav',
        constraint_prev=['br-150-rear', 'br-153', 'br-153-trolley', 'br-158-rear', 'br-156-rear', 'br-142-rear', 'br-141-1-rear', 'br-142-1-rear', 'br-144-0-rear', 'br-144-1-rear', 'BR-170Rear', 'br-159-rear', 'none'],
        constraint_next=['br-156-rear'],
        payload_by_class=[0, 84],
        comfort_by_class=[0, 95],
        liverytype=['Regional-Railways-Standard', 'One', 'Provincial', 'Strathclyde-orange-black', 'Strathclyde-carmine-cream', 'NXEA', 'Abellio-Greater-Anglia'],
        upgrade=['br-156-front-trolley'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='br-156-front-trolley',
        waytype='track',
        copyright='Kieron/Rollmaterial/jamespetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1987,
        intro_month=7,
        retire_year=1998,
        retire_month=11,
        speed=120,
        length=13,
        weight=36,
        axles=4,
        power=212,
        gear=50,
        tractive_effort=47,
        brake_force=27,
        payload=84,
        min_loading_time=20,
        max_loading_time=65,
        overcrowded_capacity=30,
        catering_level=1,
        cost=1990000,
        runningcost=64,
        fixed_cost=19036,
        upgrade_price=1500,
        increase_maintenance_after_years=23,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-light',
        constraint_prev=['br-150-rear', 'br-153', 'br-153-trolley', 'br-158-rear', 'br-156-rear', 'br-142-rear', 'br-141-1-rear', 'br-142-1-rear', 'br-144-0-rear', 'br-144-1-rear', 'BR-170Rear', 'br-159-rear', 'none'],
        constraint_next=['br-156-rear'],
        payload_by_class=[0, 84],
        comfort_by_class=[0, 95],
        liverytype=['Regional-Railways-Standard', 'One', 'Provincial', 'Strathclyde-orange-black', 'Strathclyde-carmine-cream', 'NXEA', 'Abellio-Greater-Anglia'],
        upgrade=['br-156-front'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='br-156-rear',
        waytype='track',
        copyright='Kieron/Rollmaterial/jamespetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1987,
        intro_month=7,
        retire_year=1998,
        retire_month=11,
        speed=120,
        length=13,
        weight=36,
        axles=4,
        power=212,
        gear=50,
        tractive_effort=47,
        brake_force=27,
        rolling_resistance=13,
        payload=79,
        min_loading_time=20,
        max_loading_time=65,
        overcrowded_capacity=32,
        cost=1960000,
        runningcost=64,
        fixed_cost=7021,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-light',
        sound='konakaboom-class-159.wav',
        constraint_prev=['br-156-front', 'br-156-front-trolley'],
        constraint_next=['br-150-front', 'br-153', 'br-158-front', 'br-156-front', 'br-153-trolley', 'br-156-front-trolley', 'br-142-front', 'br-141-1-front', 'br-142-1-front', 'br-144-0-front', 'br-144-1-front', 'BR-170Front', 'br-159-front', 'none'],
        payload_by_class=[0, 79],
        comfort_by_class=[0, 95],
        liverytype=['Regional-Railways-Standard', 'One', 'Provincial', 'Strathclyde-orange-black', 'Strathclyde-carmine-cream', 'NXEA', 'Abellio-Greater-Anglia'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
