"""br-101."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://www.railcar.co.uk/print/diagrams/523.jpg
_BLEND = 'trains/Railcars/BR-101-trailer-blue-grey.blend'
_UPSTREAM_DAT = 'trains/br-101.dat'

SPECS = [
    Vehicle(
        name='BR-101-DMBS',
        waytype='track',
        copyright='Junna/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1956,
        intro_month=3,
        retire_year=1959,
        retire_month=12,
        speed=113,
        length=10,
        weight=32.5,
        axles=4,
        power=224,
        gear=50,
        tractive_effort=31,
        payload=52,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=31,
        cost=1240000,
        runningcost=224,
        fixed_cost=11292,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='video47-class-121.wav',
        constraint_prev=['BR-121', 'BR-117-DMS', 'BR-104Rear', 'BR-128', 'BR-101-DMCL', 'BR-101-DTCL', 'BR-114-DTCL', 'BR-120-DMSL', 'BR-110-DMCL', 'none'],
        constraint_next=['BR-101-TSL', 'BR-101-DMCL', 'BR-101-DTCL'],
        payload_by_class=[0, 52, 0, 0],
        comfort_by_class=[0, 82, 0, 0],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'NSE-Revised', 'Regional-Railways-Standard', 'Strathclyde-orange-black'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-101-TSL',
        waytype='track',
        copyright='Junna/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1956,
        intro_month=3,
        retire_year=1959,
        retire_month=12,
        speed=113,
        length=10,
        weight=25.5,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=71,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=25,
        cost=591000,
        runningcost=0,
        fixed_cost=704,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-101-DMBS'],
        constraint_next=['BR-101-DMCL', 'BR-101-DTCL'],
        payload_by_class=[0, 71, 0, 0],
        comfort_by_class=[0, 82, 0, 0],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'Regional-Railways-Standard', 'Strathclyde-orange-black'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-101-DMCL',
        waytype='track',
        copyright='Junna/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1956,
        intro_month=3,
        retire_year=1959,
        retire_month=12,
        speed=113,
        length=10,
        weight=32.5,
        axles=4,
        power=224,
        gear=50,
        tractive_effort=31,
        payload=53,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=28,
        cost=1240000,
        runningcost=224,
        fixed_cost=11292,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='video47-class-121.wav',
        constraint_prev=['BR-101-TSL', 'BR-101-DMBS'],
        constraint_next=['BR-121', 'BR-117-DMBS', 'BR-104Front', 'BR-128', 'BR-101-DMBS', 'BR-120-DMBC', 'BR-114-DMBS', 'BR-110-DMBC', 'none'],
        payload_by_class=[0, 53, 0, 12],
        comfort_by_class=[0, 82, 0, 110],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'NSE-Revised', 'Regional-Railways-Standard', 'Strathclyde-orange-black'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-101-DTCL',
        waytype='track',
        copyright='Junna/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1956,
        intro_month=3,
        retire_year=1959,
        retire_month=12,
        speed=113,
        length=10,
        weight=26.5,
        axles=4,
        power=0,
        gear=50,
        tractive_effort=0,
        payload=53,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=28,
        cost=620000,
        runningcost=0,
        fixed_cost=738,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-121.wav',
        constraint_prev=['BR-101-TSL', 'BR-101-DMBS'],
        constraint_next=['BR-121', 'BR-117-DMBS', 'BR-104Front', 'BR-128', 'BR-101-DMBS', 'BR-120-DMBC', 'BR-114-DMBS', 'BR-110-DMBC', 'none'],
        payload_by_class=[0, 53, 0, 12],
        comfort_by_class=[0, 82, 0, 110],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'NSE-Revised', 'Regional-Railways-Standard', 'Strathclyde-orange-black'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
