"""br-158."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/br-158-a.blend'
_UPSTREAM_DAT = 'trains/br-158.dat'

SPECS = [
    Vehicle(
        name='br-158-front',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1990,
        intro_month=4,
        retire_year=1998,
        retire_month=1,
        speed=145,
        length=12,
        weight=38.5,
        axles=4,
        power=260,
        gear=50,
        tractive_effort=50,
        brake_force=29,
        rolling_resistance=13,
        payload=70,
        min_loading_time=25,
        max_loading_time=70,
        overcrowded_capacity=23,
        cost=2100000,
        runningcost=78,
        fixed_cost=7094,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-light',
        sound='konakaboom-class-159.wav',
        constraint_prev=['br-150-rear', 'br-153', 'br-153-trolley', 'br-158-rear', 'br-156-rear', 'br-142-rear', 'br-141-1-rear', 'br-142-1-rear', 'br-144-0-rear', 'br-144-1-rear', 'BR-170Rear', 'br-159-rear', 'none'],
        constraint_next=['br-158-rear', 'br-158-centre'],
        payload_by_class=[0, 70],
        comfort_by_class=[0, 118],
        liverytype=['Regional-Railways-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='br-158-centre',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1990,
        intro_month=4,
        retire_year=1998,
        retire_month=1,
        speed=145,
        length=12,
        weight=38.5,
        axles=4,
        power=260,
        gear=50,
        tractive_effort=50,
        brake_force=29,
        rolling_resistance=13,
        payload=72,
        min_loading_time=25,
        max_loading_time=70,
        overcrowded_capacity=24,
        catering_level=1,
        cost=2100000,
        runningcost=78,
        fixed_cost=1094,
        bidirectional=1,
        can_lead_from_rear=0,
        smoke='Diesel-light',
        constraint_prev=['br-158-front'],
        constraint_next=['br-158-rear'],
        payload_by_class=[0, 72],
        comfort_by_class=[0, 118],
        liverytype=['Regional-Railways-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='br-158-rear',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1990,
        intro_month=4,
        retire_year=1998,
        retire_month=1,
        speed=145,
        length=12,
        weight=38.5,
        axles=4,
        power=260,
        gear=50,
        tractive_effort=50,
        brake_force=29,
        rolling_resistance=13,
        payload=68,
        min_loading_time=25,
        max_loading_time=70,
        overcrowded_capacity=23,
        cost=2100000,
        runningcost=78,
        fixed_cost=7094,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-light',
        constraint_prev=['br-158-centre', 'br-158-front'],
        constraint_next=['br-150-front', 'br-153', 'br-158-front', 'br-156-front', 'br-153-trolley', 'br-156-front-trolley', 'br-142-front', 'br-141-1-front', 'br-142-1-front', 'br-144-0-front', 'br-144-1-front', 'BR-170Front', 'br-159-front', 'none'],
        payload_by_class=[0, 68],
        comfort_by_class=[0, 118],
        liverytype=['Regional-Railways-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
