"""br-210."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/br-210-trailer-composite-nse.blend'
_UPSTREAM_DAT = 'trains/br-210.dat'

SPECS = [
    Vehicle(
        name='BR-210-DM',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1981,
        intro_month=3,
        retire_year=1992,
        retire_month=1,
        speed=145,
        length=10,
        weight=62,
        axles=4,
        power=850,
        gear=50,
        tractive_effort=65,
        payload=37,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=15,
        cost=1400000,
        runningcost=255,
        fixed_cost=10729,
        increase_maintenance_after_years=16,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='spompeytransportvideo-class-205.wav',
        constraint_prev=['BR-210-DTSOL', 'none'],
        constraint_next=['BR-210-TSO', 'BR-210-TCOL'],
        payload_by_class=[0, 37, 0, 0],
        comfort_by_class=[0, 89, 0, 148],
        liverytype=['BR-Blue', 'Regional-Railways', 'NSE-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-210-TSO',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1981,
        intro_month=3,
        retire_year=1992,
        retire_month=1,
        speed=145,
        length=10,
        weight=51,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=78,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=50,
        cost=580000,
        runningcost=0,
        fixed_cost=1208,
        increase_maintenance_after_years=16,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-210-DM', 'BR-210-TSO', 'BR-210-TCOL'],
        constraint_next=['BR-210-DTSOL', 'BR-210-TSO', 'BR-210-TCOL'],
        payload_by_class=[0, 78, 0, 0],
        comfort_by_class=[0, 89, 0, 148],
        liverytype=['BR-Blue', 'Regional-Railways', 'NSE-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-210-TCOL',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1981,
        intro_month=3,
        retire_year=1992,
        retire_month=1,
        speed=145,
        length=10,
        weight=51,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=52,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=38,
        cost=580000,
        runningcost=0,
        fixed_cost=1208,
        increase_maintenance_after_years=16,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-210-DM', 'BR-210-TSO', 'BR-210-TCOL'],
        constraint_next=['BR-210-DTSOL', 'BR-210-TSO', 'BR-210-TCOL'],
        payload_by_class=[0, 52, 0, 18],
        comfort_by_class=[0, 89, 0, 148],
        liverytype=['BR-Blue', 'Regional-Railways', 'NSE-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-210-DTSOL',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1981,
        intro_month=3,
        retire_year=1992,
        retire_month=1,
        speed=145,
        length=10,
        weight=53,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=78,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=50,
        cost=1400000,
        runningcost=0,
        fixed_cost=2917,
        increase_maintenance_after_years=16,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='spompeytransportvideo-class-205.wav',
        constraint_prev=['BR-210-TSO', 'BR-210-TCOL'],
        constraint_next=['BR-210-DM', 'none'],
        payload_by_class=[0, 78, 0, 0],
        comfort_by_class=[0, 89, 0, 148],
        liverytype=['BR-Blue', 'Regional-Railways', 'NSE-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
