"""br-202."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/br-202-trailer-first-bg.blend'
_UPSTREAM_DAT = 'trains/br-202.dat'

SPECS = [
    Vehicle(
        name='BR-202-front',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1957,
        intro_month=4,
        retire_year=1963,
        retire_month=9,
        speed=120,
        length=11,
        weight=55.9,
        axles=4,
        power=370,
        gear=50,
        tractive_effort=28,
        payload=32,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=11,
        cost=3500000,
        runningcost=371,
        fixed_cost=9646,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-heavy',
        sound='spompeytransportvideo-class-205.wav',
        constraint_prev=['BR-205Rear', 'BR-202-rear', 'none'],
        constraint_next=['BR-202-rear', 'BR-202-trailer', 'BR-202-buffet', 'BR-202-trailer-first'],
        payload_by_class=[0, 32, 0, 0],
        comfort_by_class=[0, 129, 0, 146],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-202-rear',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1957,
        intro_month=4,
        retire_year=1963,
        retire_month=9,
        speed=120,
        length=11,
        weight=55.9,
        axles=4,
        power=370,
        tractive_effort=28,
        payload=32,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=11,
        cost=3500000,
        runningcost=371,
        fixed_cost=9646,
        increase_maintenance_after_years=15,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='spompeytransportvideo-class-205.wav',
        constraint_prev=['BR-202-front', 'BR-202-trailer', 'BR-202-buffet', 'BR-202-trailer-first'],
        constraint_next=['BR-205Front', 'BR-202-front', 'none'],
        payload_by_class=[0, 32, 0, 0],
        comfort_by_class=[0, 129, 0, 146],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-202-trailer',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1957,
        intro_month=4,
        retire_year=1963,
        retire_month=9,
        speed=120,
        length=11,
        weight=30,
        axles=4,
        power=0,
        payload=64,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=21,
        cost=1300000,
        runningcost=0,
        fixed_cost=1548,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-202-front', 'BR-202-trailer', 'BR-202-buffet', 'BR-202-trailer-first'],
        constraint_next=['BR-202-rear', 'BR-202-trailer', 'BR-202-buffet', 'BR-202-trailer-first'],
        payload_by_class=[0, 64, 0, 0],
        comfort_by_class=[0, 129, 0, 146],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-202-trailer-first',
        waytype='track',
        copyright='Junna/Cake/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1957,
        intro_month=4,
        retire_year=1963,
        retire_month=9,
        speed=120,
        length=11,
        weight=30,
        axles=4,
        power=0,
        payload=48,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=24,
        cost=1300000,
        runningcost=0,
        fixed_cost=1548,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-202-front', 'BR-202-trailer', 'BR-202-buffet', 'BR-202-trailer-first'],
        constraint_next=['BR-202-rear', 'BR-202-trailer', 'BR-202-buffet', 'BR-202-trailer-first'],
        payload_by_class=[0, 0, 0, 48],
        comfort_by_class=[0, 129, 0, 146],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-202-buffet',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1957,
        intro_month=4,
        retire_year=1963,
        retire_month=9,
        speed=120,
        length=11,
        weight=31,
        axles=4,
        power=0,
        payload=35,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=15,
        catering_level=3,
        cost=1300000,
        runningcost=0,
        fixed_cost=19548,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-202-front', 'BR-202-trailer', 'BR-202-trailer-first'],
        constraint_next=['BR-202-rear', 'BR-202-trailer', 'BR-202-trailer-first'],
        payload_by_class=[0, 35, 0, 0],
        comfort_by_class=[0, 129, 0, 146],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
