"""br-251."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/br-251-kitchen-bg.blend'
_UPSTREAM_DAT = 'trains/br-251.dat'

SPECS = [
    Vehicle(
        name='BR-251FrontFirst',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1960,
        intro_month=7,
        retire_year=1965,
        retire_month=5,
        speed=145,
        length=11,
        weight=67,
        axles=4,
        power=750,
        gear=50,
        tractive_effort=65,
        payload=12,
        min_loading_time=45,
        max_loading_time=150,
        cost=39980,
        runningcost=375,
        fixed_cost=6028,
        increase_maintenance_after_years=15,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='spompeytransportvideo-class-52.wav',
        constraint_prev=['BR-251RearFirst', 'BR-251RearSecond', 'none'],
        constraint_next=['BR-251SecondParlour', 'BR-251FirstParlour', 'BR-251Kitchen'],
        payload_by_class=[0, 0, 0, 0, 12],
        comfort_by_class=[0, 0, 156, 0, 164],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-251FrontSecond',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1960,
        intro_month=7,
        retire_year=1965,
        retire_month=5,
        speed=145,
        length=11,
        weight=67,
        axles=4,
        power=750,
        gear=50,
        tractive_effort=65,
        payload=18,
        min_loading_time=45,
        max_loading_time=150,
        cost=39980,
        runningcost=375,
        fixed_cost=28,
        increase_maintenance_after_years=15,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='spompeytransportvideo-class-52.wav',
        constraint_prev=['BR-251RearFirst', 'BR-251RearSecond', 'none'],
        constraint_next=['BR-251SecondParlour', 'BR-251FirstParlour', 'BR-251Kitchen'],
        payload_by_class=[0, 0, 18, 0, 0],
        comfort_by_class=[0, 0, 156, 0, 164],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-251FirstParlour',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1960,
        intro_month=7,
        retire_year=1965,
        retire_month=5,
        speed=145,
        length=11,
        weight=33,
        axles=4,
        power=0,
        payload=36,
        min_loading_time=45,
        max_loading_time=150,
        cost=1142000,
        runningcost=0,
        fixed_cost=1360,
        increase_maintenance_after_years=15,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-251SecondParlour', 'BR-251FirstParlour', 'BR-251Kitchen', 'BR-251FrontFirst', 'BR-251FrontSecond'],
        constraint_next=['BR-251SecondParlour', 'BR-251FirstParlour', 'BR-251Kitchen', 'BR-251RearFirst', 'BR-251RearSecond'],
        payload_by_class=[0, 0, 0, 0, 36],
        comfort_by_class=[0, 0, 156, 0, 164],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-251SecondParlour',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1960,
        intro_month=7,
        retire_year=1965,
        retire_month=5,
        speed=145,
        length=11,
        weight=45,
        axles=4,
        payload=42,
        min_loading_time=45,
        max_loading_time=150,
        cost=1142000,
        runningcost=0,
        fixed_cost=1360,
        increase_maintenance_after_years=15,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-251SecondParlour', 'BR-251FirstParlour', 'BR-251Kitchen', 'BR-251FrontFirst', 'BR-251FrontSecond'],
        constraint_next=['BR-251SecondParlour', 'BR-251FirstParlour', 'BR-251Kitchen', 'BR-251RearFirst', 'BR-251RearSecond'],
        payload_by_class=[0, 0, 42, 0, 0],
        comfort_by_class=[0, 0, 156, 0, 164],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-251Kitchen',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1960,
        intro_month=7,
        retire_year=1965,
        retire_month=5,
        speed=145,
        length=11,
        weight=45,
        axles=4,
        payload=18,
        min_loading_time=45,
        max_loading_time=150,
        catering_level=5,
        cost=1657000,
        runningcost=0,
        fixed_cost=19973,
        increase_maintenance_after_years=15,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-251SecondParlour', 'BR-251FirstParlour', 'BR-251FrontFirst', 'BR-251FrontSecond'],
        constraint_next=['BR-251SecondParlour', 'BR-251FirstParlour', 'BR-251RearFirst', 'BR-251RearSecond'],
        payload_by_class=[0, 0, 0, 0, 18],
        comfort_by_class=[0, 0, 156, 0, 164],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-251RearFirst',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1960,
        intro_month=7,
        retire_year=1965,
        retire_month=5,
        speed=145,
        length=11,
        weight=67,
        axles=4,
        power=750,
        gear=50,
        tractive_effort=65,
        payload=12,
        min_loading_time=45,
        max_loading_time=150,
        cost=3998000,
        runningcost=375,
        fixed_cost=8776,
        increase_maintenance_after_years=15,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='spompeytransportvideo-class-52.wav',
        constraint_prev=['BR-251SecondParlour', 'BR-251FirstParlour', 'BR-251Kitchen'],
        constraint_next=['BR-251FrontFirst', 'BR-251FrontFirst', 'none'],
        payload_by_class=[0, 0, 0, 0, 12],
        comfort_by_class=[0, 0, 156, 0, 164],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-251RearSecond',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1960,
        intro_month=7,
        retire_year=1965,
        retire_month=5,
        speed=145,
        length=11,
        weight=67,
        axles=4,
        power=750,
        gear=50,
        tractive_effort=65,
        payload=18,
        min_loading_time=45,
        max_loading_time=150,
        cost=3998000,
        runningcost=375,
        fixed_cost=2776,
        increase_maintenance_after_years=15,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='spompeytransportvideo-class-52.wav',
        constraint_prev=['BR-251SecondParlour', 'BR-251FirstParlour', 'BR-251Kitchen'],
        constraint_next=['BR-251FrontFirst', 'BR-251FrontFirst', 'none'],
        payload_by_class=[0, 0, 18, 0, 0],
        comfort_by_class=[0, 0, 156, 0, 164],
        liverytype=['BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
