"""br-220."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/br-220-frontrear-xc.blend'
_UPSTREAM_DAT = 'trains/br-220.dat'

SPECS = [
    Vehicle(
        name='BR-220Front',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=2001,
        intro_month=2,
        retire_year=2004,
        retire_month=6,
        speed=200,
        length=14,
        weight=48,
        axles=4,
        power=560,
        gear=50,
        tractive_effort=47,
        brake_force=36,
        payload=26,
        min_loading_time=35,
        max_loading_time=240,
        overcrowded_capacity=8,
        cost=2415000,
        runningcost=112,
        fixed_cost=7258,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-light',
        sound='video47-class-220.wav',
        constraint_prev=['BR-220Rear', 'none'],
        constraint_next=['BR-220Rear', 'BR-220Middle', 'BR-220Middle-shop'],
        payload_by_class=[0, 0, 0, 26],
        comfort_by_class=[0, 97, 0, 130],
        liverytype=['Virgin-MU', 'Arriva-original'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-220Middle',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=2001,
        intro_month=2,
        retire_year=2004,
        retire_month=6,
        speed=200,
        length=13,
        weight=45,
        axles=4,
        power=560,
        gear=50,
        tractive_effort=47,
        brake_force=33,
        rolling_resistance=13,
        payload=66,
        min_loading_time=35,
        max_loading_time=240,
        overcrowded_capacity=12,
        catering_level=1,
        cost=2415000,
        runningcost=112,
        fixed_cost=1258,
        bidirectional=1,
        can_lead_from_rear=0,
        smoke='Diesel-light',
        constraint_prev=['BR-220Front', 'BR-220Middle', 'BR-220Middle-shop'],
        constraint_next=['BR-220Rear', 'BR-220Middle', 'BR-220Middle-shop'],
        payload_by_class=[0, 66, 0, 0],
        comfort_by_class=[0, 97, 0, 130],
        liverytype=['Virgin-MU', 'Arriva-original'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-220Middle-shop',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=2001,
        intro_month=2,
        retire_year=2004,
        retire_month=6,
        speed=200,
        length=13,
        weight=45,
        axles=4,
        power=560,
        gear=50,
        tractive_effort=47,
        brake_force=33,
        rolling_resistance=13,
        payload=50,
        min_loading_time=35,
        max_loading_time=240,
        overcrowded_capacity=10,
        catering_level=2,
        cost=2630000,
        runningcost=112,
        fixed_cost=1370,
        bidirectional=1,
        can_lead_from_rear=0,
        smoke='Diesel-light',
        constraint_prev=['BR-220Front', 'BR-220Middle'],
        constraint_next=['BR-220Rear', 'BR-220Middle'],
        payload_by_class=[0, 50, 0, 0],
        comfort_by_class=[0, 97, 0, 130],
        liverytype=['Virgin-MU', 'Arriva-original'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-220Rear',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=2001,
        intro_month=2,
        retire_year=2004,
        retire_month=6,
        speed=200,
        length=14,
        weight=48,
        axles=4,
        power=560,
        gear=50,
        tractive_effort=47,
        rolling_resistance=13,
        payload=42,
        min_loading_time=35,
        max_loading_time=240,
        cost=2415000,
        runningcost=112,
        fixed_cost=7258,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-light',
        sound='video47-class-220.wav',
        constraint_prev=['BR-220Middle', 'BR-220Front', 'BR-220Middle-shop'],
        constraint_next=['BR-220Front', 'none'],
        payload_by_class=[0, 42, 0, 0],
        comfort_by_class=[0, 97, 0, 130],
        liverytype=['Virgin-MU', 'Arriva-original'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
