"""br-205."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/br-205-a-blue-grey.blend'
_UPSTREAM_DAT = 'trains/br-205.dat'

SPECS = [
    Vehicle(
        name='BR-205Front',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1957,
        intro_month=3,
        retire_year=1962,
        retire_month=11,
        speed=120,
        length=11,
        weight=56,
        axles=4,
        power=750,
        gear=50,
        tractive_effort=56,
        payload=84,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=84,
        cost=3500000,
        runningcost=751,
        fixed_cost=9646,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel-heavy',
        sound='spompeytransportvideo-class-205.wav',
        constraint_prev=['BR-205Rear', 'BR-202-rear', 'none'],
        constraint_next=['BR-205Rear', 'BR-205Middle'],
        payload_by_class=[0, 84, 0, 0],
        comfort_by_class=[0, 77, 0, 129],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-205Rear',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1957,
        intro_month=3,
        retire_year=1962,
        retire_month=11,
        speed=120,
        length=11,
        weight=32,
        axles=4,
        power=0,
        payload=49,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=62,
        cost=3500000,
        runningcost=0,
        fixed_cost=4167,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='spompeytransportvideo-class-205.wav',
        constraint_prev=['BR-205Front', 'BR-205Middle'],
        constraint_next=['BR-205Front', 'BR-202-front', 'none'],
        payload_by_class=[0, 49, 0, 13],
        comfort_by_class=[0, 77, 0, 129],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-205Middle',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1957,
        intro_month=3,
        retire_year=1962,
        retire_month=11,
        speed=120,
        length=11,
        weight=31,
        axles=4,
        power=0,
        payload=104,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=104,
        cost=1300000,
        runningcost=0,
        fixed_cost=1548,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-205Front', 'BR-205Middle'],
        constraint_next=['BR-205Rear', 'BR-205Middle'],
        payload_by_class=[0, 104, 0, 0],
        comfort_by_class=[0, 77, 0, 129],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
