"""br-310."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# https://web.archive.org/web/20071014164950/http://www.therailwaycentre.com/Recognition%20Tech%20Data%20EMU/EMU_310.html
_BLEND = 'trains/Railcars/br-310-front-blue.blend'
_UPSTREAM_DAT = 'trains/br-310.dat'

SPECS = [
    Vehicle(
        name='BR-310-BDTSOL',
        waytype='track',
        copyright='Junna/Cake/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1965,
        intro_month=11,
        retire_year=1976,
        retire_month=10,
        speed=120,
        length=11,
        weight=36.8,
        axles=4,
        power=0,
        payload=80,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=45,
        cost=1272000,
        runningcost=0,
        fixed_cost=1514,
        increase_maintenance_after_years=26,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-312-DTCOL', 'BR-304Rear', 'BR-303Rear', 'BR-302(rear)', 'BR-310-DTCOL', 'none'],
        constraint_next=['BR-310-MBSO'],
        payload_by_class=[0, 80, 0, 0],
        comfort_by_class=[0, 83, 0, 130],
        liverytype=['BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'Regional-Railways-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-310-MBSO',
        waytype='track',
        copyright='Junna/Cake/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1965,
        intro_month=11,
        retire_year=1976,
        retire_month=10,
        speed=120,
        length=11,
        weight=56.9,
        axles=4,
        power=806,
        gear=80,
        tractive_effort=75,
        payload=70,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=45,
        cost=1272000,
        runningcost=121,
        fixed_cost=11060,
        increase_maintenance_after_years=26,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-310-BDTSOL'],
        constraint_next=['BR-310-TSO', 'BR-310-DTCOL'],
        payload_by_class=[0, 70, 0, 0],
        comfort_by_class=[0, 83, 0, 130],
        liverytype=['BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'Regional-Railways-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-310-TSO',
        waytype='track',
        copyright='Junna/Cake/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1965,
        intro_month=11,
        retire_year=1976,
        retire_month=10,
        speed=120,
        length=11,
        weight=30.3,
        axles=4,
        power=0,
        payload=100,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=77,
        cost=1272000,
        runningcost=0,
        fixed_cost=1514,
        increase_maintenance_after_years=26,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-310-MBSO'],
        constraint_next=['BR-310-DTCOL'],
        payload_by_class=[0, 100, 0, 0],
        comfort_by_class=[0, 83, 0, 130],
        liverytype=['BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'Regional-Railways-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-310-DTCOL',
        waytype='track',
        copyright='Junna/Cake/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1965,
        intro_month=11,
        retire_year=1976,
        retire_month=10,
        speed=120,
        length=11,
        weight=34.0,
        axles=4,
        power=0,
        payload=43,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=50,
        cost=1272000,
        runningcost=0,
        fixed_cost=1514,
        increase_maintenance_after_years=26,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-310-TSO', 'BR-310-MBSO'],
        constraint_next=['BR-312-BDTSOL', 'BR-304Front', 'BR-303Front', 'BR-302(front)', 'BR-310-BDTSOL', 'none'],
        payload_by_class=[0, 43, 0, 26],
        comfort_by_class=[0, 83, 0, 130],
        liverytype=['BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'Regional-Railways-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
