"""br-357."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# These should have low maintenance costs: they are very reliable and save engery with regenerative braking.
# https://web.archive.org/web/20150702005602/http://www.porterbrook.co.uk/downloads/brochures/357%20Brochure.pdf
# http://www.railway-centre.com/class-357.html
_BLEND = 'trains/Railcars/br-357-pantograph.blend'
_UPSTREAM_DAT = 'trains/br-357.dat'

SPECS = [
    Vehicle(
        name='c2c-357(front)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1999,
        intro_month=8,
        retire_year=2017,
        retire_month=11,
        speed=160,
        length=11,
        weight=40.7,
        axles=4,
        power=500,
        gear=80,
        tractive_effort=44,
        brake_force=30,
        rolling_resistance=13,
        payload=71,
        min_loading_time=17,
        max_loading_time=60,
        overcrowded_capacity=53,
        cost=1512000,
        runningcost=75,
        fixed_cost=7260,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='panos-g-class-375.wav',
        constraint_prev=['c2c-357(rear)', 'none'],
        constraint_next=['c2c-357(centre1)', 'c2c-357(centre3)'],
        payload_by_class=[0, 71],
        comfort_by_class=[0, 87],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='c2c-357(centre3)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1999,
        intro_month=8,
        retire_year=2017,
        retire_month=11,
        speed=160,
        length=11,
        weight=36.7,
        axles=4,
        power=500,
        gear=80,
        tractive_effort=44,
        brake_force=27,
        payload=78,
        min_loading_time=17,
        max_loading_time=60,
        overcrowded_capacity=59,
        cost=1512000,
        runningcost=75,
        fixed_cost=3150,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['c2c-357(front)'],
        constraint_next=['c2c-357(centre1)'],
        payload_by_class=[0, 78],
        comfort_by_class=[0, 87],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='c2c-357(centre1)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1999,
        intro_month=8,
        retire_year=2017,
        retire_month=11,
        speed=160,
        length=11,
        weight=39.5,
        axles=4,
        power=0,
        gear=80,
        tractive_effort=0,
        brake_force=27,
        rolling_resistance=13,
        payload=62,
        min_loading_time=17,
        max_loading_time=60,
        overcrowded_capacity=47,
        cost=1008000,
        runningcost=0,
        fixed_cost=1260,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['c2c-357(front)', 'c2c-357(centre3)'],
        constraint_next=['c2c-357(centre2)', 'c2c-357(rear)'],
        payload_by_class=[0, 62],
        comfort_by_class=[0, 87],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='c2c-357(centre2)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1999,
        intro_month=8,
        retire_year=2017,
        retire_month=11,
        speed=160,
        length=11,
        weight=36.7,
        axles=4,
        power=500,
        gear=80,
        tractive_effort=44,
        brake_force=27,
        payload=71,
        min_loading_time=17,
        max_loading_time=60,
        overcrowded_capacity=59,
        cost=1512000,
        runningcost=75,
        fixed_cost=3150,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['c2c-357(centre1)'],
        constraint_next=['c2c-357(rear)'],
        payload_by_class=[0, 71],
        comfort_by_class=[0, 87],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='c2c-357(rear)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1999,
        intro_month=8,
        retire_year=2017,
        retire_month=11,
        speed=160,
        length=11,
        weight=40.7,
        axles=4,
        power=500,
        gear=80,
        tractive_effort=44,
        brake_force=30,
        rolling_resistance=13,
        payload=71,
        min_loading_time=17,
        max_loading_time=60,
        overcrowded_capacity=53,
        cost=1512000,
        runningcost=75,
        fixed_cost=3150,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='panos-g-class-375.wav',
        constraint_prev=['c2c-357(centre2)', 'c2c-357(centre1)'],
        constraint_next=['c2c-357(front)', 'none'],
        payload_by_class=[0, 71],
        comfort_by_class=[0, 87],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
