"""br-321."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://www.railway-centre.com/class-321.html  based on 321/4
# https://eversholtrail.co.uk/fleet/class-321/ Maximum acceleration: 0.55 ms-2 -> 97 kN
# Class 318 has the same motors, but lower top speed, so possible TE is 108 kN (accel 0.8 ms-2)
# Documentation on seats is not consistent, small differences possible due to tip-up seats
_BLEND = 'trains/Railcars/br-321-dtco-abellio.blend'
_UPSTREAM_DAT = 'trains/br-321.dat'

SPECS = [
    Vehicle(
        name='BR-321(front)',
        waytype='track',
        copyright='Kieron/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1988,
        intro_month=1,
        retire_year=1994,
        retire_month=2,
        speed=160,
        length=11,
        weight=29.8,
        axles=4,
        power=0,
        brake_force=21,
        rolling_resistance=13,
        payload=78,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=62,
        cost=1921000,
        runningcost=0,
        fixed_cost=4002,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-319.wav',
        constraint_prev=['BR-321(rear)', 'none'],
        constraint_next=['BR-321(pantograph)'],
        payload_by_class=[0, 78, 0, 0],
        comfort_by_class=[0, 84, 0, 145],
        liverytype=['NSE-Standard', 'Anglia-original', 'NXEA', 'Abellio-Greater-Anglia'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-321(front-composite)',
        waytype='track',
        copyright='Kieron/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1988,
        intro_month=1,
        retire_year=1994,
        retire_month=2,
        speed=160,
        length=11,
        weight=29.8,
        axles=4,
        power=0,
        brake_force=21,
        rolling_resistance=13,
        payload=56,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=62,
        cost=1921000,
        runningcost=0,
        fixed_cost=4002,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-319.wav',
        constraint_prev=['BR-321(rear)', 'none'],
        constraint_next=['BR-321(pantograph)'],
        payload_by_class=[0, 56, 0, 16],
        comfort_by_class=[0, 84, 0, 145],
        liverytype=['NSE-Standard', 'Anglia-original', 'NXEA', 'Abellio-Greater-Anglia'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-321(pantograph)',
        waytype='track',
        copyright='Kieron/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1988,
        intro_month=1,
        retire_year=1994,
        retire_month=2,
        speed=160,
        length=11,
        weight=51.6,
        axles=4,
        power=1072,
        gear=80,
        tractive_effort=97,
        brake_force=21,
        rolling_resistance=13,
        payload=74,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=58,
        cost=1921000,
        runningcost=0,
        fixed_cost=4002,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-321(front)', 'BR-321(front-composite)'],
        constraint_next=['BR-321(trailer)'],
        payload_by_class=[0, 74, 0, 0],
        comfort_by_class=[0, 84, 0, 145],
        liverytype=['NSE-Standard', 'Anglia-original', 'NXEA', 'Abellio-Greater-Anglia'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-321(trailer)',
        waytype='track',
        copyright='Kieron/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1988,
        intro_month=1,
        retire_year=1994,
        retire_month=2,
        speed=160,
        length=11,
        weight=29.2,
        axles=4,
        power=0,
        brake_force=38,
        rolling_resistance=13,
        payload=79,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=54,
        cost=2021000,
        runningcost=107,
        fixed_cost=11053,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-321(pantograph)'],
        constraint_next=['BR-321(rear)'],
        payload_by_class=[0, 79, 0, 0],
        comfort_by_class=[0, 84, 0, 145],
        liverytype=['NSE-Standard', 'Anglia-original', 'NXEA', 'Abellio-Greater-Anglia'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-321(rear)',
        waytype='track',
        copyright='Kieron/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1988,
        intro_month=1,
        retire_year=1994,
        retire_month=2,
        speed=160,
        length=11,
        weight=29.8,
        axles=4,
        power=0,
        brake_force=21,
        rolling_resistance=13,
        payload=78,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=62,
        cost=1921000,
        runningcost=0,
        fixed_cost=4002,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-319.wav',
        constraint_prev=['BR-321(trailer)'],
        constraint_next=['BR-321(front)', 'BR-321(front-composite)', 'none'],
        payload_by_class=[0, 78, 0, 0],
        comfort_by_class=[0, 84, 0, 145],
        liverytype=['NSE-Standard', 'Anglia-original', 'NXEA', 'Abellio-Greater-Anglia'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
