"""br-319."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# https://web.archive.org/web/20150421071217/http://www.porterbrook.co.uk/downloads/brochures/319%20Brochure.pdf
# http://www.railway-centre.com/class-319.html
# Based on 319/3 - that looks mostly as original
_BLEND = 'trains/Railcars/br-319-dtco-nse.blend'
_UPSTREAM_DAT = 'trains/br-319.dat'

SPECS = [
    Vehicle(
        name='BR-319Front',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1987,
        intro_month=7,
        retire_year=1994,
        retire_month=2,
        speed=160,
        length=11,
        weight=29.0,
        axles=4,
        power=0,
        brake_force=21,
        rolling_resistance=13,
        payload=79,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=62,
        cost=2400000,
        runningcost=0,
        fixed_cost=5000,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-319.wav',
        constraint_prev=['BR-319Rear', 'none'],
        constraint_next=['BR-319Pantograph'],
        payload_by_class=[0, 79, 0, 0],
        comfort_by_class=[0, 84, 0, 145],
        liverytype=['NSE-Standard', 'Northern'],
        upgrade=['BR-769Front'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-319FrontComposite',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1987,
        intro_month=7,
        retire_year=1994,
        retire_month=2,
        speed=160,
        length=11,
        weight=29.0,
        axles=4,
        power=0,
        brake_force=21,
        rolling_resistance=13,
        payload=56,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=55,
        cost=2400000,
        runningcost=0,
        fixed_cost=5000,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-319.wav',
        constraint_prev=['BR-319Rear', 'none'],
        constraint_next=['BR-319Pantograph'],
        payload_by_class=[0, 56, 0, 16],
        comfort_by_class=[0, 84, 0, 145],
        liverytype=['NSE-Standard', 'Northern'],
        upgrade=['BR-769FrontComposite'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-319Pantograph',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1987,
        intro_month=7,
        retire_year=1994,
        retire_month=2,
        speed=160,
        length=11,
        weight=31.0,
        axles=4,
        power=0,
        brake_force=21,
        rolling_resistance=13,
        payload=74,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=58,
        cost=2400000,
        runningcost=0,
        fixed_cost=5000,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-319Front', 'BR-319FrontComposite'],
        constraint_next=['BR-319Engine'],
        payload_by_class=[0, 74, 0, 0],
        comfort_by_class=[0, 84, 0, 145],
        liverytype=['NSE-Standard', 'Northern'],
        upgrade=['BR-769Pantograph'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-319Engine',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1987,
        intro_month=7,
        retire_year=1994,
        retire_month=2,
        speed=160,
        length=11,
        weight=50.6,
        axles=4,
        power=990,
        gear=80,
        tractive_effort=93,
        brake_force=38,
        rolling_resistance=13,
        payload=79,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=58,
        cost=2500000,
        runningcost=99,
        fixed_cost=11302,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-319Pantograph'],
        constraint_next=['BR-319Rear'],
        payload_by_class=[0, 79, 0, 0],
        comfort_by_class=[0, 84, 0, 145],
        liverytype=['NSE-Standard', 'Northern'],
        upgrade=['BR-769Motor'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-319Rear',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1987,
        intro_month=7,
        retire_year=1994,
        retire_month=2,
        speed=160,
        length=11,
        weight=29.7,
        axles=4,
        power=0,
        brake_force=21,
        rolling_resistance=13,
        payload=78,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=79,
        cost=2400000,
        runningcost=0,
        fixed_cost=5000,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-319.wav',
        constraint_prev=['BR-319Engine'],
        constraint_next=['BR-319Front', 'BR-319FrontComposite', 'none'],
        payload_by_class=[0, 78, 0, 0],
        comfort_by_class=[0, 84, 0, 145],
        liverytype=['NSE-Standard', 'Northern'],
        upgrade=['BR-769Rear'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
