"""br-314."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://www.railway-centre.com/class-314.html
_BLEND = 'trains/Railcars/br-314-front-spt-cc.blend'
_UPSTREAM_DAT = 'trains/br-314.dat'

SPECS = [
    Vehicle(
        name='BR-314Front',
        waytype='track',
        copyright='Kieron/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1979,
        intro_month=11,
        retire_year=1986,
        retire_month=9,
        speed=120,
        length=11,
        weight=34.5,
        axles=4,
        power=328,
        gear=80,
        tractive_effort=45,
        rolling_resistance=13,
        payload=68,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=56,
        cost=1120000,
        runningcost=49,
        fixed_cost=6933,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-508.wav',
        constraint_prev=['BR-314Rear', 'BR-315Rear', 'none'],
        constraint_next=['BR-314Pantograph'],
        payload_by_class=[0, 68],
        comfort_by_class=[0, 56],
        liverytype=['BR-Blue', 'Strathclyde-orange-black', 'Strathclyde-carmine-cream'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-314Pantograph',
        waytype='track',
        copyright='Kieron/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1979,
        intro_month=11,
        retire_year=1986,
        retire_month=9,
        speed=120,
        length=11,
        weight=33.0,
        axles=4,
        power=0,
        gear=80,
        tractive_effort=0,
        rolling_resistance=13,
        payload=76,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=64,
        cost=1120000,
        runningcost=0,
        fixed_cost=1333,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-314Front'],
        constraint_next=['BR-314Rear'],
        payload_by_class=[0, 76],
        comfort_by_class=[0, 56],
        liverytype=['BR-Blue', 'Strathclyde-orange-black', 'Strathclyde-carmine-cream'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-314Rear',
        waytype='track',
        copyright='Kieron/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1979,
        intro_month=11,
        retire_year=1986,
        retire_month=9,
        speed=120,
        length=11,
        weight=34.5,
        axles=4,
        power=328,
        gear=80,
        tractive_effort=45,
        rolling_resistance=13,
        payload=68,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=56,
        cost=1120000,
        runningcost=49,
        fixed_cost=6933,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-508.wav',
        constraint_prev=['BR-314Pantograph'],
        constraint_next=['BR-314Front', 'BR-315Front', 'none'],
        payload_by_class=[0, 68],
        comfort_by_class=[0, 56],
        liverytype=['BR-Blue', 'Strathclyde-orange-black', 'Strathclyde-carmine-cream'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
