"""br-312."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# https://web.archive.org/web/20071014005642/http://www.therailwaycentre.com/Recognition%20Tech%20Data%20EMU/EMU_312.html
_BLEND = 'trains/Railcars/br-312-pantotrailer-bg-1-rescale.blend'
_UPSTREAM_DAT = 'trains/br-312.dat'

SPECS = [
    Vehicle(
        name='BR-312-BDTSOL',
        waytype='track',
        copyright='Junna/Cake/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1976,
        intro_month=10,
        retire_year=1981,
        retire_month=4,
        speed=145,
        length=11,
        weight=34.9,
        axles=4,
        power=0,
        payload=84,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=45,
        cost=1272000,
        runningcost=0,
        fixed_cost=1514,
        increase_maintenance_after_years=13,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-312-DTCOL', 'BR-304Rear', 'BR-303Rear', 'BR-302(rear)', 'BR-310-DTCOL', 'none'],
        constraint_next=['BR-312-MBSO'],
        payload_by_class=[0, 84, 0, 0],
        comfort_by_class=[0, 83, 0, 130],
        liverytype=['BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'Anglia-original'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-312-MBSO',
        waytype='track',
        copyright='Junna/Cake/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1976,
        intro_month=10,
        retire_year=1981,
        retire_month=4,
        speed=145,
        length=11,
        weight=56.0,
        axles=4,
        power=806,
        gear=80,
        tractive_effort=75,
        payload=68,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=45,
        cost=1272000,
        runningcost=121,
        fixed_cost=11060,
        increase_maintenance_after_years=13,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-312-BDTSOL'],
        constraint_next=['BR-312-TSO', 'BR-312-DTCOL'],
        payload_by_class=[0, 68, 0, 0],
        comfort_by_class=[0, 83, 0, 130],
        liverytype=['BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'Anglia-original'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-312-TSO',
        waytype='track',
        copyright='Junna/Cake/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1976,
        intro_month=10,
        retire_year=1981,
        retire_month=4,
        speed=145,
        length=11,
        weight=30.5,
        axles=4,
        power=0,
        payload=98,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=77,
        cost=1272000,
        runningcost=0,
        fixed_cost=1514,
        increase_maintenance_after_years=13,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-312-MBSO'],
        constraint_next=['BR-312-DTCOL'],
        payload_by_class=[0, 98, 0, 0],
        comfort_by_class=[0, 83, 0, 130],
        liverytype=['BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'Anglia-original'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-312-DTCOL',
        waytype='track',
        copyright='Junna/Cake/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1976,
        intro_month=10,
        retire_year=1981,
        retire_month=4,
        speed=145,
        length=11,
        weight=35.2,
        axles=4,
        power=0,
        payload=47,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=50,
        cost=1272000,
        runningcost=0,
        fixed_cost=1514,
        increase_maintenance_after_years=13,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-312-TSO'],
        constraint_next=['BR-312-BDTSOL', 'BR-304Front', 'BR-303Front', 'BR-302(front)', 'BR-310-BDTSOL', 'none'],
        payload_by_class=[0, 47, 0, 25],
        comfort_by_class=[0, 83, 0, 130],
        liverytype=['BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'Anglia-original'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
