"""br-318."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://www.railway-centre.com/class-318.html
# https://eversholtrail.co.uk/fleet/class-318/ says Maximum acceleration: 0.56 ms-2 (3-cars, 1072 kW)
# https://eversholtrail.co.uk/fleet/class-321/ says Maximum acceleration: 0.55 ms-2 (4-cars, 1072 kW)
# Class 318 has the same motors, but lower top speed, so possible TE is 108 kN (accel 0.8 ms-2)
_BLEND = 'trains/Railcars/br-318-driving-spt-refurb.blend'
_UPSTREAM_DAT = 'trains/br-318.dat'

SPECS = [
    Vehicle(
        name='BR-318-Driving-Front',
        waytype='track',
        copyright='Kieron/JamesPetts/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1986,
        intro_month=9,
        retire_year=1990,
        retire_month=11,
        speed=145,
        length=10,
        weight=30.0,
        axles=4,
        power=0,
        brake_force=21,
        rolling_resistance=13,
        payload=64,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=52,
        cost=1975000,
        runningcost=0,
        fixed_cost=4115,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-508.wav',
        constraint_prev=['BR-318-Driving-Rear', 'BR-317-Driving-Rear', 'BR-320(rear)', 'none'],
        constraint_next=['BR-318-Motor'],
        payload_by_class=[0, 64, 0, 0],
        comfort_by_class=[0, 89, 0, 148],
        liverytype=['Strathclyde-orange-black', 'Strathclyde-carmine-cream', 'STP'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-318-Motor',
        waytype='track',
        copyright='Kieron/JamesPetts/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1986,
        intro_month=9,
        retire_year=1990,
        retire_month=11,
        speed=145,
        length=10,
        weight=50.9,
        axles=4,
        power=1072,
        gear=80,
        tractive_effort=107,
        brake_force=38,
        rolling_resistance=13,
        payload=77,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=48,
        cost=1975000,
        runningcost=107,
        fixed_cost=11029,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['BR-318-Driving-Front'],
        constraint_next=['BR-318-Driving-Rear'],
        payload_by_class=[0, 77, 0, 0],
        comfort_by_class=[0, 89, 0, 148],
        liverytype=['Strathclyde-orange-black', 'Strathclyde-carmine-cream', 'STP'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-318-Driving-Rear',
        waytype='track',
        copyright='Kieron/JamesPetts/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1986,
        intro_month=9,
        retire_year=1990,
        retire_month=11,
        speed=145,
        length=10,
        weight=26.6,
        axles=4,
        power=0,
        brake_force=21,
        rolling_resistance=13,
        payload=72,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=49,
        cost=1975000,
        runningcost=0,
        fixed_cost=4115,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-508.wav',
        constraint_prev=['BR-318-Motor'],
        constraint_next=['BR-318-Driving-Front', 'BR-317-Driving-Front', 'BR-320(front)', 'none'],
        payload_by_class=[0, 72, 0, 0],
        comfort_by_class=[0, 89, 0, 148],
        liverytype=['Strathclyde-orange-black', 'Strathclyde-carmine-cream', 'STP'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
