"""br-317."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://www.railway-centre.com/class-317.html
_BLEND = 'trains/Railcars/br-317-driving-wagn-purple.blend'
_UPSTREAM_DAT = 'trains/br-317.dat'

SPECS = [
    Vehicle(
        name='BR-317-Driving-Front',
        waytype='track',
        copyright='Kieron/JamesPetts/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1981,
        intro_month=1,
        retire_year=1987,
        retire_month=12,
        speed=160,
        length=10,
        weight=29.5,
        axles=4,
        power=0,
        brake_force=21,
        rolling_resistance=13,
        payload=74,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=52,
        cost=1975000,
        runningcost=0,
        fixed_cost=4115,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-508.wav',
        constraint_prev=['BR-317-Driving-Rear', 'none'],
        constraint_next=['BR-317-Trailer'],
        payload_by_class=[0, 74, 0, 0],
        comfort_by_class=[0, 89, 0, 148],
        liverytype=['BR-Blue', 'NSE-Standard', 'One', 'wagn-purple', 'Anglia-original', 'NXEA', 'Abellio-Greater-Anglia'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-317-Motor',
        waytype='track',
        copyright='Kieron/JamesPetts/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1981,
        intro_month=1,
        retire_year=1987,
        retire_month=12,
        speed=160,
        length=10,
        weight=49.0,
        axles=4,
        power=990,
        gear=80,
        tractive_effort=93,
        brake_force=38,
        rolling_resistance=13,
        payload=79,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=48,
        cost=1975000,
        runningcost=99,
        fixed_cost=11029,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['BR-317-Trailer'],
        constraint_next=['BR-317-Driving-Rear'],
        payload_by_class=[0, 79, 0, 0],
        comfort_by_class=[0, 89, 0, 148],
        liverytype=['BR-Blue', 'NSE-Standard', 'One', 'wagn-purple', 'Anglia-original', 'NXEA', 'Abellio-Greater-Anglia'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-317-Trailer',
        waytype='track',
        copyright='Kieron/JamesPetts/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1981,
        intro_month=1,
        retire_year=1987,
        retire_month=12,
        speed=160,
        length=10,
        weight=29.0,
        axles=4,
        power=0,
        brake_force=21,
        rolling_resistance=13,
        payload=46,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=52,
        cost=1975000,
        runningcost=0,
        fixed_cost=4115,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['BR-317-Driving-Front'],
        constraint_next=['BR-317-Motor'],
        payload_by_class=[0, 46, 0, 22],
        comfort_by_class=[0, 89, 0, 148],
        liverytype=['BR-Blue', 'NSE-Standard', 'One', 'wagn-purple', 'Anglia-original', 'NXEA', 'Abellio-Greater-Anglia'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-317-Driving-Rear',
        waytype='track',
        copyright='Kieron/JamesPetts/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1981,
        intro_month=1,
        retire_year=1987,
        retire_month=12,
        speed=160,
        length=10,
        weight=29.5,
        axles=4,
        power=0,
        brake_force=21,
        rolling_resistance=13,
        payload=71,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=49,
        cost=1975000,
        runningcost=0,
        fixed_cost=4115,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-508.wav',
        constraint_prev=['BR-317-Motor'],
        constraint_next=['BR-317-Driving-Front', 'none'],
        payload_by_class=[0, 71, 0, 0],
        comfort_by_class=[0, 89, 0, 148],
        liverytype=['BR-Blue', 'NSE-Standard', 'One', 'wagn-purple', 'Anglia-original', 'NXEA', 'Abellio-Greater-Anglia'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
