"""br-309."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/br-309-a1-jaffa.blend'
_UPSTREAM_DAT = 'trains/br-309.dat'

SPECS = [
    Vehicle(
        name='BR-309-1Front',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1962,
        intro_month=10,
        retire_year=1981,
        retire_month=7,
        speed=160,
        length=11,
        weight=41,
        axles=4,
        power=846,
        gear=80,
        tractive_effort=70,
        payload=56,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=17,
        cost=1272000,
        runningcost=127,
        fixed_cost=7060,
        increase_maintenance_after_years=13,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-309Rear', 'none'],
        constraint_next=['BR-309Rear'],
        payload_by_class=[0, 56, 0, 0],
        comfort_by_class=[0, 137, 0, 154],
        liverytype=['BR-Revised', 'BR-Blue', 'Jaffa-Cake', 'NSE-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-309-2Front',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1962,
        intro_month=10,
        retire_year=1981,
        retire_month=7,
        speed=160,
        length=11,
        weight=41,
        axles=4,
        power=0,
        payload=32,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=17,
        cost=1272000,
        runningcost=0,
        fixed_cost=1514,
        increase_maintenance_after_years=13,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-309Rear', 'none'],
        constraint_next=['BR-309Power'],
        payload_by_class=[0, 32, 0, 18],
        comfort_by_class=[0, 137, 0, 154],
        liverytype=['BR-Revised', 'BR-Blue', 'Jaffa-Cake', 'NSE-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-309Middle',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1962,
        intro_month=10,
        retire_year=1981,
        retire_month=7,
        speed=160,
        length=11,
        weight=34,
        axles=4,
        payload=64,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=21,
        cost=1272000,
        runningcost=0,
        fixed_cost=1514,
        increase_maintenance_after_years=13,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-309Power'],
        constraint_next=['BR-309Rear'],
        payload_by_class=[0, 64, 0, 0],
        comfort_by_class=[0, 137, 0, 154],
        liverytype=['BR-Revised', 'BR-Blue', 'Jaffa-Cake', 'NSE-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-309Griddle',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1962,
        intro_month=10,
        retire_year=1981,
        retire_month=7,
        speed=160,
        length=11,
        weight=36,
        axles=4,
        payload=34,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=17,
        catering_level=3,
        cost=1332000,
        runningcost=0,
        fixed_cost=1586,
        increase_maintenance_after_years=13,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-309Power'],
        constraint_next=['BR-309Rear'],
        payload_by_class=[0, 34, 0, 0],
        comfort_by_class=[0, 137, 0, 154],
        liverytype=['BR-Revised', 'BR-Blue', 'Jaffa-Cake', 'NSE-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-309Power',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1962,
        intro_month=10,
        retire_year=1981,
        retire_month=7,
        speed=160,
        length=11,
        weight=51,
        axles=4,
        power=846,
        gear=80,
        tractive_effort=70,
        payload=48,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=16,
        cost=1272000,
        runningcost=127,
        fixed_cost=7060,
        increase_maintenance_after_years=13,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-309-2Front'],
        constraint_next=['BR-309Middle', 'BR-309Griddle'],
        payload_by_class=[0, 48, 0, 0],
        comfort_by_class=[0, 137, 0, 154],
        liverytype=['BR-Revised', 'BR-Blue', 'Jaffa-Cake', 'NSE-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-309Rear',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1962,
        intro_month=10,
        retire_year=1981,
        retire_month=7,
        speed=160,
        length=11,
        weight=41,
        axles=4,
        power=0,
        payload=32,
        min_loading_time=25,
        max_loading_time=120,
        overcrowded_capacity=17,
        cost=1272000,
        runningcost=0,
        fixed_cost=1514,
        increase_maintenance_after_years=13,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-309Middle', 'BR-309Griddle', 'BR-309-1Front'],
        constraint_next=['BR-309-1Front', 'BR-309-2Front', 'none'],
        payload_by_class=[0, 32, 0, 18],
        comfort_by_class=[0, 137, 0, 154],
        liverytype=['BR-Revised', 'BR-Blue', 'Jaffa-Cake', 'NSE-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
