"""br-315."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://www.railway-centre.com/class-315.html
# https://eversholtrail.co.uk/fleet/class-315/ says: Maximum acceleration: 0.75 m/s/s, that would be 60 kN tractive_effort
# https://eversholtrail.co.uk/fleet/class-318/ says: Maximum acceleration: 0.56 m/s/s.
# I doubt that newer, shorter, and more powerful unit would have lower acceleration than older, longer and less powerful
# Only the lower speed 120 vs. 145 may point to more powerful gearing.
# Therefore I think the accel values are swapped. And use 0.56 as acceleration.
# That means 45 kN tractive effort, also for classes 313 and 314, which have the same traction motors
_BLEND = 'trains/Railcars/br-315-front-nxea-stripe.blend'
_UPSTREAM_DAT = 'trains/br-315.dat'

SPECS = [
    Vehicle(
        name='BR-315Front',
        waytype='track',
        copyright='Kieron/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1980,
        intro_month=5,
        retire_year=1992,
        retire_month=7,
        speed=120,
        length=11,
        weight=35.0,
        axles=4,
        power=328,
        gear=80,
        tractive_effort=45,
        rolling_resistance=13,
        payload=74,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=56,
        cost=1120000,
        runningcost=33,
        fixed_cost=6933,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-508.wav',
        constraint_prev=['BR-315Rear', 'BR-314Rear', 'none'],
        constraint_next=['BR-315Pantograph'],
        payload_by_class=[0, 74],
        comfort_by_class=[0, 56],
        liverytype=['BR-Blue', 'NSE-Standard', 'One', 'wagn-purple', 'Anglia-original', 'NXEA', 'Abellio-Greater-Anglia'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-315Pantograph',
        waytype='track',
        copyright='Kieron/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1980,
        intro_month=5,
        retire_year=1992,
        retire_month=7,
        speed=120,
        length=11,
        weight=32.0,
        axles=4,
        power=0,
        gear=80,
        tractive_effort=0,
        rolling_resistance=13,
        payload=84,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=64,
        cost=1120000,
        runningcost=0,
        fixed_cost=2333,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-315Front'],
        constraint_next=['BR-315Rear', 'BR-315Trailer'],
        payload_by_class=[0, 84],
        comfort_by_class=[0, 56],
        liverytype=['BR-Blue', 'NSE-Standard', 'One', 'wagn-purple', 'Anglia-original', 'NXEA', 'Abellio-Greater-Anglia'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-315Trailer',
        waytype='track',
        copyright='Kieron/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1980,
        intro_month=5,
        retire_year=1992,
        retire_month=7,
        speed=120,
        length=11,
        weight=25.5,
        axles=4,
        power=0,
        gear=80,
        tractive_effort=0,
        rolling_resistance=13,
        payload=86,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=64,
        cost=1120000,
        runningcost=0,
        fixed_cost=2333,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-315Pantograph'],
        constraint_next=['BR-315Rear'],
        payload_by_class=[0, 86],
        comfort_by_class=[0, 56],
        liverytype=['BR-Blue', 'NSE-Standard', 'One', 'wagn-purple', 'Anglia-original', 'NXEA', 'Abellio-Greater-Anglia'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-315Rear',
        waytype='track',
        copyright='Kieron/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1980,
        intro_month=5,
        retire_year=1992,
        retire_month=7,
        speed=120,
        length=11,
        weight=35.0,
        axles=4,
        power=328,
        gear=80,
        tractive_effort=45,
        rolling_resistance=13,
        payload=74,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=56,
        cost=1120000,
        runningcost=33,
        fixed_cost=6933,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-508.wav',
        constraint_prev=['BR-315Pantograph', 'BR-315Trailer'],
        constraint_next=['BR-315Front', 'BR-314Front', 'none'],
        payload_by_class=[0, 74],
        comfort_by_class=[0, 56],
        liverytype=['BR-Blue', 'NSE-Standard', 'One', 'wagn-purple', 'Anglia-original', 'NXEA', 'Abellio-Greater-Anglia'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
