"""br-365."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/br-365-p-nse.blend'
_UPSTREAM_DAT = 'trains/br-365.dat'

SPECS = [
    Vehicle(
        name='BR-365Front',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1994,
        intro_month=2,
        retire_year=1999,
        retire_month=10,
        speed=160,
        length=12,
        weight=47,
        axles=4,
        power=628,
        gear=80,
        tractive_effort=93,
        brake_force=35,
        rolling_resistance=13,
        payload=36,
        min_loading_time=17,
        max_loading_time=55,
        overcrowded_capacity=37,
        cost=1602000,
        runningcost=63,
        fixed_cost=7335,
        increase_maintenance_after_years=26,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='panos-g-class-465.wav',
        constraint_prev=['BR-365Rear', 'none'],
        constraint_next=['BR-365Power'],
        payload_by_class=[0, 36, 0, 12],
        comfort_by_class=[0, 100, 0, 116],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-365Power',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1994,
        intro_month=2,
        retire_year=1999,
        retire_month=10,
        speed=160,
        length=11,
        weight=34,
        axles=4,
        power=0,
        brake_force=25,
        rolling_resistance=13,
        payload=73,
        min_loading_time=17,
        max_loading_time=55,
        overcrowded_capacity=55,
        cost=1602000,
        runningcost=0,
        fixed_cost=3338,
        increase_maintenance_after_years=26,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-365Front'],
        constraint_next=['BR-365Middle'],
        payload_by_class=[0, 73, 0, 0],
        comfort_by_class=[0, 100, 0, 116],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-365Middle',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1994,
        intro_month=2,
        retire_year=1999,
        retire_month=10,
        speed=160,
        length=11,
        weight=33,
        axles=4,
        power=0,
        brake_force=24,
        rolling_resistance=13,
        payload=73,
        min_loading_time=17,
        max_loading_time=55,
        overcrowded_capacity=55,
        cost=1602000,
        runningcost=0,
        fixed_cost=3338,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-365Power'],
        constraint_next=['BR-365Rear'],
        payload_by_class=[0, 73, 0, 0],
        comfort_by_class=[0, 100, 0, 116],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-365Rear',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1994,
        intro_month=2,
        retire_year=1999,
        retire_month=10,
        speed=160,
        length=12,
        weight=47,
        axles=4,
        power=628,
        gear=80,
        tractive_effort=93,
        brake_force=35,
        rolling_resistance=13,
        payload=36,
        min_loading_time=17,
        max_loading_time=55,
        overcrowded_capacity=36,
        cost=1602000,
        runningcost=63,
        fixed_cost=7335,
        increase_maintenance_after_years=26,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='panos-g-class-465.wav',
        constraint_prev=['BR-365Middle', 'BR-365Power'],
        constraint_next=['BR-365Front', 'none'],
        payload_by_class=[0, 36, 0, 12],
        comfort_by_class=[0, 100, 0, 116],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
