"""br-302."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/br-302-DTSO-blue-grey.blend'
_UPSTREAM_DAT = 'trains/br-302.dat'

SPECS = [
    Vehicle(
        name='BR-302(front)',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1958,
        intro_month=10,
        retire_year=1960,
        retire_month=9,
        speed=120,
        length=11,
        weight=34,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=80,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=80,
        cost=1095000,
        runningcost=0,
        fixed_cost=1304,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-312-DTCOL', 'BR-304Rear', 'BR-303Rear', 'BR-302(rear)', 'BR-310-DTCOL', 'none'],
        constraint_next=['BR-302(centre1)'],
        payload_by_class=[0, 80, 0, 0],
        comfort_by_class=[0, 78, 0, 129],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-302(centre1)',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1958,
        intro_month=10,
        retire_year=1960,
        retire_month=9,
        speed=120,
        length=11,
        weight=48,
        axles=4,
        power=565,
        gear=80,
        tractive_effort=65,
        payload=96,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=96,
        cost=1885000,
        runningcost=113,
        fixed_cost=1309,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-302(front)'],
        constraint_next=['BR-302(centre2)'],
        payload_by_class=[0, 96, 0, 0],
        comfort_by_class=[0, 78, 0, 129],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-302(centre2)',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1958,
        intro_month=10,
        retire_year=1960,
        retire_month=9,
        speed=120,
        length=11,
        weight=31,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=59,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=64,
        cost=945000,
        runningcost=0,
        fixed_cost=1125,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-302(centre1)'],
        constraint_next=['BR-302(rear)'],
        payload_by_class=[0, 59, 0, 20],
        comfort_by_class=[0, 78, 0, 129],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-302(rear)',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1958,
        intro_month=10,
        retire_year=1960,
        retire_month=9,
        speed=120,
        length=11,
        weight=34,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=108,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=108,
        cost=1095000,
        runningcost=0,
        fixed_cost=1304,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-302(centre2)'],
        constraint_next=['BR-312-BDTSOL', 'BR-304Front', 'BR-303Front', 'BR-302(front)', 'BR-310-BDTSOL', 'none'],
        payload_by_class=[0, 108, 0, 0],
        comfort_by_class=[0, 78, 0, 129],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'NSE-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
