"""br-304."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/br-304-driving-trailer-blue-grey.blend'
_UPSTREAM_DAT = 'trains/br-304.dat'

SPECS = [
    Vehicle(
        name='BR-304Front',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1960,
        intro_month=4,
        retire_year=1980,
        retire_month=5,
        speed=120,
        length=11,
        weight=34,
        axles=4,
        power=0,
        payload=82,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=82,
        cost=1890000,
        runningcost=0,
        fixed_cost=2250,
        increase_maintenance_after_years=15,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-312-DTCOL', 'BR-304Rear', 'BR-303Rear', 'BR-302(rear)', 'BR-310-DTCOL', 'none'],
        constraint_next=['BR-304Centre-Trailer', 'BR-304Centre-Motor'],
        payload_by_class=[0, 82, 0, 0],
        comfort_by_class=[0, 78, 0, 129],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'Regional-Railways-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-304Centre-Trailer',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1960,
        intro_month=4,
        retire_year=1980,
        retire_month=5,
        speed=120,
        length=11,
        weight=32,
        axles=4,
        power=0,
        payload=60,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=64,
        cost=1890000,
        runningcost=0,
        fixed_cost=2250,
        increase_maintenance_after_years=15,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-304Front'],
        constraint_next=['BR-304Centre-Motor'],
        payload_by_class=[0, 60, 0, 19],
        comfort_by_class=[0, 78, 0, 129],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'Regional-Railways-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-304Centre-Motor',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1960,
        intro_month=4,
        retire_year=1980,
        retire_month=5,
        speed=120,
        length=11,
        weight=53,
        axles=4,
        power=618,
        gear=80,
        tractive_effort=72,
        payload=96,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=96,
        cost=1890000,
        runningcost=93,
        fixed_cost=1313,
        increase_maintenance_after_years=15,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-304Front', 'BR-304Centre-Trailer'],
        constraint_next=['BR-304Rear'],
        payload_by_class=[0, 96, 0, 0],
        comfort_by_class=[0, 78, 0, 129],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'Regional-Railways-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-304Rear',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1960,
        intro_month=4,
        retire_year=1980,
        retire_month=5,
        speed=120,
        length=11,
        weight=34,
        axles=4,
        power=0,
        payload=82,
        min_loading_time=12,
        max_loading_time=43,
        overcrowded_capacity=82,
        cost=1890000,
        runningcost=0,
        fixed_cost=2250,
        increase_maintenance_after_years=15,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-304Centre-Motor'],
        constraint_next=['BR-312-BDTSOL', 'BR-304Front', 'BR-303Front', 'BR-302(front)', 'BR-310-BDTSOL', 'none'],
        payload_by_class=[0, 82, 0, 0],
        comfort_by_class=[0, 78, 0, 129],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'Regional-Railways-Standard'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
