"""br-303."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/br-303-a-spt-orange.blend'
_UPSTREAM_DAT = 'trains/br-303.dat'

SPECS = [
    Vehicle(
        name='BR-303Front',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1959,
        intro_month=2,
        retire_year=1968,
        retire_month=9,
        speed=120,
        length=11,
        weight=34,
        axles=4,
        power=0,
        rolling_resistance=13,
        payload=83,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=62,
        cost=1967000,
        runningcost=0,
        fixed_cost=2342,
        increase_maintenance_after_years=23,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-312-DTCOL', 'BR-304Rear', 'BR-303Rear', 'BR-302(rear)', 'BR-310-DTCOL', 'none'],
        constraint_next=['BR-303Pantograph'],
        payload_by_class=[0, 83],
        comfort_by_class=[0, 82],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'Strathclyde-orange-black'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-303Pantograph',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1959,
        intro_month=2,
        retire_year=1968,
        retire_month=9,
        speed=120,
        length=11,
        weight=56,
        axles=4,
        power=618,
        gear=80,
        tractive_effort=69,
        rolling_resistance=13,
        payload=70,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=52,
        cost=1967000,
        runningcost=124,
        fixed_cost=1366,
        increase_maintenance_after_years=23,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-303Front'],
        constraint_next=['BR-303Rear'],
        payload_by_class=[0, 70],
        comfort_by_class=[0, 82],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'Strathclyde-orange-black'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-303Rear',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1959,
        intro_month=2,
        retire_year=1968,
        retire_month=9,
        speed=120,
        length=11,
        weight=38,
        axles=4,
        power=0,
        rolling_resistance=13,
        payload=83,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=62,
        cost=1967000,
        runningcost=0,
        fixed_cost=2342,
        increase_maintenance_after_years=23,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-303Pantograph'],
        constraint_next=['BR-312-BDTSOL', 'BR-304Front', 'BR-303Front', 'BR-302(front)', 'BR-310-BDTSOL', 'none'],
        payload_by_class=[0, 83],
        comfort_by_class=[0, 82],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo', 'Strathclyde-orange-black'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
