"""br-313."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://www.railway-centre.com/class-313.html
_BLEND = 'trains/Railcars/br-313-nse-a.blend'
_UPSTREAM_DAT = 'trains/br-313.dat'

SPECS = [
    Vehicle(
        name='BR-313Front',
        waytype='track',
        copyright='Kieron/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1975,
        intro_month=12,
        retire_year=1991,
        retire_month=12,
        speed=120,
        length=11,
        weight=36.0,
        axles=4,
        power=328,
        gear=80,
        tractive_effort=45,
        rolling_resistance=13,
        payload=74,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=56,
        cost=1237000,
        runningcost=49,
        fixed_cost=7031,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-508.wav',
        constraint_prev=['BR-313Rear', 'none'],
        constraint_next=['BR-313Pantograph'],
        payload_by_class=[0, 74],
        comfort_by_class=[0, 56],
        liverytype=['BR-Blue', 'NSE-Standard', 'wagn-purple'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-313Pantograph',
        waytype='track',
        copyright='Kieron/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1975,
        intro_month=12,
        retire_year=1991,
        retire_month=12,
        speed=120,
        length=11,
        weight=31.0,
        axles=4,
        power=0,
        gear=80,
        tractive_effort=0,
        rolling_resistance=13,
        payload=83,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=64,
        cost=1237000,
        runningcost=0,
        fixed_cost=1473,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-313Front'],
        constraint_next=['BR-313Rear'],
        payload_by_class=[0, 83],
        comfort_by_class=[0, 56],
        liverytype=['BR-Blue', 'NSE-Standard', 'wagn-purple'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-313Rear',
        waytype='track',
        copyright='Kieron/Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1975,
        intro_month=12,
        retire_year=1991,
        retire_month=12,
        speed=120,
        length=11,
        weight=37.5,
        axles=4,
        power=328,
        gear=80,
        tractive_effort=45,
        rolling_resistance=13,
        payload=74,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=56,
        cost=1237000,
        runningcost=49,
        fixed_cost=7031,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-508.wav',
        constraint_prev=['BR-313Pantograph'],
        constraint_next=['BR-313Front', 'none'],
        payload_by_class=[0, 74],
        comfort_by_class=[0, 56],
        liverytype=['BR-Blue', 'NSE-Standard', 'wagn-purple'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
