"""br-320."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://www.railway-centre.com/class-320.html
# https://eversholtrail.co.uk/fleet/class-320/ Maximum acceleration: 0.55 ms-2 -> 97 kN
# Class 318 has the same motors, but lower top speed, so possible TE is 108 kN (accel 0.8 ms-2)
# Documentation on seats is not consistent, small differences possible due to tip-up seats
_BLEND = 'trains/Railcars/br-320-panto-spt-dda.blend'
_UPSTREAM_DAT = 'trains/br-320.dat'

SPECS = [
    Vehicle(
        name='BR-320(front)',
        waytype='track',
        copyright='Kieron, Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1990,
        intro_month=1,
        retire_year=2001,
        retire_month=12,
        speed=145,
        length=11,
        weight=29.1,
        axles=4,
        power=0,
        brake_force=21,
        rolling_resistance=13,
        payload=76,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=62,
        cost=1921000,
        runningcost=0,
        fixed_cost=4002,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-319.wav',
        constraint_prev=['BR-320(rear)', 'BR-318-Driving-Rear', 'none'],
        constraint_next=['BR-320(pantograph)'],
        payload_by_class=[0, 76, 0, 0],
        comfort_by_class=[0, 84, 0, 145],
        liverytype=['Strathclyde-orange-black', 'Strathclyde-carmine-cream', 'STP'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-320(pantograph)',
        waytype='track',
        copyright='Kieron, Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1990,
        intro_month=1,
        retire_year=2001,
        retire_month=12,
        speed=145,
        length=11,
        weight=51.9,
        axles=4,
        power=1072,
        gear=80,
        tractive_effort=97,
        brake_force=21,
        rolling_resistance=13,
        payload=76,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=58,
        cost=1921000,
        runningcost=0,
        fixed_cost=4002,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-320(front)'],
        constraint_next=['BR-320(rear)'],
        payload_by_class=[0, 76, 0, 0],
        comfort_by_class=[0, 84, 0, 145],
        liverytype=['Strathclyde-orange-black', 'Strathclyde-carmine-cream', 'STP'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-320(rear)',
        waytype='track',
        copyright='Kieron, Rollmaterial',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1990,
        intro_month=1,
        retire_year=2001,
        retire_month=12,
        speed=145,
        length=11,
        weight=30.0,
        axles=4,
        power=0,
        brake_force=21,
        rolling_resistance=13,
        payload=75,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=62,
        cost=1921000,
        runningcost=0,
        fixed_cost=4002,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-319.wav',
        constraint_prev=['BR-320(pantograph)'],
        constraint_next=['BR-320(front)', 'BR-318-Driving-Front', 'none'],
        payload_by_class=[0, 75, 0, 0],
        comfort_by_class=[0, 84, 0, 145],
        liverytype=['Strathclyde-orange-black', 'Strathclyde-carmine-cream', 'STP'],
        way_constraint_permissive=[2],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
