"""br-378."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# https://en.wikipedia.org/wiki/British_Rail_Class_378
# 152 individual cars costing some £223 million (24x 3-car AC/DC, 20x 4-car DC)
# end of 2010: 36 carriages for £36 million (3x 4-car unit AC/DC, 24 extra carriages)
# 2011: 10x 4-car unit AC/DC; November 2014: 57 cars to make all units 5-car long
# 150 kN 4-car unit = 17kN per motor with 3 motors per car: http://www.districtdavesforum.co.uk/thread/22284/378-fifth-car
# https://www.whatdotheyknow.com/request/339955/response/848693/attach/3/Class%20378%20Data%20Sheet.pdf
# https://en.wikipedia.org/wiki/Bombardier_Electrostar, end of production Nov 2017
# http://www.railway-centre.com/class-378.html
_BLEND = 'trains/Railcars/br-378-a-lt.blend'
_UPSTREAM_DAT = 'trains/br-378.dat'

SPECS = [
    Vehicle(
        name='BR-378Front',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=2009,
        intro_month=7,
        retire_year=2017,
        retire_month=11,
        speed=120,
        length=12,
        weight=43.5,
        axles=4,
        power=600,
        gear=80,
        tractive_effort=50,
        brake_force=35,
        rolling_resistance=13,
        payload=36,
        min_loading_time=12,
        max_loading_time=50,
        overcrowded_capacity=120,
        cost=2116800,
        runningcost=90,
        fixed_cost=7512,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='panos-g-class-375.wav',
        constraint_prev=['BR-378Rear', 'BR-375Rear', 'BR-376Rear', 'BR-375-6Rear', 'BR-379Rear', 'BR-387Rear', 'none'],
        constraint_next=['BR-378Middle-unpowered', 'BR-378Middle'],
        payload_by_class=[0, 36],
        comfort_by_class=[0, 59],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-378Middle',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=2009,
        intro_month=7,
        retire_year=2017,
        retire_month=11,
        speed=120,
        length=12,
        weight=39.4,
        axles=4,
        power=600,
        gear=80,
        tractive_effort=50,
        brake_force=30,
        rolling_resistance=13,
        payload=40,
        min_loading_time=12,
        max_loading_time=50,
        overcrowded_capacity=140,
        cost=2116800,
        runningcost=90,
        fixed_cost=5669,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-378Front'],
        constraint_next=['BR-378Middle-unpowered'],
        payload_by_class=[0, 40],
        comfort_by_class=[0, 59],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-378Middle2',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=2009,
        intro_month=7,
        retire_year=2017,
        retire_month=11,
        speed=120,
        length=12,
        weight=39.4,
        axles=4,
        power=600,
        gear=80,
        tractive_effort=50,
        brake_force=30,
        rolling_resistance=13,
        payload=40,
        min_loading_time=12,
        max_loading_time=50,
        overcrowded_capacity=140,
        cost=2116800,
        runningcost=90,
        fixed_cost=5669,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-378Middle-unpowered'],
        constraint_next=['BR-378Rear'],
        payload_by_class=[0, 40],
        comfort_by_class=[0, 59],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-378Middle-unpowered',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=2009,
        intro_month=7,
        retire_year=2017,
        retire_month=11,
        speed=120,
        length=12,
        weight=34.3,
        axles=4,
        power=0,
        gear=80,
        brake_force=30,
        payload=40,
        min_loading_time=12,
        max_loading_time=50,
        overcrowded_capacity=140,
        cost=1008000,
        runningcost=0,
        fixed_cost=2268,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-378Front', 'BR-378Middle'],
        constraint_next=['BR-378Rear', 'BR-378Middle2'],
        payload_by_class=[0, 40],
        comfort_by_class=[0, 59],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-378Rear',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=2009,
        intro_month=7,
        retire_year=2017,
        retire_month=11,
        speed=120,
        length=12,
        weight=43.1,
        axles=4,
        power=600,
        gear=80,
        tractive_effort=50,
        brake_force=35,
        rolling_resistance=13,
        payload=36,
        min_loading_time=12,
        max_loading_time=50,
        overcrowded_capacity=120,
        cost=2116800,
        runningcost=90,
        fixed_cost=5669,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='panos-g-class-375.wav',
        constraint_prev=['BR-378Middle2', 'BR-378Middle-unpowered'],
        constraint_next=['BR-378Front', 'BR-375Front', 'BR-376Front', 'BR-375-6Front', 'BR-379Front', 'BR-387Front', 'none'],
        payload_by_class=[0, 36],
        comfort_by_class=[0, 59],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
