"""br-455."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# https://en.wikipedia.org/wiki/British_Rail_Class_455
_BLEND = 'trains/Railcars/br-455-driving-rear-swt.blend'
_UPSTREAM_DAT = 'trains/br-455.dat'

SPECS = [
    Vehicle(
        name='BR-455-Driving-Front',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1982,
        intro_month=3,
        retire_year=1992,
        retire_month=9,
        speed=121,
        length=10,
        weight=30,
        axles=4,
        power=0,
        brake_force=23,
        rolling_resistance=13,
        payload=74,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=56,
        cost=1860000,
        runningcost=0,
        fixed_cost=3875,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-508.wav',
        constraint_prev=['BR-456-DTSO', 'BR-455-Driving-Rear', 'none'],
        constraint_next=['BR-455-Motor'],
        payload_by_class=[0, 74],
        comfort_by_class=[0, 57],
        liverytype=['BR-Blue', 'NSE-Standard', 'SWT-orange-stripe', 'Southern'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-455-Motor',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1982,
        intro_month=3,
        retire_year=1992,
        retire_month=9,
        speed=121,
        length=10,
        weight=50,
        axles=4,
        power=746,
        gear=80,
        tractive_effort=75,
        brake_force=38,
        rolling_resistance=13,
        payload=84,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=63,
        cost=1860000,
        runningcost=75,
        fixed_cost=10969,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['BR-455-Driving-Front'],
        constraint_next=['BR-455-Trailer', 'BR-507(centre2)'],
        payload_by_class=[0, 84],
        comfort_by_class=[0, 57],
        liverytype=['BR-Blue', 'NSE-Standard', 'SWT-orange-stripe', 'Southern'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-455-Trailer',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1982,
        intro_month=3,
        retire_year=1992,
        retire_month=9,
        speed=121,
        length=10,
        weight=25,
        axles=4,
        power=0,
        brake_force=18,
        rolling_resistance=13,
        payload=86,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=64,
        cost=1860000,
        runningcost=0,
        fixed_cost=3875,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['BR-455-Motor'],
        constraint_next=['BR-455-Driving-Rear'],
        payload_by_class=[0, 86],
        comfort_by_class=[0, 57],
        liverytype=['BR-Blue', 'NSE-Standard', 'SWT-orange-stripe', 'Southern'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-455-Driving-Rear',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1982,
        intro_month=3,
        retire_year=1992,
        retire_month=9,
        speed=121,
        length=10,
        weight=30,
        axles=4,
        power=0,
        brake_force=23,
        rolling_resistance=13,
        payload=74,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=56,
        cost=1860000,
        runningcost=0,
        fixed_cost=3875,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-508.wav',
        constraint_prev=['BR-455-Trailer', 'BR-507(centre2)'],
        constraint_next=['BR-456-DMSO', 'BR-455-Driving-Front', 'none'],
        payload_by_class=[0, 74],
        comfort_by_class=[0, 57],
        liverytype=['BR-Blue', 'NSE-Standard', 'SWT-orange-stripe', 'Southern'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
