"""br-442."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://www.networksoutheast.net/dc.html
_BLEND = 'trains/Railcars/br-442-buffet-swt.blend'
_UPSTREAM_DAT = 'trains/br-442.dat'

SPECS = [
    Vehicle(
        name='BR-442-Front',
        waytype='track',
        copyright='James',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1988,
        intro_month=2,
        retire_year=2001,
        retire_month=3,
        speed=160,
        length=13,
        weight=39,
        axles=4,
        brake_force=29,
        rolling_resistance=13,
        payload=50,
        min_loading_time=35,
        max_loading_time=180,
        overcrowded_capacity=0,
        cost=590000,
        runningcost=0,
        fixed_cost=1229,
        increase_maintenance_after_years=21,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-442-Rear', 'none'],
        constraint_next=['BR-442-Middle1'],
        payload_by_class=[0, 0, 0, 50],
        comfort_by_class=[0, 145, 0, 159],
        liverytype=['NSE-Standard', 'SWT-orange-stripe'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-442-Middle1',
        waytype='track',
        copyright='James',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1988,
        intro_month=2,
        retire_year=2001,
        retire_month=3,
        speed=160,
        length=13,
        weight=35,
        axles=4,
        brake_force=26,
        rolling_resistance=13,
        payload=80,
        min_loading_time=35,
        max_loading_time=180,
        overcrowded_capacity=20,
        cost=590000,
        runningcost=0,
        fixed_cost=1229,
        increase_maintenance_after_years=21,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-442-Front'],
        constraint_next=['BR-442-Middle2'],
        payload_by_class=[0, 80, 0, 0],
        comfort_by_class=[0, 145, 0, 159],
        liverytype=['NSE-Standard', 'SWT-orange-stripe'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-442-Middle2',
        waytype='track',
        copyright='James',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1988,
        intro_month=2,
        retire_year=2001,
        retire_month=3,
        speed=160,
        length=13,
        weight=54,
        axles=4,
        power=1200,
        gear=80,
        tractive_effort=95,
        brake_force=41,
        rolling_resistance=13,
        payload=14,
        min_loading_time=35,
        max_loading_time=180,
        overcrowded_capacity=26,
        catering_level=3,
        cost=590000,
        runningcost=128,
        fixed_cost=246,
        upgrade_price=472000,
        increase_maintenance_after_years=21,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-442-Middle1'],
        constraint_next=['BR-442-Middle3'],
        payload_by_class=[0, 14, 0, 0],
        comfort_by_class=[0, 145, 0, 159],
        liverytype=['NSE-Standard', 'SWT-orange-stripe'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-442-Middle3',
        waytype='track',
        copyright='James',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1988,
        intro_month=2,
        retire_year=2001,
        retire_month=3,
        speed=160,
        length=13,
        weight=35,
        axles=4,
        brake_force=26,
        rolling_resistance=13,
        payload=78,
        min_loading_time=35,
        max_loading_time=180,
        overcrowded_capacity=28,
        cost=590000,
        runningcost=0,
        fixed_cost=1229,
        increase_maintenance_after_years=21,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-442-Middle2'],
        constraint_next=['BR-442-Rear'],
        payload_by_class=[0, 78, 0, 0],
        comfort_by_class=[0, 145, 0, 159],
        liverytype=['NSE-Standard', 'SWT-orange-stripe'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-442-Rear',
        waytype='track',
        copyright='James',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1988,
        intro_month=2,
        retire_year=2001,
        retire_month=3,
        speed=160,
        length=13,
        weight=39,
        axles=4,
        brake_force=29,
        rolling_resistance=13,
        payload=78,
        min_loading_time=35,
        max_loading_time=180,
        overcrowded_capacity=24,
        cost=590000,
        runningcost=0,
        fixed_cost=1229,
        increase_maintenance_after_years=21,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-442-Middle3'],
        constraint_next=['BR-442-Front', 'none'],
        payload_by_class=[0, 78, 0, 0],
        comfort_by_class=[0, 145, 0, 159],
        liverytype=['NSE-Standard', 'SWT-orange-stripe'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
