"""br-465."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://www.networksoutheast.net/dc.html
# DMSO
_BLEND = 'trains/Railcars/br-465-middle.blend'
_UPSTREAM_DAT = 'trains/br-465.dat'

SPECS = [
    Vehicle(
        name='BR-465Front',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1991,
        intro_month=9,
        retire_year=2001,
        retire_month=5,
        speed=120,
        length=12,
        weight=39,
        axles=4,
        power=600,
        gear=80,
        tractive_effort=93,
        brake_force=29,
        rolling_resistance=13,
        payload=86,
        min_loading_time=17,
        max_loading_time=55,
        overcrowded_capacity=52,
        cost=1238000,
        runningcost=60,
        fixed_cost=7032,
        increase_maintenance_after_years=23,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='panos-g-class-465.wav',
        constraint_prev=['BR-465Rear', 'none'],
        constraint_next=['BR-465Rear', 'BR-465Middle'],
        payload_by_class=[0, 86, 0, 0],
        comfort_by_class=[0, 85, 0, 111],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-465Middle',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1991,
        intro_month=9,
        retire_year=2001,
        retire_month=5,
        speed=120,
        length=11,
        weight=29,
        axles=4,
        power=0,
        brake_force=29,
        rolling_resistance=13,
        payload=88,
        min_loading_time=17,
        max_loading_time=55,
        overcrowded_capacity=65,
        cost=826000,
        runningcost=0,
        fixed_cost=1721,
        increase_maintenance_after_years=23,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-465Front', 'BR-465Middle'],
        constraint_next=['BR-465Rear', 'BR-465Middle'],
        payload_by_class=[0, 88, 0, 0],
        comfort_by_class=[0, 85, 0, 111],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-465Rear',
        waytype='track',
        copyright='Kieron',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1991,
        intro_month=9,
        retire_year=2001,
        retire_month=5,
        speed=120,
        length=12,
        weight=39,
        axles=4,
        power=600,
        gear=80,
        tractive_effort=93,
        brake_force=29,
        rolling_resistance=13,
        payload=68,
        min_loading_time=17,
        max_loading_time=55,
        overcrowded_capacity=48,
        cost=1238000,
        runningcost=60,
        fixed_cost=7032,
        increase_maintenance_after_years=23,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='panos-g-class-465.wav',
        constraint_prev=['BR-465Middle', 'BR-465Front'],
        constraint_next=['BR-465Front', 'none'],
        payload_by_class=[0, 68, 0, 16],
        comfort_by_class=[0, 85, 0, 111],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
