"""br-423."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://www.bluebell-railway.co.uk/bluebell/pic2/electric/VEP_DIAG_MS001.jpg
_BLEND = 'trains/Railcars/br-423-MBSO-nse.blend'
_UPSTREAM_DAT = 'trains/br-423.dat'

SPECS = [
    Vehicle(
        name='BR-423-DTCL-Front',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1967,
        intro_month=7,
        retire_year=1981,
        retire_month=11,
        speed=140,
        length=11,
        weight=36,
        axles=4,
        power=0,
        payload=38,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=22,
        cost=1575000,
        runningcost=0,
        fixed_cost=1875,
        increase_maintenance_after_years=23,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-410[CEP]Rear', 'BR-414[HAP]Rear', 'BR-419[MLV]', 'BR-499[TLV]', 'BR-423-DTCL-Rear', 'BR-421[CIG]Rear', 'BR-4EPB(rear)', 'BR-2EPB(rear)', 'none'],
        constraint_next=['BR-423-MBSO'],
        payload_by_class=[0, 38, 0, 24],
        comfort_by_class=[0, 79, 0, 144],
        liverytype=['BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'SWT-orange-stripe'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-423-MBSO',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1967,
        intro_month=7,
        retire_year=1981,
        retire_month=11,
        speed=140,
        length=11,
        weight=41,
        axles=4,
        power=750,
        gear=80,
        tractive_effort=74,
        payload=58,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=35,
        cost=1575000,
        runningcost=113,
        fixed_cost=11094,
        increase_maintenance_after_years=23,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-423-DTCL-Front'],
        constraint_next=['BR-423-TSO'],
        payload_by_class=[0, 58, 0, 0],
        comfort_by_class=[0, 79, 0, 144],
        liverytype=['BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'SWT-orange-stripe'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-423-TSO',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1967,
        intro_month=7,
        retire_year=1981,
        retire_month=11,
        speed=140,
        length=11,
        weight=34,
        axles=4,
        payload=98,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=59,
        cost=1575000,
        runningcost=0,
        fixed_cost=1875,
        increase_maintenance_after_years=23,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-423-MBSO'],
        constraint_next=['BR-423-DTCL-Rear'],
        payload_by_class=[0, 98, 0, 0],
        comfort_by_class=[0, 79, 0, 144],
        liverytype=['BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'SWT-orange-stripe'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-423-DTCL-Rear',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1967,
        intro_month=7,
        retire_year=1981,
        retire_month=11,
        speed=140,
        length=11,
        weight=36,
        axles=4,
        power=0,
        payload=38,
        min_loading_time=15,
        max_loading_time=50,
        overcrowded_capacity=22,
        cost=1575000,
        runningcost=0,
        fixed_cost=1875,
        increase_maintenance_after_years=23,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-423-TSO'],
        constraint_next=['BR-410[CEP]Front', 'BR-414[HAP]Front', 'BR-419[MLV]', 'BR-499[TLV]', 'BR-423-DTCL-Front', 'BR-421[CIG]Front', 'BR-4EPB(front)', 'none'],
        payload_by_class=[0, 38, 0, 24],
        comfort_by_class=[0, 79, 0, 144],
        liverytype=['BR-Blue', 'BR-Large-Logo', 'NSE-Standard', 'SWT-orange-stripe'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
