"""br-450."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/br-450-driving.blend'
_UPSTREAM_DAT = 'trains/br-450.dat'

SPECS = [
    Vehicle(
        name='BR-450(front)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=2002,
        intro_month=11,
        speed=160,
        length=11,
        weight=45,
        axles=4,
        power=750,
        gear=80,
        tractive_effort=100,
        brake_force=33,
        rolling_resistance=13,
        payload=71,
        min_loading_time=17,
        max_loading_time=55,
        overcrowded_capacity=40,
        cost=1057500,
        runningcost=113,
        fixed_cost=6881,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-350.wav',
        constraint_prev=['BR-450(rear)', 'BR-444(rear)', 'none'],
        constraint_next=['BR-450(centre1)'],
        payload_by_class=[0, 71, 0, 0],
        comfort_by_class=[0, 85, 0, 102],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-450(centre1)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=2002,
        intro_month=11,
        speed=160,
        length=11,
        weight=40,
        axles=4,
        power=0,
        tractive_effort=0,
        brake_force=30,
        rolling_resistance=13,
        payload=36,
        min_loading_time=17,
        max_loading_time=55,
        overcrowded_capacity=21,
        cost=1899100,
        runningcost=0,
        fixed_cost=3956,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-450(front)'],
        constraint_next=['BR-450(centre2)'],
        payload_by_class=[0, 36, 0, 24],
        comfort_by_class=[0, 85, 0, 102],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-450(centre2)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=2002,
        intro_month=11,
        speed=160,
        length=11,
        weight=40,
        axles=4,
        power=0,
        tractive_effort=0,
        brake_force=30,
        rolling_resistance=13,
        payload=68,
        min_loading_time=17,
        max_loading_time=55,
        overcrowded_capacity=48,
        cost=1899100,
        runningcost=0,
        fixed_cost=3956,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-450(centre1)'],
        constraint_next=['BR-450(rear)'],
        payload_by_class=[0, 68, 0, 0],
        comfort_by_class=[0, 85, 0, 102],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-450(rear)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=2002,
        intro_month=11,
        speed=160,
        length=12,
        weight=45,
        axles=4,
        power=750,
        gear=80,
        tractive_effort=100,
        brake_force=33,
        rolling_resistance=13,
        payload=71,
        min_loading_time=17,
        max_loading_time=55,
        overcrowded_capacity=40,
        cost=1057500,
        runningcost=113,
        fixed_cost=6881,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='video47-class-350.wav',
        constraint_prev=['BR-450(centre2)'],
        constraint_next=['BR-450(front)', 'BR-444(front)', 'none'],
        payload_by_class=[0, 71, 0, 0],
        comfort_by_class=[0, 85, 0, 102],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
