"""br-501."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# https://en.wikipedia.org/wiki/British_Rail_Class_501
# Give my regards to Broad Street.
_BLEND = 'trains/Railcars/br-501-front-propercamera.blend'
_UPSTREAM_DAT = 'trains/br-501.dat'

SPECS = [
    Vehicle(
        name='BR-501(DMB)',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1957,
        intro_month=10,
        retire_year=1965,
        retire_month=12,
        speed=120,
        length=11,
        weight=47,
        axles=4,
        power=740,
        gear=80,
        tractive_effort=113,
        payload=83,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=59,
        cost=1843000,
        runningcost=148,
        fixed_cost=11280,
        increase_maintenance_after_years=15,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-501(DTB)', 'none'],
        constraint_next=['BR-501(T)'],
        payload_by_class=[0, 83],
        comfort_by_class=[0, 77],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        way_constraint_permissive=[3],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-501(T)',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1957,
        intro_month=10,
        retire_year=1965,
        retire_month=12,
        speed=120,
        length=11,
        weight=29,
        axles=4,
        power=0,
        payload=90,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=66,
        cost=1843000,
        runningcost=0,
        fixed_cost=2194,
        increase_maintenance_after_years=15,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-501(DMB)'],
        constraint_next=['BR-501(DTB)'],
        payload_by_class=[0, 90],
        comfort_by_class=[0, 77],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        way_constraint_permissive=[3],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-501(DTB)',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1957,
        intro_month=10,
        retire_year=1965,
        retire_month=12,
        speed=120,
        length=11,
        weight=30,
        axles=4,
        power=0,
        payload=83,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=65,
        cost=1843000,
        runningcost=0,
        fixed_cost=2194,
        increase_maintenance_after_years=15,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-501(T)'],
        constraint_next=['BR-501(DMB)', 'none'],
        payload_by_class=[0, 83],
        comfort_by_class=[0, 77],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        way_constraint_permissive=[3],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
