"""br-506."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# https://en.wikipedia.org/wiki/British_Rail_Class_506
_BLEND = 'trains/Railcars/br-506-driving-trailer-blue-grey.blend'
_UPSTREAM_DAT = 'trains/br-506.dat'

SPECS = [
    Vehicle(
        name='BR-506Front',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1950,
        intro_month=12,
        retire_year=1965,
        retire_month=12,
        speed=120,
        length=10,
        weight=51,
        axles=4,
        power=552,
        gear=80,
        tractive_effort=64,
        payload=52,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=39,
        cost=1843000,
        runningcost=111,
        fixed_cost=11280,
        increase_maintenance_after_years=15,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-506Rear', 'none'],
        constraint_next=['BR-506Centre'],
        payload_by_class=[0, 52],
        comfort_by_class=[0, 78],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        way_constraint_permissive=[1],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-506Centre',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1950,
        intro_month=12,
        retire_year=1965,
        retire_month=12,
        speed=120,
        length=10,
        weight=26,
        axles=4,
        power=0,
        payload=62,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=46,
        cost=1843000,
        runningcost=0,
        fixed_cost=2194,
        increase_maintenance_after_years=15,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['BR-506Front'],
        constraint_next=['BR-506Rear'],
        payload_by_class=[0, 62],
        comfort_by_class=[0, 78],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        way_constraint_permissive=[1],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-506Rear',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1950,
        intro_month=12,
        retire_year=1965,
        retire_month=12,
        speed=120,
        length=10,
        weight=28,
        axles=4,
        power=0,
        payload=60,
        min_loading_time=15,
        max_loading_time=55,
        overcrowded_capacity=45,
        cost=1843000,
        runningcost=0,
        fixed_cost=2194,
        increase_maintenance_after_years=15,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['BR-506Centre'],
        constraint_next=['BR-506Front', 'none'],
        payload_by_class=[0, 60],
        comfort_by_class=[0, 78],
        liverytype=['BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        way_constraint_permissive=[1],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
