"""br-derby-lightweight."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# https://en.wikipedia.org/wiki/British_Rail_Derby_Lightweight
# https://railcar.co.uk/type/derby-lightweight/description
_BLEND = 'trains/Railcars/br-derby-lightweight-dmbs-single-bg.blend'
_UPSTREAM_DAT = 'trains/br-derby-lightweight.dat'

SPECS = [
    Vehicle(
        name='BR-Derby-Lightweight-DMBS',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1954,
        intro_month=3,
        retire_year=1959,
        retire_month=8,
        speed=100,
        length=10,
        weight=27.4,
        axles=4,
        power=224,
        gear=50,
        tractive_effort=52,
        payload=52,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=31,
        cost=1073000,
        runningcost=224,
        fixed_cost=11118,
        increase_maintenance_after_years=17,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='stuart-derby-lightweight.wav',
        constraint_prev=['BR-Derby-Lightweight-DTCL', 'BR-Derby-Lightweight-DMCL', 'BR-Derby-Lightweight-DMBS-single', 'none'],
        constraint_next=['BR-Derby-Lightweight-DTCL', 'BR-Derby-Lightweight-DMCL'],
        payload_by_class=[0, 52, 0, 0],
        comfort_by_class=[0, 84, 0, 111],
        liverytype=['BR-Early', 'BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-Derby-Lightweight-DTCL',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1954,
        intro_month=3,
        retire_year=1959,
        retire_month=8,
        speed=100,
        length=10,
        weight=22.3,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=48,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=28,
        cost=875000,
        runningcost=0,
        fixed_cost=1042,
        increase_maintenance_after_years=17,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['BR-Derby-Lightweight-DMBS', 'BR-Derby-Lightweight-DMBS-single'],
        constraint_next=['BR-Derby-Lightweight-DMBS', 'BR-Derby-Lightweight-DMBS-single', 'BR-Derby-Lightweight-DMS', 'none'],
        payload_by_class=[0, 48, 0, 12],
        comfort_by_class=[0, 84, 0, 111],
        liverytype=['BR-Early', 'BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-Derby-Lightweight-DMCL',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1954,
        intro_month=3,
        retire_year=1959,
        retire_month=8,
        speed=100,
        length=10,
        weight=27,
        axles=4,
        power=224,
        gear=50,
        tractive_effort=52,
        payload=48,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=28,
        cost=1073000,
        runningcost=224,
        fixed_cost=11118,
        increase_maintenance_after_years=17,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='stuart-derby-lightweight.wav',
        constraint_prev=['BR-Derby-Lightweight-DMBS', 'BR-Derby-Lightweight-DMBS-single', 'BR-Derby-Lightweight-TBSL', 'BR-Derby-Lightweight-TSL'],
        constraint_next=['BR-Derby-Lightweight-DMBS', 'BR-Derby-Lightweight-DMBS-single', 'BR-Derby-Lightweight-DMS', 'none'],
        payload_by_class=[0, 48, 0, 12],
        comfort_by_class=[0, 84, 0, 111],
        liverytype=['BR-Early', 'BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-Derby-Lightweight-DMS',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1954,
        intro_month=3,
        retire_year=1959,
        retire_month=8,
        speed=100,
        length=10,
        weight=27.4,
        axles=4,
        power=224,
        gear=50,
        tractive_effort=52,
        payload=64,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=38,
        cost=1073000,
        runningcost=224,
        fixed_cost=11118,
        increase_maintenance_after_years=17,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='stuart-derby-lightweight.wav',
        constraint_prev=['BR-Derby-Lightweight-DTCL', 'BR-Derby-Lightweight-DMCL', 'BR-Derby-Lightweight-DMBS-single', 'none'],
        constraint_next=['BR-Derby-Lightweight-TBSL'],
        payload_by_class=[0, 64, 0, 0],
        comfort_by_class=[0, 84, 0, 111],
        liverytype=['BR-Early', 'BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-Derby-Lightweight-TBSL',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1954,
        intro_month=3,
        retire_year=1959,
        retire_month=8,
        speed=100,
        length=10,
        weight=21.3,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=45,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=24,
        cost=845000,
        runningcost=0,
        fixed_cost=1032,
        increase_maintenance_after_years=17,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['BR-Derby-Lightweight-DMS'],
        constraint_next=['BR-Derby-Lightweight-TSL', 'BR-Derby-Lightweight-DMCL'],
        payload_by_class=[0, 45, 0, 0],
        comfort_by_class=[0, 84, 0, 111],
        liverytype=['BR-Early', 'BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-Derby-Lightweight-TSL',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1954,
        intro_month=3,
        retire_year=1959,
        retire_month=8,
        speed=100,
        length=10,
        weight=21.3,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=61,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=36,
        cost=845000,
        runningcost=0,
        fixed_cost=1032,
        increase_maintenance_after_years=17,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['BR-Derby-Lightweight-TBSL'],
        constraint_next=['BR-Derby-Lightweight-DMCL'],
        payload_by_class=[0, 61, 0, 0],
        comfort_by_class=[0, 84, 0, 111],
        liverytype=['BR-Early', 'BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='BR-Derby-Lightweight-DMBS-single',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='diesel',
        intro_year=1954,
        intro_month=3,
        retire_year=1959,
        retire_month=8,
        speed=100,
        length=10,
        weight=27.4,
        axles=4,
        power=224,
        gear=50,
        tractive_effort=52,
        payload=52,
        min_loading_time=20,
        max_loading_time=60,
        overcrowded_capacity=31,
        cost=1087500,
        runningcost=224,
        fixed_cost=11250,
        increase_maintenance_after_years=17,
        bidirectional=0,
        can_lead_from_rear=1,
        smoke='Diesel',
        sound='stuart-derby-lightweight.wav',
        constraint_prev=['BR-Derby-Lightweight-DTCL', 'BR-Derby-Lightweight-DMCL', 'BR-Derby-Lightweight-DMBS-single', 'none'],
        constraint_next=['BR-Derby-Lightweight-DMBS', 'BR-Derby-Lightweight-DMBS-single', 'BR-Derby-Lightweight-DMS', 'none'],
        payload_by_class=[0, 52, 0, 0],
        comfort_by_class=[0, 84, 0, 111],
        liverytype=['BR-Early', 'BR-Revised', 'BR-Blue', 'BR-Large-Logo'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
