"""gnr-howlden-bogie."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Carriages/gnr-howlden-bogie.blend'
_UPSTREAM_DAT = 'trains/gnr-howlden-bogie.dat'

SPECS = [
    Vehicle(
        name='gnr-howlden-bogie-third',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1895,
        intro_month=3,
        retire_year=1908,
        retire_month=4,
        speed=160,
        length=8,
        weight=22.8,
        axles=4,
        payload=40,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=20,
        cost=333000,
        runningcost=0,
        fixed_cost=396,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear'],
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 98, 100, 109],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-howlden-bogie-third-brake-front',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1895,
        intro_month=3,
        retire_year=1908,
        retire_month=4,
        speed=160,
        length=8,
        weight=22.5,
        axles=4,
        payload=16,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=8,
        cost=334500,
        runningcost=0,
        fixed_cost=5199,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear', 'none'],
        payload_by_class=[0, 0, 16, 10],
        comfort_by_class=[0, 98, 100, 109],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-howlden-bogie-third-brake-rear',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1895,
        intro_month=3,
        retire_year=1908,
        retire_month=4,
        speed=160,
        length=8,
        weight=22.5,
        axles=4,
        payload=16,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=8,
        cost=334500,
        runningcost=0,
        fixed_cost=5199,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        payload_by_class=[0, 0, 16, 10],
        comfort_by_class=[0, 98, 100, 109],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-howlden-bogie-non-lav',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1895,
        intro_month=3,
        retire_year=1908,
        retire_month=4,
        speed=160,
        length=8,
        weight=22.9,
        axles=4,
        payload=60,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=30,
        cost=320000,
        runningcost=0,
        fixed_cost=381,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear'],
        payload_by_class=[0, 60, 0, 0],
        comfort_by_class=[0, 73, 74, 81],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-howlden-bogie-non-lav-second',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1895,
        intro_month=3,
        retire_year=1908,
        retire_month=4,
        speed=160,
        length=8,
        weight=22.9,
        axles=4,
        payload=60,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=30,
        cost=325000,
        runningcost=0,
        fixed_cost=385,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear'],
        payload_by_class=[0, 0, 60, 0],
        comfort_by_class=[0, 73, 74, 81],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-howlden-bogie-non-lav-first',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1895,
        intro_month=3,
        retire_year=1908,
        retire_month=4,
        speed=160,
        length=8,
        weight=22.7,
        axles=4,
        payload=40,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=0,
        cost=331000,
        runningcost=0,
        fixed_cost=385,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear'],
        payload_by_class=[0, 0, 0, 40],
        comfort_by_class=[0, 73, 74, 81],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-howlden-bogie-non-lav-brake-front',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1895,
        intro_month=3,
        retire_year=1908,
        retire_month=4,
        speed=160,
        length=8,
        weight=22.7,
        axles=4,
        payload=50,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=25,
        cost=320000,
        runningcost=0,
        fixed_cost=5181,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear', 'none'],
        payload_by_class=[0, 50, 0, 0],
        comfort_by_class=[0, 73, 74, 81],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-howlden-bogie-non-lav-brake-rear',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1895,
        intro_month=3,
        retire_year=1908,
        retire_month=4,
        speed=160,
        length=8,
        weight=22.7,
        axles=4,
        payload=50,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=25,
        cost=320000,
        runningcost=0,
        fixed_cost=5181,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        payload_by_class=[0, 50, 0, 0],
        comfort_by_class=[0, 73, 74, 81],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-howlden-full-brake',
        waytype='track',
        copyright='Kieron/James',
        freight='Post',
        intro_year=1895,
        intro_month=3,
        retire_year=1908,
        retire_month=4,
        speed=160,
        length=8,
        weight=20.1,
        axles=4,
        payload=360,
        min_loading_time=35,
        max_loading_time=120,
        cost=320000,
        runningcost=0,
        fixed_cost=381,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
