"""gnr-non-cor-elliptical."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# Third
_BLEND = 'trains/Carriages/gnr-non-cor-lav-eliptical-austerity.blend'
_UPSTREAM_DAT = 'trains/gnr-non-cor-elliptical.dat'

SPECS = [
    Vehicle(
        name='gnr-non-cor-lav-elliptical',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1908,
        intro_month=4,
        retire_year=1925,
        retire_month=9,
        speed=160,
        length=10,
        weight=28.5,
        axles=4,
        payload=64,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=32,
        cost=580000,
        runningcost=0,
        fixed_cost=690,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear'],
        payload_by_class=[0, 64, 0, 0],
        comfort_by_class=[0, 102, 104, 111],
        liverytype=['GNR-Standard', 'LNER-Standard', 'WW2-Austerity', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-non-cor-lav-elliptical-composite',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1908,
        intro_month=4,
        retire_year=1925,
        retire_month=9,
        speed=160,
        length=10,
        weight=28.5,
        axles=4,
        payload=24,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=8,
        cost=587500,
        runningcost=0,
        fixed_cost=694,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear'],
        payload_by_class=[0, 0, 16, 24],
        comfort_by_class=[0, 102, 104, 111],
        liverytype=['GNR-Standard', 'LNER-Standard', 'WW2-Austerity', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-non-cor-lav-elliptical-brake-front',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1908,
        intro_month=4,
        retire_year=1925,
        retire_month=9,
        speed=160,
        length=10,
        weight=28.5,
        axles=4,
        payload=58,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=29,
        cost=580000,
        runningcost=0,
        fixed_cost=5490,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear', 'none'],
        payload_by_class=[0, 58, 0, 0],
        comfort_by_class=[0, 102, 104, 111],
        liverytype=['GNR-Standard', 'LNER-Standard', 'WW2-Austerity', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-non-cor-lav-elliptical-brake-rear',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1908,
        intro_month=4,
        retire_year=1925,
        retire_month=9,
        speed=160,
        length=10,
        weight=28.5,
        axles=4,
        payload=58,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=29,
        cost=580000,
        runningcost=0,
        fixed_cost=5490,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        payload_by_class=[0, 58, 0, 0],
        comfort_by_class=[0, 102, 104, 111],
        liverytype=['GNR-Standard', 'LNER-Standard', 'WW2-Austerity', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-non-cor-full-brake',
        waytype='track',
        copyright='jamespetts',
        freight='Post',
        intro_year=1908,
        intro_month=4,
        retire_year=1925,
        retire_month=9,
        speed=160,
        length=10,
        weight=27.5,
        axles=4,
        payload=330,
        min_loading_time=35,
        max_loading_time=90,
        cost=580000,
        runningcost=0,
        fixed_cost=690,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['GNR-Standard', 'LNER-Standard', 'WW2-Austerity', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-non-cor-mail',
        waytype='track',
        copyright='jamespetts',
        freight='Post',
        intro_year=1908,
        intro_month=4,
        retire_year=1925,
        retire_month=9,
        speed=160,
        length=10,
        weight=27.5,
        axles=4,
        payload=550,
        min_loading_time=35,
        max_loading_time=127,
        cost=580000,
        runningcost=0,
        fixed_cost=242,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear'],
        liverytype=['GNR-Standard', 'LNER-Standard', 'WW2-Austerity', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
