"""gnr-clerestory-cor."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# Third
_BLEND = 'trains/Carriages/gnr-clerestory-cor.blend'
_UPSTREAM_DAT = 'trains/gnr-clerestory-cor.dat'

SPECS = [
    Vehicle(
        name='gnr-clerestory-cor-63ft-5',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1897,
        intro_month=2,
        retire_year=1907,
        retire_month=6,
        speed=160,
        length=11,
        weight=32.5,
        axles=6,
        rolling_resistance=17,
        payload=72,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=22,
        cost=800000,
        runningcost=0,
        fixed_cost=952,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-front', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-front', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-front-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-front-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-front', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        constraint_next=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-rear', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-rear', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-rear-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-rear-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-rear', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        payload_by_class=[0, 72, 0, 0],
        comfort_by_class=[0, 132, 134, 147],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-clerestory-cor-63ft-5-composite',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1897,
        intro_month=2,
        retire_year=1907,
        retire_month=6,
        speed=160,
        length=11,
        weight=32.5,
        axles=6,
        rolling_resistance=17,
        payload=30,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=12,
        cost=810000,
        runningcost=0,
        fixed_cost=953,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-front', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-front', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-front-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-front-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-front', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        constraint_next=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-rear', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-rear', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-rear-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-rear-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-rear', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        payload_by_class=[0, 0, 24, 30],
        comfort_by_class=[0, 132, 134, 147],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-clerestory-cor-63ft-5-first',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1897,
        intro_month=2,
        retire_year=1907,
        retire_month=6,
        speed=160,
        length=11,
        weight=32.5,
        axles=6,
        rolling_resistance=17,
        payload=42,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=0,
        cost=818000,
        runningcost=0,
        fixed_cost=954,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-front', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-front', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-front-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-front-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-front', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        constraint_next=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-rear', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-rear', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-rear-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-rear-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-rear', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        payload_by_class=[0, 0, 0, 42],
        comfort_by_class=[0, 132, 134, 149],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-clerestory-cor-brake-front-63ft-5',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1897,
        intro_month=2,
        retire_year=1907,
        retire_month=6,
        speed=160,
        length=11,
        weight=32.5,
        axles=6,
        rolling_resistance=17,
        payload=40,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=15,
        cost=800000,
        runningcost=0,
        fixed_cost=5752,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-rear', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-rear', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-rear-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-rear-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-rear', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first', 'none'],
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 132, 134, 147],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-clerestory-cor-brake-rear-63ft-5',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1897,
        intro_month=2,
        retire_year=1907,
        retire_month=6,
        speed=160,
        length=11,
        weight=32.5,
        axles=6,
        rolling_resistance=17,
        payload=40,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=15,
        cost=800000,
        runningcost=0,
        fixed_cost=5752,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-front', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-front', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-front-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-front-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-front', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 132, 134, 147],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-clerestory-dining-car',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1897,
        intro_month=2,
        retire_year=1907,
        retire_month=6,
        speed=160,
        length=11,
        weight=33,
        axles=6,
        rolling_resistance=17,
        payload=20,
        min_loading_time=20,
        max_loading_time=50,
        catering_level=4,
        cost=950000,
        runningcost=0,
        fixed_cost=19131,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-front', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-front', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-front-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-front-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-front', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        constraint_next=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-rear', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-rear', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-rear-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-rear-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-rear', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        payload_by_class=[0, 20, 0, 16],
        comfort_by_class=[0, 132, 134, 147],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-clerestory-cor-53ft-6',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1897,
        intro_month=2,
        retire_year=1907,
        retire_month=6,
        speed=160,
        length=9,
        weight=25,
        axles=4,
        payload=56,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=16,
        cost=740000,
        runningcost=0,
        fixed_cost=881,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-front', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-front', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-front-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-front-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-front', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        constraint_next=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-rear', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-rear', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-rear-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-rear-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-rear', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        payload_by_class=[0, 56, 0, 0],
        comfort_by_class=[0, 123, 129, 144],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-clerestory-cor-composite-53ft-6',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1897,
        intro_month=2,
        retire_year=1907,
        retire_month=6,
        speed=160,
        length=9,
        weight=25,
        axles=4,
        payload=56,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=16,
        cost=740000,
        runningcost=0,
        fixed_cost=881,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-front', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-front', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-front-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-front-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-front', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        constraint_next=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-rear', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-rear', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-rear-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-rear-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-rear', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        payload_by_class=[0, 56, 0, 0],
        comfort_by_class=[0, 123, 129, 144],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-clerestory-cor-brake-front-53ft-6',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1897,
        intro_month=2,
        retire_year=1907,
        retire_month=6,
        speed=160,
        length=9,
        weight=25,
        axles=4,
        payload=32,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=10,
        cost=740000,
        runningcost=0,
        fixed_cost=5681,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['LNER-Gresley-Express-Brake-rear', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-rear', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-rear-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-rear-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-rear', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first', 'none'],
        payload_by_class=[0, 32, 0, 0],
        comfort_by_class=[0, 123, 129, 144],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-clerestory-cor-brake-rear-53ft-6',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1897,
        intro_month=2,
        retire_year=1907,
        retire_month=6,
        speed=160,
        length=9,
        weight=25,
        axles=4,
        payload=32,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=10,
        cost=740000,
        runningcost=0,
        fixed_cost=5681,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-front', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-front', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-front-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-front-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-front', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        payload_by_class=[0, 32, 0, 0],
        comfort_by_class=[0, 123, 129, 144],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-clerestory-cor-full-brake-45ft',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Post',
        intro_year=1897,
        intro_month=2,
        retire_year=1907,
        retire_month=6,
        speed=160,
        length=8,
        weight=23.5,
        axles=4,
        payload=300,
        min_loading_time=25,
        max_loading_time=180,
        cost=700000,
        runningcost=0,
        fixed_cost=5633,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-clerestory-cor-mail-45ft',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Post',
        intro_year=1897,
        intro_month=2,
        retire_year=1907,
        retire_month=6,
        speed=160,
        length=8,
        weight=23.5,
        axles=4,
        payload=600,
        min_loading_time=35,
        max_loading_time=127,
        cost=700000,
        runningcost=0,
        fixed_cost=292,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-front', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-front', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-front-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-front-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-front', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        constraint_next=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-rear', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-rear', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-rear-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-rear-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-rear', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-clerestory-cor-tpo-45ft',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Post',
        intro_year=1897,
        intro_month=2,
        retire_year=1907,
        retire_month=6,
        speed=160,
        length=8,
        weight=23.5,
        axles=4,
        payload=350,
        min_loading_time=35,
        max_loading_time=127,
        catering_level=1,
        cost=770000,
        runningcost=0,
        fixed_cost=24321,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-front', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-front', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-front-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-front-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-front', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        constraint_next=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-rear', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-rear', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-rear-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-rear-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-rear', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        liverytype=['GNR-Standard', 'LNER-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
