"""gnr-gresley-cor."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# Third class
_BLEND = 'trains/Carriages/gnr-gresley-cor-br.blend'
_UPSTREAM_DAT = 'trains/gnr-gresley-cor.dat'

SPECS = [
    Vehicle(
        name='gnr-gresley-cor',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1907,
        intro_month=6,
        retire_year=1923,
        retire_month=5,
        speed=160,
        length=10,
        weight=33,
        axles=4,
        payload=64,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=24,
        cost=740000,
        runningcost=0,
        fixed_cost=881,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-front', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-front', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-front-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-front-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-front', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        constraint_next=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-rear', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-rear', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-rear-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-rear-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-rear', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        payload_by_class=[0, 64, 0, 0],
        comfort_by_class=[0, 131, 131, 146],
        liverytype=['GNR-Standard', 'LNER-Standard', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-gresley-cor-first',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1907,
        intro_month=6,
        retire_year=1923,
        retire_month=5,
        speed=160,
        length=10,
        weight=33,
        axles=4,
        payload=42,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=0,
        cost=760000,
        runningcost=0,
        fixed_cost=889,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-front', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-front', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-front-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-front-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-front', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        constraint_next=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-rear', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-rear', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-rear-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-rear-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-rear', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        payload_by_class=[0, 0, 0, 42],
        comfort_by_class=[0, 131, 131, 146],
        liverytype=['GNR-Standard', 'LNER-Standard', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-gresley-cor-brake-front',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1907,
        intro_month=6,
        retire_year=1923,
        retire_month=5,
        speed=160,
        length=10,
        weight=32.7,
        axles=4,
        payload=40,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=16,
        cost=735000,
        runningcost=0,
        fixed_cost=5675,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-rear', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-rear', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-rear-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-rear-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-rear', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first', 'none'],
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 131, 131, 146],
        liverytype=['GNR-Standard', 'LNER-Standard', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-gresley-cor-brake-rear',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1907,
        intro_month=6,
        retire_year=1923,
        retire_month=5,
        speed=160,
        length=10,
        weight=32.7,
        axles=4,
        payload=40,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=16,
        cost=735000,
        runningcost=0,
        fixed_cost=5675,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-front', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-front', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-front-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-front-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-front', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 131, 131, 146],
        liverytype=['GNR-Standard', 'LNER-Standard', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-gresley-cor-dining',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1907,
        intro_month=6,
        retire_year=1923,
        retire_month=5,
        speed=160,
        length=11,
        weight=36,
        axles=4,
        rolling_resistance=17,
        payload=24,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=8,
        catering_level=4,
        cost=825000,
        runningcost=0,
        fixed_cost=18982,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-front', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-front', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-front-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-front-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-front', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        constraint_next=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-rear', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-rear', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-rear-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-rear-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-rear', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        payload_by_class=[0, 24, 0, 16],
        comfort_by_class=[0, 131, 131, 146],
        liverytype=['GNR-Standard', 'LNER-Standard', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-gresley-cor-parcels-brake',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Post',
        intro_year=1907,
        intro_month=6,
        retire_year=1923,
        retire_month=5,
        speed=160,
        length=10,
        weight=32,
        axles=4,
        payload=320,
        min_loading_time=25,
        max_loading_time=180,
        cost=730000,
        runningcost=0,
        fixed_cost=5669,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['GNR-Standard', 'LNER-Standard', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-gresley-cor-mail',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Post',
        intro_year=1907,
        intro_month=6,
        retire_year=1923,
        retire_month=5,
        speed=160,
        length=10,
        weight=32,
        axles=4,
        payload=500,
        min_loading_time=35,
        max_loading_time=180,
        cost=730000,
        runningcost=0,
        fixed_cost=304,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-front', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-front', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-front-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-front-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-front', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        constraint_next=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-rear', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-rear', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-rear-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-rear-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-rear', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        liverytype=['GNR-Standard', 'LNER-Standard', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gnr-gresley-cor-tpo',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Post',
        intro_year=1907,
        intro_month=6,
        retire_year=1923,
        retire_month=5,
        speed=160,
        length=10,
        weight=32,
        axles=4,
        payload=355,
        min_loading_time=35,
        max_loading_time=180,
        catering_level=1,
        cost=730000,
        runningcost=0,
        fixed_cost=24304,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-front', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-front', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-front-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-front-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-front', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        constraint_next=['LNER-Gresley-Express-Coach', 'LNER-Gresley-Express-Brake-rear', 'LNER-Gresley-Express-Dining', 'LNER-Gresley-Express-Mail', 'LNER-Gresley-Express-TPO', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Buffet', 'LNER-Gresley-Express-Coach-All-Doors', 'LNER-Gresley-Express-Brake-all-doors-rear', 'gnr-clerestory-cor-63ft-5', 'gnr-clerestory-cor-brake-rear-63ft-5', 'gnr-clerestory-dining-car', 'gnr-clerestory-cor-53ft-6', 'gnr-clerestory-cor-brake-rear-53ft-6', 'gnr-clerestory-cor-full-brake-45ft', 'gnr-clerestory-cor-mail-45ft', 'gnr-clerestory-cor-tpo-45ft', 'gnr-gresley-cor', 'gnr-gresley-cor-brake-rear', 'gnr-gresley-cor-dining', 'gnr-gresley-cor-parcels-brake', 'gnr-gresley-cor-mail', 'gnr-gresley-cor-tpo', 'gnr-gresley-cor-first', 'gnr-clerestory-cor-63ft-5-composite', 'gnr-clerestory-cor-63ft-5-first', 'gnr-clerestory-cor-composite-53ft-6', 'LNER-Gresley-Express-first', 'LNER-Gresley-Express-first'],
        liverytype=['GNR-Standard', 'LNER-Standard', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
