"""gwr-toplight-corridor."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See "Great Western Coaches from 1890" by Michael Harris at pp. 64-67 for details
# The details are incomplete, however, so reference has been made to pictures of
# models and diagrams online.
#
# These are the 57ft versions.
#
# 4 aside in the thirds and 3 aside in the firsts
_BLEND = 'trains/Carriages/gwr-toplight.blend'
_UPSTREAM_DAT = 'trains/gwr-toplight-corridor.dat'

SPECS = [
    Vehicle(
        name='gwr-toplight-corridor-third',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1907,
        intro_month=4,
        retire_year=1923,
        retire_month=1,
        speed=160,
        length=10,
        weight=27.9,
        axles=4,
        payload=64,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=36,
        cost=716000,
        runningcost=0,
        fixed_cost=852,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 64, 0, 0],
        comfort_by_class=[0, 129, 131, 147],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-toplight-corridor-composite',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1907,
        intro_month=4,
        retire_year=1923,
        retire_month=1,
        speed=160,
        length=10,
        weight=28.0,
        axles=4,
        payload=24,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=16,
        cost=716500,
        runningcost=0,
        fixed_cost=852,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 24, 0, 24],
        comfort_by_class=[0, 129, 131, 147],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-toplight-corridor-composite-second',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1907,
        intro_month=4,
        retire_year=1923,
        retire_month=1,
        speed=160,
        length=10,
        weight=28.0,
        axles=4,
        payload=24,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=16,
        cost=716550,
        runningcost=0,
        fixed_cost=852,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 0, 24, 24],
        comfort_by_class=[0, 129, 131, 147],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-toplight-corridor-brake-third-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1907,
        intro_month=4,
        retire_year=1923,
        retire_month=1,
        speed=160,
        length=10,
        weight=27.1,
        axles=4,
        payload=40,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=24,
        cost=716000,
        runningcost=0,
        fixed_cost=852,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo', 'none'],
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 129, 131, 147],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-toplight-corridor-brake-third-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1907,
        intro_month=4,
        retire_year=1923,
        retire_month=1,
        speed=160,
        length=10,
        weight=27.1,
        axles=4,
        payload=40,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=24,
        cost=716000,
        runningcost=0,
        fixed_cost=5652,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 129, 131, 147],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-toplight-corridor-restaurant',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1907,
        intro_month=4,
        retire_year=1923,
        retire_month=1,
        speed=160,
        length=10,
        weight=30.1,
        axles=4,
        payload=24,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=0,
        catering_level=4,
        cost=745000,
        runningcost=0,
        fixed_cost=18887,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 24, 0, 10],
        comfort_by_class=[0, 129, 131, 147],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-toplight-corridor-full-brake',
        waytype='track',
        copyright='JamesPetts',
        freight='Post',
        intro_year=1907,
        intro_month=4,
        retire_year=1923,
        retire_month=1,
        speed=160,
        length=10,
        weight=26.7,
        axles=4,
        payload=400,
        min_loading_time=45,
        max_loading_time=180,
        cost=714000,
        runningcost=0,
        fixed_cost=5652,
        bidirectional=1,
        can_lead_from_rear=0,
        payload_by_class=[400],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-toplight-corridor-mail',
        waytype='track',
        copyright='JamesPetts',
        freight='Post',
        intro_year=1907,
        intro_month=4,
        retire_year=1923,
        retire_month=1,
        speed=160,
        length=10,
        weight=26.6,
        axles=4,
        payload=600,
        min_loading_time=45,
        max_loading_time=180,
        cost=714000,
        runningcost=0,
        fixed_cost=300,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-toplight-corridor-tpo',
        waytype='track',
        copyright='JamesPetts',
        freight='Post',
        intro_year=1907,
        intro_month=4,
        retire_year=1923,
        retire_month=1,
        speed=160,
        length=10,
        weight=27.0,
        axles=4,
        payload=400,
        min_loading_time=45,
        max_loading_time=180,
        catering_level=1,
        cost=777000,
        runningcost=0,
        fixed_cost=24327,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
