"""gwr-bow-ended-corridor."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See "Great Western Coaches from 1890" by Michael Harris at pp. 77-82 for details
# The details are incomplete, however, so reference has been made to pictures of
# models for layouts, which may not be entirely accurate.
# 4 aside in the thirds and 3 aside in the firsts
# http://www.gw-svr-a.org.uk/images/C54-gwr-bow-end_1500px.jpg
_BLEND = 'trains/Carriages/gwr-bow-ended-corridor-tpo-lined.blend'
_UPSTREAM_DAT = 'trains/gwr-bow-ended-corridor.dat'

SPECS = [
    Vehicle(
        name='gwr-bow-ended-corridor-third',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1922,
        intro_month=12,
        retire_year=1936,
        retire_month=12,
        speed=160,
        length=10,
        weight=30.8,
        axles=4,
        payload=64,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=36,
        cost=721000,
        runningcost=0,
        fixed_cost=858,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 64, 0, 0],
        comfort_by_class=[0, 132, 132, 147],
        liverytype=['GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-bow-ended-corridor-composite',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1922,
        intro_month=12,
        retire_year=1936,
        retire_month=12,
        speed=160,
        length=10,
        weight=30.8,
        axles=4,
        payload=36,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=16,
        cost=726000,
        runningcost=0,
        fixed_cost=860,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 24, 0, 36],
        comfort_by_class=[0, 132, 132, 147],
        liverytype=['GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-bow-ended-corridor-brake-third-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1922,
        intro_month=12,
        retire_year=1936,
        retire_month=12,
        speed=160,
        length=10,
        weight=30.5,
        axles=4,
        payload=32,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=20,
        cost=720000,
        runningcost=0,
        fixed_cost=858,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo', 'none'],
        payload_by_class=[0, 32, 0, 0],
        comfort_by_class=[0, 132, 132, 147],
        liverytype=['GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-bow-ended-corridor-brake-third-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1922,
        intro_month=12,
        retire_year=1936,
        retire_month=12,
        speed=160,
        length=10,
        weight=30.5,
        axles=4,
        payload=32,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=20,
        cost=720000,
        runningcost=0,
        fixed_cost=5100,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 32, 0, 0],
        comfort_by_class=[0, 132, 132, 147],
        liverytype=['GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-bow-ended-corridor-restaurant',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1922,
        intro_month=12,
        retire_year=1936,
        retire_month=12,
        speed=160,
        length=10,
        weight=31.0,
        axles=4,
        payload=24,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=0,
        catering_level=4,
        cost=725000,
        runningcost=0,
        fixed_cost=18923,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 24, 0, 12],
        comfort_by_class=[0, 132, 132, 147],
        liverytype=['GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-bow-ended-corridor-buffet',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1931,
        intro_month=9,
        retire_year=1936,
        retire_month=12,
        speed=160,
        length=10,
        weight=30.6,
        axles=4,
        payload=2,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=24,
        catering_level=3,
        cost=722400,
        runningcost=0,
        fixed_cost=18700,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 2, 0, 0],
        comfort_by_class=[0, 132, 132, 147],
        liverytype=['GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-bow-ended-corridor-full-brake',
        waytype='track',
        copyright='JamesPetts',
        freight='Post',
        intro_year=1922,
        intro_month=12,
        retire_year=1936,
        retire_month=12,
        speed=160,
        length=10,
        weight=28.2,
        axles=4,
        payload=400,
        min_loading_time=25,
        max_loading_time=55,
        cost=721000,
        runningcost=0,
        fixed_cost=5100,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-bow-ended-corridor-mail',
        waytype='track',
        copyright='JamesPetts',
        freight='Post',
        intro_year=1922,
        intro_month=12,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=10,
        weight=28.3,
        axles=4,
        payload=600,
        min_loading_time=45,
        max_loading_time=180,
        cost=721000,
        runningcost=0,
        fixed_cost=300,
        increase_maintenance_after_years=15,
        years_before_maintenance_max_reached=30,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        liverytype=['GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-bow-ended-corridor-tpo',
        waytype='track',
        copyright='JamesPetts',
        freight='Post',
        intro_year=1922,
        intro_month=12,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=10,
        weight=28.3,
        axles=4,
        payload=400,
        min_loading_time=45,
        max_loading_time=180,
        catering_level=1,
        cost=785000,
        runningcost=0,
        fixed_cost=24327,
        increase_maintenance_after_years=15,
        years_before_maintenance_max_reached=30,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        liverytype=['GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
