"""gwr-churchward-star."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Locomotives/gwr-churchward-star-ww1-austerity.blend'
_UPSTREAM_DAT = 'trains/gwr-churchward-star.dat'

SPECS = [
    Vehicle(
        name='GWR-Churchward-Star',
        waytype='track',
        copyright='Kieron',
        freight='None',
        engine_type='steam',
        intro_year=1907,
        intro_month=5,
        retire_year=1910,
        retire_month=10,
        speed=150,
        length=6,
        weight=75,
        axle_load=20,
        power=399,
        tractive_effort=124,
        way_wear_factor=98438,
        payload=0,
        cost=10752000,
        runningcost=182,
        fixed_cost=48960,
        increase_maintenance_after_years=28,
        years_before_maintenance_max_reached=16,
        smoke='Steam',
        sound='keithpeter-gwr-hall.wav',
        constraint_next=['GWR-Churchward-Star-Tender'],
        liverytype=['GWR-standard-green', 'WW1-Austerity', 'GWR-chocolate-cream-lined', 'GWR-shirtbutton', 'GWR-hawksworth', 'WW2-Austerity', 'BR-Early'],
        upgrade=['GWR-Churchward-Star-superheated', 'GWR-Castle'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='GWR-Churchward-Star-superheated',
        waytype='track',
        copyright='Kieron',
        freight='None',
        engine_type='steam',
        intro_year=1910,
        intro_month=10,
        retire_year=1923,
        retire_month=8,
        speed=150,
        length=6,
        weight=75,
        axle_load=20,
        power=445,
        tractive_effort=124,
        way_wear_factor=98438,
        payload=0,
        cost=10752000,
        runningcost=179,
        fixed_cost=48960,
        upgrade_price=25000,
        increase_maintenance_after_years=28,
        years_before_maintenance_max_reached=16,
        smoke='Steam',
        sound='keithpeter-gwr-hall.wav',
        constraint_next=['GWR-Churchward-Star-Tender'],
        liverytype=['GWR-standard-green', 'WW1-Austerity', 'GWR-chocolate-cream-lined', 'GWR-shirtbutton', 'GWR-hawksworth', 'WW2-Austerity', 'BR-Early'],
        upgrade=['GWR-Castle'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='GWR-Churchward-Star-Tender',
        waytype='track',
        copyright='Kieron',
        freight='None',
        intro_year=1907,
        intro_month=5,
        retire_year=1923,
        retire_month=8,
        speed=150,
        length=4,
        weight=40.6,
        axles=3,
        power=0,
        payload=0,
        cost=0,
        runningcost=0,
        fixed_cost=0,
        increase_maintenance_after_years=28,
        years_before_maintenance_max_reached=16,
        constraint_prev=['GWR-Churchward-Star', 'GWR-Churchward-Star-superheated'],
        liverytype=['GWR-standard-green', 'WW1-Austerity', 'GWR-chocolate-cream-lined', 'GWR-shirtbutton', 'GWR-hawksworth', 'WW2-Austerity', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
