"""gwr-clerestory-suburban."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Carriages/gwr-clerestory-suburban-50ft-collett-unlined.blend'
_UPSTREAM_DAT = 'trains/gwr-clerestory-suburban.dat'

SPECS = [
    Vehicle(
        name='gwr-clerestory-suburban-third',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1894,
        intro_month=3,
        retire_year=1908,
        retire_month=10,
        speed=160,
        length=8,
        weight=24.0,
        axles=4,
        payload=64,
        min_loading_time=15,
        max_loading_time=45,
        overcrowded_capacity=32,
        cost=711000,
        runningcost=0,
        fixed_cost=836,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-front', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-front', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-front', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-front', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-front', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-front'],
        constraint_next=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-rear', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-rear', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-rear', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-rear', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-rear', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-rear'],
        payload_by_class=[0, 64, 0, 0],
        comfort_by_class=[0, 71, 77, 84],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-clerestory-suburban-second',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1894,
        intro_month=3,
        retire_year=1908,
        retire_month=10,
        speed=160,
        length=9,
        weight=25.7,
        axles=4,
        payload=64,
        min_loading_time=15,
        max_loading_time=45,
        overcrowded_capacity=32,
        cost=765000,
        runningcost=0,
        fixed_cost=850,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-front', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-front', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-front', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-front', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-front', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-front'],
        constraint_next=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-rear', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-rear', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-rear', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-rear', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-rear', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-rear'],
        payload_by_class=[0, 0, 64, 0],
        comfort_by_class=[0, 71, 77, 84],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-clerestory-suburban-first',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1894,
        intro_month=3,
        retire_year=1908,
        retire_month=10,
        speed=160,
        length=9,
        weight=25.6,
        axles=4,
        payload=42,
        min_loading_time=15,
        max_loading_time=45,
        overcrowded_capacity=0,
        cost=775000,
        runningcost=0,
        fixed_cost=851,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-front', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-front', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-front', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-front', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-front', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-front'],
        constraint_next=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-rear', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-rear', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-rear', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-rear', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-rear', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-rear'],
        payload_by_class=[0, 0, 0, 42],
        comfort_by_class=[0, 71, 77, 84],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-clerestory-suburban-brake-third-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1894,
        intro_month=3,
        retire_year=1908,
        retire_month=10,
        speed=160,
        length=9,
        weight=24.5,
        axles=4,
        payload=32,
        min_loading_time=15,
        max_loading_time=45,
        overcrowded_capacity=16,
        cost=771000,
        runningcost=0,
        fixed_cost=851,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-rear', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-rear', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-rear', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-rear', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-rear', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-rear', 'none'],
        payload_by_class=[0, 32, 0, 0],
        comfort_by_class=[0, 71, 77, 84],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-clerestory-suburban-brake-third-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1894,
        intro_month=3,
        retire_year=1908,
        retire_month=10,
        speed=160,
        length=9,
        weight=24.5,
        axles=4,
        payload=32,
        min_loading_time=15,
        max_loading_time=45,
        overcrowded_capacity=16,
        cost=771000,
        runningcost=0,
        fixed_cost=5230,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-front', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-front', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-front', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-front', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-front', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-front'],
        payload_by_class=[0, 32, 0, 0],
        comfort_by_class=[0, 71, 77, 84],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
