"""gwr-hawksworth-non-corridor."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See "Great Western Coaches from 1890" by Michael Harris at pp. 106-111 for details
_BLEND = 'trains/Carriages/gwr-hawksworth-non-corridor-br.blend'
_UPSTREAM_DAT = 'trains/gwr-hawksworth-non-corridor.dat'

SPECS = [
    Vehicle(
        name='gwr-hawksworth-non-corridor-third',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1945,
        intro_month=1,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=11,
        weight=31.3,
        axles=4,
        payload=100,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=50,
        cost=592500,
        runningcost=0,
        fixed_cost=700,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-front', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-front', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-front', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-front', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-front', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-front'],
        constraint_next=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-rear', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-rear', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-rear', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-rear', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-rear', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-rear'],
        payload_by_class=[0, 100, 0, 0],
        comfort_by_class=[0, 79, 79, 89],
        liverytype=['GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-hawksworth-non-corridor-composite',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1945,
        intro_month=1,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=11,
        weight=29.5,
        axles=4,
        payload=50,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=25,
        cost=599900,
        runningcost=0,
        fixed_cost=710,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-front', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-front', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-front', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-front', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-front', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-front'],
        constraint_next=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-rear', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-rear', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-rear', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-rear', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-rear', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-rear'],
        payload_by_class=[0, 50, 0, 32],
        comfort_by_class=[0, 79, 79, 89],
        liverytype=['GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-hawksworth-non-corridor-brake-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1945,
        intro_month=1,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=11,
        weight=28.9,
        axles=4,
        payload=60,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=30,
        cost=592500,
        runningcost=0,
        fixed_cost=700,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-rear', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-rear', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-rear', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-rear', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-rear', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-rear', 'none'],
        payload_by_class=[0, 60, 0, 0],
        comfort_by_class=[0, 79, 79, 89],
        liverytype=['GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-hawksworth-non-corridor-brake-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1945,
        intro_month=1,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=11,
        weight=28.9,
        axles=4,
        payload=60,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=30,
        cost=592500,
        runningcost=0,
        fixed_cost=700,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-front', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-front', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-front', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-front', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-front', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-front'],
        payload_by_class=[0, 60, 0, 0],
        comfort_by_class=[0, 79, 79, 89],
        liverytype=['GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
