"""gwr-sunshine-corridor."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See "Great Western Coaches from 1890" by Michael Harris at pp. 97-99 for details
# The details are incomplete, however, so reference has been made to pictures of
# models for layouts, which may not be entirely accurate.
# 4 aside in the thirds and 3 aside in the firsts
_BLEND = 'trains/Carriages/gwr-sunshine-corridor-br.blend'
_UPSTREAM_DAT = 'trains/gwr-sunshine-corridor.dat'

SPECS = [
    Vehicle(
        name='gwr-sunshine-corridor-third',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1936,
        intro_month=11,
        retire_year=1944,
        retire_month=5,
        speed=160,
        length=10,
        weight=32.1,
        axles=4,
        payload=64,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=36,
        cost=698250,
        runningcost=0,
        fixed_cost=5832,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 64, 0, 0],
        comfort_by_class=[0, 137, 137, 150],
        liverytype=['GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-sunshine-corridor-first',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1936,
        intro_month=11,
        retire_year=1944,
        retire_month=5,
        speed=160,
        length=10,
        weight=32.1,
        axles=4,
        payload=42,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=0,
        cost=698250,
        runningcost=0,
        fixed_cost=5832,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 0, 0, 42],
        comfort_by_class=[0, 137, 137, 150],
        liverytype=['GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-sunshine-corridor-composite-brake-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1936,
        intro_month=11,
        retire_year=1944,
        retire_month=5,
        speed=160,
        length=10,
        weight=32.1,
        axles=4,
        payload=24,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=15,
        cost=698250,
        runningcost=0,
        fixed_cost=5832,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo', 'none'],
        payload_by_class=[0, 24, 0, 12],
        comfort_by_class=[0, 137, 137, 150],
        liverytype=['GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-sunshine-corridor-composite-brake-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1936,
        intro_month=11,
        retire_year=1944,
        retire_month=5,
        speed=160,
        length=10,
        weight=32.1,
        axles=4,
        payload=24,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=15,
        cost=698250,
        runningcost=0,
        fixed_cost=5832,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 24, 0, 12],
        comfort_by_class=[0, 137, 137, 150],
        liverytype=['GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-sunshine-corridor-brake-third-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1936,
        intro_month=11,
        retire_year=1944,
        retire_month=5,
        speed=160,
        length=10,
        weight=32.1,
        axles=4,
        payload=32,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=18,
        cost=698250,
        runningcost=0,
        fixed_cost=5832,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo', 'none'],
        payload_by_class=[0, 32, 0, 0],
        comfort_by_class=[0, 137, 137, 150],
        liverytype=['GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-sunshine-corridor-brake-third-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1936,
        intro_month=11,
        retire_year=1944,
        retire_month=5,
        speed=160,
        length=10,
        weight=32.1,
        axles=4,
        payload=40,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=24,
        cost=698250,
        runningcost=0,
        fixed_cost=5832,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 137, 137, 150],
        liverytype=['GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-sunshine-corridor-full-brake',
        waytype='track',
        copyright='JamesPetts',
        freight='Post',
        intro_year=1936,
        intro_month=11,
        retire_year=1944,
        retire_month=5,
        speed=160,
        length=10,
        weight=32.1,
        axles=4,
        payload=400,
        min_loading_time=45,
        max_loading_time=180,
        cost=698250,
        runningcost=0,
        fixed_cost=5832,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-sunshine-corridor-restaurant',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1936,
        intro_month=11,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=10,
        weight=32.1,
        axles=6,
        payload=32,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=0,
        catering_level=4,
        cost=837900,
        runningcost=0,
        fixed_cost=11737,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 32, 0, 18],
        comfort_by_class=[0, 137, 137, 150],
        liverytype=['GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-sunshine-corridor-buffet',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1936,
        intro_month=11,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=10,
        weight=32.1,
        axles=6,
        payload=32,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=30,
        catering_level=3,
        cost=761095,
        runningcost=0,
        fixed_cost=7465,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 32, 0, 0],
        comfort_by_class=[0, 137, 137, 150],
        liverytype=['GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
