"""gwr-6-wheel-carriages."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# Diagram S3
_BLEND = 'trains/Carriages/gwr-6-wheel-28ft-brown.blend'
_UPSTREAM_DAT = 'trains/gwr-6-wheel-carriages.dat'

SPECS = [
    Vehicle(
        name='gwr-6-wheel-third',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1872,
        intro_month=10,
        retire_year=1893,
        retire_month=1,
        speed=150,
        length=5,
        weight=11.8,
        axles=3,
        payload=50,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=25,
        cost=325000,
        runningcost=0,
        fixed_cost=388,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-6-wheel-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'gwr-6-wheel-third', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail'],
        payload_by_class=[0, 50, 0, 0],
        comfort_by_class=[0, 63, 74, 84],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-6-wheel-clerestory-third',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1877,
        intro_month=7,
        retire_year=1893,
        retire_month=1,
        speed=150,
        length=5,
        weight=12.0,
        axles=3,
        payload=50,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=25,
        cost=355000,
        runningcost=0,
        fixed_cost=412,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-6-wheel-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'gwr-6-wheel-third', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail'],
        payload_by_class=[0, 50, 0, 0],
        comfort_by_class=[0, 64, 75, 86],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-6-wheel-composite',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1872,
        intro_month=10,
        retire_year=1893,
        retire_month=1,
        speed=150,
        length=5,
        weight=12.6,
        axles=3,
        payload=16,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=8,
        cost=345000,
        runningcost=0,
        fixed_cost=389,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-6-wheel-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'gwr-6-wheel-third', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail'],
        payload_by_class=[0, 0, 16, 12],
        comfort_by_class=[0, 63, 74, 84],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-6-wheel-clerestory-composite',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1877,
        intro_month=7,
        retire_year=1893,
        retire_month=1,
        speed=150,
        length=5,
        weight=12.9,
        axles=3,
        payload=16,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=8,
        cost=362000,
        runningcost=0,
        fixed_cost=418,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-6-wheel-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'gwr-6-wheel-third', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail'],
        payload_by_class=[0, 0, 16, 12],
        comfort_by_class=[0, 63, 74, 84],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-6-wheel-brake-third',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1872,
        intro_month=10,
        retire_year=1893,
        retire_month=1,
        speed=150,
        length=6,
        weight=12.5,
        axles=3,
        payload=50,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=25,
        cost=325000,
        runningcost=0,
        fixed_cost=5185,
        bidirectional=1,
        can_lead_from_rear=0,
        payload_by_class=[0, 50, 0, 0],
        comfort_by_class=[0, 63, 74, 84],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-6-wheel-clerestory-brake-third',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1877,
        intro_month=7,
        retire_year=1893,
        retire_month=1,
        speed=150,
        length=6,
        weight=12.7,
        axles=3,
        payload=50,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=25,
        cost=355000,
        runningcost=0,
        fixed_cost=5230,
        bidirectional=1,
        can_lead_from_rear=0,
        payload_by_class=[0, 50, 0, 0],
        comfort_by_class=[0, 64, 75, 86],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
