"""gwr-clerestory-bogie-arc-carriages."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# Diagram C2
# http://www.penrhos.me.uk/JSDCmed/C2Lot207.jpg
_BLEND = 'trains/Carriages/gwr-clerestory-40ft-brown.blend'
_UPSTREAM_DAT = 'trains/gwr-clerestory-bogie-arc-carriages.dat'

SPECS = [
    Vehicle(
        name='gwr-bogie-clerestory-third',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1881,
        intro_month=8,
        retire_year=1894,
        retire_month=6,
        speed=160,
        length=7,
        weight=18.2,
        axles=4,
        payload=56,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=28,
        cost=535000,
        runningcost=0,
        fixed_cost=635,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-6-wheel-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'gwr-6-wheel-third', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail'],
        payload_by_class=[0, 56, 0, 0],
        comfort_by_class=[0, 66, 76, 91],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-bogie-clerestory-brake-third',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1881,
        intro_month=8,
        retire_year=1894,
        retire_month=6,
        speed=160,
        length=7,
        weight=18.0,
        axles=4,
        payload=40,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=20,
        cost=535000,
        runningcost=0,
        fixed_cost=635,
        bidirectional=1,
        can_lead_from_rear=0,
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 66, 76, 91],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-bogie-clerestory-luggage-composite',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1881,
        intro_month=8,
        retire_year=1894,
        retire_month=6,
        speed=160,
        length=8,
        weight=19.6,
        axles=4,
        payload=24,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=12,
        cost=535000,
        runningcost=0,
        fixed_cost=635,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-6-wheel-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'gwr-6-wheel-third', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail'],
        payload_by_class=[0, 0, 24, 17],
        comfort_by_class=[0, 66, 76, 91],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-bogie-clerestory-brake-composite',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Passagiere',
        intro_year=1881,
        intro_month=8,
        retire_year=1894,
        retire_month=6,
        speed=160,
        length=8,
        weight=19.6,
        axles=4,
        payload=24,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=12,
        cost=535000,
        runningcost=0,
        fixed_cost=5200,
        bidirectional=1,
        can_lead_from_rear=0,
        payload_by_class=[0, 0, 24, 17],
        comfort_by_class=[0, 66, 76, 91],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-bogie-clerestory-full-brake',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Post',
        intro_year=1881,
        intro_month=8,
        retire_year=1894,
        retire_month=6,
        speed=160,
        length=7,
        weight=17.9,
        axles=4,
        payload=360,
        min_loading_time=17,
        max_loading_time=47,
        cost=530000,
        runningcost=0,
        fixed_cost=5200,
        bidirectional=1,
        can_lead_from_rear=0,
        comfort_by_class=[0, 66, 76, 91],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-bogie-clerestory-mail',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Post',
        intro_year=1881,
        intro_month=8,
        retire_year=1894,
        retire_month=6,
        speed=160,
        length=7,
        weight=17.9,
        axles=4,
        payload=550,
        min_loading_time=17,
        max_loading_time=47,
        cost=530000,
        runningcost=0,
        fixed_cost=635,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-6-wheel-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'gwr-6-wheel-third', 'gwr-6-wheel-clerestory-third', 'gwr-6-wheel-composite', 'gwr-6-wheel-clerestory-composite', 'gwr-6-wheel-brake-third', 'gwr-6-wheel-clerestory-brake-third', 'gwr-bogie-clerestory-third', 'gwr-bogie-clerestory-brake-third', 'gwr-bogie-clerestory-luggage-composite', 'gwr-bogie-clerestory-brake-composite', 'gwr-bogie-clerestory-full-brake', 'gwr-bogie-clerestory-mail'],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
