"""gwr-non-cor-1930s."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See "Great Western Coaches from 1890" by Michael Harris at pp. 99-100 for details.
# 5 aside in the thirds and 4 aside in the firsts
_BLEND = 'trains/Carriages/gwr-non-cor-1930s-br.blend'
_UPSTREAM_DAT = 'trains/gwr-non-cor-1930s.dat'

SPECS = [
    Vehicle(
        name='gwr-non-cor-1930s-third',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1937,
        intro_month=3,
        retire_year=1945,
        retire_month=8,
        speed=160,
        length=10,
        weight=30.1,
        axles=4,
        payload=90,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=45,
        cost=474000,
        runningcost=0,
        fixed_cost=720,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-front', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-front', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-front', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-front', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-front', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-front'],
        constraint_next=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-rear', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-rear', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-rear', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-rear', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-rear', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-rear'],
        payload_by_class=[0, 90, 0, 0],
        comfort_by_class=[0, 75, 75, 86],
        liverytype=['GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-non-cor-1930s-first',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1937,
        intro_month=3,
        retire_year=1945,
        retire_month=8,
        speed=160,
        length=10,
        weight=28.9,
        axles=4,
        payload=64,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=0,
        cost=479920,
        runningcost=0,
        fixed_cost=710,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-front', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-front', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-front', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-front', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-front', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-front'],
        constraint_next=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-rear', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-rear', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-rear', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-rear', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-rear', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-rear'],
        payload_by_class=[0, 0, 0, 64],
        comfort_by_class=[0, 75, 75, 86],
        liverytype=['GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-non-cor-1930s-brake-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1937,
        intro_month=3,
        retire_year=1945,
        retire_month=8,
        speed=160,
        length=10,
        weight=28.7,
        axles=4,
        payload=70,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=35,
        cost=474000,
        runningcost=0,
        fixed_cost=720,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-rear', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-rear', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-rear', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-rear', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-rear', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-rear', 'none'],
        payload_by_class=[0, 70, 0, 0],
        comfort_by_class=[0, 75, 75, 86],
        liverytype=['GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-non-cor-1930s-brake-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1937,
        intro_month=3,
        retire_year=1945,
        retire_month=8,
        speed=160,
        length=10,
        weight=28.7,
        axles=4,
        payload=70,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=35,
        cost=474000,
        runningcost=0,
        fixed_cost=720,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-hawksworth-non-corridor-third', 'gwr-hawksworth-non-corridor-composite', 'gwr-hawksworth-non-corridor-brake-front', 'gwr-non-cor-1930s-third', 'gwr-non-cor-1930s-first', 'gwr-non-cor-1930s-brake-front', 'gwr-bow-ended-non-corridor-composite', 'gwr-bow-ended-non-corridor-brake-third-front', 'gwr-bow-ended-non-corridor-60ft-third', 'gwr-bow-ended-non-corridor-60ft-brake-composite-front', 'gwr-toplight-non-corridor-composite', 'gwr-toplight-brake-third-front', 'gwr-clerestory-suburban-third', 'gwr-clerestory-suburban-second', 'gwr-clerestory-suburban-first', 'gwr-clerestory-suburban-brake-third-front'],
        payload_by_class=[0, 70, 0, 0],
        comfort_by_class=[0, 75, 75, 86],
        liverytype=['GWR-shirtbutton', 'GWR-hawksworth', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
