"""gwr-clerestory-corridor."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See "Great Western Coaches from 1890" by Michael Harris at pp. 38-52 for details
# These have the 1893 introduction date of the earliest corridor carriages, although
# some of the designs here are the 1896 production series.
#
# http://www.penrhos.me.uk/JSDCmed/C12-lot-790.jpg
# 50ft
_BLEND = 'trains/Carriages/gwr-clerestory-corridor-50ft-collett.blend'
_UPSTREAM_DAT = 'trains/gwr-clerestory-corridor.dat'

SPECS = [
    Vehicle(
        name='gwr-clerestory-corridor-second',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1893,
        intro_month=10,
        retire_year=1908,
        retire_month=2,
        speed=160,
        length=8,
        weight=24.0,
        axles=4,
        payload=56,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=28,
        cost=648000,
        runningcost=0,
        fixed_cost=771,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 0, 56, 0],
        comfort_by_class=[0, 119, 127, 148],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-clerestory-corridor-first',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1893,
        intro_month=10,
        retire_year=1908,
        retire_month=2,
        speed=160,
        length=8,
        weight=24.3,
        axles=4,
        payload=24,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=0,
        cost=652000,
        runningcost=0,
        fixed_cost=772,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 0, 0, 24],
        comfort_by_class=[0, 119, 127, 148],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-clerestory-corridor-composite',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1893,
        intro_month=10,
        retire_year=1908,
        retire_month=2,
        speed=160,
        length=10,
        weight=24.9,
        axles=4,
        payload=40,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=25,
        cost=654000,
        runningcost=0,
        fixed_cost=772,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 40, 24, 0],
        comfort_by_class=[0, 119, 127, 148],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-clerestory-brake-third-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1893,
        intro_month=10,
        retire_year=1908,
        retire_month=2,
        speed=160,
        length=10,
        weight=23.4,
        axles=4,
        payload=40,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=22,
        cost=646000,
        runningcost=0,
        fixed_cost=772,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo', 'none'],
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 119, 127, 148],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-clerestory-brake-third-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1893,
        intro_month=10,
        retire_year=1908,
        retire_month=2,
        speed=160,
        length=10,
        weight=25.3,
        axles=4,
        payload=40,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=22,
        cost=646000,
        runningcost=0,
        fixed_cost=5571,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 119, 127, 148],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-clerestory-corridor-restaurant',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1893,
        intro_month=10,
        retire_year=1908,
        retire_month=2,
        speed=160,
        length=10,
        weight=24.9,
        axles=4,
        payload=16,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=0,
        catering_level=4,
        cost=731500,
        runningcost=0,
        fixed_cost=18871,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        payload_by_class=[0, 0, 0, 16],
        comfort_by_class=[0, 119, 127, 148],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-clerestory-full-brake',
        waytype='track',
        copyright='JamesPetts',
        freight='Post',
        intro_year=1893,
        intro_month=10,
        retire_year=1908,
        retire_month=2,
        speed=160,
        length=7,
        weight=20.1,
        axles=4,
        payload=275,
        min_loading_time=25,
        max_loading_time=55,
        cost=640000,
        runningcost=0,
        fixed_cost=5571,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-clerestory-mail',
        waytype='track',
        copyright='JamesPetts',
        freight='Post',
        intro_year=1893,
        intro_month=10,
        retire_year=1908,
        retire_month=2,
        speed=160,
        length=8,
        weight=22.5,
        axles=4,
        payload=500,
        min_loading_time=45,
        max_loading_time=85,
        cost=642000,
        runningcost=0,
        fixed_cost=270,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='gwr-clerestory-tpo',
        waytype='track',
        copyright='JamesPetts',
        freight='Post',
        intro_year=1893,
        intro_month=10,
        retire_year=1908,
        retire_month=2,
        speed=160,
        length=8,
        weight=22.5,
        axles=4,
        payload=350,
        min_loading_time=45,
        max_loading_time=85,
        catering_level=1,
        cost=731500,
        runningcost=0,
        fixed_cost=24305,
        increase_maintenance_after_years=45,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-front', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-front', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-front', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-front', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-front', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-front', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        constraint_next=['gwr-sunshine-corridor-third', 'gwr-sunshine-corridor-composite-brake-rear', 'gwr-sunshine-corridor-first', 'gwr-sunshine-corridor-brake-third-rear', 'gwr-sunshine-corridor-full-brake', 'gwr-hawksworth-corridor-third', 'gwr-hawksworth-corridor-composite', 'gwr-hawksworth-corridor-first', 'gwr-hawksworth-corridor-brake-rear', 'gwr-hawksworth-corridor-full-brake', 'gwr-sunshine-corridor-restaurant', 'gwr-sunshine-corridor-buffet', 'gwr-super-saloon', 'gwr-super-saloon-kitchen', 'gwr-bow-ended-corridor-third', 'gwr-bow-ended-corridor-composite', 'gwr-bow-ended-corridor-brake-third-rear', 'gwr-bow-ended-corridor-restaurant', 'gwr-bow-ended-corridor-buffet', 'gwr-bow-ended-corridor-full-brake', 'gwr-bow-ended-corridor-mail', 'gwr-bow-ended-corridor-tpo', 'gwr-toplight-corridor-third', 'gwr-toplight-corridor-composite', 'gwr-toplight-corridor-composite-second', 'gwr-toplight-corridor-brake-third-rear', 'gwr-toplight-corridor-restaurant', 'gwr-toplight-corridor-full-brake', 'gwr-toplight-corridor-mail', 'gwr-toplight-corridor-tpo', 'gwr-clerestory-corridor-second', 'gwr-clerestory-corridor-first', 'gwr-clerestory-corridor-composite', 'gwr-clerestory-brake-third-rear', 'gwr-clerestory-corridor-restaurant', 'gwr-clerestory-full-brake', 'gwr-clerestory-mail', 'gwr-clerestory-tpo'],
        liverytype=['GWR-two-tone', 'GWR-overall-brown', 'GWR-lake', 'ww1-austerity', 'GWR-chocolate-cream-lined', 'GWR-chocolate-cream-plain', 'GWR-shirtbutton', 'GWR-hawksworth'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
