"""lbscr-6wheel-carriages."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# Details about these LBSCR 6-wheel carriages cannot be obtained from the usual sources.
# Information here extrapolated from MR 6-wheelers and guessed.
# Third class
_BLEND = 'trains/Carriages/lbscr-6wheel-brake-late.blend'
_UPSTREAM_DAT = 'trains/lbscr-6wheel-carriages.dat'

SPECS = [
    Vehicle(
        name='LBSCR-6Wheel-5-com',
        waytype='track',
        copyright='Kieron/James/JamesPetts',
        freight='Passagiere',
        intro_year=1877,
        intro_month=12,
        retire_year=1892,
        retire_month=1,
        speed=150,
        length=5,
        weight=13,
        axles=3,
        payload=50,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=25,
        cost=332000,
        runningcost=0,
        fixed_cost=395,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LBSCR-4Wheel-Brake-front-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-front', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-front', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-front', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-front', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-front', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        constraint_next=['LBSCR-4Wheel-Brake-rear-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-rear', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-rear', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-rear', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-rear', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-rear', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        payload_by_class=[0, 50, 0, 0],
        comfort_by_class=[0, 73, 76, 81],
        liverytype=['LBSCR-Stroudley', 'LBSCR-Marsh', 'LBSCR-Late', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-6Wheel-5-com-second',
        waytype='track',
        copyright='Kieron/James/JamesPetts/Jeremy',
        freight='Passagiere',
        intro_year=1877,
        intro_month=12,
        retire_year=1892,
        retire_month=1,
        speed=150,
        length=5,
        weight=13,
        axles=3,
        payload=50,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=10,
        cost=332000,
        runningcost=0,
        fixed_cost=400,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LBSCR-4Wheel-Brake-front-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-front', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-front', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-front', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-front', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-front', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        constraint_next=['LBSCR-4Wheel-Brake-rear-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-rear', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-rear', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-rear', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-rear', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-rear', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        payload_by_class=[0, 0, 50, 0],
        comfort_by_class=[0, 73, 76, 81],
        liverytype=['LBSCR-Stroudley', 'LBSCR-Marsh', 'LBSCR-Late', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-6Wheel-composite',
        waytype='track',
        copyright='Kieron/James/JamesPetts/Jeremy',
        freight='Passagiere',
        intro_year=1877,
        intro_month=12,
        retire_year=1892,
        retire_month=1,
        speed=150,
        length=5,
        weight=13,
        axles=3,
        payload=20,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=10,
        cost=342000,
        runningcost=0,
        fixed_cost=410,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LBSCR-4Wheel-Brake-front-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-front', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-front', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-front', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-front', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-front', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        constraint_next=['LBSCR-4Wheel-Brake-rear-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-rear', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-rear', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-rear', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-rear', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-rear', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        payload_by_class=[0, 0, 20, 16],
        comfort_by_class=[0, 73, 76, 81],
        liverytype=['LBSCR-Stroudley', 'LBSCR-Marsh', 'LBSCR-Late', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-6Wheel-4-com-first',
        waytype='track',
        copyright='Kieron/James/JamesPetts/Jeremy',
        freight='Passagiere',
        intro_year=1877,
        intro_month=12,
        retire_year=1892,
        retire_month=1,
        speed=150,
        length=5,
        weight=13,
        axles=3,
        payload=32,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=4,
        cost=342000,
        runningcost=0,
        fixed_cost=460,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LBSCR-4Wheel-Brake-front-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-front', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-front', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-front', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-front', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-front', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        constraint_next=['LBSCR-4Wheel-Brake-rear-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-rear', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-rear', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-rear', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-rear', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-rear', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        payload_by_class=[0, 0, 0, 32],
        comfort_by_class=[0, 73, 76, 81],
        liverytype=['LBSCR-Stroudley', 'LBSCR-Marsh', 'LBSCR-Late', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-6Wheel-brake-front',
        waytype='track',
        copyright='Kieron/James/JamesPetts',
        freight='Passagiere',
        intro_year=1877,
        intro_month=12,
        retire_year=1892,
        retire_month=1,
        speed=150,
        length=5,
        weight=13,
        axles=3,
        payload=30,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=15,
        cost=332000,
        runningcost=0,
        fixed_cost=5195,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['LBSCR-4Wheel-Brake-rear-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-rear', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-rear', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-rear', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-rear', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-rear', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'none', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        payload_by_class=[0, 30],
        comfort_by_class=[0, 73],
        liverytype=['LBSCR-Stroudley', 'LBSCR-Marsh', 'LBSCR-Late', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-6Wheel-brake-rear',
        waytype='track',
        copyright='Kieron/James/JamesPetts',
        freight='Passagiere',
        intro_year=1877,
        intro_month=12,
        retire_year=1892,
        retire_month=1,
        speed=150,
        length=5,
        weight=13,
        axles=3,
        payload=30,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=15,
        cost=332000,
        runningcost=0,
        fixed_cost=5195,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LBSCR-4Wheel-Brake-front-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-front', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-front', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-front', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-front', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-front', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        payload_by_class=[0, 30],
        comfort_by_class=[0, 73],
        liverytype=['LBSCR-Stroudley', 'LBSCR-Marsh', 'LBSCR-Late', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-6Wheel-guard',
        waytype='track',
        copyright='Kieron/James/JamesPetts',
        freight='Post',
        intro_year=1877,
        intro_month=12,
        retire_year=1907,
        retire_month=6,
        speed=150,
        length=5,
        weight=13,
        axles=3,
        payload=320,
        min_loading_time=35,
        max_loading_time=100,
        cost=332000,
        runningcost=0,
        fixed_cost=5195,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['LBSCR-Stroudley', 'LBSCR-Marsh', 'LBSCR-Late', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-6Wheel-mail',
        waytype='track',
        copyright='Kieron/James/JamesPetts',
        freight='Post',
        intro_year=1877,
        intro_month=12,
        retire_year=1907,
        retire_month=6,
        speed=150,
        length=5,
        weight=13,
        axles=3,
        payload=400,
        min_loading_time=35,
        max_loading_time=120,
        cost=332000,
        runningcost=0,
        fixed_cost=138,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LBSCR-4Wheel-Brake-front-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-front', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-front', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-front', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-front', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-front', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        constraint_next=['LBSCR-4Wheel-Brake-rear-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-rear', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-rear', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-rear', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-rear', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-rear', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        liverytype=['LBSCR-Stroudley', 'LBSCR-Marsh', 'LBSCR-Late', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-6Wheel-fruit-and-milk-van',
        waytype='track',
        copyright='Kieron/James/JamesPetts',
        freight='milk',
        intro_year=1877,
        intro_month=12,
        retire_year=1907,
        retire_month=6,
        speed=150,
        length=5,
        weight=13,
        axles=3,
        payload=14,
        min_loading_time=300,
        max_loading_time=900,
        cost=332000,
        runningcost=0,
        fixed_cost=138,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LBSCR-4Wheel-Brake-front-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-front', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-front', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-front', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-front', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-front', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        constraint_next=['LBSCR-4Wheel-Brake-rear-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-rear', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-rear', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-rear', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-rear', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-rear', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        liverytype=['LBSCR-Stroudley', 'LBSCR-Marsh', 'LBSCR-Late', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-6Wheel-fast-freight-van',
        waytype='track',
        copyright='Kieron/James/JamesPetts',
        freight='Bucher',
        intro_year=1877,
        intro_month=12,
        retire_year=1907,
        retire_month=6,
        speed=150,
        length=5,
        weight=13,
        axles=3,
        payload=14,
        min_loading_time=300,
        max_loading_time=900,
        cost=332000,
        runningcost=0,
        fixed_cost=138,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LBSCR-4Wheel-Brake-front-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-front', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-front', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-front', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-front', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-front', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        constraint_next=['LBSCR-4Wheel-Brake-rear-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-rear', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-rear', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-rear', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-rear', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-rear', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        liverytype=['LBSCR-Stroudley', 'LBSCR-Marsh', 'LBSCR-Late', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-6Wheel-fruit-and-milk-van-brake',
        waytype='track',
        copyright='Kieron/James/JamesPetts',
        freight='milk',
        intro_year=1877,
        intro_month=12,
        retire_year=1907,
        retire_month=6,
        speed=150,
        length=5,
        weight=13,
        axles=3,
        payload=11,
        min_loading_time=300,
        max_loading_time=900,
        cost=332000,
        runningcost=0,
        fixed_cost=4638,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['LBSCR-Stroudley', 'LBSCR-Marsh', 'LBSCR-Late', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-6Wheel-fast-freight-van-brake',
        waytype='track',
        copyright='Kieron/James/JamesPetts',
        freight='Bucher',
        intro_year=1877,
        intro_month=12,
        retire_year=1907,
        retire_month=6,
        speed=150,
        length=5,
        weight=13,
        axles=3,
        payload=11,
        min_loading_time=300,
        max_loading_time=900,
        cost=332000,
        runningcost=0,
        fixed_cost=4638,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['LBSCR-Stroudley', 'LBSCR-Marsh', 'LBSCR-Late', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
