"""lbscr-sub-bogie-54ft."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# Bogie suburban stock - 54ft -
# 8 compartments for 48ft, and
# 9 compartments for 54ft/
# See http://www.semgonline.com/coach/iow_01.html
# for a picture of a 9 compartment carriage.
# Third class
_BLEND = 'trains/Carriages/lbscr-sub-bogie-54ft-brake-malachite.blend'
_UPSTREAM_DAT = 'trains/lbscr-sub-bogie-54ft.dat'

SPECS = [
    Vehicle(
        name='LBSCR-sub-bogie-54ft',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1905,
        intro_month=1,
        retire_year=1923,
        retire_month=1,
        speed=160,
        length=9,
        weight=24,
        axles=4,
        payload=90,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=45,
        cost=713000,
        runningcost=0,
        fixed_cost=849,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LBSCR-4Wheel-Brake-front-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-front', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-front', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-front', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-front', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-front', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        constraint_next=['LBSCR-4Wheel-Brake-rear-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-rear', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-rear', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-rear', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-rear', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-rear', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        payload_by_class=[0, 90, 0, 0],
        comfort_by_class=[0, 70, 73, 83],
        liverytype=['LBSCR-Stroudley', 'LBSCR-Marsh', 'LBSCR-Late', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        upgrade=['LSWR-EMU(centre)', 'LSWR-EMU(rear)', 'LSWR-EMU(front)', 'SR-3SUB(front)', 'SR-3SUB(rear)', 'SR-3SUB(centre)', 'lbscr-54ft-augmentation-trailer-front', 'lbscr-54ft-augmentation-trailer-rear'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-sub-bogie-54ft-tricomposite',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1905,
        intro_month=1,
        retire_year=1923,
        retire_month=1,
        speed=160,
        length=9,
        weight=24,
        axles=4,
        payload=20,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=20,
        cost=716000,
        runningcost=0,
        fixed_cost=850,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LBSCR-4Wheel-Brake-front-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-front', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-front', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-front', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-front', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-front', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        constraint_next=['LBSCR-4Wheel-Brake-rear-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-rear', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-rear', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-rear', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-rear', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-rear', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        payload_by_class=[0, 20, 20, 18],
        comfort_by_class=[0, 70, 73, 83],
        liverytype=['LBSCR-Stroudley', 'LBSCR-Marsh', 'LBSCR-Late', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        upgrade=['LSWR-EMU(centre)', 'LSWR-EMU(rear)', 'LSWR-EMU(front)', 'SR-3SUB(front)', 'SR-3SUB(rear)', 'SR-3SUB(centre)', 'lbscr-54ft-augmentation-trailer-front', 'lbscr-54ft-augmentation-trailer-rear'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-sub-bogie-54ft-brake-rear',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1905,
        intro_month=1,
        retire_year=1923,
        retire_month=1,
        speed=160,
        length=9,
        weight=23.5,
        axles=4,
        payload=70,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=35,
        cost=713000,
        runningcost=0,
        fixed_cost=5649,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LBSCR-4Wheel-Brake-front-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-front', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-front', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-front', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-front', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-front', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        payload_by_class=[0, 70, 0, 0],
        comfort_by_class=[0, 70, 73, 83],
        liverytype=['LBSCR-Stroudley', 'LBSCR-Marsh', 'LBSCR-Late', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        upgrade=['LSWR-EMU(centre)', 'LSWR-EMU(rear)', 'LSWR-EMU(front)', 'SR-3SUB(front)', 'SR-3SUB(rear)', 'SR-3SUB(centre)', 'lbscr-54ft-augmentation-trailer-front', 'lbscr-54ft-augmentation-trailer-rear'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-sub-bogie-54ft-brake-front',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1905,
        intro_month=1,
        retire_year=1923,
        retire_month=1,
        speed=160,
        length=9,
        weight=23.5,
        axles=4,
        payload=70,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=35,
        cost=713000,
        runningcost=0,
        fixed_cost=5649,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['LBSCR-4Wheel-Brake-rear-fitted', 'LBSCR-4Wheel-First-fitted', 'LBSCR-4Wheel-full-brake-fitted', 'LBSCR-4Wheel-Second-fitted', 'LBSCR-6Wheel-5-com', 'LBSCR-6Wheel-brake-rear', 'LBSCR-6Wheel-guard', 'LBSCR-6Wheel-mail', 'LBSCR-balloon', 'LBSCR-balloon-brake-rear', 'LBSCR-balloon-full-brake', 'LBSCR-non-cor-lav', 'LBSCR-non-cor-lav-brake-rear', 'LBSCR-sub-bogie-48ft', 'LBSCR-sub-bogie-48ft-brake-rear', 'LBSCR-sub-bogie-54ft', 'LBSCR-sub-bogie-54ft-brake-rear', 'LBSCR-6Wheel-fruit-and-milk-van', 'LBSCR-6Wheel-fast-freight-van', 'LBSCR-6Wheel-5-com-second', 'LBSCR-6Wheel-composite', 'LBSCR-6Wheel-4-com-first', 'LBSCR-6Wheel-fruit-and-milk-van-brake', 'LBSCR-6Wheel-fast-freight-van-brake', 'LBSCR-4Wheel-third-fitted', 'LBSCR-4Wheel-composite-fitted', 'LBSCR-sub-bogie-48ft-composite', 'LBSCR-sub-bogie-48ft-first', 'LBSCR-non-cor-lav-first', 'LBSCR-sub-bogie-54ft-tricomposite', 'LBSCR-balloon-tricomposite', 'pullman-open-platform-kitchen', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-kitchen', 'pullman-1908-kitchen', 'pullman-k-type-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'none'],
        payload_by_class=[0, 70, 0, 0],
        comfort_by_class=[0, 70, 73, 83],
        liverytype=['LBSCR-Stroudley', 'LBSCR-Marsh', 'LBSCR-Late', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        upgrade=['LSWR-EMU(centre)', 'LSWR-EMU(rear)', 'LSWR-EMU(front)', 'SR-3SUB(front)', 'SR-3SUB(rear)', 'SR-3SUB(centre)', 'lbscr-54ft-augmentation-trailer-front', 'lbscr-54ft-augmentation-trailer-rear'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
