"""lbscr-4wheel-craven."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See http://www.5and9models.co.uk/coaches.html
# These are assumed to be five a side seating.
# Five compartments
_BLEND = 'trains/Carriages/lbscr-4wheel-craven-brake-third.blend'
_UPSTREAM_DAT = 'trains/lbscr-4wheel-craven.dat'

SPECS = [
    Vehicle(
        name='LBSCR-craven-third',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1866,
        intro_month=7,
        retire_year=1872,
        retire_month=4,
        speed=135,
        length=4,
        weight=8,
        axles=2,
        brake_force=0,
        rolling_resistance=19,
        payload=50,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=25,
        cost=200000,
        runningcost=0,
        fixed_cost=238,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['any'],
        constraint_next=['any'],
        payload_by_class=[0, 50, 0],
        comfort_by_class=[0, 38, 42],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-craven-second',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1866,
        intro_month=7,
        retire_year=1872,
        retire_month=4,
        speed=135,
        length=4,
        weight=8,
        axles=2,
        brake_force=0,
        rolling_resistance=19,
        payload=40,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=20,
        cost=200000,
        runningcost=0,
        fixed_cost=238,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['any'],
        constraint_next=['any'],
        payload_by_class=[0, 0, 40],
        comfort_by_class=[0, 38, 42],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-craven-brake-front',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1866,
        intro_month=7,
        retire_year=1872,
        retire_month=4,
        speed=135,
        length=4,
        weight=8,
        axles=2,
        brake_force=3,
        rolling_resistance=19,
        payload=30,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=15,
        cost=200000,
        runningcost=0,
        fixed_cost=5038,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['any'],
        constraint_next=['any'],
        payload_by_class=[0, 30],
        comfort_by_class=[0, 38],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-craven-brake-rear',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1866,
        intro_month=7,
        retire_year=1872,
        retire_month=4,
        speed=135,
        length=4,
        weight=8,
        axles=2,
        brake_force=3,
        rolling_resistance=19,
        payload=30,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=15,
        cost=200000,
        runningcost=0,
        fixed_cost=5038,
        bidirectional=1,
        can_lead_from_rear=0,
        payload_by_class=[0, 30],
        comfort_by_class=[0, 38],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-craven-full-brake',
        waytype='track',
        copyright='Kieron/James',
        freight='Post',
        intro_year=1866,
        intro_month=7,
        retire_year=1872,
        retire_month=4,
        speed=135,
        length=4,
        weight=8,
        axles=2,
        brake_force=3,
        rolling_resistance=19,
        payload=240,
        min_loading_time=35,
        max_loading_time=100,
        cost=154000,
        runningcost=0,
        fixed_cost=183,
        bidirectional=1,
        can_lead_from_rear=0,
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LBSCR-craven-mail',
        waytype='track',
        copyright='Kieron/James',
        freight='Post',
        intro_year=1866,
        intro_month=7,
        retire_year=1872,
        retire_month=4,
        speed=135,
        length=3,
        weight=8,
        axles=2,
        brake_force=0,
        rolling_resistance=19,
        payload=360,
        min_loading_time=35,
        max_loading_time=120,
        cost=154000,
        runningcost=0,
        fixed_cost=64,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['any'],
        constraint_next=['any'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
