"""lmr-4wheel-first-short-wheelbase."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# This is the original, short wheelbase type
# See Hamilton Ellis, pp. 15-6
_BLEND = 'trains/Carriages/4wheel-first-short-wheelbase.blend'
_UPSTREAM_DAT = 'trains/lmr-4wheel-first-short-wheelbase.dat'

SPECS = [
    Vehicle(
        name='LMR-4wheel-first-short-wheelbase',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1829,
        intro_month=8,
        retire_year=1834,
        retire_month=7,
        speed=75,
        length=3,
        weight=2.7,
        axles=2,
        brake_force=0,
        rolling_resistance=20,
        payload=18,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=9,
        cost=140000,
        runningcost=0,
        fixed_cost=117,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['any'],
        constraint_next=['any'],
        payload_by_class=[0, 0, 0, 18],
        comfort_by_class=[0, 0, 0, 46],
        liverytype=['LMR-Standard'],
        upgrade=['LMR-4Wheel-First'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMR-4wheel-first-short-wheelbase-Guard-front',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1829,
        intro_month=8,
        retire_year=1834,
        retire_month=7,
        speed=75,
        length=3,
        weight=2.7,
        axles=2,
        brake_force=1,
        rolling_resistance=20,
        payload=18,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=9,
        cost=146000,
        runningcost=0,
        fixed_cost=4922,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['any'],
        constraint_next=['any'],
        payload_by_class=[0, 0, 0, 18],
        comfort_by_class=[0, 0, 0, 46],
        liverytype=['LMR-Standard'],
        upgrade=['LMR-4Wheel-First-Guard-front'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMR-4wheel-first-short-wheelbase-Guard-rear',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1829,
        intro_month=8,
        retire_year=1834,
        retire_month=7,
        speed=75,
        length=3,
        weight=2.7,
        axles=2,
        brake_force=1,
        rolling_resistance=20,
        payload=18,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=9,
        cost=146000,
        runningcost=0,
        fixed_cost=4922,
        bidirectional=1,
        can_lead_from_rear=0,
        payload_by_class=[0, 0, 0, 18],
        comfort_by_class=[0, 0, 0, 46],
        liverytype=['LMR-Standard'],
        upgrade=['LMR-4Wheel-First-Guard-rear'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
