"""lms-period3-cor."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# Period 3 vehicles. Stanier design
# Third
# D1899
_BLEND = 'trains/Carriages/lms-period3.blend'
_UPSTREAM_DAT = 'trains/lms-period3-cor.dat'

SPECS = [
    Vehicle(
        name='LMS-cor',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1933,
        intro_month=6,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=10,
        weight=33,
        axles=4,
        payload=42,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=20,
        cost=755000,
        runningcost=0,
        fixed_cost=899,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046'],
        payload_by_class=[0, 42, 0, 0],
        comfort_by_class=[0, 145, 145, 159],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMS-cor-composite',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1933,
        intro_month=6,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=10,
        weight=33,
        axles=4,
        payload=24,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=0,
        cost=760000,
        runningcost=0,
        fixed_cost=899,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046'],
        payload_by_class=[0, 24, 0, 12],
        comfort_by_class=[0, 145, 145, 159],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMS-cor-first',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1933,
        intro_month=6,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=10,
        weight=33,
        axles=4,
        payload=22,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=0,
        cost=765000,
        runningcost=0,
        fixed_cost=899,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046'],
        payload_by_class=[0, 0, 0, 22],
        comfort_by_class=[0, 145, 145, 159],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMS-cor-brake-front',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1933,
        intro_month=6,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=10,
        weight=32,
        axles=4,
        payload=24,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=10,
        cost=755000,
        runningcost=0,
        fixed_cost=5699,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046', 'none'],
        payload_by_class=[0, 24, 0, 0],
        comfort_by_class=[0, 145, 145, 159],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMS-cor-brake-rear',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1933,
        intro_month=6,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=10,
        weight=32,
        axles=4,
        payload=24,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=10,
        cost=755000,
        runningcost=0,
        fixed_cost=5699,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        payload_by_class=[0, 24, 0, 0],
        comfort_by_class=[0, 145, 145, 159],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMS-open',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1933,
        intro_month=6,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=10,
        weight=31,
        axles=4,
        payload=60,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=32,
        cost=700000,
        runningcost=0,
        fixed_cost=833,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046'],
        payload_by_class=[0, 60, 0, 0],
        comfort_by_class=[0, 136, 136, 152],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMS-open-composite',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1933,
        intro_month=6,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=10,
        weight=31,
        axles=4,
        payload=30,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=18,
        cost=705000,
        runningcost=0,
        fixed_cost=833,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046'],
        payload_by_class=[0, 30, 0, 24],
        comfort_by_class=[0, 136, 136, 152],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMS-open-first',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1933,
        intro_month=6,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=10,
        weight=31,
        axles=4,
        payload=48,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=0,
        cost=710000,
        runningcost=0,
        fixed_cost=833,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046'],
        payload_by_class=[0, 0, 0, 48],
        comfort_by_class=[0, 136, 136, 152],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMS-open-brake-front',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1933,
        intro_month=6,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=10,
        weight=30,
        axles=4,
        payload=40,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=22,
        cost=700000,
        runningcost=0,
        fixed_cost=5633,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046', 'none'],
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 136, 136, 152],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMS-open-brake-rear',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1933,
        intro_month=6,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=10,
        weight=30,
        axles=4,
        payload=40,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=22,
        cost=700000,
        runningcost=0,
        fixed_cost=5633,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 136, 136, 152],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMS-diner',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1933,
        intro_month=6,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=12,
        weight=44,
        axles=4,
        rolling_resistance=17,
        payload=22,
        min_loading_time=25,
        max_loading_time=180,
        catering_level=4,
        cost=910000,
        runningcost=0,
        fixed_cost=19083,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046'],
        payload_by_class=[0, 22, 0, 11],
        comfort_by_class=[0, 137, 137, 153],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMS-buffet',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1933,
        intro_month=6,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=10,
        weight=34,
        axles=4,
        payload=24,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=10,
        catering_level=3,
        cost=820000,
        runningcost=0,
        fixed_cost=18976,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046'],
        payload_by_class=[0, 24, 0, 0],
        comfort_by_class=[0, 136, 136, 152],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMS-full-brake',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Post',
        intro_year=1933,
        intro_month=6,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=9,
        weight=27,
        axles=4,
        payload=400,
        min_loading_time=25,
        max_loading_time=120,
        cost=548000,
        runningcost=0,
        fixed_cost=652,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMS-Mail',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Post',
        intro_year=1933,
        intro_month=6,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=10,
        weight=30,
        axles=4,
        payload=530,
        min_loading_time=35,
        max_loading_time=180,
        cost=700000,
        runningcost=0,
        fixed_cost=292,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046'],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMS-TPO',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Post',
        intro_year=1933,
        intro_month=6,
        retire_year=1959,
        retire_month=2,
        speed=160,
        length=10,
        weight=30,
        axles=4,
        payload=300,
        min_loading_time=35,
        max_loading_time=180,
        catering_level=1,
        cost=777500,
        runningcost=0,
        fixed_cost=24324,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046', 'BR-Mk1-BG'],
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046', 'BR-Mk1-BG'],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
