"""lms-push-pull."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# http://www.rmweb.co.uk/community/index.php?/topic/32732-lms-push-pull-coaches/page-2
_BLEND = 'trains/Carriages/lms-push-pull-br-cc.blend'
_UPSTREAM_DAT = 'trains/lms-push-pull.dat'

SPECS = [
    Vehicle(
        name='LMS-push-pull-brake',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1924,
        intro_month=4,
        retire_year=1952,
        retire_month=10,
        speed=140,
        length=10,
        weight=27,
        axles=4,
        payload=72,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=36,
        cost=500000,
        runningcost=0,
        fixed_cost=5395,
        upgrade_price=27500,
        increase_maintenance_after_years=17,
        years_before_maintenance_max_reached=30,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['MR-1632', 'LMS-0-4-4T', 'LMS-Fowler-3P-Tank-Push-Pull', 'BR-2MT-Tank-Push-Pull', 'LMS-push-pull-centre-1', 'LMS-push-pull-centre-2', 'LMS-3F-Jinty-Push-Pull', 'LMS-Ivatt-2P-Tank-Push-Pull', 'LMS-Stanier-3P-Tank-Push-Pull'],
        constraint_next=['none'],
        payload_by_class=[0, 72, 0, 0],
        comfort_by_class=[0, 78, 78, 93],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMS-push-pull-centre-1',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1924,
        intro_month=4,
        retire_year=1952,
        retire_month=10,
        speed=140,
        length=10,
        weight=27,
        axles=4,
        payload=72,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=36,
        cost=505000,
        runningcost=0,
        fixed_cost=601,
        upgrade_price=5000,
        increase_maintenance_after_years=17,
        years_before_maintenance_max_reached=30,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['MR-1632', 'LMS-0-4-4T', 'LMS-Fowler-3P-Tank-Push-Pull', 'BR-2MT-Tank-Push-Pull', 'LMS-push-pull-centre-1', 'LMS-push-pull-centre-2', 'LMS-3F-Jinty-Push-Pull', 'LMS-Ivatt-2P-Tank-Push-Pull', 'LMS-Stanier-3P-Tank-Push-Pull'],
        constraint_next=['LMS-push-pull-centre-2', 'LMS-push-pull-brake'],
        payload_by_class=[0, 72, 0, 24],
        comfort_by_class=[0, 75, 78, 93],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LMS-push-pull-centre-2',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1924,
        intro_month=4,
        retire_year=1952,
        retire_month=10,
        speed=140,
        length=10,
        weight=27,
        axles=4,
        payload=108,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=54,
        cost=505000,
        runningcost=0,
        fixed_cost=601,
        upgrade_price=5000,
        increase_maintenance_after_years=17,
        years_before_maintenance_max_reached=30,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LMS-push-pull-centre-1'],
        constraint_next=['LMS-push-pull-brake'],
        payload_by_class=[0, 108, 0, 0],
        comfort_by_class=[0, 78, 78, 93],
        liverytype=['LMS-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
