"""lner-standard-51ft."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# https://d240vprofozpi.cloudfront.net/stock/carriages/local/Diagram_56_57_8NVCompartmentThird_Diagram_55_Second.pdf
_BLEND = 'trains/Carriages/lner-standard-51ft-composite-lavatory-carmine.blend'
_UPSTREAM_DAT = 'trains/lner-standard-51ft.dat'

SPECS = [
    Vehicle(
        name='LNER-standard-51ft-t',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=3,
        retire_year=1942,
        retire_month=6,
        speed=160,
        length=8,
        weight=32.5,
        axles=3,
        payload=80,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=40,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear'],
        payload_by_class=[0, 80, 0, 0],
        comfort_by_class=[0, 80, 82, 98],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-standard-51ft-s',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=3,
        retire_year=1942,
        retire_month=6,
        speed=160,
        length=8,
        weight=32.5,
        axles=3,
        payload=80,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=40,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear'],
        payload_by_class=[0, 0, 80, 0],
        comfort_by_class=[0, 80, 82, 98],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-standard-51ft-bt4-for',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=3,
        retire_year=1942,
        retire_month=6,
        speed=160,
        length=8,
        weight=32.5,
        axles=3,
        payload=40,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=20,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear', 'none'],
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 80, 82, 98],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-standard-51ft-bt4-rev',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=3,
        retire_year=1942,
        retire_month=6,
        speed=160,
        length=8,
        weight=32.5,
        axles=3,
        payload=40,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=20,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 80, 82, 98],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-standard-51ft-cl',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=3,
        retire_year=1942,
        retire_month=6,
        speed=160,
        length=8,
        weight=32.5,
        axles=3,
        payload=33,
        min_loading_time=16,
        max_loading_time=48,
        overcrowded_capacity=16,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear'],
        payload_by_class=[0, 33, 0, 19],
        comfort_by_class=[0, 90, 95, 110],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-standard-51ft-f',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=3,
        retire_year=1942,
        retire_month=6,
        speed=160,
        length=8,
        weight=32.5,
        axles=3,
        payload=56,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=0,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear'],
        payload_by_class=[0, 0, 0, 56],
        comfort_by_class=[0, 80, 82, 98],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-standard-51ft-f2',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=3,
        retire_year=1942,
        retire_month=6,
        speed=160,
        length=8,
        weight=32.5,
        axles=3,
        payload=70,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=0,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear'],
        payload_by_class=[0, 0, 0, 70],
        comfort_by_class=[0, 80, 82, 94],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-standard-51ft-com',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=3,
        retire_year=1942,
        retire_month=6,
        speed=160,
        length=8,
        weight=32.5,
        axles=3,
        payload=32,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=15,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-front', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-front', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-front', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-front', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-for', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-front'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'GNR-6Wheel-First', 'GNR-6Wheel-cor-lav', 'GNR-6Wheel-Mail', 'GNR-6Wheel-tpo', 'GNR-6Wheel-brake-third-rear', 'GNR-6Wheel-Guard', 'gnr-howlden-bogie-third', 'gnr-howlden-bogie-third-brake-rear', 'gnr-howlden-bogie-non-lav', 'gnr-howlden-bogie-non-lav-brake-rear', 'gnr-howlden-full-brake', 'gnr-non-cor-lav-elliptical', 'gnr-non-cor-lav-elliptical-brake-rear', 'gnr-non-cor-full-brake', 'gnr-non-cor-mail', 'gnr-non-cor-lav-elliptical-composite', 'gnr-howlden-bogie-non-lav-second', 'gnr-howlden-bogie-non-lav-first', 'GNR-6Wheel-Third', 'GNR-6Wheel-Second', 'GNR-6Wheel-cor-lav-second', 'GNR-6Wheel-cor-lav-third', 'LNER-standard-51ft-t', 'LNER-standard-51ft-s', 'LNER-standard-51ft-bt4-rev', 'LNER-standard-51ft-cl', 'LNER-standard-51ft-f', 'LNER-standard-51ft-f2', 'LNER-standard-51ft-com', 'gnr-suburban-4wheel-third', 'gnr-suburban-4wheel-second', 'gnr-suburban-4wheel-first', 'gnr-suburban-4wheel-brake-third-rear'],
        payload_by_class=[0, 30, 0, 32],
        comfort_by_class=[0, 80, 82, 98],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
