"""lner-tyneside-emu."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/LNER_Tyneside_EMU_postal-br-green.blend'
_UPSTREAM_DAT = 'trains/lner-tyneside-emu.dat'

SPECS = [
    Vehicle(
        name='LNER-1937-Tyneside-EMU-front',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1936,
        intro_month=7,
        retire_year=1956,
        retire_month=12,
        speed=90,
        length=10,
        weight=43,
        axles=4,
        power=320,
        gear=80,
        tractive_effort=70,
        payload=64,
        min_loading_time=35,
        max_loading_time=59,
        overcrowded_capacity=75,
        cost=1512000,
        runningcost=128,
        fixed_cost=7260,
        increase_maintenance_after_years=23,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['LNER-1937-Tyneside-EMU-rear', 'LNER-1937-Tyneside-EMU-rear-composite', 'LNER-1937-Tyneside-EMU-MPV', 'none'],
        constraint_next=['LNER-1937-Tyneside-EMU-rear', 'LNER-1937-Tyneside-EMU-rear-composite'],
        payload_by_class=[0, 64, 0, 0],
        comfort_by_class=[0, 69, 0, 76],
        liverytype=['LNER', 'BR-Early'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-1937-Tyneside-EMU-rear',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1936,
        intro_month=7,
        retire_year=1956,
        retire_month=12,
        speed=90,
        length=10,
        weight=31,
        axles=4,
        power=0,
        payload=64,
        min_loading_time=35,
        max_loading_time=59,
        overcrowded_capacity=75,
        cost=1512000,
        runningcost=0,
        fixed_cost=1800,
        increase_maintenance_after_years=23,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['LNER-1937-Tyneside-EMU-front'],
        constraint_next=['LNER-1937-Tyneside-EMU-front', 'LNER-1937-Tyneside-EMU-MPV', 'none'],
        payload_by_class=[0, 64, 0, 0],
        comfort_by_class=[0, 69, 0, 76],
        liverytype=['LNER', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-1937-Tyneside-EMU-rear-composite',
        waytype='track',
        copyright='Junna/Cake',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1936,
        intro_month=7,
        retire_year=1956,
        retire_month=12,
        speed=90,
        length=10,
        weight=31,
        axles=4,
        power=0,
        payload=32,
        min_loading_time=35,
        max_loading_time=59,
        overcrowded_capacity=48,
        cost=1512000,
        runningcost=0,
        fixed_cost=1800,
        increase_maintenance_after_years=23,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['LNER-1937-Tyneside-EMU-front'],
        constraint_next=['LNER-1937-Tyneside-EMU-front', 'LNER-1937-Tyneside-EMU-MPV', 'none'],
        payload_by_class=[0, 32, 0, 28],
        comfort_by_class=[0, 69, 0, 76],
        liverytype=['LNER', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-1937-Tyneside-EMU-MPV',
        waytype='track',
        copyright='Junna/Cake',
        freight='Post',
        engine_type='electric',
        intro_year=1936,
        intro_month=7,
        retire_year=1959,
        retire_month=2,
        speed=90,
        length=10,
        weight=43,
        axles=4,
        power=640,
        gear=80,
        tractive_effort=140,
        payload=500,
        min_loading_time=30,
        max_loading_time=180,
        cost=1620000,
        runningcost=256,
        fixed_cost=7350,
        increase_maintenance_after_years=23,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['LNER-1937-Tyneside-EMU-rear', 'LNER-1937-Tyneside-EMU-rear-composite', 'none'],
        constraint_next=['LNER-1937-Tyneside-EMU-front', 'LNER-Gresley-Express-Parcel-Brake', 'LNER-Gresley-Express-Mail', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'SR-Maunsell-Parcels', 'BR-Mk1-POS', 'BR-Mk1-TPO', 'none'],
        liverytype=['LNER', 'BR-Early'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
