"""lner-quint-art."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# https://www.rmweb.co.uk/community/index.php?/blogs/blog/2443-isinglass-lner-ge-quint-articulated-set/
_BLEND = 'trains/Carriages/lner-quint-art-a-carmine.blend'
_UPSTREAM_DAT = 'trains/lner-quint-art.dat'

SPECS = [
    Vehicle(
        name='LNER-quint-art-a',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=1,
        retire_year=1941,
        retire_month=6,
        speed=160,
        length=6,
        weight=20,
        axles=3,
        payload=60,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=30,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['LNER-quint-art-b-1'],
        payload_by_class=[0, 60, 0, 0],
        comfort_by_class=[0, 60, 63, 75],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-quint-art-b-1',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=1,
        retire_year=1941,
        retire_month=6,
        speed=160,
        length=6,
        weight=20,
        axles=2,
        payload=80,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=40,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-quint-art-a'],
        constraint_next=['LNER-quint-art-b-2'],
        payload_by_class=[0, 80, 0, 0],
        comfort_by_class=[0, 60, 62, 75],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-quint-art-b-2',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=1,
        retire_year=1941,
        retire_month=6,
        speed=160,
        length=6,
        weight=24,
        axles=2,
        payload=80,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=40,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-quint-art-b-1'],
        constraint_next=['LNER-quint-art-b-3'],
        payload_by_class=[0, 80, 0, 0],
        comfort_by_class=[0, 60, 62, 75],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-quint-art-b-3',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=1,
        retire_year=1941,
        retire_month=6,
        speed=160,
        length=6,
        weight=24,
        axles=2,
        payload=80,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=40,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-quint-art-b-2'],
        constraint_next=['LNER-quint-art-c'],
        payload_by_class=[0, 80, 0, 0],
        comfort_by_class=[0, 60, 62, 75],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-quint-art-c',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=1,
        retire_year=1941,
        retire_month=6,
        speed=160,
        length=7,
        weight=24,
        axles=3,
        payload=30,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=15,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-quint-art-b-3'],
        payload_by_class=[0, 0, 30, 16],
        comfort_by_class=[0, 60, 62, 75],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-quint-art-d',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=1,
        retire_year=1941,
        retire_month=6,
        speed=160,
        length=6,
        weight=24,
        axles=3,
        payload=30,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=15,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['LNER-quint-art-e-1'],
        payload_by_class=[0, 0, 30, 16],
        comfort_by_class=[0, 60, 62, 75],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-quint-art-e-1',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=1,
        retire_year=1941,
        retire_month=6,
        speed=160,
        length=6,
        weight=20,
        axles=2,
        payload=80,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=40,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-quint-art-d'],
        constraint_next=['LNER-quint-art-e-2'],
        payload_by_class=[0, 80, 0, 0],
        comfort_by_class=[0, 60, 62, 75],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-quint-art-e-2',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=1,
        retire_year=1941,
        retire_month=6,
        speed=160,
        length=6,
        weight=20,
        axles=2,
        payload=80,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=40,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-quint-art-e-1'],
        constraint_next=['LNER-quint-art-e-3'],
        payload_by_class=[0, 80, 0, 0],
        comfort_by_class=[0, 60, 62, 75],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-quint-art-e-3',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=1,
        retire_year=1941,
        retire_month=6,
        speed=160,
        length=6,
        weight=20,
        axles=2,
        payload=80,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=40,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-quint-art-e-2'],
        constraint_next=['LNER-quint-art-f'],
        payload_by_class=[0, 80, 0, 0],
        comfort_by_class=[0, 60, 62, 75],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNER-quint-art-f',
        waytype='track',
        copyright='Jeremy',
        freight='Passagiere',
        intro_year=1925,
        intro_month=1,
        retire_year=1941,
        retire_month=6,
        speed=160,
        length=7,
        weight=20,
        axles=3,
        payload=60,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=30,
        catering_level=0,
        cost=700000,
        runningcost=0,
        fixed_cost=15054,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNER-quint-art-e-3'],
        payload_by_class=[0, 60, 0, 0],
        comfort_by_class=[0, 60, 62, 75],
        liverytype=['LNER-Standard', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
