"""lnwr-6wheel-30ft."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# These vehicles the later 30'1" standard types built from
# the mid 1880s onwards. See "London & North Western Railway
# Thirty Foot One Inch Carriages" by Philip A. Millard for details.
# For the purposes of comfort, note 5'10" between compartments in third.
# D297 - see Millard p. 8
_BLEND = 'trains/Carriages/lnwr-6wheel-brake-composite-lms.blend'
_UPSTREAM_DAT = 'trains/lnwr-6wheel-30ft.dat'

SPECS = [
    Vehicle(
        name='LNWR-6Wheel-non-lav',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1887,
        intro_month=7,
        retire_year=1896,
        retire_month=2,
        speed=150,
        length=5,
        weight=12.9,
        axles=3,
        brake_force=5,
        payload=50,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=25,
        cost=304000,
        runningcost=0,
        fixed_cost=362,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        payload_by_class=[0, 50, 0, 0],
        comfort_by_class=[0, 69, 71, 84],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        upgrade=['LNWR-6Wheel-lav'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-6Wheel-lav',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1895,
        intro_month=12,
        retire_year=1916,
        retire_month=5,
        speed=150,
        length=5,
        weight=12.9,
        axles=3,
        brake_force=5,
        payload=38,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=20,
        cost=520000,
        runningcost=0,
        fixed_cost=619,
        upgrade_price=49285,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        payload_by_class=[0, 38, 0, 0],
        comfort_by_class=[0, 76, 76, 84],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-6Wheel-lav-tricomposite',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1890,
        intro_month=12,
        retire_year=1896,
        retire_month=2,
        speed=150,
        length=5,
        weight=12.9,
        axles=3,
        brake_force=5,
        payload=20,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=10,
        cost=530000,
        runningcost=0,
        fixed_cost=619,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        payload_by_class=[0, 20, 4, 5],
        comfort_by_class=[0, 69, 71, 91],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-6Wheel-brake-third',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1887,
        intro_month=7,
        retire_year=1896,
        retire_month=2,
        speed=150,
        length=5,
        weight=12,
        axles=3,
        brake_force=5,
        payload=30,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=15,
        cost=304000,
        runningcost=0,
        fixed_cost=5162,
        bidirectional=1,
        can_lead_from_rear=0,
        payload_by_class=[0, 30, 0, 0],
        comfort_by_class=[0, 69, 71, 84],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-6Wheel-brake-composite',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1887,
        intro_month=7,
        retire_year=1896,
        retire_month=2,
        speed=150,
        length=5,
        weight=12,
        axles=3,
        brake_force=5,
        payload=10,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=10,
        cost=309000,
        runningcost=0,
        fixed_cost=5162,
        bidirectional=1,
        can_lead_from_rear=0,
        payload_by_class=[0, 10, 10, 6],
        comfort_by_class=[0, 69, 71, 84],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-6Wheel-Guard',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Post',
        intro_year=1887,
        intro_month=7,
        retire_year=1896,
        retire_month=2,
        speed=150,
        length=5,
        weight=12,
        axles=3,
        brake_force=5,
        payload=320,
        min_loading_time=35,
        max_loading_time=90,
        cost=304000,
        runningcost=0,
        fixed_cost=5162,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['LNWR-Black', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-6Wheel-Mail',
        waytype='track',
        copyright='Kieron/James/jamespettspetts',
        freight='Post',
        intro_year=1887,
        intro_month=7,
        retire_year=1896,
        retire_month=2,
        speed=150,
        length=5,
        weight=12,
        axles=3,
        brake_force=5,
        payload=400,
        min_loading_time=35,
        max_loading_time=120,
        cost=304000,
        runningcost=0,
        fixed_cost=127,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-6Wheel-tpo',
        waytype='track',
        copyright='Kieron/James/jamespetts',
        freight='Post',
        intro_year=1887,
        intro_month=7,
        retire_year=1896,
        retire_month=2,
        speed=150,
        length=5,
        weight=12,
        axles=3,
        brake_force=5,
        payload=200,
        min_loading_time=35,
        max_loading_time=120,
        catering_level=1,
        cost=304000,
        runningcost=0,
        fixed_cost=24127,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
