"""lnwr-6wheel-radials."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# The introduction date for these vehicles is unclear.
# These are the 32' designs to which Jenkinson (LNWR)
# refers. Millard (p. 5) suggests that these were
# introduced in the "early 1880s", and refers to earlier
# 30'0" 6 wheel carriages from the 1870s.
# Weights are not available, but these are wooden framed
# vehicles, unlike the 30'1" carriages, which had steel
# underframes.
# D296 - see Jenkinson (LNWR) p. 110
# (Third class)
_BLEND = 'trains/Carriages/lnwr-6wheel-radial.blend'
_UPSTREAM_DAT = 'trains/lnwr-6wheel-radials.dat'

SPECS = [
    Vehicle(
        name='LNWR-6wheel-radial',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1873,
        intro_month=3,
        retire_year=1887,
        retire_month=7,
        speed=150,
        length=6,
        weight=12,
        axles=3,
        brake_force=5,
        payload=50,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=25,
        cost=317500,
        runningcost=0,
        fixed_cost=378,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        payload_by_class=[0, 50, 0, 0],
        comfort_by_class=[0, 63, 73, 86],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-6wheel-radial-first',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1873,
        intro_month=3,
        retire_year=1887,
        retire_month=7,
        speed=150,
        length=6,
        weight=12,
        axles=3,
        brake_force=5,
        payload=32,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=0,
        cost=326700,
        runningcost=28,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        payload_by_class=[0, 0, 0, 32],
        comfort_by_class=[0, 63, 73, 86],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-6wheel-radial-tricomposite',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1873,
        intro_month=3,
        retire_year=1887,
        retire_month=7,
        speed=150,
        length=6,
        weight=12,
        axles=3,
        brake_force=5,
        payload=12,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=0,
        cost=321500,
        runningcost=27,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        payload_by_class=[0, 10, 10, 12],
        comfort_by_class=[0, 63, 73, 86],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-6wheel-radial-brake-third',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Passagiere',
        intro_year=1873,
        intro_month=3,
        retire_year=1887,
        retire_month=7,
        speed=150,
        length=6,
        weight=12,
        axles=3,
        brake_force=5,
        payload=30,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=15,
        cost=317500,
        runningcost=0,
        fixed_cost=5178,
        bidirectional=1,
        can_lead_from_rear=0,
        payload_by_class=[0, 30, 0, 0],
        comfort_by_class=[0, 63, 73, 86],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-6wheel-radial-full-brake',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Post',
        intro_year=1873,
        intro_month=3,
        retire_year=1887,
        retire_month=7,
        speed=150,
        length=6,
        weight=12,
        brake_force=5,
        payload=320,
        min_loading_time=35,
        max_loading_time=90,
        cost=317500,
        runningcost=0,
        fixed_cost=378,
        bidirectional=1,
        can_lead_from_rear=0,
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-6wheel-radial-mail',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Post',
        intro_year=1873,
        intro_month=3,
        retire_year=1887,
        retire_month=7,
        speed=150,
        length=6,
        weight=11,
        axles=3,
        brake_force=5,
        payload=400,
        min_loading_time=35,
        max_loading_time=120,
        cost=314500,
        runningcost=0,
        fixed_cost=131,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-6wheel-radial-tpo',
        waytype='track',
        copyright='Kieron/jamespetts',
        freight='Post',
        intro_year=1873,
        intro_month=3,
        retire_year=1887,
        retire_month=7,
        speed=150,
        length=6,
        weight=11,
        axles=3,
        brake_force=5,
        payload=200,
        min_loading_time=35,
        max_loading_time=120,
        catering_level=1,
        cost=314500,
        runningcost=0,
        fixed_cost=24131,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
