"""lnwr-8wheel-radials."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# D352
# See Jenkinson (LNWR) p. 110
_BLEND = 'trains/Carriages/lnwr-8wheel-radial-lav-tricomposite-lms.blend'
_UPSTREAM_DAT = 'trains/lnwr-8wheel-radials.dat'

SPECS = [
    Vehicle(
        name='LNWR-8wheel-radial-brake',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1883,
        intro_month=6,
        retire_year=1893,
        retire_month=9,
        speed=135,
        length=7,
        weight=18,
        axles=4,
        payload=40,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=20,
        cost=340000,
        runningcost=0,
        fixed_cost=5205,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first', 'none'],
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 63, 73, 86],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        upgrade=['LNWR-8wheel-radial-brake-lav-front', 'LNWR-42ft-non-cor-brake-front'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-8wheel-radial-brake-lav-front',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1895,
        intro_month=12,
        retire_year=1915,
        retire_month=5,
        speed=135,
        length=7,
        weight=18,
        axles=4,
        payload=22,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=15,
        cost=520000,
        runningcost=0,
        fixed_cost=5419,
        upgrade_price=49285,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first', 'none'],
        payload_by_class=[0, 22, 0, 0],
        comfort_by_class=[0, 70, 80, 93],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        upgrade=['LNWR-42ft-non-cor-brake-lav-front'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-8wheel-radial-lav',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1895,
        intro_month=12,
        retire_year=1915,
        retire_month=5,
        speed=135,
        length=7,
        weight=18,
        axles=4,
        payload=56,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=30,
        cost=520000,
        runningcost=0,
        fixed_cost=619,
        upgrade_price=49285,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        payload_by_class=[0, 56, 0, 0],
        comfort_by_class=[0, 70, 80, 93],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        upgrade=['LNWR-42ft-non-cor-lav'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-8wheel-radial-lav-first',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1895,
        intro_month=12,
        retire_year=1915,
        retire_month=5,
        speed=135,
        length=7,
        weight=18,
        axles=4,
        payload=23,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=0,
        cost=530000,
        runningcost=0,
        fixed_cost=633,
        upgrade_price=49285,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        payload_by_class=[0, 0, 0, 23],
        comfort_by_class=[0, 70, 80, 93],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        upgrade=['LNWR-42ft-non-cor-lav-first'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-8wheel-radial-lav-tricomposite',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1895,
        intro_month=12,
        retire_year=1915,
        retire_month=5,
        speed=135,
        length=7,
        weight=18,
        axles=4,
        payload=16,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=12,
        cost=530000,
        runningcost=0,
        fixed_cost=633,
        upgrade_price=49285,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        payload_by_class=[0, 16, 4, 10],
        comfort_by_class=[0, 70, 80, 93],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        upgrade=['LNWR-42ft-non-cor-lav-tricomposite'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-8wheel-radial-non-lav',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1883,
        intro_month=6,
        retire_year=1893,
        retire_month=9,
        speed=135,
        length=7,
        weight=18,
        axles=4,
        payload=70,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=35,
        cost=340000,
        runningcost=0,
        fixed_cost=405,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        payload_by_class=[0, 70, 0, 0],
        comfort_by_class=[0, 63, 73, 86],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        upgrade=['LNWR-8wheel-radial-lav', 'LNWR-42ft-non-cor-non-lav'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-8wheel-radial-non-lav-composite',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1883,
        intro_month=6,
        retire_year=1893,
        retire_month=9,
        speed=135,
        length=7,
        weight=18,
        axles=4,
        payload=50,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=35,
        cost=342000,
        runningcost=0,
        fixed_cost=405,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        payload_by_class=[0, 50, 20, 0],
        comfort_by_class=[0, 63, 73, 86],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        upgrade=['LNWR-8wheel-radial-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-composite'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-8wheel-radial-non-lav-first',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1883,
        intro_month=6,
        retire_year=1893,
        retire_month=9,
        speed=135,
        length=7,
        weight=18,
        axles=4,
        payload=33,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=0,
        cost=350000,
        runningcost=0,
        fixed_cost=407,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        payload_by_class=[0, 0, 0, 33],
        comfort_by_class=[0, 63, 73, 86],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        upgrade=['LNWR-8wheel-radial-lav-first', 'LNWR-42ft-non-cor-non-lav-first'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-8wheel-radial-brake-rear',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1883,
        intro_month=6,
        retire_year=1893,
        retire_month=9,
        speed=135,
        length=7,
        weight=18,
        axles=4,
        payload=40,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=20,
        cost=350000,
        runningcost=0,
        fixed_cost=5217,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        payload_by_class=[0, 40, 0, 0],
        comfort_by_class=[0, 63, 73, 86],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        upgrade=['LNWR-8wheel-radial-brake-lav-rear', 'LNWR-42ft-non-cor-brake-rear'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-8wheel-radial-brake-lav-rear',
        waytype='track',
        copyright='Kieron/James',
        freight='Passagiere',
        intro_year=1895,
        intro_month=12,
        retire_year=1915,
        retire_month=5,
        speed=135,
        length=7,
        weight=18,
        axles=4,
        payload=22,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=15,
        cost=520000,
        runningcost=0,
        fixed_cost=5419,
        upgrade_price=49285,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        payload_by_class=[0, 22, 0, 0],
        comfort_by_class=[0, 70, 80, 93],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        upgrade=['LNWR-42ft-non-cor-brake-lav-rear'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-8wheel-radial-full-brake',
        waytype='track',
        copyright='Kieron/James',
        freight='Post',
        intro_year=1883,
        intro_month=6,
        retire_year=1893,
        retire_month=9,
        speed=135,
        length=7,
        weight=18,
        axles=4,
        payload=360,
        min_loading_time=35,
        max_loading_time=120,
        cost=350000,
        runningcost=0,
        fixed_cost=5205,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['LNWR-Black', 'LMS-Standard'],
        upgrade=['LNWR-42ft-non-cor-full-brake'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-8wheel-radial-mail',
        waytype='track',
        copyright='Kieron/James',
        freight='Post',
        intro_year=1883,
        intro_month=6,
        retire_year=1893,
        retire_month=9,
        speed=135,
        length=7,
        weight=18,
        axles=4,
        payload=550,
        min_loading_time=35,
        max_loading_time=180,
        cost=350000,
        runningcost=0,
        fixed_cost=146,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        upgrade=['LNWR-42ft-non-cor-mail'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LNWR-8wheel-radial-tpo',
        waytype='track',
        copyright='Kieron/James',
        freight='Post',
        intro_year=1883,
        intro_month=6,
        retire_year=1893,
        retire_month=9,
        speed=135,
        length=7,
        weight=18,
        axles=4,
        payload=550,
        min_loading_time=35,
        max_loading_time=180,
        catering_level=1,
        cost=350000,
        runningcost=0,
        fixed_cost=24146,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-front', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-front', 'LNWR-42ft-non-cor-brake-lav-front', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-front', 'LNWR-50ft-non-cor-eliptical-brake-front', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-front', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-front', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', 'LNWR-6Wheel-non-lav', 'LNWR-6Wheel-Mail', 'LNWR-6Wheel-tpo', 'LNWR-6Wheel-Guard', 'LNWR-6Wheel-lav', 'LNWR-6Wheel-brake-third', 'LNWR-8wheel-radial-lav', 'LNWR-8wheel-radial-brake-rear', 'LNWR-8wheel-radial-mail', 'LNWR-8wheel-radial-tpo', 'LNWR-8wheel-radial-non-lav', 'LNWR-8wheel-radial-brake-lav-rear', 'LNWR-8wheel-radial-full-brake', 'LNWR-42ft-non-cor-lav', 'LNWR-42ft-non-cor-non-lav', 'LNWR-42ft-non-cor-brake-rear', 'LNWR-42ft-non-cor-brake-lav-rear', 'LNWR-42ft-non-cor-mail', 'LNWR-42ft-non-cor-full-brake', 'LNWR-45ft-non-cor-lav', 'LNWR-45ft-non-cor-lav-brake', 'LNWR-50ft-non-cor-arc', 'LNWR-50ft-non-cor-arc-brake-rear', 'LNWR-50ft-non-cor-eliptical-brake-rear', 'LNWR-50ft-non-cor-eliptical', 'LNWR-57ft-non-cor-lav-brake-rear', 'LNWR-57ft-non-cor-lav', 'LNWR-57ft-non-cor-brake-rear', 'LNWR-57ft-non-cor', 'LNWR-6wheel-radial', 'LNWR-6wheel-radial-brake-third', 'LNWR-6wheel-radial-full-brake', 'LNWR-6wheel-radial-mail', 'LNWR-6wheel-radial-tpo', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'LNWR-6wheel-radial-first', 'LNWR-6wheel-radial-tricomposite', 'LNWR-8wheel-radial-lav-first', 'LNWR-8wheel-radial-lav-tricomposite', 'LNWR-8wheel-radial-non-lav-composite', 'LNWR-8wheel-radial-non-lav-first', 'LNWR-42ft-non-cor-lav-first', 'LNWR-42ft-non-cor-lav-tricomposite', 'LNWR-42ft-non-cor-non-lav-first', 'LNWR-42ft-non-cor-non-lav-composite', 'LNWR-6Wheel-lav-tricomposite', 'LNWR-6Wheel-brake-composite', 'LNWR-45ft-non-cor-lav-tricomposite', 'LNWR-50ft-non-cor-arc-composite', 'LNWR-50ft-non-cor-arc-first', 'LNWR-50ft-non-cor-eliptical-composite-first-second', 'LNWR-50ft-non-cor-eliptical-composite-first-third', 'LNWR-54ft-non-cor-lav-third', 'LNWR-54ft-non-cor-lav-composite', 'LNWR-57ft-non-cor-first', 'LNWR-57ft-non-cor-composite', 'LMS-non-cor-lav-first', 'LMS-non-cor-non-lav-composite', 'LMS-non-cor-non-lav-first'],
        liverytype=['LNWR-Black', 'LMS-Standard'],
        upgrade=['LNWR-42ft-non-cor-mail'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
