"""lswr-42ft."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# Non-lavatory compartment carriages with arc rooves
_BLEND = 'trains/Carriages/lswr-42ft-olive.blend'
_UPSTREAM_DAT = 'trains/lswr-42ft.dat'

SPECS = [
    Vehicle(
        name='lswr-42ft-brake-third-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1884,
        intro_month=1,
        retire_year=1896,
        retire_month=10,
        speed=160,
        length=7,
        weight=17.4,
        axles=4,
        payload=50,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=25,
        cost=585000,
        runningcost=0,
        fixed_cost=5600,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-48ft-lav-brake', 'lswr-48ft-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-arc-lav-composite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'none'],
        payload_by_class=[0, 50, 0, 0],
        comfort_by_class=[0, 77, 78, 84],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-42ft-brake-third-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1884,
        intro_month=1,
        retire_year=1896,
        retire_month=10,
        speed=160,
        length=7,
        weight=17.4,
        axles=4,
        payload=50,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=25,
        cost=585000,
        runningcost=0,
        fixed_cost=5600,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-front', 'lswr-56ft-lav-brake-front', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-front', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-front', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-front', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-front', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-48ft-lav-brake', 'lswr-48ft-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-arc-lav-composite', 'lswr-42ft-brake-third-front', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite'],
        payload_by_class=[0, 50, 0, 0],
        comfort_by_class=[0, 77, 78, 84],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-42ft-third',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1884,
        intro_month=1,
        retire_year=1896,
        retire_month=10,
        speed=160,
        length=7,
        weight=17.8,
        axles=4,
        payload=70,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=35,
        cost=630000,
        runningcost=0,
        fixed_cost=842,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-front', 'lswr-56ft-lav-brake-front', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-front', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-front', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-front', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-front', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-48ft-lav-brake', 'lswr-48ft-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-arc-lav-composite', 'lswr-42ft-brake-third-front', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-48ft-lav-brake', 'lswr-48ft-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-arc-lav-composite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite'],
        payload_by_class=[0, 70, 0, 0],
        comfort_by_class=[0, 77, 78, 84],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-42ft-first',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1884,
        intro_month=1,
        retire_year=1896,
        retire_month=10,
        speed=160,
        length=7,
        weight=17.7,
        axles=4,
        payload=36,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=0,
        cost=640800,
        runningcost=0,
        fixed_cost=847,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-front', 'lswr-56ft-lav-brake-front', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-front', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-front', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-front', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-front', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-48ft-lav-brake', 'lswr-48ft-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-arc-lav-composite', 'lswr-42ft-brake-third-front', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-48ft-lav-brake', 'lswr-48ft-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-arc-lav-composite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite'],
        payload_by_class=[0, 0, 0, 36],
        comfort_by_class=[0, 77, 78, 84],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-42ft-tricomposite',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1884,
        intro_month=1,
        retire_year=1896,
        retire_month=10,
        speed=160,
        length=7,
        weight=17.8,
        axles=4,
        payload=30,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=45,
        cost=640800,
        runningcost=0,
        fixed_cost=845,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-front', 'lswr-56ft-lav-brake-front', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-front', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-front', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-front', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-front', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-48ft-lav-brake', 'lswr-48ft-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-arc-lav-composite', 'lswr-42ft-brake-third-front', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-48ft-lav-brake', 'lswr-48ft-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-arc-lav-composite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite'],
        payload_by_class=[0, 30, 20, 12],
        comfort_by_class=[0, 74, 78, 84],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
