"""lswr-44ft-full-brake."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# Arc roof
_BLEND = 'trains/Carriages/lswr-44ft-full-brake-elliptical-malachite.blend'
_UPSTREAM_DAT = 'trains/lswr-44ft-full-brake.dat'

SPECS = [
    Vehicle(
        name='lswr-44ft-full-brake',
        waytype='track',
        copyright='JamesPetts',
        freight='Post',
        intro_year=1885,
        intro_month=7,
        retire_year=1893,
        retire_month=4,
        speed=160,
        length=7,
        weight=19.6,
        axles=4,
        payload=255,
        min_loading_time=35,
        max_loading_time=90,
        cost=675000,
        runningcost=0,
        fixed_cost=804,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-44ft-fruit-brake',
        waytype='track',
        copyright='JamesPetts',
        freight='fruit',
        intro_year=1885,
        intro_month=7,
        retire_year=1893,
        retire_month=4,
        speed=160,
        length=7,
        weight=19.6,
        axles=4,
        payload=18,
        min_loading_time=35,
        max_loading_time=90,
        cost=675000,
        runningcost=0,
        fixed_cost=804,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-44ft-full-brake-elliptical',
        waytype='track',
        copyright='JamesPetts',
        freight='Post',
        intro_year=1893,
        intro_month=4,
        retire_year=1902,
        retire_month=9,
        speed=160,
        length=8,
        weight=19.9,
        axles=4,
        payload=260,
        min_loading_time=35,
        max_loading_time=90,
        cost=687400,
        runningcost=0,
        fixed_cost=818,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-44ft-fruit-brake-elliptical',
        waytype='track',
        copyright='JamesPetts',
        freight='fruit',
        intro_year=1893,
        intro_month=4,
        retire_year=1902,
        retire_month=9,
        speed=160,
        length=8,
        weight=19.9,
        axles=4,
        payload=18,
        min_loading_time=35,
        max_loading_time=90,
        cost=687400,
        runningcost=0,
        fixed_cost=818,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
