"""lswr-emu."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Railcars/lswr-emu-driving-motor-br-revised.blend'
_UPSTREAM_DAT = 'trains/lswr-emu.dat'

SPECS = [
    Vehicle(
        name='LSWR-EMU(front)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1913,
        intro_month=6,
        retire_year=1927,
        retire_month=9,
        speed=97,
        length=10,
        weight=30,
        axles=4,
        power=402,
        gear=80,
        tractive_effort=35,
        payload=70,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=35,
        cost=1461000,
        runningcost=241,
        fixed_cost=7218,
        upgrade_price=1022700,
        increase_maintenance_after_years=30,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['SR-3SUB(rear)', 'LSWR-EMU(rear)', 'SR-4SUB(rear)', 'SR-2-NOL-rear', 'SR-4LAV(rear)', 'SR-401[BIL]Rear', 'SR-6PAN(rear)', 'sr-2hal-rear', 'SR-404[COR]Rear', 'lbscr-48ft-augmentation-trailer-rear', 'lbscr-54ft-augmentation-trailer-rear', 'lswr-48ft-arc-augmentation-trailer-rear', 'lswr-48ft-augmentation-trailer-rear', 'lswr-56ft-augmentation-trailer-rear', 'SR-5-BEL-driving-motor-rear', 'none'],
        constraint_next=['LSWR-EMU(centre)'],
        payload_by_class=[0, 70, 0, 0],
        comfort_by_class=[0, 66, 0, 83],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Revised'],
        upgrade=['BR-414[HAP]Front', 'BR-414[HAP]Rear', 'BR-4EPB(front)', 'BR-2EPB(rear)', 'BR-4EPB(rear)', 'BR-4EPB(centre1)', 'BR-4EPB(centre2)'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LSWR-EMU(centre)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1913,
        intro_month=6,
        retire_year=1927,
        retire_month=9,
        speed=97,
        length=10,
        weight=25,
        axles=4,
        payload=48,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=15,
        cost=716000,
        runningcost=0,
        fixed_cost=852,
        upgrade_price=143200,
        increase_maintenance_after_years=30,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LSWR-EMU(front)'],
        constraint_next=['LSWR-EMU(rear)', 'SR-4SUB(centre2)'],
        payload_by_class=[0, 30, 0, 48],
        comfort_by_class=[0, 66, 0, 83],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Revised'],
        upgrade=['BR-414[HAP]Front', 'BR-414[HAP]Rear', 'BR-4EPB(front)', 'BR-2EPB(rear)', 'BR-4EPB(rear)', 'BR-4EPB(centre1)', 'BR-4EPB(centre2)'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LSWR-EMU(rear)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1913,
        intro_month=6,
        retire_year=1927,
        retire_month=9,
        speed=97,
        length=10,
        weight=30,
        axles=4,
        power=402,
        gear=80,
        tractive_effort=35,
        payload=70,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=35,
        cost=1461000,
        runningcost=241,
        fixed_cost=7218,
        upgrade_price=1022700,
        increase_maintenance_after_years=30,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['LSWR-EMU(centre)', 'SR-4SUB(centre2)'],
        constraint_next=['SR-3SUB(front)', 'LSWR-EMU(front)', 'SR-4SUB(front)', 'SR-2-NOL-front', 'SR-4LAV(front)', 'SR-401[BIL]Front', 'SR-6PAN(front)', 'sr-2hal-front', 'SR-404[COR]Front', 'lbscr-48ft-augmentation-trailer-front', 'lbscr-54ft-augmentation-trailer-front', 'lswr-48ft-arc-augmentation-trailer-front', 'lswr-48ft-augmentation-trailer-front', 'lswr-56ft-augmentation-trailer-front', 'SR-5-BEL-driving-motor-front', 'none'],
        payload_by_class=[0, 70, 0, 0],
        comfort_by_class=[0, 66, 0, 83],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Revised'],
        upgrade=['BR-414[HAP]Front', 'BR-414[HAP]Rear', 'BR-4EPB(front)', 'BR-2EPB(rear)', 'BR-4EPB(rear)', 'BR-4EPB(centre1)', 'BR-4EPB(centre2)'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
