"""lswr-6-wheel-30ft."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# Brake third
_BLEND = 'trains/Carriages/lswr-6-wheel-30ft-olive.blend'
_UPSTREAM_DAT = 'trains/lswr-6-wheel-30ft.dat'

SPECS = [
    Vehicle(
        name='lswr-6-wheel-30ft-brake-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1886,
        intro_month=9,
        retire_year=1897,
        retire_month=1,
        speed=150,
        length=5,
        weight=13.0,
        axles=3,
        payload=30,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=15,
        cost=331850,
        runningcost=0,
        fixed_cost=5195,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite', 'none'],
        payload_by_class=[0, 30, 0, 0],
        comfort_by_class=[0, 72, 75, 83],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-6-wheel-30ft-brake-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1886,
        intro_month=9,
        retire_year=1897,
        retire_month=1,
        speed=150,
        length=5,
        weight=13.0,
        axles=3,
        payload=30,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=15,
        cost=331850,
        runningcost=0,
        fixed_cost=5195,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-front', 'lswr-56ft-lav-brake-front', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-front', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-front', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-front', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-front', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-front', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite'],
        payload_by_class=[0, 30, 0, 0],
        comfort_by_class=[0, 72, 75, 83],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-6-wheel-30ft',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1886,
        intro_month=9,
        retire_year=1897,
        retire_month=1,
        speed=150,
        length=5,
        weight=13.0,
        axles=3,
        payload=50,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=25,
        cost=331850,
        runningcost=0,
        fixed_cost=395,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-front', 'lswr-56ft-lav-brake-front', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-front', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-front', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-front', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-front', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-front', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite'],
        payload_by_class=[0, 50],
        comfort_by_class=[0, 72, 75, 83],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-6-wheel-30ft-second',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1886,
        intro_month=9,
        retire_year=1897,
        retire_month=1,
        speed=150,
        length=5,
        weight=13.0,
        axles=3,
        payload=50,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=25,
        cost=331850,
        runningcost=0,
        fixed_cost=395,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-front', 'lswr-56ft-lav-brake-front', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-front', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-front', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-front', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-front', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-front', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite'],
        payload_by_class=[0, 0, 50, 0],
        comfort_by_class=[0, 72, 75, 83],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-6-wheel-29ft-6-first',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1886,
        intro_month=9,
        retire_year=1897,
        retire_month=1,
        speed=150,
        length=5,
        weight=13.0,
        axles=3,
        payload=24,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=0,
        cost=331850,
        runningcost=0,
        fixed_cost=395,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-front', 'lswr-56ft-lav-brake-front', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-front', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-front', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-front', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-front', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-front', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite'],
        payload_by_class=[0, 0, 0, 24],
        comfort_by_class=[0, 72, 75, 83],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-6-wheel-30ft-lav',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1888,
        intro_month=11,
        retire_year=1897,
        retire_month=1,
        speed=150,
        length=6,
        weight=13.5,
        axles=3,
        payload=22,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=0,
        cost=349000,
        runningcost=0,
        fixed_cost=398,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-front', 'lswr-56ft-lav-brake-front', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-front', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-front', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-front', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-front', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-front', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite'],
        payload_by_class=[0, 0, 0, 22],
        comfort_by_class=[0, 72, 75, 90],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-6-wheel-30ft-full-brake',
        waytype='track',
        copyright='JamesPetts',
        freight='Post',
        intro_year=1887,
        intro_month=8,
        retire_year=1893,
        retire_month=4,
        speed=150,
        length=5,
        weight=12.9,
        axles=3,
        payload=245,
        min_loading_time=35,
        max_loading_time=85,
        cost=331850,
        runningcost=0,
        fixed_cost=395,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-6-wheel-30ft-fruit-brake',
        waytype='track',
        copyright='JamesPetts',
        freight='fruit',
        intro_year=1887,
        intro_month=8,
        retire_year=1893,
        retire_month=4,
        speed=150,
        length=5,
        weight=12.9,
        axles=3,
        payload=10,
        min_loading_time=35,
        max_loading_time=120,
        cost=331850,
        runningcost=0,
        fixed_cost=138,
        bidirectional=1,
        can_lead_from_rear=0,
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-6-wheel-30ft-parcels-van',
        waytype='track',
        copyright='JamesPetts',
        freight='Post',
        intro_year=1887,
        intro_month=8,
        retire_year=1893,
        retire_month=4,
        speed=150,
        length=5,
        weight=12.9,
        axles=3,
        payload=400,
        min_loading_time=35,
        max_loading_time=120,
        cost=331850,
        runningcost=0,
        fixed_cost=138,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-front', 'lswr-56ft-lav-brake-front', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-front', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-front', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-front', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-front', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-front', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite'],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-6-wheel-30ft-fruit-van',
        waytype='track',
        copyright='JamesPetts',
        freight='fruit',
        intro_year=1887,
        intro_month=8,
        retire_year=1893,
        retire_month=4,
        speed=150,
        length=5,
        weight=12.9,
        axles=3,
        payload=14,
        min_loading_time=35,
        max_loading_time=120,
        cost=331850,
        runningcost=0,
        fixed_cost=138,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-front', 'lswr-56ft-lav-brake-front', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-front', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-front', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-front', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-front', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-front', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'lswr-56ft-sub', 'lswr-56ft-sub-brake-rear', 'lswr-56ft-lav-brake-rear', 'lswr-56ft-lav', 'lswr-48ft-sub-brake-rear', 'lswr-48ft-sub', 'lswr-48ft-lav', 'lswr-48ft-arc-parcels-brake', 'lswr-48ft-arc-fruit-brake', 'lswr-44ft-full-brake', 'lswr-44ft-full-brake-elliptical', 'lswr-48ft-fruit-brake', 'lswr-48ft-parcels-brake', 'lswr-48ft-arc-sub-brake-rear', 'lswr-48ft-arc-sub', 'lswr-48ft-arc-lav-brake', 'lswr-48ft-arc-lav', 'lswr-30ft-full-brake-6-wheel-elliptical', 'lswr-30ft-fruit-brake-6-wheel-elliptical', 'lswr-6-wheel-28ft-brake-rear', 'lswr-6-wheel-28ft', 'lswr-6-wheel-30ft-lantern-roof-brake', 'lswr-6-wheel-30ft-brake-rear', 'lswr-6-wheel-30ft', 'lswr-6-wheel-30ft-lav', 'lswr-6-wheel-30ft-full-brake', 'lswr-6-wheel-30ft-fruit-brake', 'lswr-6-wheel-30ft-parcels-van', 'lswr-6-wheel-30ft-fruit-van', 'lswr-6-wheel-28ft-composite', 'lswr-56ft-lav-composite-1st-3rd', 'lswr-56ft-sub-tricomposite', 'lswr-42ft-brake-third-rear', 'lswr-42ft-third', 'lswr-42ft-first', 'lswr-42ft-tricomposite', 'lswr-6-wheel-30ft-second', 'lswr-6-wheel-29ft-6-first', 'lswr-48ft-arc-lav-composite', 'lswr-48ft-lav-tricomposite', 'lswr-48ft-lav-composite'],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
