"""lswr-corridor."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# Third
_BLEND = 'trains/Carriages/lswr-corridor-brake-malachite.blend'
_UPSTREAM_DAT = 'trains/lswr-corridor.dat'

SPECS = [
    Vehicle(
        name='LSWR-corridor',
        waytype='track',
        copyright='James/jamespetts',
        freight='Passagiere',
        intro_year=1903,
        retire_year=1921,
        retire_month=5,
        speed=160,
        length=10,
        weight=26,
        axles=4,
        payload=64,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=33,
        cost=702000,
        runningcost=0,
        fixed_cost=836,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        payload_by_class=[0, 64, 0, 0],
        comfort_by_class=[0, 110, 125, 146],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LSWR-corridor-composite',
        waytype='track',
        copyright='James/jamespetts',
        freight='Passagiere',
        intro_year=1903,
        retire_year=1921,
        retire_month=5,
        speed=160,
        length=10,
        weight=26,
        axles=4,
        payload=24,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=16,
        cost=704000,
        runningcost=0,
        fixed_cost=837,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        payload_by_class=[0, 0, 24, 16],
        comfort_by_class=[0, 110, 125, 146],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LSWR-corridor-brake-front',
        waytype='track',
        copyright='James/jamespetts',
        freight='Passagiere',
        intro_year=1903,
        intro_month=9,
        retire_year=1921,
        retire_month=5,
        speed=160,
        length=10,
        weight=25.4,
        axles=4,
        payload=32,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=17,
        cost=702000,
        runningcost=0,
        fixed_cost=5636,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first', 'none'],
        payload_by_class=[0, 32, 0, 0],
        comfort_by_class=[0, 110, 125, 146],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LSWR-corridor-brake-rear',
        waytype='track',
        copyright='James/jamespetts',
        freight='Passagiere',
        intro_year=1903,
        intro_month=9,
        retire_year=1921,
        retire_month=5,
        speed=160,
        length=10,
        weight=25.4,
        axles=4,
        payload=32,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=17,
        cost=702000,
        runningcost=0,
        fixed_cost=5636,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        payload_by_class=[0, 32, 0, 0],
        comfort_by_class=[0, 110, 125, 146],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LSWR-dining-saloon',
        waytype='track',
        copyright='James/jamespetts',
        freight='Passagiere',
        intro_year=1903,
        intro_month=9,
        retire_year=1921,
        retire_month=5,
        speed=160,
        length=10,
        weight=26.8,
        axles=4,
        payload=24,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=10,
        catering_level=4,
        cost=725000,
        runningcost=0,
        fixed_cost=18863,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        payload_by_class=[0, 24, 0, 0],
        comfort_by_class=[0, 140, 140, 146],
        liverytype=['LSWR-pea-green', 'LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
