"""lswr-ironclads."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# Third
_BLEND = 'trains/Carriages/lswr-ironclad-restaurant-car-malachite.blend'
_UPSTREAM_DAT = 'trains/lswr-ironclads.dat'

SPECS = [
    Vehicle(
        name='LSWR-Ironclad',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Passagiere',
        intro_year=1921,
        intro_month=5,
        retire_year=1926,
        retire_month=9,
        speed=160,
        length=10,
        weight=34.5,
        axles=4,
        payload=64,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=30,
        cost=633000,
        runningcost=0,
        fixed_cost=754,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        payload_by_class=[0, 64, 0, 0],
        comfort_by_class=[0, 127, 127, 143],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LSWR-Ironclad-First',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Passagiere',
        intro_year=1921,
        intro_month=5,
        retire_year=1926,
        retire_month=9,
        speed=160,
        length=10,
        weight=34.5,
        axles=4,
        payload=28,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=0,
        cost=642000,
        runningcost=0,
        fixed_cost=755,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        payload_by_class=[0, 0, 0, 28],
        comfort_by_class=[0, 127, 127, 143],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LSWR-Ironclad-Dining',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Passagiere',
        intro_year=1922,
        intro_month=6,
        retire_year=1926,
        retire_month=9,
        speed=160,
        length=10,
        weight=34.8,
        axles=4,
        payload=24,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=0,
        catering_level=3,
        cost=675000,
        runningcost=0,
        fixed_cost=18804,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        payload_by_class=[0, 0, 0, 24],
        comfort_by_class=[0, 127, 127, 143],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LSWR-Ironclad-Pantry',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Passagiere',
        intro_year=1921,
        intro_month=5,
        retire_year=1926,
        retire_month=9,
        speed=160,
        length=10,
        weight=34.6,
        axles=4,
        payload=56,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=16,
        catering_level=2,
        cost=646000,
        runningcost=0,
        fixed_cost=6769,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        payload_by_class=[0, 56, 0, 0],
        comfort_by_class=[0, 127, 127, 143],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LSWR-Ironclad-Brake-rear',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Passagiere',
        intro_year=1921,
        intro_month=5,
        retire_year=1926,
        retire_month=9,
        speed=160,
        length=10,
        weight=33.5,
        axles=4,
        payload=32,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=19,
        cost=633000,
        runningcost=0,
        fixed_cost=5554,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        payload_by_class=[0, 32, 0, 0],
        comfort_by_class=[0, 127, 127, 143],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LSWR-Ironclad-Brake-front',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Passagiere',
        intro_year=1921,
        intro_month=5,
        retire_year=1926,
        retire_month=9,
        speed=160,
        length=10,
        weight=33.5,
        axles=4,
        payload=32,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=19,
        cost=633000,
        runningcost=0,
        fixed_cost=5554,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first', 'none'],
        payload_by_class=[0, 32, 0, 0],
        comfort_by_class=[0, 127, 127, 143],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LSWR-Ironclad-Mail',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Post',
        intro_year=1921,
        intro_month=5,
        retire_year=1926,
        retire_month=9,
        speed=160,
        length=10,
        weight=33.3,
        axles=4,
        payload=600,
        min_loading_time=25,
        max_loading_time=55,
        cost=633000,
        runningcost=0,
        fixed_cost=264,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='LSWR-Ironclad-TPO',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Post',
        intro_year=1921,
        intro_month=5,
        retire_year=1926,
        retire_month=9,
        speed=160,
        length=10,
        weight=33.3,
        axles=4,
        payload=450,
        min_loading_time=25,
        max_loading_time=55,
        catering_level=1,
        cost=675000,
        runningcost=0,
        fixed_cost=24281,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
