"""ltsr-cor."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See Lacy & Dow vol. 2 p. 480
_BLEND = 'trains/Carriages/ltsr-cor-brake-lms.blend'
_UPSTREAM_DAT = 'trains/ltsr-cor.dat'

SPECS = [
    Vehicle(
        name='ltsr-cor',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1911,
        intro_month=5,
        retire_year=1914,
        retire_month=9,
        speed=160,
        length=8,
        weight=27.9,
        axles=4,
        payload=56,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=35,
        cost=560000,
        runningcost=0,
        fixed_cost=645,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['ltsr-cor', 'ltsr-cor-brake', 'ltsr-cor-composite', 'ltsr-dining-saloon'],
        constraint_next=['ltsr-cor', 'ltsr-cor-brake', 'ltsr-cor-composite', 'ltsr-dining-saloon'],
        payload_by_class=[0, 56, 0, 0],
        comfort_by_class=[0, 116, 116, 134],
        liverytype=['LTSR-standard', 'MR-Standard', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='ltsr-cor-composite',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1911,
        intro_month=5,
        retire_year=1914,
        retire_month=9,
        speed=160,
        length=8,
        weight=27.9,
        axles=4,
        payload=34,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=17,
        cost=565000,
        runningcost=0,
        fixed_cost=655,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['ltsr-cor', 'ltsr-cor-brake', 'ltsr-cor-composite', 'ltsr-dining-saloon'],
        constraint_next=['ltsr-cor', 'ltsr-cor-brake', 'ltsr-cor-composite', 'ltsr-dining-saloon'],
        payload_by_class=[0, 34, 0, 18],
        comfort_by_class=[0, 116, 116, 134],
        liverytype=['LTSR-standard', 'MR-Standard', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='ltsr-cor-brake',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1911,
        intro_month=5,
        retire_year=1914,
        retire_month=9,
        speed=160,
        length=8,
        weight=27.9,
        axles=4,
        payload=36,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=22,
        cost=558000,
        runningcost=0,
        fixed_cost=5502,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['ltsr-cor', 'ltsr-cor-brake', 'ltsr-cor-composite', 'ltsr-dining-saloon', 'none'],
        payload_by_class=[0, 36, 0, 0],
        comfort_by_class=[0, 116, 116, 134],
        liverytype=['LTSR-standard', 'MR-Standard', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='ltsr-dining-saloon',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1911,
        intro_month=5,
        retire_year=1914,
        retire_month=9,
        speed=160,
        length=8,
        weight=28.5,
        axles=4,
        payload=21,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=0,
        catering_level=3,
        cost=580000,
        runningcost=0,
        fixed_cost=5650,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['ltsr-cor', 'ltsr-cor-brake', 'ltsr-cor-composite', 'ltsr-dining-saloon'],
        constraint_next=['ltsr-cor', 'ltsr-cor-brake', 'ltsr-cor-composite', 'ltsr-dining-saloon'],
        payload_by_class=[0, 0, 0, 21],
        comfort_by_class=[0, 116, 116, 134],
        liverytype=['LTSR-standard', 'MR-Standard', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
