"""ltsr-6wheel."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# Third class
_BLEND = 'trains/Carriages/ltsr-6wheel-dia4-lms.blend'
_UPSTREAM_DAT = 'trains/ltsr-6wheel.dat'

SPECS = [
    Vehicle(
        name='ltsr-6wheel-dia17',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1891,
        intro_month=1,
        retire_year=1902,
        retire_month=6,
        speed=150,
        length=6,
        weight=14.8,
        axles=3,
        payload=60,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=30,
        cost=310000,
        runningcost=0,
        fixed_cost=381,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7'],
        constraint_next=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7'],
        payload_by_class=[0, 60, 0, 0],
        comfort_by_class=[0, 59, 63, 79],
        liverytype=['LTSR-standard', 'MR-Standard', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='ltsr-6wheel-composite-dia8',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1891,
        intro_month=1,
        retire_year=1902,
        retire_month=6,
        speed=150,
        length=5,
        weight=12.2,
        axles=3,
        payload=24,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=10,
        cost=313000,
        runningcost=0,
        fixed_cost=381,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7'],
        constraint_next=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7'],
        payload_by_class=[0, 20, 0, 24],
        comfort_by_class=[0, 59, 63, 79],
        liverytype=['LTSR-standard', 'MR-Standard', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='ltsr-6wheel-composite-dia9',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1891,
        intro_month=1,
        retire_year=1902,
        retire_month=6,
        speed=150,
        length=6,
        weight=13.8,
        axles=3,
        payload=24,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=10,
        cost=318400,
        runningcost=0,
        fixed_cost=381,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7'],
        constraint_next=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7'],
        payload_by_class=[0, 0, 20, 24],
        comfort_by_class=[0, 59, 63, 79],
        liverytype=['LTSR-standard', 'MR-Standard', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='ltsr-6wheel-dia4',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1891,
        intro_month=1,
        retire_year=1902,
        retire_month=6,
        speed=150,
        length=5,
        weight=12.2,
        axles=3,
        payload=32,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=0,
        cost=320000,
        runningcost=0,
        fixed_cost=381,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7'],
        constraint_next=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7'],
        payload_by_class=[0, 0, 0, 32],
        comfort_by_class=[0, 59, 63, 79],
        liverytype=['LTSR-standard', 'MR-Standard', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='ltsr-6wheel-brake-dia22',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1891,
        intro_month=1,
        retire_year=1902,
        retire_month=6,
        speed=150,
        length=6,
        weight=14.8,
        axles=3,
        payload=30,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=15,
        cost=295000,
        runningcost=0,
        fixed_cost=5157,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7', 'none'],
        payload_by_class=[0, 30, 0, 0],
        comfort_by_class=[0, 59, 63, 79],
        liverytype=['LTSR-standard', 'MR-Standard', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
