"""ltsr-4wheel."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See Lacy & Dow vol. 2 p. 478
# rear brake carriage
_BLEND = 'trains/Carriages/ltsr-4wheel-full-brake-dia29-lms.blend'
_UPSTREAM_DAT = 'trains/ltsr-4wheel.dat'

SPECS = [
    Vehicle(
        name='ltsr-4wheel-brake-dia21',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1877,
        intro_month=10,
        retire_year=1891,
        retire_month=4,
        speed=145,
        length=4,
        weight=9.1,
        axles=2,
        brake_force=5,
        rolling_resistance=18,
        payload=20,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=10,
        cost=280000,
        runningcost=0,
        fixed_cost=5169,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7', 'none'],
        payload_by_class=[0, 20, 0, 0],
        comfort_by_class=[0, 51, 60, 64],
        liverytype=['LTSR-standard', 'MR-Standard', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='ltsr-4wheel-brake-dia22',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1877,
        intro_month=10,
        retire_year=1891,
        retire_month=4,
        speed=145,
        length=4,
        weight=9.1,
        axles=2,
        brake_force=5,
        rolling_resistance=18,
        payload=20,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=10,
        cost=280000,
        runningcost=0,
        fixed_cost=5169,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7', 'none'],
        payload_by_class=[0, 20, 0, 0],
        comfort_by_class=[0, 51, 60, 64],
        liverytype=['LTSR-standard', 'MR-Standard', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='ltsr-4wheel-dia12',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1877,
        intro_month=10,
        retire_year=1891,
        retire_month=4,
        speed=145,
        length=4,
        weight=9.7,
        axles=2,
        brake_force=5,
        rolling_resistance=18,
        payload=50,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=25,
        cost=280000,
        runningcost=0,
        fixed_cost=369,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7'],
        constraint_next=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7'],
        payload_by_class=[0, 50, 0, 0],
        comfort_by_class=[0, 51, 60, 64],
        liverytype=['LTSR-standard', 'MR-Standard', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='ltsr-4wheel-composite-dia7',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1877,
        intro_month=10,
        retire_year=1891,
        retire_month=4,
        speed=145,
        length=4,
        weight=9.6,
        axles=2,
        brake_force=5,
        rolling_resistance=18,
        payload=20,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=10,
        cost=284000,
        runningcost=0,
        fixed_cost=369,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7'],
        constraint_next=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7'],
        payload_by_class=[0, 0, 20, 16],
        comfort_by_class=[0, 51, 60, 64],
        liverytype=['LTSR-standard', 'MR-Standard', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='ltsr-4wheel-first-dia1',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1877,
        intro_month=10,
        retire_year=1891,
        retire_month=4,
        speed=145,
        length=4,
        weight=9.1,
        axles=2,
        brake_force=5,
        rolling_resistance=18,
        payload=32,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=0,
        cost=287500,
        runningcost=0,
        fixed_cost=369,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7'],
        constraint_next=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7'],
        payload_by_class=[0, 0, 0, 32],
        comfort_by_class=[0, 51, 60, 64],
        liverytype=['LTSR-standard', 'MR-Standard', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='ltsr-4wheel-full-brake-dia29',
        waytype='track',
        copyright='JamesPetts',
        freight='Post',
        intro_year=1877,
        intro_month=10,
        retire_year=1913,
        retire_month=1,
        speed=145,
        length=4,
        weight=9.1,
        axles=2,
        brake_force=5,
        rolling_resistance=18,
        payload=210,
        min_loading_time=35,
        max_loading_time=100,
        cost=275000,
        runningcost=0,
        fixed_cost=369,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7', 'none'],
        liverytype=['LTSR-standard', 'MR-Standard', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='ltsr-4wheel-mail',
        waytype='track',
        copyright='JamesPetts',
        freight='Post',
        intro_year=1877,
        intro_month=10,
        retire_year=1913,
        retire_month=1,
        speed=145,
        length=4,
        weight=9.1,
        axles=2,
        brake_force=5,
        rolling_resistance=18,
        payload=340,
        min_loading_time=35,
        max_loading_time=100,
        cost=273000,
        runningcost=0,
        fixed_cost=125,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7'],
        constraint_next=['ltsr-4wheel-brake-dia21', 'ltsr-4wheel-dia12', 'ltsr-4wheel-full-brake-dia29', 'ltsr-4wheel-mail', 'ltsr-6wheel-dia17', 'ltsr-6wheel-brake-dia22', 'ltsr-46ft-bogie-dia18', 'ltsr-46ft-bogie-lav', 'ltsr-46ft-bogie-brake-dia26', 'ltsr-4wheel-first-dia1', 'ltsr-6wheel-dia4', 'ltsr-48ft-bogie-dia10', 'ltsr-48ft-bogie-dia6', 'ltsr-48ft-bogie-lav-composite', 'ltsr-48ft-bogie-lav-first', 'ltsr-6wheel-composite-dia9', 'ltsr-6wheel-composite-dia8', 'ltsr-4wheel-composite-dia7'],
        liverytype=['LTSR-standard', 'MR-Standard', 'LMS-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
