"""mcr-4wheel-open-second."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See Lacy & Dow p. 4
_BLEND = 'trains/Carriages/mcr-4wheel-open-second-varnished.blend'
_UPSTREAM_DAT = 'trains/mcr-4wheel-open-second.dat'

SPECS = [
    Vehicle(
        name='mcr-4wheel-open-second',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1844,
        intro_month=4,
        retire_year=1856,
        retire_month=6,
        speed=130,
        length=3,
        weight=4,
        axles=2,
        brake_force=0,
        rolling_resistance=19,
        payload=30,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=15,
        cost=167000,
        runningcost=0,
        fixed_cost=348,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['any'],
        constraint_next=['any'],
        payload_by_class=[0, 0, 30],
        comfort_by_class=[0, 0, 24],
        liverytype=['MR-Early', 'London-&-Birmingham-standard', 'LNWR-Early', 'GNR-early', 'LSWR-early', 'Stockton-Darlington-lake', 'ECR-standard', 'MCR-standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='mcr-4wheel-open-second-brake-front',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1844,
        intro_month=4,
        retire_year=1856,
        retire_month=6,
        speed=130,
        length=3,
        weight=4,
        axles=2,
        brake_force=1,
        rolling_resistance=19,
        payload=30,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=15,
        cost=169000,
        runningcost=0,
        fixed_cost=5152,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['any'],
        constraint_next=['any'],
        payload_by_class=[0, 0, 30],
        comfort_by_class=[0, 0, 24],
        liverytype=['MR-Early', 'London-&-Birmingham-standard', 'LNWR-Early', 'GNR-early', 'LSWR-early', 'Stockton-Darlington-lake', 'ECR-standard', 'MCR-standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='mcr-4wheel-open-second-brake-rear',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1844,
        intro_month=4,
        retire_year=1856,
        retire_month=6,
        speed=130,
        length=3,
        weight=4,
        axles=2,
        brake_force=1,
        rolling_resistance=19,
        payload=30,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=15,
        cost=169000,
        runningcost=0,
        fixed_cost=5152,
        bidirectional=1,
        can_lead_from_rear=0,
        payload_by_class=[0, 0, 30],
        comfort_by_class=[0, 0, 24],
        liverytype=['MR-Early', 'London-&-Birmingham-standard', 'LNWR-Early', 'GNR-early', 'LSWR-early', 'Stockton-Darlington-lake', 'ECR-standard', 'MCR-standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
