"""mr-33ft-6-clerestory-carriages."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See Lacy & Dow vol. 1 p. 137
_BLEND = 'trains/Carriages/mr-33ft-6in-clerestory.blend'
_UPSTREAM_DAT = 'trains/mr-33ft-6-clerestory-carriages.dat'

SPECS = [
    Vehicle(
        name='MR-33ft-6in-clerestory-d491',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1897,
        intro_month=3,
        retire_year=1898,
        retire_month=10,
        speed=150,
        length=6,
        weight=13,
        axles=3,
        payload=50,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=25,
        cost=350000,
        runningcost=0,
        fixed_cost=417,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-front', 'MR-6Wheel-Mail', 'MR-31ft-clerestory-kitchen-car-d532', 'MR-6wheel-cove-brake-d530a', 'MR-6wheel-clerestory-brake-d530', 'MR-31ft-clerestory-lavatory-d492', 'MR-33ft-6in-clerestory-d491', 'MR-33ft-6in-clerestory-brake-d503-front', 'MR-clayton-8wheel-arc-roof-third', 'MR-clayton-8wheel-arc-roof-third-lav', 'MR-clayton-8wheel-arc-roof-brake-front', 'MR-clayton-8wheel-arc-roof-brake-lav-front', 'MR-clayton-8wheel-arc-roof-mail', 'MR-clayton-8wheel-clerestory-third', 'MR-clayton-8wheel-clerestory-third-lav', 'MR-clayton-8wheel-clerestory-brake-front', 'MR-clayton-8wheel-clerestory-brake-lav-front', 'MR-clayton-8wheel-clerestory-mail', 'MR-45ft-clerestory-full-brake-d531', 'MR-48ft-arc-d487', 'MR-48ft-arc-brake-d501-front', 'MR-48ft-clerestory-lav-3rd-d486', 'MR-48ft-clerestory-lav-brake-d499-front', 'MR-48ft-clerestory-non-lav-brake-d500-front', 'MR-48ft-clerestory-non-lav', 'MR-48ft-clerestory-mail', 'MR-48ft-clerestory-tpo', 'MR-50ft-arc-lav-d1060', 'MR-50ft-arc-brake-front-d557', 'MR-clayton-12wheel-arc-roof-third', 'MR-clayton-12wheel-arc-roof-third-lav', 'MR-clayton-12wheel-arc-roof-brake-front', 'MR-clayton-12wheel-arc-roof-brake-lav-front', 'MR-clayton-12wheel-clerestory-third', 'MR-clayton-12wheel-clerestory-third-lav', 'MR-clayton-12wheel-clerestory-brake-front', 'MR-clayton-12wheel-clerestory-brake-lav-front', 'MR-54ft-clerestory-lav-d1056', 'MR-54ft-clerestory-lav-brake-d550-front', 'MR-54ft-clerestory-non-lav-d485', 'MR-54ft-clerestory-brake-d497-front', 'MR-54ft-clerestory-mail', 'MR-54ft-clerestory-tpo', 'MR-54ft-eliptical-non-lav-d1277', 'MR-54ft-eliptical-non-lav-brake-front-d1246', 'MR-60ft-clerestory-lav-3rd-d484', 'MR-60ft-clerestory-brake-3rd-d496-front', 'MR-33ft-6in-clerestory-lav-composite-d514', 'MR-48ft-clerestory-lav-composite-d509', 'MR-48ft-clerestory-non-lav-brake-d500-front', 'MR-60ft-clerestory-lav-composite-d539', 'MR-54ft-clerestory-brake-composite-d519a-front', 'MR-54ft-clerestory-lav-brake-composite-d521-front', 'MR-48ft-arc-first-d481', 'MR-48ft-arc-composite-d551', 'MR-50ft-arc-first-d553', 'MR-50ft-arc-composite-d554', 'MR-54ft-eliptical-non-lav-first-d1301', 'MR-54ft-eliptical-non-lav-composite-d1559', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-vestibule-kitchen'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-rear', 'MR-6Wheel-Mail', 'MR-60ft-clerestory-dining-d448', 'MR-6wheel-cove-brake-d530a', 'MR-6wheel-clerestory-brake-d530', 'MR-31ft-clerestory-lavatory-d492', 'MR-33ft-6in-clerestory-d491', 'MR-33ft-6in-clerestory-brake-d503-rear', 'MR-clayton-8wheel-arc-roof-third', 'MR-clayton-8wheel-arc-roof-third-lav', 'MR-clayton-8wheel-arc-roof-brake-rear', 'MR-clayton-8wheel-arc-roof-brake-lav-rear', 'MR-clayton-8wheel-arc-roof-mail', 'MR-clayton-8wheel-clerestory-third', 'MR-clayton-8wheel-clerestory-third-lav', 'MR-clayton-8wheel-clerestory-brake-rear', 'MR-clayton-8wheel-clerestory-brake-lav-rear', 'MR-clayton-8wheel-clerestory-mail', 'MR-45ft-clerestory-full-brake-d531', 'MR-48ft-arc-d487', 'MR-48ft-arc-brake-d501-rear', 'MR-48ft-clerestory-lav-3rd-d486', 'MR-48ft-clerestory-lav-brake-d499-rear', 'MR-48ft-clerestory-non-lav-brake-d500-rear', 'MR-48ft-clerestory-non-lav', 'MR-48ft-clerestory-mail', 'MR-48ft-clerestory-tpo', 'MR-50ft-arc-lav-d1060', 'MR-50ft-arc-brake-rear-d557', 'MR-clayton-12wheel-arc-roof-third', 'MR-clayton-12wheel-arc-roof-third-lav', 'MR-clayton-12wheel-arc-roof-brake-rear', 'MR-clayton-12wheel-arc-roof-brake-lav-rear', 'MR-clayton-12wheel-clerestory-third', 'MR-clayton-12wheel-clerestory-third-lav', 'MR-clayton-12wheel-clerestory-brake-rear', 'MR-clayton-12wheel-clerestory-brake-lav-rear', 'MR-54ft-clerestory-lav-d1056', 'MR-54ft-clerestory-lav-brake-d550-rear', 'MR-54ft-clerestory-non-lav-d485', 'MR-54ft-clerestory-brake-d497-rear', 'MR-54ft-clerestory-mail', 'MR-54ft-clerestory-tpo', 'MR-54ft-eliptical-non-lav-d1277', 'MR-54ft-eliptical-non-lav-brake-rear-d1246', 'MR-60ft-clerestory-lav-3rd-d484', 'MR-60ft-clerestory-brake-3rd-d496-rear', 'MR-33ft-6in-clerestory-lav-composite-d514', 'MR-48ft-clerestory-lav-composite-d509', 'MR-48ft-clerestory-non-lav-brake-d500-rear', 'MR-60ft-clerestory-lav-composite-d539', 'MR-54ft-clerestory-brake-composite-d519a-rear', 'MR-54ft-clerestory-lav-brake-composite-d521-rear', 'MR-48ft-arc-first-d481', 'MR-48ft-arc-composite-d551', 'MR-50ft-arc-first-d553', 'MR-50ft-arc-composite-d554', 'MR-54ft-eliptical-non-lav-first-d1301', 'MR-54ft-eliptical-non-lav-composite-d1559', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-vestibule-kitchen'],
        payload_by_class=[0, 50],
        comfort_by_class=[0, 79],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-33ft-6in-clerestory-lav-composite-d514',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1897,
        intro_month=3,
        retire_year=1898,
        retire_month=10,
        speed=150,
        length=6,
        weight=13,
        axles=3,
        payload=19,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=12,
        cost=365000,
        runningcost=0,
        fixed_cost=418,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-front', 'MR-6Wheel-Mail', 'MR-31ft-clerestory-kitchen-car-d532', 'MR-6wheel-cove-brake-d530a', 'MR-6wheel-clerestory-brake-d530', 'MR-31ft-clerestory-lavatory-d492', 'MR-33ft-6in-clerestory-d491', 'MR-33ft-6in-clerestory-brake-d503-front', 'MR-clayton-8wheel-arc-roof-third', 'MR-clayton-8wheel-arc-roof-third-lav', 'MR-clayton-8wheel-arc-roof-brake-front', 'MR-clayton-8wheel-arc-roof-brake-lav-front', 'MR-clayton-8wheel-arc-roof-mail', 'MR-clayton-8wheel-clerestory-third', 'MR-clayton-8wheel-clerestory-third-lav', 'MR-clayton-8wheel-clerestory-brake-front', 'MR-clayton-8wheel-clerestory-brake-lav-front', 'MR-clayton-8wheel-clerestory-mail', 'MR-45ft-clerestory-full-brake-d531', 'MR-48ft-arc-d487', 'MR-48ft-arc-brake-d501-front', 'MR-48ft-clerestory-lav-3rd-d486', 'MR-48ft-clerestory-lav-brake-d499-front', 'MR-48ft-clerestory-non-lav-brake-d500-front', 'MR-48ft-clerestory-non-lav', 'MR-48ft-clerestory-mail', 'MR-48ft-clerestory-tpo', 'MR-50ft-arc-lav-d1060', 'MR-50ft-arc-brake-front-d557', 'MR-clayton-12wheel-arc-roof-third', 'MR-clayton-12wheel-arc-roof-third-lav', 'MR-clayton-12wheel-arc-roof-brake-front', 'MR-clayton-12wheel-arc-roof-brake-lav-front', 'MR-clayton-12wheel-clerestory-third', 'MR-clayton-12wheel-clerestory-third-lav', 'MR-clayton-12wheel-clerestory-brake-front', 'MR-clayton-12wheel-clerestory-brake-lav-front', 'MR-54ft-clerestory-lav-d1056', 'MR-54ft-clerestory-lav-brake-d550-front', 'MR-54ft-clerestory-non-lav-d485', 'MR-54ft-clerestory-brake-d497-front', 'MR-54ft-clerestory-mail', 'MR-54ft-clerestory-tpo', 'MR-54ft-eliptical-non-lav-d1277', 'MR-54ft-eliptical-non-lav-brake-front-d1246', 'MR-60ft-clerestory-lav-3rd-d484', 'MR-60ft-clerestory-brake-3rd-d496-front', 'MR-33ft-6in-clerestory-lav-composite-d514', 'MR-48ft-clerestory-lav-composite-d509', 'MR-48ft-clerestory-non-lav-brake-d500-front', 'MR-60ft-clerestory-lav-composite-d539', 'MR-54ft-clerestory-brake-composite-d519a-front', 'MR-54ft-clerestory-lav-brake-composite-d521-front', 'MR-48ft-arc-first-d481', 'MR-48ft-arc-composite-d551', 'MR-50ft-arc-first-d553', 'MR-50ft-arc-composite-d554', 'MR-54ft-eliptical-non-lav-first-d1301', 'MR-54ft-eliptical-non-lav-composite-d1559', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-vestibule-kitchen'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-rear', 'MR-6Wheel-Mail', 'MR-60ft-clerestory-dining-d448', 'MR-6wheel-cove-brake-d530a', 'MR-6wheel-clerestory-brake-d530', 'MR-31ft-clerestory-lavatory-d492', 'MR-33ft-6in-clerestory-d491', 'MR-33ft-6in-clerestory-brake-d503-rear', 'MR-clayton-8wheel-arc-roof-third', 'MR-clayton-8wheel-arc-roof-third-lav', 'MR-clayton-8wheel-arc-roof-brake-rear', 'MR-clayton-8wheel-arc-roof-brake-lav-rear', 'MR-clayton-8wheel-arc-roof-mail', 'MR-clayton-8wheel-clerestory-third', 'MR-clayton-8wheel-clerestory-third-lav', 'MR-clayton-8wheel-clerestory-brake-rear', 'MR-clayton-8wheel-clerestory-brake-lav-rear', 'MR-clayton-8wheel-clerestory-mail', 'MR-45ft-clerestory-full-brake-d531', 'MR-48ft-arc-d487', 'MR-48ft-arc-brake-d501-rear', 'MR-48ft-clerestory-lav-3rd-d486', 'MR-48ft-clerestory-lav-brake-d499-rear', 'MR-48ft-clerestory-non-lav-brake-d500-rear', 'MR-48ft-clerestory-non-lav', 'MR-48ft-clerestory-mail', 'MR-48ft-clerestory-tpo', 'MR-50ft-arc-lav-d1060', 'MR-50ft-arc-brake-rear-d557', 'MR-clayton-12wheel-arc-roof-third', 'MR-clayton-12wheel-arc-roof-third-lav', 'MR-clayton-12wheel-arc-roof-brake-rear', 'MR-clayton-12wheel-arc-roof-brake-lav-rear', 'MR-clayton-12wheel-clerestory-third', 'MR-clayton-12wheel-clerestory-third-lav', 'MR-clayton-12wheel-clerestory-brake-rear', 'MR-clayton-12wheel-clerestory-brake-lav-rear', 'MR-54ft-clerestory-lav-d1056', 'MR-54ft-clerestory-lav-brake-d550-rear', 'MR-54ft-clerestory-non-lav-d485', 'MR-54ft-clerestory-brake-d497-rear', 'MR-54ft-clerestory-mail', 'MR-54ft-clerestory-tpo', 'MR-54ft-eliptical-non-lav-d1277', 'MR-54ft-eliptical-non-lav-brake-rear-d1246', 'MR-60ft-clerestory-lav-3rd-d484', 'MR-60ft-clerestory-brake-3rd-d496-rear', 'MR-33ft-6in-clerestory-lav-composite-d514', 'MR-48ft-clerestory-lav-composite-d509', 'MR-48ft-clerestory-non-lav-brake-d500-rear', 'MR-60ft-clerestory-lav-composite-d539', 'MR-54ft-clerestory-brake-composite-d519a-rear', 'MR-54ft-clerestory-lav-brake-composite-d521-rear', 'MR-48ft-arc-first-d481', 'MR-48ft-arc-composite-d551', 'MR-50ft-arc-first-d553', 'MR-50ft-arc-composite-d554', 'MR-54ft-eliptical-non-lav-first-d1301', 'MR-54ft-eliptical-non-lav-composite-d1559', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-vestibule-kitchen'],
        payload_by_class=[0, 19, 0, 11],
        comfort_by_class=[0, 86, 0, 106],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-33ft-6in-clerestory-brake-d503-front',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1897,
        intro_month=3,
        retire_year=1898,
        retire_month=10,
        speed=150,
        length=6,
        weight=13,
        axles=3,
        payload=30,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=15,
        cost=350000,
        runningcost=0,
        fixed_cost=5217,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-rear', 'MR-6Wheel-Mail', 'MR-60ft-clerestory-dining-d448', 'MR-6wheel-cove-brake-d530a', 'MR-6wheel-clerestory-brake-d530', 'MR-31ft-clerestory-lavatory-d492', 'MR-33ft-6in-clerestory-d491', 'MR-33ft-6in-clerestory-brake-d503-rear', 'MR-clayton-8wheel-arc-roof-third', 'MR-clayton-8wheel-arc-roof-third-lav', 'MR-clayton-8wheel-arc-roof-brake-rear', 'MR-clayton-8wheel-arc-roof-brake-lav-rear', 'MR-clayton-8wheel-arc-roof-mail', 'MR-clayton-8wheel-clerestory-third', 'MR-clayton-8wheel-clerestory-third-lav', 'MR-clayton-8wheel-clerestory-brake-rear', 'MR-clayton-8wheel-clerestory-brake-lav-rear', 'MR-clayton-8wheel-clerestory-mail', 'MR-45ft-clerestory-full-brake-d531', 'MR-48ft-arc-d487', 'MR-48ft-arc-brake-d501-rear', 'MR-48ft-clerestory-lav-3rd-d486', 'MR-48ft-clerestory-lav-brake-d499-rear', 'MR-48ft-clerestory-non-lav-brake-d500-rear', 'MR-48ft-clerestory-non-lav', 'MR-48ft-clerestory-mail', 'MR-48ft-clerestory-tpo', 'MR-50ft-arc-lav-d1060', 'MR-50ft-arc-brake-rear-d557', 'MR-clayton-12wheel-arc-roof-third', 'MR-clayton-12wheel-arc-roof-third-lav', 'MR-clayton-12wheel-arc-roof-brake-rear', 'MR-clayton-12wheel-arc-roof-brake-lav-rear', 'MR-clayton-12wheel-clerestory-third', 'MR-clayton-12wheel-clerestory-third-lav', 'MR-clayton-12wheel-clerestory-brake-rear', 'MR-clayton-12wheel-clerestory-brake-lav-rear', 'MR-54ft-clerestory-lav-d1056', 'MR-54ft-clerestory-lav-brake-d550-rear', 'MR-54ft-clerestory-non-lav-d485', 'MR-54ft-clerestory-brake-d497-rear', 'MR-54ft-clerestory-mail', 'MR-54ft-clerestory-tpo', 'MR-54ft-eliptical-non-lav-d1277', 'MR-54ft-eliptical-non-lav-brake-rear-d1246', 'MR-60ft-clerestory-lav-3rd-d484', 'MR-60ft-clerestory-brake-3rd-d496-rear', 'MR-33ft-6in-clerestory-lav-composite-d514', 'MR-48ft-clerestory-lav-composite-d509', 'MR-48ft-clerestory-non-lav-brake-d500-rear', 'MR-60ft-clerestory-lav-composite-d539', 'MR-54ft-clerestory-brake-composite-d519a-rear', 'MR-54ft-clerestory-lav-brake-composite-d521-rear', 'MR-48ft-arc-first-d481', 'MR-48ft-arc-composite-d551', 'MR-50ft-arc-first-d553', 'MR-50ft-arc-composite-d554', 'MR-54ft-eliptical-non-lav-first-d1301', 'MR-54ft-eliptical-non-lav-composite-d1559', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-vestibule-kitchen', 'none'],
        payload_by_class=[0, 30],
        comfort_by_class=[0, 79],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-33ft-6in-clerestory-brake-d503-rear',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1897,
        intro_month=3,
        retire_year=1898,
        retire_month=10,
        speed=150,
        length=6,
        weight=13,
        axles=3,
        payload=30,
        min_loading_time=17,
        max_loading_time=47,
        overcrowded_capacity=15,
        cost=350000,
        runningcost=0,
        fixed_cost=5217,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-front', 'MR-6Wheel-Mail', 'MR-31ft-clerestory-kitchen-car-d532', 'MR-6wheel-cove-brake-d530a', 'MR-6wheel-clerestory-brake-d530', 'MR-31ft-clerestory-lavatory-d492', 'MR-33ft-6in-clerestory-d491', 'MR-33ft-6in-clerestory-brake-d503-front', 'MR-clayton-8wheel-arc-roof-third', 'MR-clayton-8wheel-arc-roof-third-lav', 'MR-clayton-8wheel-arc-roof-brake-front', 'MR-clayton-8wheel-arc-roof-brake-lav-front', 'MR-clayton-8wheel-arc-roof-mail', 'MR-clayton-8wheel-clerestory-third', 'MR-clayton-8wheel-clerestory-third-lav', 'MR-clayton-8wheel-clerestory-brake-front', 'MR-clayton-8wheel-clerestory-brake-lav-front', 'MR-clayton-8wheel-clerestory-mail', 'MR-45ft-clerestory-full-brake-d531', 'MR-48ft-arc-d487', 'MR-48ft-arc-brake-d501-front', 'MR-48ft-clerestory-lav-3rd-d486', 'MR-48ft-clerestory-lav-brake-d499-front', 'MR-48ft-clerestory-non-lav-brake-d500-front', 'MR-48ft-clerestory-non-lav', 'MR-48ft-clerestory-mail', 'MR-48ft-clerestory-tpo', 'MR-50ft-arc-lav-d1060', 'MR-50ft-arc-brake-front-d557', 'MR-clayton-12wheel-arc-roof-third', 'MR-clayton-12wheel-arc-roof-third-lav', 'MR-clayton-12wheel-arc-roof-brake-front', 'MR-clayton-12wheel-arc-roof-brake-lav-front', 'MR-clayton-12wheel-clerestory-third', 'MR-clayton-12wheel-clerestory-third-lav', 'MR-clayton-12wheel-clerestory-brake-front', 'MR-clayton-12wheel-clerestory-brake-lav-front', 'MR-54ft-clerestory-lav-d1056', 'MR-54ft-clerestory-lav-brake-d550-front', 'MR-54ft-clerestory-non-lav-d485', 'MR-54ft-clerestory-brake-d497-front', 'MR-54ft-clerestory-mail', 'MR-54ft-clerestory-tpo', 'MR-54ft-eliptical-non-lav-d1277', 'MR-54ft-eliptical-non-lav-brake-front-d1246', 'MR-60ft-clerestory-lav-3rd-d484', 'MR-60ft-clerestory-brake-3rd-d496-front', 'MR-33ft-6in-clerestory-lav-composite-d514', 'MR-48ft-clerestory-lav-composite-d509', 'MR-48ft-clerestory-non-lav-brake-d500-front', 'MR-60ft-clerestory-lav-composite-d539', 'MR-54ft-clerestory-brake-composite-d519a-front', 'MR-54ft-clerestory-lav-brake-composite-d521-front', 'MR-48ft-arc-first-d481', 'MR-48ft-arc-composite-d551', 'MR-50ft-arc-first-d553', 'MR-50ft-arc-composite-d554', 'MR-54ft-eliptical-non-lav-first-d1301', 'MR-54ft-eliptical-non-lav-composite-d1559', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-vestibule-kitchen'],
        payload_by_class=[0, 30],
        comfort_by_class=[0, 79],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
