"""mr-48ft-arc-carriages."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See Lacy & Dow vol. 2 pp. 273-6
_BLEND = 'trains/Carriages/mr-48ft-arc.blend'
_UPSTREAM_DAT = 'trains/mr-48ft-arc-carriages.dat'

SPECS = [
    Vehicle(
        name='MR-48ft-arc-d487',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1902,
        intro_month=11,
        retire_year=1910,
        retire_month=4,
        speed=140,
        length=8,
        weight=24.5,
        axles=4,
        payload=80,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=40,
        cost=440000,
        runningcost=0,
        fixed_cost=524,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-front', 'MR-6Wheel-Mail', 'MR-31ft-clerestory-kitchen-car-d532', 'MR-6wheel-cove-brake-d530a', 'MR-6wheel-clerestory-brake-d530', 'MR-31ft-clerestory-lavatory-d492', 'MR-33ft-6in-clerestory-d491', 'MR-33ft-6in-clerestory-brake-d503-front', 'MR-clayton-8wheel-arc-roof-third', 'MR-clayton-8wheel-arc-roof-third-lav', 'MR-clayton-8wheel-arc-roof-brake-front', 'MR-clayton-8wheel-arc-roof-brake-lav-front', 'MR-clayton-8wheel-arc-roof-mail', 'MR-clayton-8wheel-clerestory-third', 'MR-clayton-8wheel-clerestory-third-lav', 'MR-clayton-8wheel-clerestory-brake-front', 'MR-clayton-8wheel-clerestory-brake-lav-front', 'MR-clayton-8wheel-clerestory-mail', 'MR-45ft-clerestory-full-brake-d531', 'MR-48ft-arc-d487', 'MR-48ft-arc-brake-d501-front', 'MR-48ft-clerestory-lav-3rd-d486', 'MR-48ft-clerestory-lav-brake-d499-front', 'MR-48ft-clerestory-non-lav-brake-d500-front', 'MR-48ft-clerestory-non-lav', 'MR-48ft-clerestory-mail', 'MR-48ft-clerestory-tpo', 'MR-50ft-arc-lav-d1060', 'MR-50ft-arc-brake-front-d557', 'MR-clayton-12wheel-arc-roof-third', 'MR-clayton-12wheel-arc-roof-third-lav', 'MR-clayton-12wheel-arc-roof-brake-front', 'MR-clayton-12wheel-arc-roof-brake-lav-front', 'MR-clayton-12wheel-clerestory-third', 'MR-clayton-12wheel-clerestory-third-lav', 'MR-clayton-12wheel-clerestory-brake-front', 'MR-clayton-12wheel-clerestory-brake-lav-front', 'MR-54ft-clerestory-lav-d1056', 'MR-54ft-clerestory-lav-brake-d550-front', 'MR-54ft-clerestory-non-lav-d485', 'MR-54ft-clerestory-brake-d497-front', 'MR-54ft-clerestory-mail', 'MR-54ft-clerestory-tpo', 'MR-54ft-eliptical-non-lav-d1277', 'MR-54ft-eliptical-non-lav-brake-front-d1246', 'MR-60ft-clerestory-lav-3rd-d484', 'MR-60ft-clerestory-brake-3rd-d496-front', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'MR-50ft-arc-non-lav-d555', 'MR-33ft-6in-clerestory-lav-composite-d514', 'MR-48ft-clerestory-lav-composite-d509', 'MR-48ft-clerestory-non-lav-brake-d500-front', 'MR-60ft-clerestory-lav-composite-d539', 'MR-54ft-clerestory-brake-composite-d519a-front', 'MR-54ft-clerestory-lav-brake-composite-d521-front', 'MR-48ft-arc-first-d481', 'MR-48ft-arc-composite-d551', 'MR-50ft-arc-first-d553', 'MR-50ft-arc-composite-d554', 'MR-54ft-eliptical-non-lav-first-d1301', 'MR-54ft-eliptical-non-lav-composite-d1559', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-vestibule-kitchen', 'MR-clayton-12wheel-arc-roof-composite', 'MR-clayton-12wheel-arc-roof-composite-lav', 'MR-clayton-8wheel-arc-roof-composite-lav', 'MR-clayton-8wheel-arc-roof-composite', 'MR-clayton-8wheel-clerestory-composite', 'MR-clayton-8wheel-clerestory-composite-lav', 'MR-clayton-12wheel-clerestory-composite', 'MR-clayton-12wheel-clerestory-composite-lav'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-rear', 'MR-6Wheel-Mail', 'MR-60ft-clerestory-dining-d448', 'MR-6wheel-cove-brake-d530a', 'MR-6wheel-clerestory-brake-d530', 'MR-31ft-clerestory-lavatory-d492', 'MR-33ft-6in-clerestory-d491', 'MR-33ft-6in-clerestory-brake-d503-rear', 'MR-clayton-8wheel-arc-roof-third', 'MR-clayton-8wheel-arc-roof-third-lav', 'MR-clayton-8wheel-arc-roof-brake-rear', 'MR-clayton-8wheel-arc-roof-brake-lav-rear', 'MR-clayton-8wheel-arc-roof-mail', 'MR-clayton-8wheel-clerestory-third', 'MR-clayton-8wheel-clerestory-third-lav', 'MR-clayton-8wheel-clerestory-brake-rear', 'MR-clayton-8wheel-clerestory-brake-lav-rear', 'MR-clayton-8wheel-clerestory-mail', 'MR-45ft-clerestory-full-brake-d531', 'MR-48ft-arc-d487', 'MR-48ft-arc-brake-d501-rear', 'MR-48ft-clerestory-lav-3rd-d486', 'MR-48ft-clerestory-lav-brake-d499-rear', 'MR-48ft-clerestory-non-lav-brake-d500-rear', 'MR-48ft-clerestory-non-lav', 'MR-48ft-clerestory-mail', 'MR-48ft-clerestory-tpo', 'MR-50ft-arc-lav-d1060', 'MR-50ft-arc-brake-rear-d557', 'MR-clayton-12wheel-arc-roof-third', 'MR-clayton-12wheel-arc-roof-third-lav', 'MR-clayton-12wheel-arc-roof-brake-rear', 'MR-clayton-12wheel-arc-roof-brake-lav-rear', 'MR-clayton-12wheel-clerestory-third', 'MR-clayton-12wheel-clerestory-third-lav', 'MR-clayton-12wheel-clerestory-brake-rear', 'MR-clayton-12wheel-clerestory-brake-lav-rear', 'MR-54ft-clerestory-lav-d1056', 'MR-54ft-clerestory-lav-brake-d550-rear', 'MR-54ft-clerestory-non-lav-d485', 'MR-54ft-clerestory-brake-d497-rear', 'MR-54ft-clerestory-mail', 'MR-54ft-clerestory-tpo', 'MR-54ft-eliptical-non-lav-d1277', 'MR-54ft-eliptical-non-lav-brake-rear-d1246', 'MR-60ft-clerestory-lav-3rd-d484', 'MR-60ft-clerestory-brake-3rd-d496-rear', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'MR-50ft-arc-non-lav-d555', 'MR-33ft-6in-clerestory-lav-composite-d514', 'MR-48ft-clerestory-lav-composite-d509', 'MR-48ft-clerestory-non-lav-brake-d500-rear', 'MR-60ft-clerestory-lav-composite-d539', 'MR-54ft-clerestory-brake-composite-d519a-rear', 'MR-54ft-clerestory-lav-brake-composite-d521-rear', 'MR-48ft-arc-first-d481', 'MR-48ft-arc-composite-d551', 'MR-50ft-arc-first-d553', 'MR-50ft-arc-composite-d554', 'MR-54ft-eliptical-non-lav-first-d1301', 'MR-54ft-eliptical-non-lav-composite-d1559', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-vestibule-kitchen', 'MR-clayton-12wheel-arc-roof-composite', 'MR-clayton-12wheel-arc-roof-composite-lav', 'MR-clayton-8wheel-arc-roof-composite-lav', 'MR-clayton-8wheel-arc-roof-composite', 'MR-clayton-8wheel-clerestory-composite', 'MR-clayton-8wheel-clerestory-composite-lav', 'MR-clayton-12wheel-clerestory-composite', 'MR-clayton-12wheel-clerestory-composite-lav'],
        payload_by_class=[0, 80, 0, 0],
        comfort_by_class=[0, 73, 0, 82],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-48ft-arc-first-d481',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1902,
        intro_month=11,
        retire_year=1910,
        retire_month=4,
        speed=140,
        length=8,
        weight=24.5,
        axles=4,
        payload=42,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=0,
        cost=450000,
        runningcost=0,
        fixed_cost=525,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-front', 'MR-6Wheel-Mail', 'MR-31ft-clerestory-kitchen-car-d532', 'MR-6wheel-cove-brake-d530a', 'MR-6wheel-clerestory-brake-d530', 'MR-31ft-clerestory-lavatory-d492', 'MR-33ft-6in-clerestory-d491', 'MR-33ft-6in-clerestory-brake-d503-front', 'MR-clayton-8wheel-arc-roof-third', 'MR-clayton-8wheel-arc-roof-third-lav', 'MR-clayton-8wheel-arc-roof-brake-front', 'MR-clayton-8wheel-arc-roof-brake-lav-front', 'MR-clayton-8wheel-arc-roof-mail', 'MR-clayton-8wheel-clerestory-third', 'MR-clayton-8wheel-clerestory-third-lav', 'MR-clayton-8wheel-clerestory-brake-front', 'MR-clayton-8wheel-clerestory-brake-lav-front', 'MR-clayton-8wheel-clerestory-mail', 'MR-45ft-clerestory-full-brake-d531', 'MR-48ft-arc-d487', 'MR-48ft-arc-brake-d501-front', 'MR-48ft-clerestory-lav-3rd-d486', 'MR-48ft-clerestory-lav-brake-d499-front', 'MR-48ft-clerestory-non-lav-brake-d500-front', 'MR-48ft-clerestory-non-lav', 'MR-48ft-clerestory-mail', 'MR-48ft-clerestory-tpo', 'MR-50ft-arc-lav-d1060', 'MR-50ft-arc-brake-front-d557', 'MR-clayton-12wheel-arc-roof-third', 'MR-clayton-12wheel-arc-roof-third-lav', 'MR-clayton-12wheel-arc-roof-brake-front', 'MR-clayton-12wheel-arc-roof-brake-lav-front', 'MR-clayton-12wheel-clerestory-third', 'MR-clayton-12wheel-clerestory-third-lav', 'MR-clayton-12wheel-clerestory-brake-front', 'MR-clayton-12wheel-clerestory-brake-lav-front', 'MR-54ft-clerestory-lav-d1056', 'MR-54ft-clerestory-lav-brake-d550-front', 'MR-54ft-clerestory-non-lav-d485', 'MR-54ft-clerestory-brake-d497-front', 'MR-54ft-clerestory-mail', 'MR-54ft-clerestory-tpo', 'MR-54ft-eliptical-non-lav-d1277', 'MR-54ft-eliptical-non-lav-brake-front-d1246', 'MR-60ft-clerestory-lav-3rd-d484', 'MR-60ft-clerestory-brake-3rd-d496-front', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'MR-50ft-arc-non-lav-d555', 'MR-33ft-6in-clerestory-lav-composite-d514', 'MR-48ft-clerestory-lav-composite-d509', 'MR-48ft-clerestory-non-lav-brake-d500-front', 'MR-60ft-clerestory-lav-composite-d539', 'MR-54ft-clerestory-brake-composite-d519a-front', 'MR-54ft-clerestory-lav-brake-composite-d521-front', 'MR-48ft-arc-first-d481', 'MR-48ft-arc-composite-d551', 'MR-50ft-arc-first-d553', 'MR-50ft-arc-composite-d554', 'MR-54ft-eliptical-non-lav-first-d1301', 'MR-54ft-eliptical-non-lav-composite-d1559', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-vestibule-kitchen', 'MR-clayton-12wheel-arc-roof-composite', 'MR-clayton-12wheel-arc-roof-composite-lav', 'MR-clayton-8wheel-arc-roof-composite-lav', 'MR-clayton-8wheel-arc-roof-composite', 'MR-clayton-8wheel-clerestory-composite', 'MR-clayton-8wheel-clerestory-composite-lav', 'MR-clayton-12wheel-clerestory-composite', 'MR-clayton-12wheel-clerestory-composite-lav'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-rear', 'MR-6Wheel-Mail', 'MR-60ft-clerestory-dining-d448', 'MR-6wheel-cove-brake-d530a', 'MR-6wheel-clerestory-brake-d530', 'MR-31ft-clerestory-lavatory-d492', 'MR-33ft-6in-clerestory-d491', 'MR-33ft-6in-clerestory-brake-d503-rear', 'MR-clayton-8wheel-arc-roof-third', 'MR-clayton-8wheel-arc-roof-third-lav', 'MR-clayton-8wheel-arc-roof-brake-rear', 'MR-clayton-8wheel-arc-roof-brake-lav-rear', 'MR-clayton-8wheel-arc-roof-mail', 'MR-clayton-8wheel-clerestory-third', 'MR-clayton-8wheel-clerestory-third-lav', 'MR-clayton-8wheel-clerestory-brake-rear', 'MR-clayton-8wheel-clerestory-brake-lav-rear', 'MR-clayton-8wheel-clerestory-mail', 'MR-45ft-clerestory-full-brake-d531', 'MR-48ft-arc-d487', 'MR-48ft-arc-brake-d501-rear', 'MR-48ft-clerestory-lav-3rd-d486', 'MR-48ft-clerestory-lav-brake-d499-rear', 'MR-48ft-clerestory-non-lav-brake-d500-rear', 'MR-48ft-clerestory-non-lav', 'MR-48ft-clerestory-mail', 'MR-48ft-clerestory-tpo', 'MR-50ft-arc-lav-d1060', 'MR-50ft-arc-brake-rear-d557', 'MR-clayton-12wheel-arc-roof-third', 'MR-clayton-12wheel-arc-roof-third-lav', 'MR-clayton-12wheel-arc-roof-brake-rear', 'MR-clayton-12wheel-arc-roof-brake-lav-rear', 'MR-clayton-12wheel-clerestory-third', 'MR-clayton-12wheel-clerestory-third-lav', 'MR-clayton-12wheel-clerestory-brake-rear', 'MR-clayton-12wheel-clerestory-brake-lav-rear', 'MR-54ft-clerestory-lav-d1056', 'MR-54ft-clerestory-lav-brake-d550-rear', 'MR-54ft-clerestory-non-lav-d485', 'MR-54ft-clerestory-brake-d497-rear', 'MR-54ft-clerestory-mail', 'MR-54ft-clerestory-tpo', 'MR-54ft-eliptical-non-lav-d1277', 'MR-54ft-eliptical-non-lav-brake-rear-d1246', 'MR-60ft-clerestory-lav-3rd-d484', 'MR-60ft-clerestory-brake-3rd-d496-rear', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'MR-50ft-arc-non-lav-d555', 'MR-33ft-6in-clerestory-lav-composite-d514', 'MR-48ft-clerestory-lav-composite-d509', 'MR-48ft-clerestory-non-lav-brake-d500-rear', 'MR-60ft-clerestory-lav-composite-d539', 'MR-54ft-clerestory-brake-composite-d519a-rear', 'MR-54ft-clerestory-lav-brake-composite-d521-rear', 'MR-48ft-arc-first-d481', 'MR-48ft-arc-composite-d551', 'MR-50ft-arc-first-d553', 'MR-50ft-arc-composite-d554', 'MR-54ft-eliptical-non-lav-first-d1301', 'MR-54ft-eliptical-non-lav-composite-d1559', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-vestibule-kitchen', 'MR-clayton-12wheel-arc-roof-composite', 'MR-clayton-12wheel-arc-roof-composite-lav', 'MR-clayton-8wheel-arc-roof-composite-lav', 'MR-clayton-8wheel-arc-roof-composite', 'MR-clayton-8wheel-clerestory-composite', 'MR-clayton-8wheel-clerestory-composite-lav', 'MR-clayton-12wheel-clerestory-composite', 'MR-clayton-12wheel-clerestory-composite-lav'],
        payload_by_class=[0, 0, 0, 42],
        comfort_by_class=[0, 73, 0, 82],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-48ft-arc-composite-d551',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1902,
        intro_month=11,
        retire_year=1910,
        retire_month=4,
        speed=140,
        length=8,
        weight=24.5,
        axles=4,
        payload=30,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=15,
        cost=447000,
        runningcost=0,
        fixed_cost=525,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-front', 'MR-6Wheel-Mail', 'MR-31ft-clerestory-kitchen-car-d532', 'MR-6wheel-cove-brake-d530a', 'MR-6wheel-clerestory-brake-d530', 'MR-31ft-clerestory-lavatory-d492', 'MR-33ft-6in-clerestory-d491', 'MR-33ft-6in-clerestory-brake-d503-front', 'MR-clayton-8wheel-arc-roof-third', 'MR-clayton-8wheel-arc-roof-third-lav', 'MR-clayton-8wheel-arc-roof-brake-front', 'MR-clayton-8wheel-arc-roof-brake-lav-front', 'MR-clayton-8wheel-arc-roof-mail', 'MR-clayton-8wheel-clerestory-third', 'MR-clayton-8wheel-clerestory-third-lav', 'MR-clayton-8wheel-clerestory-brake-front', 'MR-clayton-8wheel-clerestory-brake-lav-front', 'MR-clayton-8wheel-clerestory-mail', 'MR-45ft-clerestory-full-brake-d531', 'MR-48ft-arc-d487', 'MR-48ft-arc-brake-d501-front', 'MR-48ft-clerestory-lav-3rd-d486', 'MR-48ft-clerestory-lav-brake-d499-front', 'MR-48ft-clerestory-non-lav-brake-d500-front', 'MR-48ft-clerestory-non-lav', 'MR-48ft-clerestory-mail', 'MR-48ft-clerestory-tpo', 'MR-50ft-arc-lav-d1060', 'MR-50ft-arc-brake-front-d557', 'MR-clayton-12wheel-arc-roof-third', 'MR-clayton-12wheel-arc-roof-third-lav', 'MR-clayton-12wheel-arc-roof-brake-front', 'MR-clayton-12wheel-arc-roof-brake-lav-front', 'MR-clayton-12wheel-clerestory-third', 'MR-clayton-12wheel-clerestory-third-lav', 'MR-clayton-12wheel-clerestory-brake-front', 'MR-clayton-12wheel-clerestory-brake-lav-front', 'MR-54ft-clerestory-lav-d1056', 'MR-54ft-clerestory-lav-brake-d550-front', 'MR-54ft-clerestory-non-lav-d485', 'MR-54ft-clerestory-brake-d497-front', 'MR-54ft-clerestory-mail', 'MR-54ft-clerestory-tpo', 'MR-54ft-eliptical-non-lav-d1277', 'MR-54ft-eliptical-non-lav-brake-front-d1246', 'MR-60ft-clerestory-lav-3rd-d484', 'MR-60ft-clerestory-brake-3rd-d496-front', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'MR-50ft-arc-non-lav-d555', 'MR-33ft-6in-clerestory-lav-composite-d514', 'MR-48ft-clerestory-lav-composite-d509', 'MR-48ft-clerestory-non-lav-brake-d500-front', 'MR-60ft-clerestory-lav-composite-d539', 'MR-54ft-clerestory-brake-composite-d519a-front', 'MR-54ft-clerestory-lav-brake-composite-d521-front', 'MR-48ft-arc-first-d481', 'MR-48ft-arc-composite-d551', 'MR-50ft-arc-first-d553', 'MR-50ft-arc-composite-d554', 'MR-54ft-eliptical-non-lav-first-d1301', 'MR-54ft-eliptical-non-lav-composite-d1559', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-vestibule-kitchen', 'MR-clayton-12wheel-arc-roof-composite', 'MR-clayton-12wheel-arc-roof-composite-lav', 'MR-clayton-8wheel-arc-roof-composite-lav', 'MR-clayton-8wheel-arc-roof-composite', 'MR-clayton-8wheel-clerestory-composite', 'MR-clayton-8wheel-clerestory-composite-lav', 'MR-clayton-12wheel-clerestory-composite', 'MR-clayton-12wheel-clerestory-composite-lav'],
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-rear', 'MR-6Wheel-Mail', 'MR-60ft-clerestory-dining-d448', 'MR-6wheel-cove-brake-d530a', 'MR-6wheel-clerestory-brake-d530', 'MR-31ft-clerestory-lavatory-d492', 'MR-33ft-6in-clerestory-d491', 'MR-33ft-6in-clerestory-brake-d503-rear', 'MR-clayton-8wheel-arc-roof-third', 'MR-clayton-8wheel-arc-roof-third-lav', 'MR-clayton-8wheel-arc-roof-brake-rear', 'MR-clayton-8wheel-arc-roof-brake-lav-rear', 'MR-clayton-8wheel-arc-roof-mail', 'MR-clayton-8wheel-clerestory-third', 'MR-clayton-8wheel-clerestory-third-lav', 'MR-clayton-8wheel-clerestory-brake-rear', 'MR-clayton-8wheel-clerestory-brake-lav-rear', 'MR-clayton-8wheel-clerestory-mail', 'MR-45ft-clerestory-full-brake-d531', 'MR-48ft-arc-d487', 'MR-48ft-arc-brake-d501-rear', 'MR-48ft-clerestory-lav-3rd-d486', 'MR-48ft-clerestory-lav-brake-d499-rear', 'MR-48ft-clerestory-non-lav-brake-d500-rear', 'MR-48ft-clerestory-non-lav', 'MR-48ft-clerestory-mail', 'MR-48ft-clerestory-tpo', 'MR-50ft-arc-lav-d1060', 'MR-50ft-arc-brake-rear-d557', 'MR-clayton-12wheel-arc-roof-third', 'MR-clayton-12wheel-arc-roof-third-lav', 'MR-clayton-12wheel-arc-roof-brake-rear', 'MR-clayton-12wheel-arc-roof-brake-lav-rear', 'MR-clayton-12wheel-clerestory-third', 'MR-clayton-12wheel-clerestory-third-lav', 'MR-clayton-12wheel-clerestory-brake-rear', 'MR-clayton-12wheel-clerestory-brake-lav-rear', 'MR-54ft-clerestory-lav-d1056', 'MR-54ft-clerestory-lav-brake-d550-rear', 'MR-54ft-clerestory-non-lav-d485', 'MR-54ft-clerestory-brake-d497-rear', 'MR-54ft-clerestory-mail', 'MR-54ft-clerestory-tpo', 'MR-54ft-eliptical-non-lav-d1277', 'MR-54ft-eliptical-non-lav-brake-rear-d1246', 'MR-60ft-clerestory-lav-3rd-d484', 'MR-60ft-clerestory-brake-3rd-d496-rear', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'MR-50ft-arc-non-lav-d555', 'MR-33ft-6in-clerestory-lav-composite-d514', 'MR-48ft-clerestory-lav-composite-d509', 'MR-48ft-clerestory-non-lav-brake-d500-rear', 'MR-60ft-clerestory-lav-composite-d539', 'MR-54ft-clerestory-brake-composite-d519a-rear', 'MR-54ft-clerestory-lav-brake-composite-d521-rear', 'MR-48ft-arc-first-d481', 'MR-48ft-arc-composite-d551', 'MR-50ft-arc-first-d553', 'MR-50ft-arc-composite-d554', 'MR-54ft-eliptical-non-lav-first-d1301', 'MR-54ft-eliptical-non-lav-composite-d1559', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-vestibule-kitchen', 'MR-clayton-12wheel-arc-roof-composite', 'MR-clayton-12wheel-arc-roof-composite-lav', 'MR-clayton-8wheel-arc-roof-composite-lav', 'MR-clayton-8wheel-arc-roof-composite', 'MR-clayton-8wheel-clerestory-composite', 'MR-clayton-8wheel-clerestory-composite-lav', 'MR-clayton-12wheel-clerestory-composite', 'MR-clayton-12wheel-clerestory-composite-lav'],
        payload_by_class=[0, 30, 0, 24],
        comfort_by_class=[0, 73, 0, 82],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-48ft-arc-brake-d501-front',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1902,
        intro_month=11,
        retire_year=1910,
        retire_month=4,
        speed=140,
        length=8,
        weight=24.3,
        axles=4,
        payload=60,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=30,
        cost=432000,
        runningcost=0,
        fixed_cost=5314,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-rear-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-rear', 'MR-6Wheel-Mail', 'MR-60ft-clerestory-dining-d448', 'MR-6wheel-cove-brake-d530a', 'MR-6wheel-clerestory-brake-d530', 'MR-31ft-clerestory-lavatory-d492', 'MR-33ft-6in-clerestory-d491', 'MR-33ft-6in-clerestory-brake-d503-rear', 'MR-clayton-8wheel-arc-roof-third', 'MR-clayton-8wheel-arc-roof-third-lav', 'MR-clayton-8wheel-arc-roof-brake-rear', 'MR-clayton-8wheel-arc-roof-brake-lav-rear', 'MR-clayton-8wheel-arc-roof-mail', 'MR-clayton-8wheel-clerestory-third', 'MR-clayton-8wheel-clerestory-third-lav', 'MR-clayton-8wheel-clerestory-brake-rear', 'MR-clayton-8wheel-clerestory-brake-lav-rear', 'MR-clayton-8wheel-clerestory-mail', 'MR-45ft-clerestory-full-brake-d531', 'MR-48ft-arc-d487', 'MR-48ft-arc-brake-d501-rear', 'MR-48ft-clerestory-lav-3rd-d486', 'MR-48ft-clerestory-lav-brake-d499-rear', 'MR-48ft-clerestory-non-lav-brake-d500-rear', 'MR-48ft-clerestory-non-lav', 'MR-48ft-clerestory-mail', 'MR-48ft-clerestory-tpo', 'MR-50ft-arc-lav-d1060', 'MR-50ft-arc-brake-rear-d557', 'MR-clayton-12wheel-arc-roof-third', 'MR-clayton-12wheel-arc-roof-third-lav', 'MR-clayton-12wheel-arc-roof-brake-rear', 'MR-clayton-12wheel-arc-roof-brake-lav-rear', 'MR-clayton-12wheel-clerestory-third', 'MR-clayton-12wheel-clerestory-third-lav', 'MR-clayton-12wheel-clerestory-brake-rear', 'MR-clayton-12wheel-clerestory-brake-lav-rear', 'MR-54ft-clerestory-lav-d1056', 'MR-54ft-clerestory-lav-brake-d550-rear', 'MR-54ft-clerestory-non-lav-d485', 'MR-54ft-clerestory-brake-d497-rear', 'MR-54ft-clerestory-mail', 'MR-54ft-clerestory-tpo', 'MR-54ft-eliptical-non-lav-d1277', 'MR-54ft-eliptical-non-lav-brake-rear-d1246', 'MR-60ft-clerestory-lav-3rd-d484', 'MR-60ft-clerestory-brake-3rd-d496-rear', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-rear', 'LMS-non-cor-brake-lav-rear', 'MR-50ft-arc-non-lav-d555', 'MR-33ft-6in-clerestory-lav-composite-d514', 'MR-48ft-clerestory-lav-composite-d509', 'MR-48ft-clerestory-non-lav-brake-d500-rear', 'MR-60ft-clerestory-lav-composite-d539', 'MR-54ft-clerestory-brake-composite-d519a-rear', 'MR-54ft-clerestory-lav-brake-composite-d521-rear', 'MR-48ft-arc-first-d481', 'MR-48ft-arc-composite-d551', 'MR-50ft-arc-first-d553', 'MR-50ft-arc-composite-d554', 'MR-54ft-eliptical-non-lav-first-d1301', 'MR-54ft-eliptical-non-lav-composite-d1559', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-vestibule-kitchen', 'MR-clayton-12wheel-arc-roof-composite', 'MR-clayton-12wheel-arc-roof-composite-lav', 'MR-clayton-8wheel-arc-roof-composite-lav', 'MR-clayton-8wheel-arc-roof-composite', 'MR-clayton-8wheel-clerestory-composite', 'MR-clayton-8wheel-clerestory-composite-lav', 'MR-clayton-12wheel-clerestory-composite', 'MR-clayton-12wheel-clerestory-composite-lav', 'none'],
        payload_by_class=[0, 60, 0, 0],
        comfort_by_class=[0, 73, 0, 82],
        liverytype=['MR-Standard'],
        upgrade=['MR-push-pull-front', 'MR-push-pull-rear'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-48ft-arc-brake-d501-rear',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1902,
        intro_month=11,
        retire_year=1910,
        retire_month=4,
        speed=140,
        length=8,
        weight=24.3,
        axles=4,
        payload=60,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=30,
        cost=432000,
        runningcost=0,
        fixed_cost=5314,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['4-wheel-1870s-fitted', '4-wheel-1870s-brake-fitted', '4-wheel-1870s-mail-fitted', '4-wheel-1870s-tpo-fitted', '4-wheel-sub-1870s-fitted', '4-wheel-sub-1870s-brake-front-fitted', '4-wheel-1870s-fast-freight-fitted', '4-wheel-1870s-milk-fitted', 'MR-6Wheel-tpo', 'MR-6Wheel-non-lav', 'MR-6Wheel-lav', 'MR-6Wheel-brake-front', 'MR-6Wheel-Mail', 'MR-31ft-clerestory-kitchen-car-d532', 'MR-6wheel-cove-brake-d530a', 'MR-6wheel-clerestory-brake-d530', 'MR-31ft-clerestory-lavatory-d492', 'MR-33ft-6in-clerestory-d491', 'MR-33ft-6in-clerestory-brake-d503-front', 'MR-clayton-8wheel-arc-roof-third', 'MR-clayton-8wheel-arc-roof-third-lav', 'MR-clayton-8wheel-arc-roof-brake-front', 'MR-clayton-8wheel-arc-roof-brake-lav-front', 'MR-clayton-8wheel-arc-roof-mail', 'MR-clayton-8wheel-clerestory-third', 'MR-clayton-8wheel-clerestory-third-lav', 'MR-clayton-8wheel-clerestory-brake-front', 'MR-clayton-8wheel-clerestory-brake-lav-front', 'MR-clayton-8wheel-clerestory-mail', 'MR-45ft-clerestory-full-brake-d531', 'MR-48ft-arc-d487', 'MR-48ft-arc-brake-d501-front', 'MR-48ft-clerestory-lav-3rd-d486', 'MR-48ft-clerestory-lav-brake-d499-front', 'MR-48ft-clerestory-non-lav-brake-d500-front', 'MR-48ft-clerestory-non-lav', 'MR-48ft-clerestory-mail', 'MR-48ft-clerestory-tpo', 'MR-50ft-arc-lav-d1060', 'MR-50ft-arc-brake-front-d557', 'MR-clayton-12wheel-arc-roof-third', 'MR-clayton-12wheel-arc-roof-third-lav', 'MR-clayton-12wheel-arc-roof-brake-front', 'MR-clayton-12wheel-arc-roof-brake-lav-front', 'MR-clayton-12wheel-clerestory-third', 'MR-clayton-12wheel-clerestory-third-lav', 'MR-clayton-12wheel-clerestory-brake-front', 'MR-clayton-12wheel-clerestory-brake-lav-front', 'MR-54ft-clerestory-lav-d1056', 'MR-54ft-clerestory-lav-brake-d550-front', 'MR-54ft-clerestory-non-lav-d485', 'MR-54ft-clerestory-brake-d497-front', 'MR-54ft-clerestory-mail', 'MR-54ft-clerestory-tpo', 'MR-54ft-eliptical-non-lav-d1277', 'MR-54ft-eliptical-non-lav-brake-front-d1246', 'MR-60ft-clerestory-lav-3rd-d484', 'MR-60ft-clerestory-brake-3rd-d496-front', 'LMS-non-cor-lav', 'LMS-non-cor-non-lav', 'LMS-non-cor-brake-front', 'LMS-non-cor-brake-lav-front', 'MR-50ft-arc-non-lav-d555', 'MR-33ft-6in-clerestory-lav-composite-d514', 'MR-48ft-clerestory-lav-composite-d509', 'MR-48ft-clerestory-non-lav-brake-d500-front', 'MR-60ft-clerestory-lav-composite-d539', 'MR-54ft-clerestory-brake-composite-d519a-front', 'MR-54ft-clerestory-lav-brake-composite-d521-front', 'MR-48ft-arc-first-d481', 'MR-48ft-arc-composite-d551', 'MR-50ft-arc-first-d553', 'MR-50ft-arc-composite-d554', 'MR-54ft-eliptical-non-lav-first-d1301', 'MR-54ft-eliptical-non-lav-composite-d1559', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-12-wheel-kitchen', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-vestibule-kitchen', 'MR-clayton-12wheel-arc-roof-composite', 'MR-clayton-12wheel-arc-roof-composite-lav', 'MR-clayton-8wheel-arc-roof-composite-lav', 'MR-clayton-8wheel-arc-roof-composite', 'MR-clayton-8wheel-clerestory-composite', 'MR-clayton-8wheel-clerestory-composite-lav', 'MR-clayton-12wheel-clerestory-composite', 'MR-clayton-12wheel-clerestory-composite-lav'],
        payload_by_class=[0, 60, 0, 0],
        comfort_by_class=[0, 73, 0, 82],
        liverytype=['MR-Standard'],
        upgrade=['MR-push-pull-front', 'MR-push-pull-rear'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-push-pull-front',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1907,
        intro_month=8,
        retire_year=1924,
        retire_month=4,
        speed=140,
        length=8,
        weight=24.3,
        axles=4,
        payload=60,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=30,
        cost=432000,
        runningcost=0,
        fixed_cost=514,
        upgrade_price=25000,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['none'],
        constraint_next=['MR-1632', 'LMS-0-4-4T', 'LMS-Fowler-3P-Tank-Push-Pull', 'BR-2MT-Tank-Push-Pull', 'LMS-3F-Jinty-Push-Pull', 'MR-1833'],
        payload_by_class=[0, 60, 0, 0],
        comfort_by_class=[0, 73, 0, 82],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-push-pull-rear',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1907,
        intro_month=8,
        retire_year=1924,
        retire_month=4,
        speed=140,
        length=8,
        weight=24.3,
        axles=4,
        payload=60,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=30,
        cost=432000,
        runningcost=0,
        fixed_cost=514,
        upgrade_price=25000,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['MR-1632', 'LMS-0-4-4T', 'LMS-Fowler-3P-Tank-Push-Pull', 'BR-2MT-Tank-Push-Pull', 'LMS-3F-Jinty-Push-Pull', 'MR-1833', 'MR-push-pull-front'],
        constraint_next=['none'],
        payload_by_class=[0, 60, 0, 0],
        comfort_by_class=[0, 73, 0, 82],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
