"""mr-54ft-clerestory-corridor-carriages."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See Lacy & Dow vol. 2 pp. 185-6
_BLEND = 'trains/Carriages/mr-54ft-clerestory.blend'
_UPSTREAM_DAT = 'trains/mr-54ft-clerestory-corridor-carriages.dat'

SPECS = [
    Vehicle(
        name='MR-54ft-clerestory-cor-d560',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1903,
        intro_month=9,
        retire_year=1917,
        retire_month=12,
        speed=160,
        length=9,
        weight=25,
        axles=4,
        payload=42,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=24,
        cost=628000,
        runningcost=0,
        fixed_cost=748,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046'],
        payload_by_class=[0, 42, 0, 0],
        comfort_by_class=[0, 131, 0, 145],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-54ft-clerestory-cor-composite-d593',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1903,
        intro_month=9,
        retire_year=1917,
        retire_month=12,
        speed=160,
        length=9,
        weight=25,
        axles=4,
        payload=32,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=20,
        cost=633000,
        runningcost=0,
        fixed_cost=749,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046'],
        payload_by_class=[0, 32, 0, 10],
        comfort_by_class=[0, 131, 0, 145],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-54ft-clerestory-cor-first-d600',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1903,
        intro_month=9,
        retire_year=1917,
        retire_month=12,
        speed=160,
        length=9,
        weight=25,
        axles=4,
        payload=24,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=0,
        cost=639000,
        runningcost=0,
        fixed_cost=749,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046'],
        payload_by_class=[0, 0, 0, 24],
        comfort_by_class=[0, 131, 0, 145],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-54ft-clerestory-cor-brake-d467-front',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1903,
        intro_month=9,
        retire_year=1917,
        retire_month=12,
        speed=160,
        length=9,
        weight=25,
        axles=4,
        payload=18,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=12,
        cost=600000,
        runningcost=0,
        fixed_cost=5514,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046', 'none'],
        payload_by_class=[0, 18, 0, 0],
        comfort_by_class=[0, 131, 0, 145],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-54ft-clerestory-cor-brake-d467-rear',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1903,
        intro_month=9,
        retire_year=1917,
        retire_month=12,
        speed=160,
        length=9,
        weight=25,
        axles=4,
        payload=18,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=12,
        cost=600000,
        runningcost=0,
        fixed_cost=5514,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        payload_by_class=[0, 18, 0, 0],
        comfort_by_class=[0, 131, 0, 145],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-54ft-clerestory-mini-restaurant-brake-d443-front',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1907,
        intro_month=5,
        retire_year=1917,
        retire_month=12,
        speed=160,
        length=9,
        weight=25.5,
        axles=4,
        payload=20,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=15,
        catering_level=3,
        cost=750000,
        runningcost=0,
        fixed_cost=18893,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046', 'none'],
        payload_by_class=[0, 20, 0, 8],
        comfort_by_class=[0, 131, 0, 145],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-54ft-clerestory-mini-restaurant-brake-d443-rear',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1907,
        intro_month=5,
        retire_year=1917,
        retire_month=12,
        speed=160,
        length=9,
        weight=25.5,
        axles=4,
        payload=20,
        min_loading_time=20,
        max_loading_time=50,
        overcrowded_capacity=15,
        catering_level=3,
        cost=750000,
        runningcost=0,
        fixed_cost=18893,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        payload_by_class=[0, 20, 0, 8],
        comfort_by_class=[0, 131, 0, 145],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-54ft-clerestory-open-vestibule-d595',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1910,
        intro_month=6,
        retire_year=1917,
        retire_month=12,
        speed=160,
        length=9,
        weight=24.8,
        axles=4,
        payload=56,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=34,
        cost=570000,
        runningcost=0,
        fixed_cost=679,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046'],
        payload_by_class=[0, 56],
        comfort_by_class=[0, 125],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-54ft-clerestory-open-vestibule-brake-d594-front',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1910,
        intro_month=6,
        retire_year=1917,
        retire_month=12,
        speed=160,
        length=9,
        weight=24.8,
        axles=4,
        payload=40,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=26,
        cost=569000,
        runningcost=0,
        fixed_cost=5477,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-rear', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-kitchen', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-rear', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-rear', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-rear', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-rear', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-rear', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-rear', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-rear', 'MR-54ft-clerestory-mini-restaurant-brake-d443-rear', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-rear', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-rear-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-rear', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-rear-d1046', 'none'],
        payload_by_class=[0, 40],
        comfort_by_class=[0, 125],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='MR-54ft-clerestory-open-vestibule-brake-d594-rear',
        waytype='track',
        copyright='jamespetts',
        freight='Passagiere',
        intro_year=1910,
        intro_month=6,
        retire_year=1917,
        retire_month=12,
        speed=160,
        length=9,
        weight=24.8,
        axles=4,
        payload=40,
        min_loading_time=25,
        max_loading_time=180,
        overcrowded_capacity=26,
        cost=569000,
        runningcost=0,
        fixed_cost=5477,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['LNWR-45ft-cor-full-brake', 'LNWR-42ft-cor', 'LNWR-42ft-cor-brake-front', 'LNWR-42ft-cor-mail', 'LNWR-42ft-cor-tpo', 'LNWR-50ft-6in-diner-twin-saloon', 'LNWR-50ft-cor', 'LNWR-50ft-cor-brake', 'LNWR-60ft-6in-diner', 'LNWR-57ft-cor', 'LNWR-57ft-cor-brake-front', 'LNWR-57ft-cor-tpo', 'LNWR-57ft-cor-tea-car', 'LNWR-60ft-6in-diner-non-clerestory', 'LNWR-50ft-cor-mail', 'LNWR-50ft-cor-full-brake', 'LMS-period1-cor', 'LMS-period1-cor-brake-front', 'LMS-period1-cor-open', 'LMS-period1-cor-open-brake-front', 'LMS-period1-mail', 'LMS-period1-tpo', 'LMS-period1-full-brake', 'LMS-period1-cor-diner', 'LMS-open', 'LMS-full-brake', 'LMS-open-brake-front', 'LMS-diner', 'LMS-Mail', 'LMS-TPO', 'LMS-cor', 'LMS-cor-brake-front', 'LMS-buffet', 'MR-31ft-clerestory-cor-brake-d568', 'MR-48ft-clerestory-cor-d575', 'MR-48ft-clerestory-cor-lav-brake-front', 'MR-48ft-clerestory-full-brake-d1067', 'MR-54ft-clerestory-cor-d560', 'MR-54ft-clerestory-cor-brake-d467-front', 'MR-54ft-clerestory-mini-restaurant-brake-d443-front', 'MR-54ft-clerestory-open-vestibule-d595', 'MR-54ft-clerestory-open-vestibule-brake-d594-front', 'MR-54ft-eliptical-cor-d1047', 'MR-54ft-eliptical-cor-brake-front-d1048', 'MR-54ft-eliptical-full-brake-d1114', 'MR-60ft-clerestory-kitchen-dining-d444', 'MR-65ft-clerestory-dining-d575', 'MR-65ft-eliptical-dining-d1196', 'LNWR-42ft-cor-first', 'LNWR-42ft-cor-composite', 'LNWR-42ft-cor-brake-composite-front', 'LNWR-50ft-cor-first', 'LNWR-57ft-cor-composite', 'LNWR-57ft-cor-first', 'LMS-period1-cor-open-first', 'LMS-period1-cor-first', 'LMS-period1-cor-composite', 'LMS-open-first', 'LMS-open-composite', 'LMS-cor-first', 'LMS-cor-composite', 'MR-54ft-clerestory-cor-composite-d593', 'MR-54ft-clerestory-cor-first-d600', 'MR-54ft-eliptical-cor-brake-composite-front-d1046'],
        payload_by_class=[0, 40],
        comfort_by_class=[0, 125],
        liverytype=['MR-Standard'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
