"""pullman-elliptical-8-wheel."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Carriages/pullman-elliptical-8-wheel-ivory.blend'
_UPSTREAM_DAT = 'trains/pullman-elliptical-8-wheel.dat'

SPECS = [
    Vehicle(
        name='pullman-elliptical-8-wheel-parlour-first',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1906,
        intro_month=9,
        retire_year=1924,
        retire_month=2,
        speed=160,
        length=10,
        weight=36.0,
        axles=4,
        payload=28,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        cost=665000,
        runningcost=0,
        fixed_cost=680,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-front', 'pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-front', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-front', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-front', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-front', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        constraint_next=['pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-rear', 'pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-rear', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-rear', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-rear', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-rear', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        payload_by_class=[0, 0, 0, 0, 28],
        comfort_by_class=[0, 0, 136, 136, 150],
        liverytype=['Pullman-Ivory-Umber', 'Pullman-Cream-Umber'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='pullman-elliptical-8-wheel-parlour-third',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1912,
        intro_month=7,
        retire_year=1924,
        retire_month=2,
        speed=160,
        length=10,
        weight=36.0,
        axles=4,
        payload=36,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        cost=662000,
        runningcost=0,
        fixed_cost=678,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-front', 'pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-front', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-front', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-front', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-front', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        constraint_next=['pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-rear', 'pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-rear', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-rear', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-rear', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-rear', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        payload_by_class=[0, 0, 36, 0, 0],
        comfort_by_class=[0, 0, 136, 136, 150],
        liverytype=['Pullman-Ivory-Umber', 'Pullman-Cream-Umber'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='pullman-elliptical-8-wheel-kitchen',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1906,
        intro_month=9,
        retire_year=1924,
        retire_month=2,
        speed=160,
        length=10,
        weight=39.9,
        axles=4,
        payload=21,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        catering_level=5,
        cost=695000,
        runningcost=0,
        fixed_cost=1800,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['any'],
        payload_by_class=[0, 0, 0, 0, 21],
        comfort_by_class=[0, 0, 136, 136, 150],
        liverytype=['Pullman-Ivory-Umber', 'Pullman-Cream-Umber'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='pullman-elliptical-8-wheel-brake-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1906,
        intro_month=9,
        retire_year=1924,
        retire_month=2,
        speed=160,
        length=10,
        weight=37.1,
        axles=4,
        payload=27,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        cost=655000,
        runningcost=0,
        fixed_cost=675,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-rear', 'pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-rear', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-rear', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-rear', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-rear', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen', 'none'],
        payload_by_class=[0, 0, 0, 0, 27],
        comfort_by_class=[0, 0, 136, 136, 150],
        liverytype=['Pullman-Ivory-Umber', 'Pullman-Cream-Umber'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='pullman-elliptical-8-wheel-brake-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1906,
        intro_month=9,
        retire_year=1924,
        retire_month=2,
        speed=160,
        length=10,
        weight=37.1,
        axles=4,
        payload=27,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        cost=655000,
        runningcost=0,
        fixed_cost=675,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-front', 'pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-front', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-front', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-front', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-front', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        payload_by_class=[0, 0, 0, 0, 27],
        comfort_by_class=[0, 0, 136, 136, 150],
        liverytype=['Pullman-Ivory-Umber', 'Pullman-Cream-Umber'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
