"""pullman-1908."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Carriages/pullman-1908-ivory.blend'
_UPSTREAM_DAT = 'trains/pullman-1908.dat'

SPECS = [
    Vehicle(
        name='pullman-1908-parlour-first',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1908,
        intro_month=4,
        retire_year=1924,
        retire_month=2,
        speed=160,
        length=11,
        weight=39.2,
        axles=4,
        payload=33,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        cost=715000,
        runningcost=0,
        fixed_cost=730,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-front', 'pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-front', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-front', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-front', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-front', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        constraint_next=['pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-rear', 'pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-rear', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-rear', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-rear', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-rear', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        payload_by_class=[0, 0, 0, 0, 33],
        comfort_by_class=[0, 0, 139, 139, 153],
        liverytype=['Pullman-Ivory-Umber', 'Pullman-Cream-Umber'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='pullman-1908-parlour-third',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1912,
        intro_month=7,
        retire_year=1924,
        retire_month=2,
        speed=160,
        length=11,
        weight=39.2,
        axles=4,
        payload=44,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        cost=715000,
        runningcost=0,
        fixed_cost=730,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-front', 'pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-front', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-front', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-front', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-front', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        constraint_next=['pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-rear', 'pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-rear', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-rear', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-rear', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-rear', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        payload_by_class=[0, 0, 44, 0, 0],
        comfort_by_class=[0, 0, 139, 139, 153],
        liverytype=['Pullman-Ivory-Umber', 'Pullman-Cream-Umber'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='pullman-1908-kitchen',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1908,
        intro_month=4,
        retire_year=1924,
        retire_month=2,
        speed=160,
        length=11,
        weight=42.7,
        axles=4,
        payload=25,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        catering_level=5,
        cost=725000,
        runningcost=0,
        fixed_cost=1950,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['any'],
        constraint_next=['any'],
        payload_by_class=[0, 0, 0, 0, 25],
        comfort_by_class=[0, 0, 139, 139, 153],
        liverytype=['Pullman-Ivory-Umber', 'Pullman-Cream-Umber'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='pullman-1908-brake-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1908,
        intro_month=4,
        retire_year=1924,
        retire_month=2,
        speed=160,
        length=11,
        weight=39.0,
        axles=4,
        payload=31,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        cost=714000,
        runningcost=0,
        fixed_cost=730,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-rear', 'pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-rear', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-rear', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-rear', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-rear', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen', 'none'],
        payload_by_class=[0, 0, 0, 0, 31],
        comfort_by_class=[0, 0, 139, 139, 153],
        liverytype=['Pullman-Ivory-Umber', 'Pullman-Cream-Umber'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='pullman-1908-brake-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1908,
        intro_month=4,
        retire_year=1924,
        retire_month=2,
        speed=160,
        length=11,
        weight=39.0,
        axles=4,
        payload=31,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        cost=714000,
        runningcost=0,
        fixed_cost=730,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-front', 'pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-front', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-front', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-front', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-front', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        payload_by_class=[0, 0, 0, 0, 31],
        comfort_by_class=[0, 0, 139, 139, 153],
        liverytype=['Pullman-Ivory-Umber', 'Pullman-Cream-Umber'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
