"""pullman-1928."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Carriages/pullman-1928-6-pul-austerity.blend'
_UPSTREAM_DAT = 'trains/pullman-1928.dat'

SPECS = [
    Vehicle(
        name='pullman-1928-parlour-first',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1928,
        intro_month=7,
        retire_year=1951,
        retire_month=6,
        speed=160,
        length=11,
        weight=38.6,
        axles=4,
        payload=24,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        cost=700000,
        runningcost=0,
        fixed_cost=730,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-front', 'pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-front', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-front', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-front', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-front', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        constraint_next=['pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-rear', 'pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-rear', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-rear', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-rear', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-rear', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        payload_by_class=[0, 0, 0, 0, 24],
        comfort_by_class=[0, 0, 145, 145, 158],
        liverytype=['Pullman-Cream-Umber', 'WW2-Austerity'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='pullman-1928-parlour-third',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1928,
        intro_month=7,
        retire_year=1951,
        retire_month=6,
        speed=160,
        length=11,
        weight=38.6,
        axles=4,
        payload=42,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        cost=700000,
        runningcost=0,
        fixed_cost=730,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-front', 'pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-front', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-front', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-front', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-front', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        constraint_next=['pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-rear', 'pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-rear', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-rear', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-rear', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-rear', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        payload_by_class=[0, 0, 42, 0, 0],
        comfort_by_class=[0, 0, 145, 145, 158],
        liverytype=['Pullman-Cream-Umber', 'WW2-Austerity'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='pullman-1928-kitchen-third',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1928,
        intro_month=7,
        retire_year=1951,
        retire_month=6,
        speed=160,
        length=11,
        weight=38.6,
        axles=4,
        payload=30,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        catering_level=5,
        cost=710000,
        runningcost=0,
        fixed_cost=1850,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-front', 'pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-front', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-front', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-front', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-front', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        constraint_next=['pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-rear', 'pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-rear', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-rear', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-rear', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-rear', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        payload_by_class=[0, 0, 30, 0, 0],
        comfort_by_class=[0, 0, 145, 145, 158],
        liverytype=['Pullman-Cream-Umber', 'WW2-Austerity'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='pullman-1928-kitchen-first',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1928,
        intro_month=7,
        retire_year=1951,
        retire_month=6,
        speed=160,
        length=11,
        weight=38.6,
        axles=4,
        payload=20,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        catering_level=5,
        cost=711000,
        runningcost=0,
        fixed_cost=1850,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['any'],
        constraint_next=['any'],
        payload_by_class=[0, 0, 0, 0, 20],
        comfort_by_class=[0, 0, 145, 145, 158],
        liverytype=['Pullman-Cream-Umber', 'WW2-Austerity'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='pullman-1928-brake-third-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1928,
        intro_month=7,
        retire_year=1951,
        retire_month=6,
        speed=160,
        length=11,
        weight=38.6,
        axles=4,
        payload=30,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        cost=700000,
        runningcost=0,
        fixed_cost=730,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-rear', 'pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-rear', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-rear', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-rear', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-rear', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen', 'none'],
        payload_by_class=[0, 0, 30, 0, 0],
        comfort_by_class=[0, 0, 145, 145, 158],
        liverytype=['Pullman-Cream-Umber', 'WW2-Austerity'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='pullman-1928-brake-third-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1928,
        intro_month=7,
        retire_year=1951,
        retire_month=6,
        speed=160,
        length=11,
        weight=38.6,
        axles=4,
        payload=30,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        cost=700000,
        runningcost=0,
        fixed_cost=730,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['pullman-1928-parlour-first', 'pullman-1928-parlour-third', 'pullman-1928-kitchen-third', 'pullman-1928-kitchen-first', 'pullman-1928-brake-third-front', 'pullman-1951-parlour-first', 'pullman-1951-parlour-third', 'pullman-1951-kitchen-third', 'pullman-1951-kitchen-first', 'pullman-1951-brake-third-front', 'pullman-k-type-parlour-first', 'pullman-k-type-parlour-third', 'pullman-k-type-kitchen-third', 'pullman-k-type-kitchen-first', 'pullman-k-type-brake-third-front', 'pullman-1908-parlour-first', 'pullman-1908-parlour-third', 'pullman-1908-kitchen', 'pullman-1908-brake-front', 'pullman-elliptical-8-wheel-parlour-first', 'pullman-elliptical-8-wheel-parlour-third', 'pullman-elliptical-8-wheel-kitchen', 'pullman-elliptical-8-wheel-brake-front', 'pullman-open-platform-parlour', 'pullman-open-platform-kitchen', 'pullman-vestibule-parlour', 'pullman-vestibule-kitchen', 'pullman-vestibule-12-wheel-parlour', 'pullman-vestibule-12-wheel-kitchen'],
        payload_by_class=[0, 0, 30, 0, 0],
        comfort_by_class=[0, 0, 145, 145, 158],
        liverytype=['Pullman-Cream-Umber', 'WW2-Austerity'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
