"""sr-3sub."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See Jenkinson p. 387
_BLEND = 'trains/Railcars/sr-3-sub-driving-motor-malachite-rear.blend'
_UPSTREAM_DAT = 'trains/sr-3sub.dat'

SPECS = [
    Vehicle(
        name='SR-3SUB(front)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1925,
        intro_month=4,
        retire_year=1941,
        retire_month=5,
        speed=97,
        length=10,
        weight=41.7,
        axles=4,
        power=410,
        gear=80,
        tractive_effort=38,
        payload=80,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=40,
        cost=1700000,
        runningcost=164,
        fixed_cost=7417,
        upgrade_price=1101700,
        increase_maintenance_after_years=25,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['SR-3SUB(rear)', 'LSWR-EMU(rear)', 'SR-4SUB(rear)', 'SR-2-NOL-rear', 'SR-4LAV(rear)', 'SR-401[BIL]Rear', 'SR-6PAN(rear)', 'sr-2hal-rear', 'SR-404[COR]Rear', 'lbscr-48ft-augmentation-trailer-rear', 'lbscr-54ft-augmentation-trailer-rear', 'lswr-48ft-arc-augmentation-trailer-rear', 'lswr-48ft-augmentation-trailer-rear', 'lswr-56ft-augmentation-trailer-rear', 'none'],
        constraint_next=['SR-3SUB(centre)'],
        payload_by_class=[0, 80, 0, 0],
        comfort_by_class=[0, 66, 0, 83],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Revised'],
        upgrade=['BR-414[HAP]Front', 'BR-414[HAP]Rear', 'BR-4EPB(front)', 'BR-2EPB(rear)', 'BR-4EPB(rear)', 'BR-4EPB(centre1)', 'BR-4EPB(centre2)'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-3SUB(centre)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1925,
        intro_month=4,
        retire_year=1941,
        retire_month=5,
        speed=97,
        length=10,
        weight=27.8,
        axles=4,
        power=0,
        tractive_effort=0,
        payload=56,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=45,
        cost=787600,
        runningcost=0,
        fixed_cost=938,
        upgrade_price=157520,
        increase_maintenance_after_years=25,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-3SUB(front)'],
        constraint_next=['SR-3SUB(rear)', 'SR-4SUB(centre2)'],
        payload_by_class=[0, 20, 0, 56],
        comfort_by_class=[0, 66, 0, 83],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Revised'],
        upgrade=['BR-414[HAP]Front', 'BR-414[HAP]Rear', 'BR-4EPB(front)', 'BR-2EPB(rear)', 'BR-4EPB(rear)', 'BR-4EPB(centre1)', 'BR-4EPB(centre2)'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-3SUB(rear)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1925,
        intro_month=4,
        retire_year=1941,
        retire_month=5,
        speed=97,
        length=11,
        weight=41.7,
        axles=4,
        power=410,
        gear=80,
        tractive_effort=38,
        payload=80,
        min_loading_time=10,
        max_loading_time=40,
        overcrowded_capacity=40,
        cost=1700000,
        runningcost=164,
        fixed_cost=7417,
        upgrade_price=1101700,
        increase_maintenance_after_years=25,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['SR-3SUB(centre)', 'SR-4SUB(centre2)'],
        constraint_next=['SR-3SUB(front)', 'LSWR-EMU(front)', 'SR-4SUB(front)', 'SR-2-NOL-front', 'SR-4LAV(front)', 'SR-401[BIL]Front', 'SR-6PAN(front)', 'sr-2hal-front', 'SR-404[COR]Front', 'lbscr-48ft-augmentation-trailer-front', 'lbscr-54ft-augmentation-trailer-front', 'lswr-48ft-arc-augmentation-trailer-front', 'lswr-48ft-augmentation-trailer-front', 'lswr-56ft-augmentation-trailer-front', 'none'],
        payload_by_class=[0, 80, 0, 0],
        comfort_by_class=[0, 66, 0, 83],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Revised'],
        upgrade=['BR-414[HAP]Front', 'BR-414[HAP]Rear', 'BR-4EPB(front)', 'BR-2EPB(rear)', 'BR-4EPB(rear)', 'BR-4EPB(centre1)', 'BR-4EPB(centre2)'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
