"""sr-4-lav."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See Jenkinson p. 397 for diagrams
_BLEND = 'trains/Railcars/sr-4-lav-trailer1-malachite.blend'
_UPSTREAM_DAT = 'trains/sr-4-lav.dat'

SPECS = [
    Vehicle(
        name='SR-4LAV(front)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1930,
        intro_month=6,
        retire_year=1936,
        retire_month=10,
        speed=120,
        length=10,
        weight=41.7,
        axles=4,
        power=410,
        gear=80,
        tractive_effort=30,
        payload=70,
        min_loading_time=20,
        max_loading_time=46,
        overcrowded_capacity=35,
        cost=1421000,
        runningcost=164,
        fixed_cost=7184,
        increase_maintenance_after_years=25,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['SR-3SUB(rear)', 'LSWR-EMU(rear)', 'SR-4SUB(rear)', 'SR-2-NOL-rear', 'SR-4LAV(rear)', 'SR-401[BIL]Rear', 'SR-6PAN(rear)', 'sr-2hal-rear', 'SR-404[COR]Rear', 'lbscr-48ft-augmentation-trailer-rear', 'lbscr-54ft-augmentation-trailer-rear', 'lswr-48ft-arc-augmentation-trailer-rear', 'lswr-48ft-augmentation-trailer-rear', 'lswr-56ft-augmentation-trailer-rear', 'SR-5-BEL-driving-motor-rear', 'none'],
        constraint_next=['SR-4LAV(centre1)'],
        payload_by_class=[0, 70, 0, 0],
        comfort_by_class=[0, 76, 0, 84],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Revised'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-4LAV(centre1)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1930,
        intro_month=6,
        retire_year=1936,
        retire_month=10,
        speed=120,
        length=10,
        weight=28.4,
        axles=4,
        power=0,
        payload=40,
        min_loading_time=20,
        max_loading_time=46,
        overcrowded_capacity=20,
        cost=801000,
        runningcost=0,
        fixed_cost=954,
        increase_maintenance_after_years=25,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['SR-4LAV(front)'],
        constraint_next=['SR-4LAV(centre2)'],
        payload_by_class=[0, 40, 0, 40],
        comfort_by_class=[0, 76, 0, 84],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-4LAV(centre2)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1930,
        intro_month=6,
        retire_year=1936,
        retire_month=10,
        speed=120,
        length=10,
        weight=29.4,
        axles=4,
        power=0,
        payload=30,
        min_loading_time=20,
        max_loading_time=46,
        overcrowded_capacity=12,
        cost=901200,
        runningcost=0,
        fixed_cost=1073,
        increase_maintenance_after_years=25,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['SR-4LAV(centre1)'],
        constraint_next=['SR-4LAV(rear)'],
        payload_by_class=[0, 24, 0, 30],
        comfort_by_class=[0, 90, 0, 110],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-4LAV(rear)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1930,
        intro_month=6,
        retire_year=1936,
        retire_month=10,
        speed=120,
        length=11,
        weight=41.7,
        axles=4,
        power=410,
        gear=80,
        tractive_effort=30,
        payload=80,
        min_loading_time=20,
        max_loading_time=46,
        overcrowded_capacity=35,
        cost=1421000,
        runningcost=164,
        fixed_cost=7184,
        increase_maintenance_after_years=25,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['SR-4LAV(centre2)'],
        constraint_next=['SR-3SUB(front)', 'LSWR-EMU(front)', 'SR-4SUB(front)', 'SR-2-NOL-front', 'SR-4LAV(front)', 'SR-401[BIL]Front', 'SR-6PAN(front)', 'sr-2hal-front', 'SR-404[COR]Front', 'lbscr-48ft-augmentation-trailer-front', 'lbscr-54ft-augmentation-trailer-front', 'lswr-48ft-arc-augmentation-trailer-front', 'lswr-48ft-augmentation-trailer-front', 'lswr-56ft-augmentation-trailer-front', 'SR-5-BEL-driving-motor-front', 'none'],
        payload_by_class=[0, 80, 0, 0],
        comfort_by_class=[0, 76, 0, 84],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
