"""sr-5-bel."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See Jenkinson p. 506
# See also http://extra.southernelectric.org.uk/features/historical-features/fleet_bel.html
_BLEND = 'trains/Railcars/sr-5-bel-motor-austerity.blend'
_UPSTREAM_DAT = 'trains/sr-5-bel.dat'

SPECS = [
    Vehicle(
        name='SR-5-BEL-driving-motor-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1932,
        intro_month=12,
        retire_year=1939,
        retire_month=9,
        speed=120,
        length=11,
        weight=43.6,
        axles=4,
        power=671,
        gear=80,
        tractive_effort=63,
        payload=48,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        cost=1790000,
        runningcost=269,
        fixed_cost=7459,
        increase_maintenance_after_years=25,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['SR-3SUB(rear)', 'LSWR-EMU(rear)', 'SR-4SUB(rear)', 'SR-2-NOL-rear', 'SR-4LAV(rear)', 'SR-401[BIL]Rear', 'SR-6PAN(rear)', 'sr-2hal-rear', 'SR-404[COR]Rear', 'lbscr-48ft-augmentation-trailer-rear', 'lbscr-54ft-augmentation-trailer-rear', 'lswr-48ft-arc-augmentation-trailer-rear', 'lswr-48ft-augmentation-trailer-rear', 'lswr-56ft-augmentation-trailer-rear', 'SR-5-BEL-driving-motor-rear', 'none'],
        constraint_next=['SR-5-BEL-parlour-third'],
        payload_by_class=[0, 0, 48, 0, 0],
        comfort_by_class=[0, 0, 145, 145, 158],
        liverytype=['Pullman-Cream-Umber', 'WW2-Austerity', 'BR-Revised', 'BR-Blue'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-5-BEL-parlour-third',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1932,
        intro_month=12,
        retire_year=1939,
        retire_month=9,
        speed=120,
        length=11,
        weight=38.6,
        axles=4,
        payload=56,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        cost=700000,
        runningcost=0,
        fixed_cost=730,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-5-BEL-driving-motor-front'],
        constraint_next=['SR-5-bel-kitchen-first-1'],
        payload_by_class=[0, 0, 56, 0, 0],
        comfort_by_class=[0, 0, 145, 145, 158],
        liverytype=['Pullman-Cream-Umber', 'WW2-Austerity', 'BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-5-bel-kitchen-first-1',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1928,
        intro_month=7,
        retire_year=1951,
        retire_month=6,
        speed=160,
        length=11,
        weight=38.6,
        axles=4,
        payload=20,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        catering_level=5,
        cost=711000,
        runningcost=0,
        fixed_cost=1850,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-5-BEL-parlour-third'],
        constraint_next=['SR-5-bel-kitchen-first-2'],
        payload_by_class=[0, 0, 0, 0, 20],
        comfort_by_class=[0, 0, 145, 145, 158],
        liverytype=['Pullman-Cream-Umber', 'WW2-Austerity', 'BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-5-bel-kitchen-first-2',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1928,
        intro_month=7,
        retire_year=1951,
        retire_month=6,
        speed=160,
        length=11,
        weight=38.6,
        axles=4,
        payload=20,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        catering_level=5,
        cost=711000,
        runningcost=0,
        fixed_cost=1850,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-5-bel-kitchen-first-1'],
        constraint_next=['SR-5-BEL-driving-motor-rear'],
        payload_by_class=[0, 0, 0, 0, 20],
        comfort_by_class=[0, 0, 145, 145, 158],
        liverytype=['Pullman-Cream-Umber', 'WW2-Austerity', 'BR-Revised', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-5-BEL-driving-motor-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1932,
        intro_month=12,
        retire_year=1939,
        retire_month=9,
        speed=120,
        length=11,
        weight=43.6,
        axles=4,
        power=671,
        gear=80,
        tractive_effort=63,
        payload=48,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        cost=1790000,
        runningcost=269,
        fixed_cost=7459,
        increase_maintenance_after_years=25,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['SR-5-bel-kitchen-first-2'],
        constraint_next=['SR-3SUB(front)', 'LSWR-EMU(front)', 'SR-4SUB(front)', 'SR-2-NOL-front', 'SR-4LAV(front)', 'SR-401[BIL]Front', 'SR-6PAN(front)', 'sr-2hal-front', 'SR-404[COR]Front', 'lbscr-48ft-augmentation-trailer-front', 'lbscr-54ft-augmentation-trailer-front', 'lswr-48ft-arc-augmentation-trailer-front', 'lswr-48ft-augmentation-trailer-front', 'lswr-56ft-augmentation-trailer-front', 'SR-5-BEL-driving-motor-front', 'none'],
        payload_by_class=[0, 0, 48, 0, 0],
        comfort_by_class=[0, 0, 145, 145, 158],
        liverytype=['Pullman-Cream-Umber', 'WW2-Austerity', 'BR-Early', 'BR-Blue'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
