"""sr-6-pan."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# See Jenkinson p. 399
_BLEND = 'trains/Railcars/sr-6-pan-buffet-br-revised.blend'
_UPSTREAM_DAT = 'trains/sr-6-pan.dat'

SPECS = [
    Vehicle(
        name='SR-6PAN(front)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1932,
        intro_month=4,
        retire_year=1939,
        retire_month=5,
        speed=120,
        length=11,
        weight=59.9,
        axles=4,
        power=671,
        gear=80,
        tractive_effort=63,
        payload=52,
        min_loading_time=20,
        max_loading_time=70,
        overcrowded_capacity=18,
        cost=1751000,
        runningcost=269,
        fixed_cost=7459,
        increase_maintenance_after_years=25,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['SR-3SUB(rear)', 'LSWR-EMU(rear)', 'SR-4SUB(rear)', 'SR-2-NOL-rear', 'SR-4LAV(rear)', 'SR-401[BIL]Rear', 'SR-6PAN(rear)', 'sr-2hal-rear', 'SR-404[COR]Rear', 'lbscr-48ft-augmentation-trailer-rear', 'lbscr-54ft-augmentation-trailer-rear', 'lswr-48ft-arc-augmentation-trailer-rear', 'lswr-48ft-augmentation-trailer-rear', 'lswr-56ft-augmentation-trailer-rear', 'SR-5-BEL-driving-motor-rear', 'none'],
        constraint_next=['SR-6PAN(trailer1)'],
        payload_by_class=[0, 52],
        comfort_by_class=[0, 136],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Revised'],
        way_constraint_permissive=[0],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-6PAN(trailer1)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1932,
        intro_month=4,
        retire_year=1939,
        retire_month=5,
        speed=120,
        length=11,
        weight=32.0,
        axles=4,
        power=0,
        payload=68,
        min_loading_time=20,
        max_loading_time=70,
        overcrowded_capacity=28,
        cost=805000,
        runningcost=0,
        fixed_cost=958,
        increase_maintenance_after_years=25,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['SR-6PAN(front)'],
        constraint_next=['SR-6PAN(trailer2)'],
        payload_by_class=[0, 68, 0, 0],
        comfort_by_class=[0, 130, 0, 153],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-6PAN(trailer2)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1932,
        intro_month=4,
        retire_year=1939,
        retire_month=5,
        speed=120,
        length=11,
        weight=31.4,
        axles=4,
        power=0,
        payload=42,
        min_loading_time=20,
        max_loading_time=70,
        overcrowded_capacity=0,
        cost=805000,
        runningcost=0,
        fixed_cost=958,
        increase_maintenance_after_years=25,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['SR-6PAN(trailer1)'],
        constraint_next=['SR-6PAN(buffet)', 'pullman-kitchen-composite'],
        payload_by_class=[0, 0, 0, 42],
        comfort_by_class=[0, 130, 0, 153],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-6PAN(buffet)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1932,
        intro_month=4,
        retire_year=1939,
        retire_month=5,
        speed=120,
        length=11,
        weight=32.5,
        axles=4,
        power=0,
        payload=30,
        min_loading_time=20,
        max_loading_time=70,
        overcrowded_capacity=0,
        catering_level=3,
        cost=805000,
        runningcost=0,
        fixed_cost=18958,
        increase_maintenance_after_years=25,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['SR-6PAN(trailer2)'],
        constraint_next=['SR-6PAN(trailer4)'],
        payload_by_class=[0, 0, 0, 30],
        comfort_by_class=[0, 130, 0, 153],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='pullman-kitchen-composite',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1932,
        intro_month=4,
        retire_year=1939,
        retire_month=5,
        speed=120,
        length=11,
        weight=38.6,
        axles=4,
        power=0,
        payload=16,
        min_loading_time=40,
        max_loading_time=200,
        overcrowded_capacity=0,
        catering_level=5,
        cost=855000,
        runningcost=0,
        fixed_cost=20958,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['SR-6PAN(trailer2)'],
        constraint_next=['SR-6PAN(trailer4)'],
        payload_by_class=[0, 0, 16, 0, 12],
        comfort_by_class=[0, 0, 145, 145, 158],
        liverytype=['Pullman-Cream-Umber', 'WW2-Austerity'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-6PAN(trailer4)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1932,
        intro_month=4,
        retire_year=1939,
        retire_month=5,
        speed=120,
        length=11,
        weight=32.0,
        axles=4,
        power=0,
        payload=68,
        min_loading_time=20,
        max_loading_time=70,
        overcrowded_capacity=34,
        cost=805000,
        runningcost=0,
        fixed_cost=958,
        increase_maintenance_after_years=25,
        bidirectional=0,
        can_lead_from_rear=1,
        constraint_prev=['SR-6PAN(buffet)', 'pullman-kitchen-composite'],
        constraint_next=['SR-6PAN(rear)'],
        payload_by_class=[0, 68, 0, 0],
        comfort_by_class=[0, 130, 0, 153],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-6PAN(rear)',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        engine_type='electric',
        intro_year=1932,
        intro_month=4,
        retire_year=1939,
        retire_month=5,
        speed=120,
        length=11,
        weight=59.9,
        axles=4,
        power=671,
        gear=80,
        tractive_effort=63,
        payload=52,
        min_loading_time=20,
        max_loading_time=70,
        overcrowded_capacity=18,
        cost=1751000,
        runningcost=269,
        fixed_cost=7459,
        increase_maintenance_after_years=25,
        bidirectional=0,
        can_lead_from_rear=1,
        sound='x24tohayes-epb.wav',
        constraint_prev=['SR-6PAN(trailer4)'],
        constraint_next=['SR-3SUB(front)', 'LSWR-EMU(front)', 'SR-4SUB(front)', 'SR-2-NOL-front', 'SR-4LAV(front)', 'SR-401[BIL]Front', 'SR-6PAN(front)', 'sr-2hal-front', 'SR-404[COR]Front', 'lbscr-48ft-augmentation-trailer-front', 'lbscr-54ft-augmentation-trailer-front', 'lswr-48ft-arc-augmentation-trailer-front', 'lswr-48ft-augmentation-trailer-front', 'lswr-56ft-augmentation-trailer-front', 'SR-5-BEL-driving-motor-front', 'none'],
        payload_by_class=[0, 52],
        comfort_by_class=[0, 136],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Revised'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
