"""sr-augmentation-trailers."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

# Augmentation trailers for the 3-Sub EMUs
# Each type of carriage from which these are built has its own type of trailer.
_BLEND = 'trains/Railcars/sr-augmentation-trailer-malachite.blend'
_UPSTREAM_DAT = 'trains/sr-augmentation-trailers.dat'

SPECS = [
    Vehicle(
        name='lbscr-48ft-augmentation-trailer-front',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1916,
        intro_month=2,
        retire_year=1941,
        retire_month=5,
        speed=160,
        length=8,
        weight=22,
        axles=4,
        payload=80,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=40,
        cost=703000,
        runningcost=0,
        fixed_cost=840,
        upgrade_price=109200,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-3SUB(rear)', 'LSWR-EMU(rear)'],
        constraint_next=['lbscr-48ft-augmentation-trailer-rear', 'lbscr-54ft-augmentation-trailer-rear', 'lswr-48ft-arc-augmentation-trailer-rear', 'lswr-48ft-augmentation-trailer-rear', 'lswr-56ft-augmentation-trailer-rear'],
        payload_by_class=[0, 80, 0, 0],
        comfort_by_class=[0, 69, 72, 82],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lbscr-48ft-augmentation-trailer-rear',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1916,
        intro_month=2,
        retire_year=1941,
        retire_month=5,
        speed=160,
        length=8,
        weight=22,
        axles=4,
        payload=80,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=40,
        cost=703000,
        runningcost=0,
        fixed_cost=840,
        upgrade_price=109200,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['lbscr-48ft-augmentation-trailer-front', 'lbscr-54ft-augmentation-trailer-front', 'lswr-48ft-arc-augmentation-trailer-front', 'lswr-48ft-augmentation-trailer-front', 'lswr-56ft-augmentation-trailer-front'],
        constraint_next=['SR-3SUB(front)', 'LSWR-EMU(front)'],
        payload_by_class=[0, 80, 0, 0],
        comfort_by_class=[0, 69, 72, 82],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lbscr-54ft-augmentation-trailer-front',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1916,
        intro_month=2,
        retire_year=1941,
        retire_month=5,
        speed=160,
        length=9,
        weight=23.8,
        payload=90,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=45,
        cost=713000,
        runningcost=0,
        fixed_cost=849,
        upgrade_price=109200,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-3SUB(rear)', 'LSWR-EMU(rear)'],
        constraint_next=['lbscr-48ft-augmentation-trailer-rear', 'lbscr-54ft-augmentation-trailer-rear', 'lswr-48ft-arc-augmentation-trailer-rear', 'lswr-48ft-augmentation-trailer-rear', 'lswr-56ft-augmentation-trailer-rear'],
        payload_by_class=[0, 90],
        comfort_by_class=[0, 75],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lbscr-54ft-augmentation-trailer-rear',
        waytype='track',
        copyright='Kieron/JamesPetts',
        freight='Passagiere',
        intro_year=1916,
        intro_month=2,
        retire_year=1941,
        retire_month=5,
        speed=160,
        length=9,
        weight=23.8,
        payload=90,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=45,
        cost=713000,
        runningcost=0,
        fixed_cost=849,
        upgrade_price=109200,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['lbscr-48ft-augmentation-trailer-front', 'lbscr-54ft-augmentation-trailer-front', 'lswr-48ft-arc-augmentation-trailer-front', 'lswr-48ft-augmentation-trailer-front', 'lswr-56ft-augmentation-trailer-front'],
        constraint_next=['SR-3SUB(front)', 'LSWR-EMU(front)'],
        payload_by_class=[0, 90],
        comfort_by_class=[0, 75],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-48ft-arc-augmentation-trailer-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1916,
        intro_month=2,
        retire_year=1941,
        retire_month=5,
        speed=160,
        length=8,
        weight=20.0,
        axles=4,
        payload=80,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=40,
        cost=709000,
        runningcost=0,
        fixed_cost=844,
        upgrade_price=109200,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-3SUB(rear)', 'LSWR-EMU(rear)'],
        constraint_next=['lbscr-48ft-augmentation-trailer-rear', 'lbscr-54ft-augmentation-trailer-rear', 'lswr-48ft-arc-augmentation-trailer-rear', 'lswr-48ft-augmentation-trailer-rear', 'lswr-56ft-augmentation-trailer-rear'],
        payload_by_class=[0, 80],
        comfort_by_class=[0, 77],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-48ft-arc-augmentation-trailer-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1916,
        intro_month=2,
        retire_year=1941,
        retire_month=5,
        speed=160,
        length=8,
        weight=20.0,
        axles=4,
        payload=80,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=40,
        cost=709000,
        runningcost=0,
        fixed_cost=844,
        upgrade_price=109200,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['lbscr-48ft-augmentation-trailer-front', 'lbscr-54ft-augmentation-trailer-front', 'lswr-48ft-arc-augmentation-trailer-front', 'lswr-48ft-augmentation-trailer-front', 'lswr-56ft-augmentation-trailer-front'],
        constraint_next=['SR-3SUB(front)', 'LSWR-EMU(front)'],
        payload_by_class=[0, 80],
        comfort_by_class=[0, 77],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-48ft-augmentation-trailer-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1916,
        intro_month=2,
        retire_year=1941,
        retire_month=5,
        speed=160,
        length=8,
        weight=20.0,
        axles=4,
        payload=80,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=40,
        cost=709000,
        runningcost=0,
        fixed_cost=844,
        upgrade_price=109200,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-3SUB(rear)', 'LSWR-EMU(rear)'],
        constraint_next=['lbscr-48ft-augmentation-trailer-rear', 'lbscr-54ft-augmentation-trailer-rear', 'lswr-48ft-arc-augmentation-trailer-rear', 'lswr-48ft-augmentation-trailer-rear', 'lswr-56ft-augmentation-trailer-rear'],
        payload_by_class=[0, 80],
        comfort_by_class=[0, 78],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-48ft-augmentation-trailer-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1916,
        intro_month=2,
        retire_year=1941,
        retire_month=5,
        speed=160,
        length=8,
        weight=20.0,
        axles=4,
        payload=80,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=40,
        cost=709000,
        runningcost=0,
        fixed_cost=844,
        upgrade_price=109200,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['lbscr-48ft-augmentation-trailer-front', 'lbscr-54ft-augmentation-trailer-front', 'lswr-48ft-arc-augmentation-trailer-front', 'lswr-48ft-augmentation-trailer-front', 'lswr-56ft-augmentation-trailer-front'],
        constraint_next=['SR-3SUB(front)', 'LSWR-EMU(front)'],
        payload_by_class=[0, 80],
        comfort_by_class=[0, 78],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-56ft-augmentation-trailer-front',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1916,
        intro_month=2,
        retire_year=1941,
        retire_month=5,
        speed=160,
        length=10,
        weight=22.2,
        axles=4,
        payload=90,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=45,
        cost=720000,
        runningcost=0,
        fixed_cost=857,
        upgrade_price=109200,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-3SUB(rear)', 'LSWR-EMU(rear)'],
        constraint_next=['lbscr-48ft-augmentation-trailer-rear', 'lbscr-54ft-augmentation-trailer-rear', 'lswr-48ft-arc-augmentation-trailer-rear', 'lswr-48ft-augmentation-trailer-rear', 'lswr-56ft-augmentation-trailer-rear'],
        payload_by_class=[0, 90],
        comfort_by_class=[0, 78],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='lswr-56ft-augmentation-trailer-rear',
        waytype='track',
        copyright='JamesPetts',
        freight='Passagiere',
        intro_year=1916,
        intro_month=2,
        retire_year=1941,
        retire_month=5,
        speed=160,
        length=10,
        weight=22.2,
        axles=4,
        payload=90,
        min_loading_time=10,
        max_loading_time=30,
        overcrowded_capacity=45,
        cost=720000,
        runningcost=0,
        fixed_cost=857,
        upgrade_price=109200,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['lbscr-48ft-augmentation-trailer-front', 'lbscr-54ft-augmentation-trailer-front', 'lswr-48ft-arc-augmentation-trailer-front', 'lswr-48ft-augmentation-trailer-front', 'lswr-56ft-augmentation-trailer-front'],
        constraint_next=['SR-3SUB(front)', 'LSWR-EMU(front)'],
        payload_by_class=[0, 90],
        comfort_by_class=[0, 78],
        liverytype=['LSWR-sage', 'SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
