"""sr-maunsell-carriages."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trains/Carriages/sr-maunsell-brake-br.blend'
_UPSTREAM_DAT = 'trains/sr-maunsell-carriages.dat'

SPECS = [
    Vehicle(
        name='SR-Maunsell-Third',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Passagiere',
        intro_year=1926,
        intro_month=9,
        retire_year=1941,
        retire_month=9,
        speed=160,
        length=10,
        weight=32.7,
        axles=4,
        payload=64,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=30,
        cost=633000,
        runningcost=0,
        fixed_cost=754,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        payload_by_class=[0, 64, 0, 0],
        comfort_by_class=[0, 129, 129, 146],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-Maunsell-First',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Passagiere',
        intro_year=1926,
        intro_month=9,
        retire_year=1941,
        retire_month=9,
        speed=160,
        length=10,
        weight=32.7,
        axles=4,
        payload=42,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=0,
        cost=645000,
        runningcost=0,
        fixed_cost=755,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-k-type-kitchen-first'],
        payload_by_class=[0, 0, 0, 42],
        comfort_by_class=[0, 129, 129, 146],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-Maunsell-Composite',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Passagiere',
        intro_year=1926,
        intro_month=9,
        retire_year=1941,
        retire_month=9,
        speed=160,
        length=10,
        weight=32.7,
        axles=4,
        payload=24,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=15,
        cost=640000,
        runningcost=0,
        fixed_cost=755,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first'],
        payload_by_class=[0, 24, 0, 24],
        comfort_by_class=[0, 129, 129, 146],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-Maunsell-Saloon',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Passagiere',
        intro_year=1930,
        intro_month=3,
        retire_year=1941,
        retire_month=9,
        speed=160,
        length=10,
        weight=32.6,
        axles=4,
        payload=56,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=34,
        cost=625000,
        runningcost=0,
        fixed_cost=6744,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        payload_by_class=[0, 56, 0, 0],
        comfort_by_class=[0, 136, 136, 136],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-Maunsell-Dining',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Passagiere',
        intro_year=1926,
        intro_month=9,
        retire_year=1941,
        retire_month=9,
        speed=160,
        length=10,
        weight=32.8,
        axles=4,
        payload=24,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=10,
        catering_level=4,
        cost=675000,
        runningcost=0,
        fixed_cost=18804,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        payload_by_class=[0, 0, 0, 24],
        comfort_by_class=[0, 129, 129, 146],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-Maunsell-Buffet',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Passagiere',
        intro_year=1926,
        intro_month=9,
        retire_year=1941,
        retire_month=9,
        speed=160,
        length=10,
        weight=32.8,
        axles=4,
        payload=24,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=10,
        catering_level=3,
        cost=650000,
        runningcost=0,
        fixed_cost=18774,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        payload_by_class=[0, 24, 0, 0],
        comfort_by_class=[0, 129, 129, 146],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-Maunsell-Brake-rear',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Passagiere',
        intro_year=1926,
        intro_month=9,
        retire_year=1941,
        retire_month=9,
        speed=160,
        length=10,
        weight=32.5,
        axles=4,
        payload=48,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=24,
        cost=633000,
        runningcost=0,
        fixed_cost=5554,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        payload_by_class=[0, 48, 0, 0],
        comfort_by_class=[0, 129, 129, 146],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-Maunsell-Brake-front',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Passagiere',
        intro_year=1926,
        intro_month=9,
        retire_year=1941,
        retire_month=9,
        speed=160,
        length=10,
        weight=32.5,
        axles=4,
        payload=48,
        min_loading_time=25,
        max_loading_time=55,
        overcrowded_capacity=24,
        cost=633000,
        runningcost=0,
        fixed_cost=5554,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first', 'none'],
        payload_by_class=[0, 48, 0, 0],
        comfort_by_class=[0, 129, 129, 146],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-Maunsell-Parcels',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Post',
        intro_year=1928,
        intro_month=3,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=6,
        weight=12,
        axles=2,
        payload=400,
        min_loading_time=45,
        max_loading_time=180,
        cost=633000,
        runningcost=0,
        fixed_cost=264,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-Maunsell-Parcels-Brake',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Post',
        intro_year=1928,
        intro_month=3,
        retire_year=1951,
        retire_month=2,
        speed=160,
        length=6,
        weight=12,
        axles=2,
        payload=300,
        min_loading_time=45,
        max_loading_time=120,
        cost=633000,
        runningcost=0,
        fixed_cost=5064,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first', 'none'],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early', 'BR-Blue'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-Maunsell-Mail',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Post',
        intro_year=1926,
        intro_month=9,
        retire_year=1951,
        retire_month=9,
        speed=160,
        length=10,
        weight=32.3,
        axles=4,
        payload=600,
        min_loading_time=45,
        max_loading_time=180,
        cost=633000,
        runningcost=0,
        fixed_cost=264,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Vehicle(
        name='SR-Maunsell-TPO',
        waytype='track',
        copyright='James/JamesPetts',
        freight='Post',
        intro_year=1926,
        intro_month=9,
        retire_year=1951,
        retire_month=9,
        speed=160,
        length=10,
        weight=32.4,
        axles=4,
        payload=450,
        min_loading_time=45,
        max_loading_time=180,
        catering_level=1,
        cost=675000,
        runningcost=0,
        fixed_cost=24281,
        bidirectional=1,
        can_lead_from_rear=0,
        constraint_prev=['SR-Maunsell-Third', 'SR-Maunsell-Brake-front', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-front', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-front', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-front', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-front-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        constraint_next=['SR-Maunsell-Third', 'SR-Maunsell-Brake-rear', 'SR-Maunsell-Dining', 'SR-Maunsell-Parcels', 'SR-Maunsell-Mail', 'SR-Maunsell-TPO', 'LSWR-Ironclad-Pantry', 'SR-Bulleid-Express-Coach', 'SR-Bulleid-Express-Brake-rear', 'SR-Bulleid-Express-Dining', 'LSWR-Ironclad-Brake-rear', 'LSWR-Ironclad', 'LSWR-Ironclad-Dining', 'LSWR-Ironclad-Mail', 'LSWR-Ironclad-TPO', 'LSWR-corridor', 'LSWR-corridor-brake-rear', 'SR-Maunsell-Saloon', 'SR-Maunsell-Buffet', 'SR-Bulleid-Express-Coach-all-doors', 'SR-Bulleid-Express-brake-rear-all-doors', 'SR-Bulleid-Express-Saloon', 'SR-Bulleid-Express-Buffet', 'LSWR-dining-saloon', 'SR-Maunsell-Parcels-Brake', 'secr-utility-van', 'LSWR-corridor-composite', 'LSWR-Ironclad-First', 'SR-Maunsell-First', 'SR-Maunsell-Composite', 'SR-Bulleid-Express-Coach-all-doors-composite', 'SR-Bulleid-Express-composite', 'SR-Bulleid-Express-first', 'pullman-1928-kitchen-first', 'pullman-1951-kitchen-first', 'pullman-k-type-kitchen-first'],
        liverytype=['SR-Olive-Green', 'SR-Malachite-Green', 'BR-Early'],
        blend=_BLEND,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
