"""autoport stub — see docs/porting.md."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'air/aero-commander-500.blend'
_UPSTREAM_DAT = 'air/aero-commander-500.dat'

SPECS = [
Vehicle(
    name='aero-commander-520',
    waytype='air',
    copyright='Emmanuel Baranger',
    freight='Passagiere',
    engine_type='petrol',
    intro_year=1951,
    intro_month=4,
    retire_year=1986,
    retire_month=8,
    speed=326,
    weight=2.1,
    power=432,
    tractive_effort=3,
    payload=7,
    min_loading_time=1600,
    max_loading_time=1600,
    catering_level=0,
    cost=1800123,
    runningcost=16,
    fixed_cost=51250,
    sound='planelow.wav',
    minimum_runway_length=950,
    range=850,
    constraint_prev=['none'],
    constraint_next=['none'],
    payload_by_class=[0, 0, 7],
    comfort_by_class=[0, 0, 75],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='aero-commander-500',
    waytype='air',
    copyright='Emmanuel Baranger',
    freight='Post',
    engine_type='petrol',
    intro_year=1951,
    intro_month=4,
    retire_year=1986,
    retire_month=8,
    speed=326,
    weight=2.1,
    power=432,
    tractive_effort=3,
    payload=1000,
    min_loading_time=1600,
    max_loading_time=1800,
    catering_level=0,
    cost=1800123,
    runningcost=16,
    fixed_cost=51250,
    sound='planelow.wav',
    minimum_runway_length=950,
    range=850,
    constraint_prev=['none'],
    constraint_next=['none'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='aero-commander-681',
    waytype='air',
    copyright='Emmanuel Baranger',
    freight='Passagiere',
    engine_type='petrol',
    intro_year=1955,
    intro_month=9,
    retire_year=1986,
    retire_month=8,
    speed=370,
    weight=4.3,
    power=456,
    tractive_effort=4,
    payload=11,
    min_loading_time=1650,
    max_loading_time=1650,
    catering_level=0,
    cost=2200000,
    runningcost=20,
    fixed_cost=51528,
    sound='bigpickle51-turboprop.wav',
    minimum_runway_length=1575,
    range=1480,
    constraint_prev=['none'],
    constraint_next=['none'],
    payload_by_class=[0, 0, 11],
    comfort_by_class=[0, 0, 76],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
