"""Parametric ground-baker CLI dispatcher.

Each `grounds/<asset>.py` baker calls `bake_pakset(...)` after
defining its per-cell renderer.  This module owns the argparse
boilerplate, the projection switch (`HexGeom` for hex, `SquareGeom`
for the upstream-Britain pixel-diff harness via
`pak/diff_grounds.py`), the atlas allocation and the PNG/dat emit.

Carved out of `pak.hex_synth` so the projection split (which leads
hex_synth ↔ square_synth into a cycle) and the PIL dependency stay
out of `pak.hex_synth`'s constant-export surface — `pak.viewpoints`
re-exports those constants and is itself reachable from Blender's
bundled Python via `RenderPayload` unpickle, where PIL isn't
installed.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image

from pak.hex_synth import DEFAULT_W, HexGeom
from pak.square_synth import SquareGeom


def repo_root_for(script_path: Path) -> Path:
    """Walk up from `script_path` until we find a Makefile (the repo root
    marker for this pak).  Used purely for pretty `relative_to(...)`
    printouts in the stderr summary and the .dat header comment."""
    for parent in script_path.parents:
        if (parent / "Makefile").is_file():
            return parent
    return script_path.parent


def bake_pakset(*, script_path: Path, asset_name: str, obj_name: str,
                render_cell, iter_entries,
                default_cols: int = 12, argv=None):
    """Run argparse, bake atlas + .dat for one synth-overlay family.

    Hex is the production projection; `--projection square` swaps in
    `square_synth.SquareGeom` for the upstream-Britain pixel-diff
    harness (`pak/diff_grounds.py`).
    """
    p = argparse.ArgumentParser()
    p.add_argument("--w", type=int, default=DEFAULT_W,
                   help=f"raster tile width (default {DEFAULT_W})")
    p.add_argument("--cols", type=int, default=default_cols,
                   help=f"atlas columns (default {default_cols})")
    p.add_argument("--out-dir", type=Path, default=script_path.parent,
                   help="output directory (default: the script's own dir)")
    p.add_argument("--projection", choices=("hex", "square"), default="hex",
                   help="ground geom (hex by default; square for upstream diff)")
    args = p.parse_args(argv)

    args.out_dir.mkdir(parents=True, exist_ok=True)

    if args.projection == "square":
        geom = SquareGeom(raster_w=args.w)
    else:
        geom = HexGeom(raster_w=args.w)
    entries = list(iter_entries(geom))
    n_entries = len(entries)
    rows = (n_entries + args.cols - 1) // args.cols
    cell_w, cell_h = geom.w, geom.h
    atlas = np.zeros((rows * cell_h, args.cols * cell_w, 4), dtype=np.uint8)

    rel_root = repo_root_for(script_path)
    script_rel = script_path.relative_to(rel_root)

    dat_lines = [
        f"# Generated by {script_rel.as_posix()} — do not edit by hand.",
        "Obj=ground",
        f"Name={obj_name}",
        "",
    ]

    for idx, (dat_typ, dat_stage, render_args, comment) in enumerate(entries):
        r, c = divmod(idx, args.cols)
        cell = render_cell(*render_args, geom=geom)
        atlas[r * cell_h:(r + 1) * cell_h,
              c * cell_w:(c + 1) * cell_w] = cell
        dat_lines.append(
            f"Image[{dat_typ}][{dat_stage}]={asset_name}.{r}.{c}\t# {comment}"
        )
    dat_lines.append("")

    png_path = args.out_dir / f"{asset_name}.png"
    dat_path = args.out_dir / f"{asset_name}.dat"
    Image.fromarray(atlas, mode="RGBA").save(str(png_path))
    dat_path.write_text("\n".join(dat_lines))

    def _pretty(p: Path) -> str:
        try:
            return p.relative_to(rel_root).as_posix()
        except ValueError:
            return str(p)

    print(f"{script_rel.as_posix()}: wrote {n_entries} cells into "
          f"{_pretty(png_path)} "
          f"({args.cols}x{rows} atlas, {atlas.shape[1]}x{atlas.shape[0]} px)",
          file=sys.stderr)
    print(f"{script_rel.as_posix()}: wrote .dat with {n_entries} entries -> "
          f"{_pretty(dat_path)}",
          file=sys.stderr)
