"""Shared utilities for the hex pipeline.

Two consumers live in the same module:

* **Blender baker** (`pak/render.py`, `viewpoints.py`):
  pakset-wide projection constants for re-rendering upstream
  Pak128.Britain blends through the hex camera.  These don't appear
  in the regular pak128 sibling — they're Britain-specific blend
  calibration.

* **Parametric ground synth** (`grounds/<asset>/build_pakset.py`):
  per-slope geometry, per-region plane partition, polygon fill, atlas
  + .dat baker.  Mirrors the engine's `descriptor/synth_geometry.h` +
  `descriptor/synth_plane_partition.h`.  Ported from
  `hextrans-pak128/tools/threed/hex_synth.py`; keep the bottom half
  aligned with that file when constants drift, but the file has two
  Britain-only adjustments at the bottom of `bake_pakset` (the
  repo-root walk in `repo_root_for` looks for `.git` and the
  "Generated by" comment carries the `grounds/...` prefix — the
  regular pak puts its bakers under `landscape/grounds/`, this pak
  under `grounds/`).

Engine source-of-truth: `hextrans/src/simutrans/display/hex_proj.h`,
`display/synth_geometry.h`, `descriptor/synth_plane_partition.h`.
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

import numpy as np


# ---- Engine constants (from `src/simutrans/descriptor/synth_geometry.h`) ----

# Tile raster width (output image pixel width for a single hex cell).
# `u = W/4` is the natural lattice unit and drops into the pakset's
# 128x128 cell layout.  Override via --w for other sizes.
DEFAULT_W = 128

# Per-step logical height; matches `env_t::pak_tile_height_step`
# (8 since the 2013 "Pak128 Half Height Conversion").  Combined with
# the unhalved `hex_height_raster_scale_y` this gives a 16-pixel screen
# lift per step at `W = 128`, the legacy pre-hex pak128 z scale.
HEIGHT_STEP = 8

# World-coords corner radius (one entry-edge length).  Bakers express
# asset dimensions in these units so the camera math doesn't depend on W.
# Re-exported from `pak.way` so the constant has a single source of truth
# and `pak.way` (pure-Python ribi vocab + hex geometry) doesn't have to
# pull in numpy via this module just to read it.
from .way import HEX_TILE_RADIUS  # noqa: E402,F401

# Pixel lift per world-z unit, shared with pak128 square dimetric so a
# given 3D part has comparable on-screen height in both projections.
PIXELS_PER_UNIT = DEFAULT_W / math.sqrt(2.0)


def engine_z_per_step(height_step: int = 1, w: int = DEFAULT_W) -> float:
    """World-z value whose hex projection lifts the screen by `height_step`
    engine height steps.  A bespoke render that wants its sloped sprite
    to align with the engine's ground rendering tilts world-z by this
    amount across one height-step's worth of slope.  Engine callers
    pass `z * TILE_HEIGHT_STEP` into `hex_height_raster_scale_y` (see
    `display/viewport.cc`); we mirror that here — a height_step of 1
    is `HEIGHT_STEP` raster units, ~16 px lift at W=128.
    """
    return hex_height_raster_scale_y(height_step * HEIGHT_STEP, w) / PIXELS_PER_UNIT

# Upstream Britain blends are authored against a fixed ortho camera
# with this scale rendering to 128x128 px (per the pak128.Britain
# contributing-graphics thread).  See `INTRA_TILE_PER_BLEND_UNIT`
# below for the consequence.
UPSTREAM_ORTHO_SCALE = 24.0


# ---- Coord systems --------------------------------------------------------
#
# Three coord systems show up in the bake pipeline; mixing them up is the
# usual source of "the strand renders 5x too big / too small" bugs.
#
# * **Tile coords** — integers.  Adjacent tile is `(x+1, y)` in either
#   hex or square; no projection difference lives here.  Outside this
#   module's scope.
# * **Intra-tile coords** — continuous within one tile.  Tile edge =
#   1 intra-tile unit in both projections (`HEX_TILE_RADIUS = 1` for
#   hex's entry-edge length, also the square tile side).  This is
#   where the cross-projection invariant holds: a way of width 0.4
#   spans 40% of an edge in *both* projections, so the way is
#   complete at every tile boundary regardless of which view the
#   game is rendered through.
# * **Blend coords** — upstream pak128.Britain's authoring frame
#   where `ortho_scale = UPSTREAM_ORTHO_SCALE` is the 15 m ruler.
#   The blend's native unit doesn't equal the intra-tile unit; the
#   conversion below.
#
# The conversion that lands the blend's authored sizes (rail gauge,
# tie pitch, ballast extent, vehicle dimensions) at the right
# intra-tile size is:

INTRA_TILE_PER_BLEND_UNIT = (2.0 * HEX_TILE_RADIUS) / UPSTREAM_ORTHO_SCALE
# = 1/12 at the current pakset constants.  This is the same ratio
# `pak.render::_compute_fit` applies under `fit_kind="hex"` for
# vehicles, and the same ratio the way bake will switch to once
# multi-atom-per-chord composition lands (TODO.md → "Way multi-
# atom-per-chord composition").


# Sun: from south (-y), 60 deg above horizon. Light travels north and
# downward.  Used to set a SUN lamp's -Z so shading stays consistent
# across facings (model rotates, sun does not).
SUN_DIR = (
    0.0,
    math.cos(math.radians(60.0)),
    -math.sin(math.radians(60.0)),
)


def hex_proj_shear() -> tuple[tuple[float, ...], ...]:
    """4x4 matrix mapping world (x, y, z) into a render frame in which a
    standard ortho-from-south Blender camera reproduces the hex
    projection.

    Derivation: the engine's projection is
        sx = w/2 + x * (w / (2R))
        sy = base_y - y * (w / (2R sqrt(3))) - z * PIXELS_PER_UNIT
    The y- and z-coefficients on screen-y differ, so a single isotropic
    Blender ortho cannot reproduce it without pre-distortion.  After the
    shear below, a camera with `ortho_scale = 2R` and image width `W`
    looking down +Y sees the right pixels:
        sx_blender = W/2 + x * (W / (2R))                  -> same as engine
        sy_blender = H/2 + (y/sqrt(3) + z*sqrt(2)) * (W/(2R))
                   = H/2 + y * W/(2R sqrt(3)) + z * (W*sqrt(2)/(2R))
                   = H/2 + y * w-coef + z * (W*sqrt(2)/2)
                   z-coef at R=1, W=128: 128*sqrt(2)/2 = 64*sqrt(2) = 90.51
                   PIXELS_PER_UNIT = 128/sqrt(2) = 90.51  -> match
    """
    inv_sqrt3 = 1.0 / math.sqrt(3.0)
    sqrt2 = math.sqrt(2.0)
    # Column-major would matter for some math libs; Blender's `Matrix`
    # constructor takes row-major and we return the same.
    return (
        (1.0, 0.0,       0.0,   0.0),
        (0.0, 1.0,       0.0,   0.0),
        (0.0, inv_sqrt3, sqrt2, 0.0),
        (0.0, 0.0,       0.0,   1.0),
    )


# =========================================================================
# Parametric ground synth — ported from
# `hextrans-pak128/tools/threed/hex_synth.py`.
# =========================================================================


def tile_raster_scale_y(v: int, rh: int) -> int:
    # `simconst.h`: `tile_raster_scale_y(v, rh)   (((v)*(rh)) >> 6)`
    return (v * rh) >> 6


def hex_height_raster_scale_y(height_steps: int, w: int) -> int:
    # `display/hex_proj.h`: matches the legacy square
    # `tile_raster_scale_y` so base-elevation, per-corner relief and
    # object z-offsets share one projection.
    return tile_raster_scale_y(height_steps, w)


# ---- Hex corner indices (matching `hex_corner_t::type` in dataobj/ribi.h) --

E, SE, SW, W_C, NW, NE = 0, 1, 2, 3, 4, 5
CORNER_COUNT = 6


# ---- Hex way axes (matching `hex_way_axis_t::type` in display/hex_proj.h) --

NS, NE_SW, NW_SE = 0, 1, 2


# Depth-clip plane normals (Front-side, in world coords).  See engine
# spec in `display/hex_proj.h` ("Depth-clip plane spec").

_SQRT3 = math.sqrt(3.0)

HEX_DEPTH_CLIP_NORMAL = {
    NS:    ( 1.0,           0.0          ),
    NE_SW: ( 0.5,          -_SQRT3 / 2.0 ),
    NW_SE: (-0.5,          -_SQRT3 / 2.0 ),
}


def front_back_split(world_x, world_y, axis: int):
    """True for the Front layer, False for Back.  Vectorises over numpy."""
    nx, ny = HEX_DEPTH_CLIP_NORMAL[axis]
    return nx * np.asarray(world_x) + ny * np.asarray(world_y) > 0.0


# Raw slope_t per-corner weights.  `slope = sum(ch[i] * CORNER_WEIGHTS[i])`.
CORNER_WEIGHTS = (1, 4, 16, 64, 256, 1024)


def decode_corner_heights(slope: int) -> list[int]:
    return [(slope // CORNER_WEIGHTS[i]) % 4 for i in range(CORNER_COUNT)]


# ---- synth_hex_geometry replication (from synth_geometry.h) ---------------

class HexGeom:
    """The output of `synth_overlay::synth_hex_geometry(u, height_step)`.

    Mirrors the C++ struct field for field — kept verbose rather than
    folded into a function so the call sites read like the engine's.

    Also implements the `Geom` interface consumed by the generic
    partition / region / outline helpers below (`corner_count`,
    `corner_world_xy`, `corner_projected_xy`, `all_chords`,
    `decode_corner_heights`, `iter_valid_slopes`), so the same
    helpers work against `SquareGeom` (see `square.py`) without
    branching on projection.
    """

    # ---- Geom interface (projection-agnostic constants) -------------------
    corner_count = CORNER_COUNT
    corner_labels = ("E", "SE", "SW", "W", "NW", "NE")
    full_path: tuple[int, ...]    # set in __init__ once HEX_FULL_PATH is defined

    def __init__(self, raster_w: int = DEFAULT_W, height_step: int = HEIGHT_STEP):
        u = raster_w // 4
        self.u = u
        self.w = 4 * u
        self.lift = hex_height_raster_scale_y(height_step, self.w)
        self.top_pad = 4 * self.lift
        self.h = 2 * u + self.top_pad
        self.top_y = self.top_pad
        self.mid_y = self.top_pad + u
        self.bot_y = self.top_pad + 2 * u - 1

        # Vertex screen X (independent of slope) and Y baseline (no lift).
        self.vx = [0] * CORNER_COUNT
        self.vy_base = [0] * CORNER_COUNT
        self.vx[E ] = self.w - 1; self.vy_base[E ] = self.mid_y
        self.vx[SE] = 3 * u;      self.vy_base[SE] = self.bot_y
        self.vx[SW] = u;          self.vy_base[SW] = self.bot_y
        self.vx[W_C] = 0;         self.vy_base[W_C] = self.mid_y
        self.vx[NW] = u;          self.vy_base[NW] = self.top_y
        self.vx[NE] = 3 * u;      self.vy_base[NE] = self.top_y

    def lifted_vy(self, slope: int) -> list[int]:
        """All 6 corner screen-y values for `slope`, with corner lift applied.

        Y grows down; corner height lifts UP, so subtract `ch[i]*lift`.
        """
        ch = self.decode_corner_heights(slope)
        return [self.vy_base[i] - ch[i] * self.lift for i in range(self.corner_count)]

    # ---- Geom interface --------------------------------------------------

    @staticmethod
    def decode_corner_heights(slope: int) -> list[int]:
        return decode_corner_heights(slope)

    @staticmethod
    def iter_valid_slopes():
        return iter_valid_slopes()

    @staticmethod
    def slope_is_valid(slope: int) -> bool:
        return slope_is_valid(slope)

    # `corner_world_xy`, `corner_projected_xy`, `all_chords`, `full_path`
    # are assigned at module scope below, once the hex tables they alias
    # are defined.


# Canonical corner traversal paths matching `synth_overlay.cc`:
#
#   FULL_PATH  — closed 6-edge hex outline (engine debug-grid).
#   BACK_PATH  — open polyline of the 3 north-side edges (E → NE → NW → W).
#   FRONT_PATH — open polyline of the 3 south-side edges (E → SE → SW → W).
HEX_FULL_PATH  = (E, SE, SW, W_C, NW, NE)
HEX_BACK_PATH  = (E, NE, NW, W_C)
HEX_FRONT_PATH = (E, SE, SW, W_C)


# Bind the Geom-interface tables onto HexGeom (deferred from the class body
# because they reference module-scope tables defined below the class).
# Set later, once HEX_ALL_CHORDS and HEX_CORNER_PROJECTED_X/Y are in scope.


# ---- Cliff cells ----------------------------------------------------------

CLIFF_WALL_ENDPOINTS = (
    (W_C, NW),  # wall 0: NW edge
    (NW,  NE),  # wall 1: N  edge
    (NE,  E ),  # wall 2: NE edge
    (E,   SE),  # wall 3: SE edge
    (SE,  SW),  # wall 4: S  edge
    (SW,  W_C), # wall 5: SW edge
)
CLIFF_IMAGE_COUNT = 11  # per-wall image slots; index 0 = "no cliff"


def decode_cliff_index(index: int) -> tuple[int, int]:
    """`(h1, h2)` for a cliff cell's two endpoint lifts.

    Indices 1..8 are the standard `index = h1 + 3*h2` encoding;
    indices 9 and 10 are placeholder half-cliffs for the legacy
    double-height notch.
    """
    if index == 10:
        return 1, 0
    if index == 9:
        return 0, 1
    return index % 3, index // 3


def render_cliff_cell(wall: int, h1: int, h2: int, color,
                      geom: HexGeom | None = None) -> "np.ndarray":
    """Render one cliff-face cell into a HxWx4 RGBA buffer."""
    if geom is None:
        geom = HexGeom()

    buf = np.zeros((geom.h, geom.w, 4), dtype=np.uint8)
    if h1 == 0 and h2 == 0:
        return buf

    a, b = CLIFF_WALL_ENDPOINTS[wall]
    ax, ay = geom.vx[a], geom.vy_base[a]
    bx, by = geom.vx[b], geom.vy_base[b]

    xs = [ax, bx, bx,                   ax                  ]
    ys = [ay, by, by - h2 * geom.lift,  ay - h1 * geom.lift ]
    fill_polygon(buf, xs, ys, color)
    seal_horizontal_edges(buf, xs, ys, color)
    return buf


# ---- Way-axis geometry (nasyp / way-cut) ----------------------------------

WAY_HALF_WIDTH = 0.5

# Tile corner positions in world XY.  Hex circumradius `HEX_TILE_RADIUS = 1`
# so corners sit at distance 1 from origin and 1 world unit = 1 edge length.
HEX_CORNER_XY = [
    ( 1.0,        0.0      ),  # E   (0)
    ( 0.5,       -_SQRT3 / 2.0),  # SE  (1)
    (-0.5,       -_SQRT3 / 2.0),  # SW  (2)
    (-1.0,        0.0      ),  # W_C (3)
    (-0.5,        _SQRT3 / 2.0),  # NW  (4)
    ( 0.5,        _SQRT3 / 2.0),  # NE  (5)
]

# Touched-edge corner indices per axis: `((a0, a1), (b0, b1))`.
AXIS_EDGE_CORNERS = {
    NS:    ((NW,  NE), (SE, SW )),
    NE_SW: ((NE,  E ), (SW, W_C)),
    NW_SE: ((W_C, NW), (E,  SE )),
}

# Off-axis corners per axis: `(off_pos, off_neg)`.
AXIS_OFF_AXIS_CORNERS = {
    NS:    (E,  W_C),
    NE_SW: (SE, NW ),
    NW_SE: (NE, SW ),
}


def axis_corners(slope: int, axis: int):
    """Return `(a0, a1, b0, b1)` corner heights for `axis` on `slope`."""
    ch = decode_corner_heights(slope)
    (a0_i, a1_i), (b0_i, b1_i) = AXIS_EDGE_CORNERS[axis]
    return ch[a0_i], ch[a1_i], ch[b0_i], ch[b1_i]


def axis_h_way(slope: int, axis: int):
    """Return `(h_edge1, h_edge2)` for the way's chord on `axis`, or
    `None` if the axis is not way-buildable on `slope`."""
    a0, a1, b0, b1 = axis_corners(slope, axis)
    if a0 != a1 or b0 != b1:
        return None
    if abs(a0 - b0) <= 2:
        return a0, b0
    return None


def axis_edge_midpoints(axis: int):
    """`(mp1, mp2)` for the touched-edge midpoints (world XY)."""
    (a0_i, a1_i), (b0_i, b1_i) = AXIS_EDGE_CORNERS[axis]
    mp1 = ((HEX_CORNER_XY[a0_i][0] + HEX_CORNER_XY[a1_i][0]) / 2.0,
           (HEX_CORNER_XY[a0_i][1] + HEX_CORNER_XY[a1_i][1]) / 2.0)
    mp2 = ((HEX_CORNER_XY[b0_i][0] + HEX_CORNER_XY[b1_i][0]) / 2.0,
           (HEX_CORNER_XY[b0_i][1] + HEX_CORNER_XY[b1_i][1]) / 2.0)
    return mp1, mp2


def axis_unit_vector(axis: int):
    mp1, mp2 = axis_edge_midpoints(axis)
    dx, dy = mp2[0] - mp1[0], mp2[1] - mp1[1]
    n = math.sqrt(dx * dx + dy * dy)
    return (dx / n, dy / n)


def axis_perp_vector(axis: int):
    """Unit perpendicular (90° CCW from the axis direction)."""
    ux, uy = axis_unit_vector(axis)
    return (-uy, ux)


# ---- Slope validity -------------------------------------------------------

def slope_is_valid(slope: int) -> bool:
    """Whether a raw slope_t encoding is a normalised pakset slope."""
    ch = decode_corner_heights(slope)
    if min(ch) != 0:
        return False
    for i in range(CORNER_COUNT):
        j = (i + 1) % CORNER_COUNT
        if ch[i] > ch[j] + 1 or ch[j] > ch[i] + 1:
            return False
    return True


def iter_valid_slopes():
    for slope in range(4096):
        if slope_is_valid(slope):
            yield slope


def slope_is_way(slope: int) -> bool:
    """Whether a way (road, rail, …) can be laid across this hex slope."""
    ch = decode_corner_heights(slope)
    return (_is_way_axis(ch, ch[NW], ch[NE], ch[SE], ch[SW]) or
            _is_way_axis(ch, ch[NE], ch[E],  ch[SW], ch[W_C]) or
            _is_way_axis(ch, ch[W_C], ch[NW], ch[E], ch[SE]))


def _is_way_axis(ch: list[int], a0: int, a1: int, b0: int, b1: int) -> bool:
    if a0 == a1 and b0 == b1 and abs(a0 - b0) <= 1:
        return True  # ramp
    if any(c >= 2 for c in ch):
        return False  # double-corner: only the ramp case admits a way
    a_lo, a_hi = min(a0, a1), max(a0, a1)
    b_lo, b_hi = min(b0, b1), max(b0, b1)
    return max(a_lo, b_lo) <= min(a_hi, b_hi)


# ---- Lambert lighting (from synth_geometry.h) -----------------------------

LIGHT = (-1.0, 1.0, 2.0)


def lambert_brightness(nx: float, ny: float, nz: float) -> int:
    Lx, Ly, Lz = LIGHT
    L_norm = math.sqrt(Lx * Lx + Ly * Ly + Lz * Lz)
    flat_cos = Lz / L_norm

    n_norm = math.sqrt(nx * nx + ny * ny + nz * nz)
    if n_norm <= 0.0:
        return 256
    cos_theta = (nx * Lx + ny * Ly + nz * Lz) / (n_norm * L_norm)
    brightness = 256 + int((cos_theta - flat_cos) * 384.0)
    if brightness < 128:
        brightness = 128
    if brightness > 352:
        brightness = 352
    return brightness


# ---- Plane partitioning (from synth_plane_partition.h) --------------------

HEX_ALL_CHORDS = [
    (0, 2), (0, 3), (0, 4),
    (1, 3), (1, 4), (1, 5),
    (2, 4), (2, 5), (3, 5),
]

HEX_CORNER_PROJECTED_X = [ 1,  0, -1, -1,  0,  1]
HEX_CORNER_PROJECTED_Y = [ 0,  1,  1,  0, -1, -1]


# Finish the HexGeom Geom interface now that the hex tables exist.
HexGeom.corner_world_xy = HEX_CORNER_XY
HexGeom.corner_projected_xy = list(zip(HEX_CORNER_PROJECTED_X, HEX_CORNER_PROJECTED_Y))
HexGeom.all_chords = HEX_ALL_CHORDS
HexGeom.full_path = HEX_FULL_PATH


def _chords_cross(c1, c2) -> bool:
    a, b = sorted(c1)
    c, d = sorted(c2)
    return (a < c < b < d) or (c < a < d < b)


def _compute_regions_from_chord_mask(geom, mask: int):
    """Walk `geom.all_chords` masked by `mask`, returning the polygon
    regions or `None` if the mask is inconsistent.

    Mirrors the engine's `synth_plane_partition.h::compute_regions_from_chord_mask`,
    parameterised over `geom.corner_count` (4 for square, 6 for hex) and
    `geom.all_chords`."""
    n = geom.corner_count
    chords = geom.all_chords
    regions: list[list[int]] = [list(range(n))]
    for ci in range(len(chords)):
        if not (mask & (1 << ci)):
            continue
        a, b = chords[ci]
        split_idx = -1
        for ri, reg in enumerate(regions):
            if a in reg and b in reg:
                split_idx = ri
                break
        if split_idx < 0 or len(regions) >= n:
            return None
        reg = regions[split_idx]
        ai = reg.index(a)
        bi = reg.index(b)
        s = min(ai, bi)
        e = max(ai, bi)
        r1 = reg[s:e + 1]
        r2 = reg[e:] + reg[:s + 1]
        if len(r1) > n or len(r2) > n:
            return None
        regions[split_idx] = r1
        regions.append(r2)
    return regions


def _region_coplanar(geom, region: list[int], ch: list[int]) -> bool:
    n = len(region)
    if n <= 3:
        return True
    px = [geom.corner_projected_xy[i][0] for i in range(geom.corner_count)]
    py = [geom.corner_projected_xy[i][1] for i in range(geom.corner_count)]
    for a in range(n):
        for b in range(a + 1, n):
            for c in range(b + 1, n):
                for d in range(c + 1, n):
                    ia, ib, ic, id_ = region[a], region[b], region[c], region[d]
                    v1x = px[ib] - px[ia]
                    v1y = py[ib] - py[ia]
                    v1z = ch[ib] - ch[ia]
                    v2x = px[ic] - px[ia]
                    v2y = py[ic] - py[ia]
                    v2z = ch[ic] - ch[ia]
                    v3x = px[id_] - px[ia]
                    v3y = py[id_] - py[ia]
                    v3z = ch[id_] - ch[ia]
                    det = (v1x * (v2y * v3z - v2z * v3y)
                           - v1y * (v2x * v3z - v2z * v3x)
                           + v1z * (v2x * v3y - v2y * v3x))
                    if det != 0:
                        return False
    return True


def _region_flat_horizontal(region: list[int], ch: list[int]) -> bool:
    return all(ch[v] == ch[region[0]] for v in region)


def _region_projected_area2(geom, region: list[int]) -> int:
    a2 = 0
    n = len(region)
    px = [geom.corner_projected_xy[i][0] for i in range(geom.corner_count)]
    py = [geom.corner_projected_xy[i][1] for i in range(geom.corner_count)]
    for i in range(n):
        j = (i + 1) % n
        a2 += (px[region[i]] * py[region[j]]
               - px[region[j]] * py[region[i]])
    return abs(a2)


def find_min_partition(slope: int, geom=None) -> list[list[int]]:
    """Engine-equivalent minimum-region partition for a slope.

    `geom` selects the projection (defaults to `HexGeom()`).  The
    algorithm is projection-independent: it sweeps every chord-mask
    subset of `geom.all_chords`, drops masks with crossing chords or
    non-coplanar regions, and minimises (region count, -flat_area).
    """
    if geom is None:
        geom = HexGeom()
    ch = geom.decode_corner_heights(slope)
    chords = geom.all_chords
    best: list[list[int]] | None = None
    best_count = geom.corner_count + 1
    best_flat_area = -1

    for mask in range(1 << len(chords)):
        chords_set = [chords[i] for i in range(len(chords)) if mask & (1 << i)]
        ok = True
        for i in range(len(chords_set)):
            for j in range(i + 1, len(chords_set)):
                if _chords_cross(chords_set[i], chords_set[j]):
                    ok = False
                    break
            if not ok:
                break
        if not ok:
            continue

        cand = _compute_regions_from_chord_mask(geom, mask)
        if cand is None:
            continue
        if not all(_region_coplanar(geom, r, ch) for r in cand):
            continue

        flat_area = sum(_region_projected_area2(geom, r)
                        for r in cand if _region_flat_horizontal(r, ch))
        if (len(cand) < best_count
                or (len(cand) == best_count and flat_area > best_flat_area)):
            best = cand
            best_count = len(cand)
            best_flat_area = flat_area
            if best_count == 1:
                break

    return best if best is not None else [list(range(geom.corner_count))]


def trivial_partition(geom=None) -> list[list[int]]:
    if geom is None:
        geom = HexGeom()
    return [list(range(geom.corner_count))]


# ---- Polygon fill (independent re-implementation of synth_overlay.cc) -----

def fill_polygon(buf: np.ndarray, xs: list[int], ys: list[int],
                 color_rgb: tuple[int, int, int]):
    """Even-odd half-open scanline fill into an HxWx4 RGBA buffer."""
    h, w, _ = buf.shape
    n = len(xs)
    y_min = max(0, min(ys))
    y_max = min(h - 1, max(ys))

    for y in range(y_min, y_max + 1):
        xints: list[int] = []
        for i in range(n):
            j = (i + 1) % n
            ya, yb = ys[i], ys[j]
            if ya == yb:
                continue  # skip horizontal edges (parity)
            y_lo = min(ya, yb)
            y_hi = max(ya, yb)
            if y < y_lo or y >= y_hi:
                continue
            xa, xb = xs[i], xs[j]
            num = (y - ya) * (xb - xa)
            den = (yb - ya)
            q = abs(num) // abs(den)
            if (num < 0) ^ (den < 0):
                q = -q
            xints.append(xa + q)
        xints.sort()
        for k in range(0, len(xints) - 1, 2):
            x0 = max(0, xints[k])
            x1 = min(w - 1, xints[k + 1])
            if x0 <= x1:
                buf[y, x0:x1 + 1, 0] = color_rgb[0]
                buf[y, x0:x1 + 1, 1] = color_rgb[1]
                buf[y, x0:x1 + 1, 2] = color_rgb[2]
                buf[y, x0:x1 + 1, 3] = 255


def seal_horizontal_edges(buf: np.ndarray, xs: list[int], ys: list[int],
                          color_rgb: tuple[int, int, int]):
    """Fill horizontal polygon edges that the parity scanline skips."""
    h, w, _ = buf.shape
    n = len(xs)
    for i in range(n):
        j = (i + 1) % n
        if ys[i] != ys[j]:
            continue
        y = ys[i]
        if y < 0 or y >= h:
            continue
        x0 = min(xs[i], xs[j])
        x1 = max(xs[i], xs[j])
        x0 = max(0, x0)
        x1 = min(w - 1, x1)
        buf[y, x0:x1 + 1, 0] = color_rgb[0]
        buf[y, x0:x1 + 1, 1] = color_rgb[1]
        buf[y, x0:x1 + 1, 2] = color_rgb[2]
        buf[y, x0:x1 + 1, 3] = 255


# ---- Line drawing (from synth_overlay.cc draw_line) -----------------------

def draw_line(buf: np.ndarray, x0: int, y0: int, x1: int, y1: int,
              color_rgb: tuple[int, int, int]):
    """Bresenham line into an HxWx4 RGBA buffer with full-alpha output."""
    h, w, _ = buf.shape
    dx = abs(x1 - x0)
    dy = -abs(y1 - y0)
    sx = 1 if x0 < x1 else -1
    sy = 1 if y0 < y1 else -1
    err = dx + dy
    while True:
        if 0 <= x0 < w and 0 <= y0 < h:
            buf[y0, x0, 0] = color_rgb[0]
            buf[y0, x0, 1] = color_rgb[1]
            buf[y0, x0, 2] = color_rgb[2]
            buf[y0, x0, 3] = 255
        if x0 == x1 and y0 == y1:
            break
        e2 = 2 * err
        if e2 >= dy:
            err += dy
            x0 += sx
        if e2 <= dx:
            err += dx
            y0 += sy


# ---- Per-pixel barycentric helpers (shared by alpha-bake renderers) -------

def hash_noise01(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    """Vectorised position-deterministic noise in `[0.0, 1.0)`."""
    h = ((x.astype(np.uint32) * np.uint32(73856093))
         ^ (y.astype(np.uint32) * np.uint32(19349663)))
    h ^= h >> np.uint32(13)
    h *= np.uint32(1274126177)
    h ^= h >> np.uint32(16)
    return ((h & np.uint32(0xFFFF)).astype(np.float32)
            / np.float32(65536.0))


def centre_fan_field(slope: int, corner_values, centre_value: float,
                     geom) -> np.ndarray:
    """Per-pixel barycentric mix over the slope's centre-fan triangles."""
    vx = np.array(geom.vx, dtype=np.float32)
    vy = np.array(geom.lifted_vy(slope), dtype=np.float32)
    weight = np.asarray(corner_values, dtype=np.float32)

    cx = float(vx.mean())
    cy = float(vy.mean())
    cw = float(centre_value)

    xs = np.arange(geom.w, dtype=np.float32) + 0.5
    ys = np.arange(geom.h, dtype=np.float32) + 0.5
    px, py = np.meshgrid(xs, ys)

    field = np.full((geom.h, geom.w), cw, dtype=np.float32)
    assigned = np.zeros((geom.h, geom.w), dtype=bool)

    n = geom.corner_count
    for i in range(n):
        j = (i + 1) % n
        ax, ay, aw = vx[i], vy[i], weight[i]
        bx, by, bw = vx[j], vy[j], weight[j]
        denom = (by - cy) * (ax - cx) + (cx - bx) * (ay - cy)
        if denom == 0.0:
            continue
        u = ((by - cy) * (px - cx) + (cx - bx) * (py - cy)) / denom
        v = ((cy - ay) * (px - cx) + (ax - cx) * (py - cy)) / denom
        w = 1.0 - u - v
        in_tri = (u >= 0) & (v >= 0) & (w >= 0) & ~assigned
        field[in_tri] = (u[in_tri] * aw + v[in_tri] * bw + w[in_tri] * cw)
        assigned |= in_tri

    return field


def iter_region_polygons(slope: int, geom):
    """Yield `(region, xs, ys)` for each polygon in `find_min_partition(slope)`."""
    vy = geom.lifted_vy(slope)
    for region in find_min_partition(slope, geom):
        if len(region) < 3:
            continue
        xs = [geom.vx[i] for i in region]
        ys = [vy[i] for i in region]
        yield region, xs, ys


def face_normal_brightness(pts) -> int:
    """Lambert brightness (256 = 1.0×) for a polygonal face given its
    vertices in the engine's Lambert frame."""
    p0 = pts[0]
    for k in range(2, len(pts)):
        p1, p2 = pts[k - 1], pts[k]
        ax, ay, az = p1[0] - p0[0], p1[1] - p0[1], p1[2] - p0[2]
        bx, by, bz = p2[0] - p0[0], p2[1] - p0[1], p2[2] - p0[2]
        nx = ay * bz - az * by
        ny = az * bx - ax * bz
        nz = ax * by - ay * bx
        if nx == 0.0 and ny == 0.0 and nz == 0.0:
            continue
        if nz < 0.0:
            nx, ny, nz = -nx, -ny, -nz
        return lambert_brightness(nx, ny, nz)
    return lambert_brightness(0.0, 0.0, 1.0)


def region_brightness(region: list[int], slope: int, geom) -> int:
    """Lambert brightness (256 = 1.0×) for one coplanar region."""
    ch = geom.decode_corner_heights(slope)
    vy = geom.lifted_vy(slope)
    pts = [(geom.vx[i], vy[i], ch[i] * geom.lift) for i in region]
    return face_normal_brightness(pts)


def silhouette_mask(slope: int, geom) -> np.ndarray:
    """Boolean (H, W) mask of pixels inside the slope silhouette."""
    buf = np.zeros((geom.h, geom.w, 4), dtype=np.uint8)
    sentinel = (1, 1, 1)
    for _region, xs, ys in iter_region_polygons(slope, geom):
        fill_polygon(buf, xs, ys, sentinel)
        seal_horizontal_edges(buf, xs, ys, sentinel)
    return buf[..., 3] != 0


def rasterise_outline(buf: np.ndarray, geom, slope: int,
                      path, color_rgb: tuple[int, int, int],
                      closed: bool):
    """Walk `path` (a sequence of corner indices), drawing each edge."""
    vy = geom.lifted_vy(slope)
    n_edges = len(path) if closed else len(path) - 1
    for i in range(n_edges):
        a = path[i]
        b = path[(i + 1) % len(path)]
        draw_line(buf, geom.vx[a], vy[a], geom.vx[b], vy[b], color_rgb)


# ---- Atlas + bake helpers -------------------------------------------------
#
# `bake_pakset` runs the bake → atlas + .dat pipeline shared by every
# parametric ground family.  Each per-asset baker is a single
# `grounds/<asset>.py` file (Britain convention — script and emitted
# .dat/.png siblings under `grounds/`) that defines a `render_cell`
# function and calls `bake_pakset` from `__main__`.


def repo_root_for(script_path: Path) -> Path:
    """Walk up from `script_path` until we find a Makefile (the repo root
    marker for this pak).  Used purely for pretty `relative_to(...)`
    printouts in the stderr summary and the .dat header comment."""
    for parent in script_path.parents:
        if (parent / "Makefile").is_file():
            return parent
    return script_path.parent


def slope_keyed_entries(halves: int = 1, slope_filter=None):
    """Default `iter_entries` for slope-keyed assets.

    Uses `geom.iter_valid_slopes()` / `geom.decode_corner_heights()`,
    so the same factory drives both `HexGeom` and `SquareGeom` runs;
    the per-cell comment names corners via `geom.corner_labels`.
    """
    def gen(geom):
        labels = geom.corner_labels
        for half in range(halves):
            for slope in geom.iter_valid_slopes():
                if slope_filter is not None and not slope_filter(slope):
                    continue
                ch = geom.decode_corner_heights(slope)
                side = "" if halves == 1 else ("front " if half == 0 else "back ")
                inner = " ".join(f"{labels[i]}={ch[i]}" for i in range(geom.corner_count))
                comment = f"{side}corners=({inner})"
                yield slope, half, (slope, half), comment
    return gen


def bake_pakset(*, script_path: Path, asset_name: str, obj_name: str,
                render_cell, iter_entries,
                default_cols: int = 12, argv=None):
    """Run argparse, bake atlas + .dat for one synth-overlay family.

    Hex is the production projection; `--projection square` swaps in
    `square_synth.SquareGeom` for the upstream-Britain pixel-diff
    harness (`pak/diff_grounds.py`).
    """
    p = argparse.ArgumentParser()
    p.add_argument("--w", type=int, default=DEFAULT_W,
                   help=f"raster tile width (default {DEFAULT_W})")
    p.add_argument("--cols", type=int, default=default_cols,
                   help=f"atlas columns (default {default_cols})")
    p.add_argument("--out-dir", type=Path, default=script_path.parent,
                   help="output directory (default: the script's own dir)")
    p.add_argument("--projection", choices=("hex", "square"), default="hex",
                   help="ground geom (hex by default; square for upstream diff)")
    args = p.parse_args(argv)

    args.out_dir.mkdir(parents=True, exist_ok=True)

    if args.projection == "square":
        from pak.square_synth import SquareGeom
        geom = SquareGeom(raster_w=args.w)
    else:
        geom = HexGeom(raster_w=args.w)
    entries = list(iter_entries(geom))
    n_entries = len(entries)
    rows = (n_entries + args.cols - 1) // args.cols
    cell_w, cell_h = geom.w, geom.h
    atlas = np.zeros((rows * cell_h, args.cols * cell_w, 4), dtype=np.uint8)

    rel_root = repo_root_for(script_path)
    script_rel = script_path.relative_to(rel_root)

    dat_lines = [
        f"# Generated by {script_rel.as_posix()} — do not edit by hand.",
        "Obj=ground",
        f"Name={obj_name}",
        "",
    ]

    for idx, (dat_typ, dat_stage, render_args, comment) in enumerate(entries):
        r, c = divmod(idx, args.cols)
        cell = render_cell(*render_args, geom=geom)
        atlas[r * cell_h:(r + 1) * cell_h,
              c * cell_w:(c + 1) * cell_w] = cell
        dat_lines.append(
            f"Image[{dat_typ}][{dat_stage}]={asset_name}.{r}.{c}\t# {comment}"
        )
    dat_lines.append("")

    png_path = args.out_dir / f"{asset_name}.png"
    dat_path = args.out_dir / f"{asset_name}.dat"
    from PIL import Image
    Image.fromarray(atlas, mode="RGBA").save(str(png_path))
    dat_path.write_text("\n".join(dat_lines))

    def _pretty(p: Path) -> str:
        try:
            return p.relative_to(rel_root).as_posix()
        except ValueError:
            return str(p)

    print(f"{script_rel.as_posix()}: wrote {n_entries} cells into "
          f"{_pretty(png_path)} "
          f"({args.cols}x{rows} atlas, {atlas.shape[1]}x{atlas.shape[0]} px)",
          file=sys.stderr)
    print(f"{script_rel.as_posix()}: wrote .dat with {n_entries} entries -> "
          f"{_pretty(dat_path)}",
          file=sys.stderr)
