"""Fishing Port 1750 + 1840 + 1910 + 1945 + 1975 — shared-sprite chain.

All five eras render off the typo-named upstream
`industries/fishihng-port.blend` (and its `-snow` sibling).  The
five eras share the `fishing-port.*` atlas so one bake covers
the chain.
"""

from pak.bake import bake_main
from pak.dat import Factory

_BLEND = "industries/fishihng-port.blend"
_BLEND_WINTER = "industries/fishihng-port-snow.blend"
_UPSTREAM_DAT = "industry/fishing-port.dat"

SPECS = [
    Factory(
        name="FishPort1750",
        copyright="James",
        seasons=2,
        level=3,
        intro_year=1750, intro_month=1,
        retire_year=1840, retire_month=4,
        needs_ground=1,
        climates="water",
        population_and_visitor_demand_capacity=0,
        # Guessed employment figures.
        employment_capacity=40,
        mail_demand=2,
        class_proportion_jobs=[15, 80, 5, 0, 0],
        upgrade=["FishPort1840", "FishPort1910", "FishPort1945", "FishPort1975"],
        location="shore_city",
        max_distance_to_consumer=50,
        productivity=9,
        range=6,
        distributionweight=4,
        mapcolor=7,
        electricity_amount=0,
        electricity_boost=0,
        passenger_boost=700,
        mail_boost=50,
        inputgood=["FreshFish"],
        inputcapacity=[30],
        inputfactor=[100],
        inputsupplier=[1],
        outputgood=["fish"],
        outputcapacity=[30],
        outputfactor=[200],
        blend=_BLEND,
        blend_winter=_BLEND_WINTER,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Factory(
        name="FishPort1840",
        copyright="James",
        seasons=2,
        intro_year=1840, intro_month=4,
        retire_year=1910, retire_month=8,
        needs_ground=1,
        climates="water",
        population_and_visitor_demand_capacity=0,
        employment_capacity=120,
        mail_demand=4,
        class_proportion_jobs=[12, 80, 8, 0, 0],
        upgrade=["FishPort1910", "FishPort1945", "FishPort1975"],
        location="shore_city",
        max_distance_to_consumer=250,
        productivity=29,
        range=11,
        distributionweight=4,
        mapcolor=7,
        electricity_amount=1,
        electricity_boost=300,
        passenger_boost=700,
        mail_boost=50,
        inputgood=["FreshFish"],
        inputcapacity=[64],
        inputfactor=[100],
        inputsupplier=[1],
        outputgood=["fish"],
        outputcapacity=[64],
        outputfactor=[133],
        blend=_BLEND,
        blend_winter=_BLEND_WINTER,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Factory(
        name="FishPort1910",
        copyright="James",
        seasons=2,
        level=3,
        intro_year=1910, intro_month=8,
        retire_year=1945, retire_month=2,
        needs_ground=1,
        climates="water",
        population_and_visitor_demand_capacity=0,
        employment_capacity=220,
        mail_demand=4,
        class_proportion_jobs=[10, 80, 10, 0, 0],
        upgrade=["FishPort1945", "FishPort1975"],
        location="shore_city",
        productivity=80,
        range=46,
        distributionweight=4,
        mapcolor=7,
        electricity_amount=2,
        electricity_boost=500,
        passenger_boost=700,
        mail_boost=50,
        inputgood=["FreshFish"],
        inputcapacity=[180],
        inputfactor=[100],
        inputsupplier=[1],
        outputgood=["fish"],
        outputcapacity=[240],
        outputfactor=[200],
        blend=_BLEND,
        blend_winter=_BLEND_WINTER,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Factory(
        name="FishPort1945",
        copyright="James",
        seasons=2,
        level=3,
        intro_year=1945, intro_month=2,
        retire_year=1975, retire_month=3,
        needs_ground=1,
        climates="water",
        population_and_visitor_demand_capacity=0,
        employment_capacity=200,
        mail_demand=5,
        class_proportion_jobs=[10, 78, 12, 0, 0],
        upgrade=["FishPort1975"],
        location="shore_city",
        productivity=143,
        range=34,
        distributionweight=4,
        mapcolor=7,
        electricity_amount=2,
        electricity_boost=750,
        passenger_boost=700,
        mail_boost=50,
        inputgood=["FreshFish"],
        inputcapacity=[270],
        inputfactor=[100],
        inputsupplier=[1],
        outputgood=["fish"],
        outputcapacity=[180],
        outputfactor=[67],
        blend=_BLEND,
        blend_winter=_BLEND_WINTER,
        upstream_dat=_UPSTREAM_DAT,
    ),
    Factory(
        name="FishPort1975",
        copyright="James",
        seasons=2,
        level=3,
        intro_year=1975, intro_month=3,
        needs_ground=1,
        climates="water",
        population_and_visitor_demand_capacity=0,
        employment_capacity=160,
        mail_demand=5,
        class_proportion_jobs=[10, 75, 20, 0, 0],
        location="shore_city",
        productivity=183,
        range=80,
        distributionweight=4,
        mapcolor=7,
        electricity_amount=3,
        electricity_boost=1000,
        passenger_boost=700,
        mail_boost=46,
        inputgood=["FreshFish"],
        inputcapacity=[360],
        inputfactor=[100],
        inputsupplier=[1],
        outputgood=["fish"],
        outputcapacity=[160],
        outputfactor=[44],
        blend=_BLEND,
        blend_winter=_BLEND_WINTER,
        upstream_dat=_UPSTREAM_DAT,
    ),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
