"""autoport stub — see docs/porting.md."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'boats/humber-keel.blend'
_UPSTREAM_DAT = 'boats/humber-keel.dat'

SPECS = [
Vehicle(
    name='HumberKeelBulk',
    waytype='water',
    copyright='James',
    freight='Kohle',
    engine_type='sail',
    intro_year=1750,
    intro_month=1,
    retire_year=1900,
    retire_month=6,
    speed=12,
    length=6,
    weight=20,
    power=111,
    payload=50,
    min_loading_time=2700,
    max_loading_time=3600,
    cost=182500,
    runningcost=0,
    fixed_cost=16127,
    range=50,
    constraint_prev=['none'],
    constraint_next=['none'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='HumberKeelLong',
    waytype='water',
    copyright='James',
    freight='Bretter',
    engine_type='sail',
    intro_year=1750,
    intro_month=1,
    retire_year=1900,
    retire_month=6,
    speed=12,
    length=6,
    weight=20,
    power=111,
    payload=50,
    min_loading_time=2700,
    max_loading_time=3600,
    cost=182500,
    runningcost=0,
    fixed_cost=16127,
    range=50,
    constraint_prev=['none'],
    constraint_next=['none'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='HumberKeelPiece',
    waytype='water',
    copyright='James',
    freight='vegetables',
    engine_type='sail',
    intro_year=1750,
    intro_month=1,
    retire_year=1900,
    retire_month=6,
    speed=12,
    length=6,
    weight=20,
    power=111,
    payload=50,
    min_loading_time=2700,
    max_loading_time=3600,
    cost=182500,
    runningcost=0,
    fixed_cost=16127,
    range=50,
    constraint_prev=['none'],
    constraint_next=['none'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='HumberKeelCool',
    waytype='water',
    copyright='James',
    freight='meat',
    engine_type='sail',
    intro_year=1750,
    intro_month=1,
    retire_year=1900,
    retire_month=6,
    speed=12,
    length=6,
    weight=20,
    power=111,
    payload=50,
    min_loading_time=2700,
    max_loading_time=3600,
    cost=182500,
    runningcost=0,
    fixed_cost=16127,
    range=50,
    constraint_prev=['none'],
    constraint_next=['none'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='HumberKeelLivestock',
    waytype='water',
    copyright='James',
    freight='livestock',
    engine_type='sail',
    intro_year=1750,
    intro_month=1,
    retire_year=1900,
    retire_month=6,
    speed=12,
    length=6,
    weight=20,
    power=111,
    payload=50,
    min_loading_time=2700,
    max_loading_time=3600,
    cost=182500,
    runningcost=0,
    fixed_cost=16127,
    range=50,
    constraint_prev=['none'],
    constraint_next=['none'],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='HumberKeelPassenger',
    waytype='water',
    copyright='James',
    freight='Passagiere',
    engine_type='sail',
    intro_year=1750,
    intro_month=1,
    retire_year=1900,
    retire_month=6,
    speed=12,
    length=6,
    weight=20,
    power=111,
    payload=24,
    min_loading_time=240,
    max_loading_time=360,
    cost=182500,
    runningcost=0,
    fixed_cost=16127,
    range=50,
    constraint_prev=['none'],
    constraint_next=['humber-keel-mail-hold'],
    payload_by_class=[0, 24],
    comfort_by_class=[0, 39],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
