"""autoport stub — see docs/porting.md."""

from __future__ import annotations

from pak.bake import bake_main
from pak.dat import Vehicle

_BLEND = 'trams/glasgow-standard-1.blend'
_UPSTREAM_DAT = 'trams/glasgow-standard.dat'

SPECS = [
Vehicle(
    name='glasgow-standard-1',
    waytype='tram_track',
    copyright='James/jamespetts',
    freight='Passagiere',
    engine_type='electric',
    intro_year=1898,
    intro_month=6,
    retire_year=1904,
    retire_month=5,
    speed=32,
    length=5,
    weight=12.5,
    axles=2,
    power=45,
    gear=80,
    tractive_effort=26,
    payload=62,
    min_loading_time=10,
    max_loading_time=52,
    overcrowded_capacity=6,
    comfort=34,
    cost=360000,
    runningcost=27,
    fixed_cost=6300,
    bidirectional=1,
    can_lead_from_rear=1,
    sound='tom-tait-tram.wav',
    constraint_prev=['none'],
    constraint_next=['none'],
    liverytype=['Glasgow-Corporation-early', 'Glasgow-Corporation-standard'],
    upgrade=['glasgow-standard-3', 'glasgow-standard-4'],
    way_constraint_permissive=[1],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='glasgow-standard-3',
    waytype='tram_track',
    copyright='James/jamespetts',
    freight='Passagiere',
    engine_type='electric',
    intro_year=1904,
    intro_month=3,
    retire_year=1928,
    retire_month=9,
    speed=32,
    length=5,
    weight=12.7,
    axles=2,
    power=60,
    gear=80,
    tractive_effort=35,
    payload=62,
    min_loading_time=10,
    max_loading_time=52,
    overcrowded_capacity=6,
    comfort=37,
    cost=375000,
    runningcost=36,
    fixed_cost=6313,
    upgrade_price=93750,
    bidirectional=1,
    can_lead_from_rear=1,
    constraint_prev=['none'],
    constraint_next=['none'],
    liverytype=['Glasgow-Corporation-early', 'Glasgow-Corporation-standard'],
    upgrade=['glasgow-standard-4'],
    way_constraint_permissive=[1],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
Vehicle(
    name='glasgow-standard-4',
    waytype='tram_track',
    copyright='James/jamespetts',
    freight='Passagiere',
    engine_type='electric',
    intro_year=1928,
    intro_month=7,
    retire_year=1938,
    retire_month=12,
    speed=32,
    length=5,
    weight=12.8,
    axles=2,
    power=89,
    gear=80,
    tractive_effort=52,
    payload=62,
    min_loading_time=10,
    max_loading_time=52,
    overcrowded_capacity=6,
    comfort=43,
    cost=382000,
    runningcost=36,
    fixed_cost=6318,
    upgrade_price=95500,
    bidirectional=1,
    can_lead_from_rear=1,
    constraint_prev=['none'],
    constraint_next=['none'],
    liverytype=['Glasgow-Corporation-early', 'Glasgow-Corporation-standard'],
    way_constraint_permissive=[1],
    blend=_BLEND,
    upstream_dat=_UPSTREAM_DAT,
),
]


if __name__ == "__main__":
    bake_main(SPECS, __file__)
