#!/usr/bin/env python3
"""Vendor pak128.Britain's `texture-climate.png` as the hex pak's climate atlas.

No hex-flavoured biome palette is authored yet (see TODO.md); the
engine multiplies climate cells against the lightmap at runtime via
`create_textured_tile`, so the lightmap atlas needs *some* climate
texture to composite against.  Until a hex-native version exists this
baker pulls upstream's verbatim through `fetch_pak` and writes the
`Obj=ground Name=ClimateTexture` descriptor next to it.

Cell order matches `ground_desc.cc::climate_names` (sea, desert,
tropic, mediterran, temperate, tundra, rocky, arctic) — upstream's
PNG is already laid out 8×1 at 128 px so no resampling needed.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from pak.fetch_pak import fetch

UPSTREAM = "grounds/images/texture-climate.png"
CLIMATES = (
    "sea", "desert", "tropic", "mediterran",
    "temperate", "tundra", "rocky", "arctic",
)


def write(out_dir: Path) -> None:
    shutil.copy2(fetch(UPSTREAM), out_dir / "climate_texture.png")

    lines = [
        "# Generated by grounds/climate_texture.py — do not edit by hand.",
        f"# Upstream source: jamespetts/simutrans-pak128.britain {UPSTREAM}",
        "# pinned via pak.lock.",
        "Obj=ground",
        "Name=ClimateTexture",
        "",
    ]
    for i, climate in enumerate(CLIMATES):
        lines.append(f"Image[{i}][0]=climate_texture.0.{i}\t# {climate}")
    lines += ["---", ""]
    (out_dir / "climate_texture.dat").write_text("\n".join(lines))


if __name__ == "__main__":
    write(Path(__file__).resolve().parent)
